metabrainz/picard

.github/workflows/package.yml, .github/workflows/pypi-release.yml, .github/workflows/run-tests.yml
It seems much less prone to failures
* This is a…
=> Bump github actions checkout to v2

picard/ui/widgets/editablelistview.py, picard/ui/widgets/taglisteditor.py
* This is a…
Users seem to be confused about how to enter the tag names in the top tags dialog. I think the main problem is that the autocomplete dropdown only triggers in some cases, it would be easier if the user would see the complete list of tags to select from. The other part seems to be the use of display name.
* JIRA ticket (_optional_): PICARD-1759
- Change the autocompleter to be case-insensitive and always show the full list of tags (jumping to the first matching selection). This should make it obvious to users what to enter once they start typing.
- Use the internal tag name directly for display.
=> PICARD-1759: Try to make top tags editor more intuitive

picard/script.py, test/test_script.py
=> Introduce MultiValue class to simplify script functions

test/formats/common.py, test/test_acoustidmanager.py, test/test_bytes2human.py, test/test_config.py, test/test_coverart_image.py, test/test_coverart_utils.py, test/test_imagelist.py, test/test_metadata.py, test/test_textencoding.py, test/test_util_lrucache.py, test/test_util_natsort.py, test/test_versions.py
=> Tests cleanup

picard/ui/ui_widget_taglisteditor.py, picard/ui/widgets/editablelistview.py, ui/widget_taglisteditor.ui
Prevent entering duplicate values in top tags options.
* This is a…
It was possible to enter duplicate values in the top tags editor. Those duplicated tracks would also show up duplicated in the metadatabox. This behavior is at least confusing.
* JIRA ticket (_optional_): PICARD-1760
Implement a `UniqueEditableListView` and use it for the `TagListEditor`. If a value is inserted or an existing row is edited all other occurrences of the same value will be removed.
=> PICARD-1760: Prevent duplicate in top tags editor

picard/script.py, test/test_script.py
* This is a…
* **Describe this change in 1-2 sentences**:  Adds scripting `$sortmulti` and `$reversemulti` functions.
The ability to sort a multi-value variable could be handy for example to sort the `artists` list alphabetically before saving to a tag.  In addition, the ability to reverse the order of a multi-value variable could be used to provide a descending sort, and may be useful in other instances.
* JIRA ticket: PICARD-1743
Added scripting `$sortmulti` and `$reversemulti` functions.
If these additions are approved, the Picard Website documentation will need to be updated.
=> PICARD-1743: Add multi-value sort and reverse functions

picard/util/__init__.py, test/test_union_sorted_lists.py, test/test_utils.py
Improve test coverage and general cleanup with the help of coverage tools.
=> Coverage & cleanup

picard/ui/mainwindow.py
Change "Generate Fingerprints" shortcut to Ctrl+Shift+Y (⌘⇧Y on macOS).
This change brings the fingerprint action shortcut inline with other shortcuts in two ways:
- The current Scan shortcut is "Ctrl+Y". Having just the fingerprinting done with another modifier using "Ctrl+Shift+Y" makes this more intuitive
- Replacing Alt with Shift is consistent with the open browser shortcut (Ctrl+Shift+L), which is available in the same menu
* This is a…
* JIRA ticket (_optional_): PICARD-1746
=> PICARD-1746: Change "Generate Fingerprints" shortcut to Ctrl+Shift+Y

picard/util/preservedtags.py, test/test_util_preservedtags.py
* This is a…
`PreservedTags` only lower cased the tags on loading, not when adding or removing tags. This makes behavior inconsistent when upercased tags are added to the list.
* JIRA ticket (_optional_): PICARD-1765
=> Adding / removing preserved tags must normalize the tags

.github/workflows/package.yml, setup.py
Count the number of commits on the master branch since last release tag. This reduces the size and avoids issues for building the patch version for the Windows store app, since this is limited to a maximum of 65535.
The new patch version for Windows is now calculated basically by `actual_patch_version * 1000 + git_commits_since_last_tag`.
* This is a…
=> Fix build numbers for CI builds

picard/script.py, test/test_script.py
* This is a…
* **Describe this change in 1-2 sentences**: Added error handling and test for ZeroDivisionError to the `$mod` function.
* JIRA ticket: PICARD-1773
The `$mod` function does not trap the ZeroDivisionError.
Add error handling and test for ZeroDivisionError to the `$mod` function.
=> PICARD-1773: Add ZeroDivisionError handling in $mod function

picard/script.py, test/test_script.py
See https://github.com/metabrainz/picard/pull/1505
This also fixes issues with some functions:
- $lenmulti with empty value must return 0
- $foreach and $map must loop zero times on empty value
* This is a…
* JIRA ticket (_optional_): PICARD-1774
=> PICARD-1774: Fix MultiValue returning [] on empty value

picard/script.py, test/test_script.py
* This is a…
* **Describe this change in 1-2 sentences**:  Added `IndexError` check to `$firstwords` function.
* JIRA ticket: PICARD-1775
The `$firstwords` function does not catch and handle IndexError.  For example, the following will crash.
```
$firstwords(one two three four,-40)
```
Add `IndexError` check to `$firstwords` function, and add tests to check.
=> PICARD-1775: Add IndexError check to $firstwords function

picard/formats/apev2.py, picard/formats/id3.py, picard/formats/mp4.py, picard/formats/vorbis.py, test/formats/common.py, test/formats/test_mp4.py
This adds tests for deleting comment, performer and lyrics tags and fixes various issues with this in ID3, MP4, Vorbis and APEv2.
* This is a…
Adding tests for saving the tags which can have optional description (lyrcis:, performer:, comment:) reveals various issues with deleting those tags.
* JIRA ticket (_optional_): PICARD-1783
=> PICARD-1783: Fix deletion of comment, performer and lyrics tags

picard/coverart/providers/caa.py, test/test_coverartprovider_caa.py
=> Improve handling of CAA thumbnail sizes, add tests

test/formats/common.py, test/formats/coverart.py, test/formats/test_asf.py
Add test cases for handling unsupported or invalid images in tags. Closes some holes in the test coverage for formats to handle `CoverArtImageError`.
* This is a…
=> Added tests for loading unsupported images from tags

picard/formats/id3.py, picard/formats/mp4.py, test/formats/common.py, test/formats/test_id3.py, test/formats/test_midi.py, test/formats/test_mp4.py
This is an attempt to close holes in format test coverage. During implementation a couple of issues have been discovered, which are also getting fixed here.
* This is a…
* JIRA ticket (_optional_): PICARD-1785, PICARD-1786, PICARD-1787, PICARD-1788
@zas: This was all done during a single session of adding tests. I tried to pull out fixed issues as separate commits so I could pull those out as separate PRs if wanted.
=> Increase formats test coverage and fix discovered issues

picard/script.py, test/test_script.py
* This is a…
* **Describe this change in 1-2 sentences**:  Have function `ScriptRuntimeError` show the proper start position of the function that raised the exception.  Add tests.
The column number currently displayed for a `ScriptRuntimeError` exception is one character past the closing bracket for the function that raised the exception.  This is confusing.
Update the code to pass the starting column number of the function (actually the $ at the start of the function name) to the exception.  Add tests.
=> Fix function line, column in ScriptRuntimeError.  Add tests.

picard/ui/options/plugins.py
* This is a…
Picard crashes when selecting a plugin with available updates due to version no longer being a string.
* JIRA ticket (_optional_): PICARD-1790
Fixed the crash issue by explicitly converting version into a string (using the nicer short format). Also refactored the description generation a bit to make it more readable and no longer prone to such errors by using str.format.
=> PICARD-1790: Fix crash when selecting plugins with update

picard/ui/options/about.py
* This is a…
* **Describe this change in 1-2 sentences**: Update the copyright date in the "About" screen to 2020.
The "About" screen still shows the copyright date as 2019, even though there have been releases in 2020.
Update the year in the "About" screen.
=> Update copyright year to 2020

picard/formats/id3.py, test/formats/test_id3.py
* This is a…
The tags `comment:iTunNORM` and `comment:iTunPGAP` in ID3 tags cannot be deleted.
* JIRA ticket (_optional_): PICARD-1795
There was a special code preventing the deletion of those tags added in https://github.com/metabrainz/picard/commit/bff60dab8a69674bfe14e6b5f02b5b597bdcb4ec
I don't see any harm being done allowing those tags to be deleted on request. There is some special handling for storing the `iTunNORM` tag as iTunes expected it, but this is independent of the issue of allow the deletion.
=> PICARD-1795: Allow deleting iTunNORM and iTunPGAP tags from ID3

.github/workflows/package.yml, scripts/package/macos-setup.sh, scripts/package/win-setup.ps1
Upgrade to fpcalc 1.5.0 for Windows and macOS builds
* This is a…
We had been using my fork for builds of chromaprint, as there was no official release yet with the new build system (which is needed for macOS binaries compatible with the Apple notarization). chromaprint 1.5.0 is the first release build on the new build system.
For changes see also
https://github.com/acoustid/chromaprint/releases/tag/v1.5.0
=> Upgrade to fpcalc 1.5.0 for Windows and macOS builds

picard/webservice/__init__.py
Qt's network monitoring sometimes reports falsly the network being inaccessible. Ignore this state and rely on handling request errors.
Perform network requests independent of Qt's network accessible status.
* This is a…
Qt tracks the accessibility of the network. This seems to fail under certain circumstances. We have report that this is failing with Qt 5.14 on Windows when using a VPN. But I found another way to replicate the issue: Disable networking on Windows, start Picard, re-enable networking. The network will be reported to be inaccessible by Qt for the entire session, only restarting Picard helps.
* JIRA ticket (_optional_): PICARD-1791
Ignore the `QNetworkAccessManager.NotAccessible` by intercepting the state change and setting it to …
=> PICARD-1791: Ignore Qt's network inaccessible state

setup.py
When running `update_constants` ensure the files `countries.py` and `attributes.py` get written with UTF-8 encoding.
* This is a…
When running update_constants on Windows 10 I got the files written with a iso-8859-1 encoding.
=> Ensure using UTF-8 encoding when running update_constants

picard/ui/options/scripting.py, picard/ui/ui_options_script.py, ui/options_script.ui
Also show a placeholder text in the script editor to make it clear where the user can input code.
* This is a…
A newly installed Picard shows a very empty page in Options Scripting, with scripting disabled and two empty panes. For a new user it is not clear how and where to enter the script.
* JIRA ticket (_optional_): PICARD-1805
- Automatically add the first script when scripting gets enabled
- Show a hint in the script editor that new scripts should be entered there
=> PICARD-1805: Add a default tagger script when user enables scripting

.github/workflows/package.yml, .github/workflows/run-tests.yml
Fix gettext not being in path for macOS builds. This seemed to have changed with recent brew updates.
* This is a…
=> ci: fixed macOS builds not finding msgfmt

picard/formats/wav.py, test/formats/test_wav.py
This adds support for tagging WAVE files with ID3, if supported by mutagen. 
* This is a…
* JIRA ticket (_optional_): PICARD-1128
Use the WAVE ID3 support in mutagen, if available. Falls back to the basic WAVE file support Picard currently supports.
mutagen support has finally been merged, see https://github.com/quodlibet/mutagen/pull/408 . So this will be in the next mutagen release.
A future improbement could be to also support reading the RIFF INFO chunk. I have some basic implementation of this in https://github.com/phw/picard/commit/d827cb6f3e9757c9a0d33f2c101af2ad6ab292cf
Once we have merged the WAV support I will review this code and do a separate PR.
=> PICARD-1128: Allow tagging WAVE files with ID3

picard/script.py, test/test_script.py
Fix calling `$title(%someemptyvar%)` fails with "string index out of range".
* This is a…
* JIRA ticket (_optional_): PICARD-1813
=> PICARD-1813: Fixed calling $title with empty value

picard/ui/cdlookup.py, picard/ui/options/interface.py, picard/util/filenaming.py, test/test_bytes2human.py
Fixes the issue E741 reported by flake8 >= 3.8.
https://www.flake8rules.com/rules/E741.html
* This is a…
=> Avoid using ambiguous variable name "l"

.github/workflows/run-tests.yml, picard/disc.py, test/test_disc.py
Fix error handling if python-libdiscid is used instead of python-discid.
* This is a…
* JIRA ticket (_optional_): PICARD-1807
`discid.disc.DiscError` only exists in python-discid, not in the compat version of python-libdiscid. The proper way in both libraries is to access `discid.DiscError`.
=> PICARD-1807: Fix error handling when using python-libdiscid

INSTALL.md
There have been some changes to the requirements (python-markdown and python-dateutil). Document this in INSTALL.md
* This is a…
=> INSTALL.md: Document updated requirements

picard/formats/id3.py
While both DSF and DFF contain DSD encoded audio data they are separate file formats and not compatible. Remove ` .dff` from the list of supported file extensions.
See also:
- https://www.blisshq.com/music-library-management-blog/2016/03/15/dsd-versus-dsf-versus-dff-what-mean-audio-libraries/
- https://dsd-guide.com/faq/what-difference-between-dsd-dsf-dff-files
* This is a…
* JIRA ticket (_optional_): PICARD-1838
=> PICARD-1838: Remove .dff from supported file extensions for DSF

picard/file.py
This fixes a small issue in exception handling, where loading an unsupported file type which has a known file extension (e.g. some random file having an .mp3 extension) would throw 
```
File "./picard/util/thread.py", line 60, in run
result = self.func()
File "./picard/file.py", line 180, in _load_check
return file_format._load(filename)
AttributeError: 'NoneType' object has no attribute '_load'
```
in addition to the actual exception.
* This is a…
=> Fix exception handling when loading unsupported files

picard/ui/infodialog.py
* This is a…
Cluster info dialog is able to show a tracklist to be copied, but it doesn't support disc numbers.
https://community.metabrainz.org/t/sending-lengths-from-mp3tag-to-mb/477254/4?u=zas
* JIRA ticket (_optional_): PICARD-1829
=> PICARD-1829: Add support for disc numbers in cluster Info dialog tracklists

picard/mbjson.py, test/data/ws_data/recording_instrumental.json, test/test_mbjson.py
If a recording is an instrumental of a work, unset the lyricist and set the language to zxx ("No lyrics").
* This is a…
For a work, that was originally written with lyrics, there are sometimes purely instrumental recordings. For those the lyricist and language do not apply. This is also how the MB server handles it.
See also:
https://musicbrainz.org/relationship/a3005666-a872-32c3-ad06-98af558e99b0
https://www.mail-archive.com/musicbrainz-style@lists.musicbrainz.org/msg10698.html
* JIRA ticket (_optional_): PICARD-1840, PICARD-1117
=> PICARD-1840: For instrumental recordings unset lyricist

picard/ui/options/dialog.py
Expand all options in the tree view by default.
Make it easier for users to discover sub-options, but persist the state so users can choose to collapse individual options.
* This is a…
New users often do not realize that some options have additional sub option pages, which can be accessed by expanding the tree view on the left of the options dialog.
Also some users might access certain sub option pages frequently. Having them expanded makes this easier.
* JIRA ticket (_optional_): PICARD-824
by default expand all options in the tree view. But persist the state when closing the dialog, so users can actively decide to collapse certain options.
=> PICARD-824: Expand all option pages by default

picard/ui/itemviews.py
Improve performance of column sorting in main view.
* This is a…
* JIRA ticket (_optional_): PICARD-1854
- Calculate the sort key only once
- Do not use natsort for all columns
In current master having loaded around 27k files changing the sort order (either sorting by a new column or switching from ascending to descending order) takes slightly above 2s. With this patch only the initial sorting is slow (but still a bit faster, as it optimizes that the sortkey needs to be calculated twice for each comparison), later sort order changes are 0.5 to clearly under 1s.
=> PICARD-1854: Improve sort performance

picard/script.py
=> Script doc fixes

picard/tagger.py, picard/ui/theme.py, picard/ui/widgets/scripttextedit.py
Enable a dark layout for Picard on Windows if Windows has dark mode enabled.
* This is a…
This is an alternative suggestion to #1536. I had this started as an experiment, but now putting it up for further discussion.
The colors are using the actual colors used by the core Windows apps (Settings, Explorer).
One detail that cannot be changed that way is the color of the Windows title bar, as this is done by Windows itself. And for some reason Windows either renders this for the active Window in the configured accent color, but inactive Windows always get a light gray even in dark mode. Only UWP apps get a dark titlebar. The only way around for a native app is rendering its own titlebar, but I honestly think we should not do this.
* JIRA ticket …
=> PICARD-1704: Support Windows 10 dark mode

NEWS.md, picard/__init__.py
=> Release 2.4.0b1

NEWS.md
Standardize the headings in NEWS.md, using plural for all ticket categories
* This is a…
=> NEWS: Use consistent headings

picard/coverart/providers/caa.py
* This is a…
The cover art type selection dialog does not translate "Unknown".
* JIRA ticket (_optional_): PICARD-1868
=> PICARD-1868: Translate the cover art type "Unknown"

requirements-macos.txt, requirements-win.txt
=> Use mutagen 1.45 for macOS and Win builds

picard/script.py
Clarify the documentation for the default value of $firstalphachar a bit.
* This is a…
* JIRA ticket (_optional_): PICARD-1875
=> PICARD-1875: Improve function documentation for $firstalphachar

picard/ui/__init__.py, picard/ui/options/scripting.py
* This is a…
* JIRA ticket (_optional_): PICARD-1873, PICARD-1880
Rely more on default font selection (which is sensible and actually works), but use the system specific monospace font used elsewhere in Picard. Also change to using Consolas on Windows, which looks a bit more modern.
See PICARD-1873 for a screenshot of the wrong font display. Below is a screenshot with cleanly rendered font after this PR.
=> PICARD-1873: Fix ugly font rendering in script docs on Windows

picard/mbjson.py, test/data/ws_data/track_pregap.json, test/test_mbjson.py
Fix `tracknumber` tag not getting set for track number "0".
* This is a…
* JIRA ticket (_optional_): PICARD-1884
Don't treat integer `0` as empty value when setting tags.
This might also fix some other cases, but I could not find one real case of this.
=> PICARD-1884: Fix tracknumber tag with value 0 not set

picard/ui/theme.py
If Qt uses a dark UI on macOS (because dark mode is enabled in macOS preferences) Picard should detect this and use the new dark syntax theme.
* This is a…
If macOS is configured to use a dark UI Qt5 will automatically use the dark colors. But then the syntax theme becomes hardly readable.
* JIRA ticket (_optional_): PICARD-1887
Detect the use of dark mode on macOS. This allows setting the proper dark syntax theme.
Note that this does not mean dark mode will work in our current release version. Having the release builds using dark mode is done in PICARD-1357. Dark mode works when running from source, it's an issue with I think mainly PyInstaller being built against older SDK. Fixing this requires some care and probably releasing two different …
=> PICARD-1887: Detect use of macOS dark mode

picard/ui/theme.py
* This is a…
This simplifies the code to get a link color with a certain lightness implemented in #1581
=> theme: Refactor getting link color with lightness of 160

picard/ui/colors.py, picard/ui/options/interface_colors.py, test/test_interface_colors.py
* This is a…
* JIRA ticket (_optional_): PICARD-1890
- detection of color changes was broken, user was getting warn message even when there were no changes.
- rework save to config part
- code cleanup
- added tests
=> PICARD-1890: Fix spurious Restart Picard message about color changes

picard/mbjson.py
* This is a…
* JIRA ticket (_optional_): PICARD-1896
Rename  "instrumentator" to "instrument arranger". See also https://tickets.metabrainz.org/browse/STYLE-217.
=> PICARD-1896: Fixed mapping "instrument arranger" to arranger tag

picard/ui/theme.py
* This is a…
The registry entries checked by Picard do not exist on previous Windows releases, causing it to fail.
* JIRA ticket (_optional_): PICARD-1904
Extend the try-catch block to catch not only the registry value check but also the registry hive load.
=> PICARD-1904: Fix Dark theme checks for older Windows releases

picard/ui/metadatabox.py
Without this deleted tags are not immediately reflected in the list views. See discussion in 1603
* This is a…
=> PICARD-1911: Update tree view on tag deletion

picard/ui/theme.py
* This is a…
Theming support throws an untreated exception on older releases of MacOS.
* JIRA ticket (_optional_): PICARD-1916
Untreated exception causes Picard to crash while opening.
https://community.metabrainz.org/t/picard-crashing-on-mac-osx-10-13/490263
Treat AtributeError exception.
=> PICARD-1916: Fix Dark theme checks for older OS X releases

picard/ui/mainwindow.py, picard/ui/metadatabox.py
Ensure the metadatabox does get updated after removal, pasting from clipboard or "use original values".
* This is a…
The metadatabox did not trigge rthe updates on important actions.
* JIRA ticket (_optional_): PICARD-1909
Run `MetadataBox.update()` after those actions. I tried to make sure to run this update only after the entire action, so not for every call to e.g. `set_tag_values()`.
=> PICARD-1909: Update metadatabox on tag modifying actions

picard/album.py, picard/track.py, picard/ui/mainwindow.py
When a album finished loading **and** is selected, update the metadata view.
* This is a…
* JIRA ticket (_optional_): PICARD-1915, PICARD-1914
Update the metadatabox.
@zas @Gabrielcarvfer This might have quite serious performance impact if the user is loading a lot of albums **and** has all of them selected. In this case it is run after every album load and a tag diff over all albums is created. Should we limit this update, e.g. only run the update when 1 or a few albums are selected?
=> PICARD-1915: Update metadata view after selected album finished loading

README.md, org.musicbrainz.Picard.appdata.xml.in, picard/const/__init__.py, picard/coverart/providers/caa.py, picard/coverart/providers/local.py, picard/ui/options/__init__.py, picard/ui/options/advanced.py, picard/ui/options/cdlookup.py, picard/ui/options/cover.py, picard/ui/options/dialog.py, picard/ui/options/fingerprinting.py, picard/ui/options/general.py, picard/ui/options/genres.py, picard/ui/options/interface.py, picard/ui/options/interface_colors.py, picard/ui/options/interface_top_tags.py, picard/ui/options/matching.py, picard/ui/options/metadata.py, picard/ui/options/network.py, picard/ui/options/plugins.py, picard/ui/options/ratings.py, picard/ui/options/releases.py, picard/ui/options/renaming.py, picard/ui/options/scripting.py, picard/ui/options/tags.py, picard/ui/options/tags_compatibility_aac.py, picard/ui/options/tags_compatibility_ac3.py, picard/ui/options/tags_compatibility_id3.py, picard/ui/options/tags_compatibility_wave.py
Update all documentation links to point directly to picard-docs.musicbrainz.org. 
* This is a…
* JIRA ticket (_optional_): PICARD-1899
Update the URLs. Also allow explicit definition of help URLs for each option page by specifying a `HELP_URL`. `HELP_URL` might be an absolute URL with protocol (e.g. a plugin could directly link to https://github.com/rdswift/picard-plugins/blob/2.0/plugins/format_performer_tags/docs/README.md or something nicer) or start with a slash `/config/options_filerenaming.html`. The first case is primarily meant for plugins which want to link to their own documentation, the later case will always be linked to picard-docs.musicbrainz.org. 
Language handling is excluded for now, but can be easily added later. As currently …
=> PICARD-1899: Link to new documentation pages

picard/ui/options/dialog.py
Open documentation in options dialog using platforms help shortcut (e.g. `F1` on Windows and Linux or `Ctrl+?` on macOS)
* This is a…
* JIRA ticket (_optional_): PICARD-1920
=> PICARD-1920: Open help in options with platform's help shortcut

picard/ui/theme.py
* This is a…
https://community.metabrainz.org/t/picard-crashing-on-mac-osx-10-13/490263
* JIRA ticket (_optional_): PICARD-1916
=> PICARD-1916: Fix another AttributeError on macOS < 10.14

.pylintrc, picard/config_upgrade.py, picard/coverart/providers/__init__.py, picard/coverart/providers/urlrels.py, picard/formats/apev2.py, picard/ui/options/cover.py, test/test_config_upgrade.py, test/test_taggenrefilter.py
This PR makes changes to avoid the terms blacklist or whitelist in the sources and UI.
Most notable it renames the "Whitelist" cover art provider to "Allowed Cover Art URLs", which also helps in clarifying what this provider is actually about.
* This is a…
* JIRA ticket (_optional_): PICARD-1936
=> PICARD-1936: Rename the "Whitelist" cover art provider to "Allowed Cover Art URLs"

installer/i18n/sources/en.json
Make the wording in the dialog to uninstall the previous version in the Windows installer clearer.
* This is a…
* JIRA ticket (_optional_): PICARD-1906
=> PICARD-1906: Clarify uninstall message in NSIS installer

picard/ui/coverartbox.py, picard/ui/widgets/__init__.py
Adds a context menu entry to the cover art box to choose a local file using the file browser.
* This is a…
* JIRA ticket (_optional_): PICARD-1937
Add the context menu option.
I also added some refactoring to move the `ActiveLabel` class to picard.ui.widgets, and by this also moving the drag and drop handlers to the proper class.
=> PICARD-1937: local coverart context menu

picard/ui/filebrowser.py
Extend the context menu of the file browser with a "Load selected files" action
* This is a…
* JIRA ticket (_optional_): PICARD-1938
Extend the context menu with the "Load selected files" action. Also switch to a manually created context menu to include the separator
=> PICARD-1938: Add "Load selected files" action to file browser

scripts/tools/tag-release.sh
Added a script to automate the creation of the release tags. That makes it easier to have consistent release tags and avoid mistakes.
I had actually used this the last couple of releases instead of trying to manually get everything right (and mistyping 
* This is a…
=> Added tag-release.sh script to create the release tags

picard/ui/metadatabox.py
Fixes multi-value tags on tracks always showing up as changed
* This is a…
* JIRA ticket (_optional_): PICARD-1941
Proper comparison of multi-value tags
=> PICARD-1941: Properly compare multi value tags of tracks

picard/album.py, picard/file.py, picard/ui/infodialog.py, picard/ui/item.py
On not-yet-matched clusters, context menu shows Infos item and user can see a copiable tracklist in the Info tab.
On loaded albums the context menu will be there only when album has cover art (and no errors).
This patch unifies things a bit without adding much code, Infos dialog is accessible as soon an album is loaded, and Infos tab displays a text tracklist for it, which can be convenient for the user as it is copiable.
* This is a…
* JIRA ticket (_optional_): PICARD-1942
=> PICARD-1942: Display tracklist in Info Dialog Infos tab for albums too

requirements-build.txt, requirements-win.txt
* This is a…
Update to make sure this runs on Windows well with the next release.
On macOS backward compatibility with macOS 10.12 is still holding us back, but we could consider providing separate builds for older and newer macOS releases. This could also enable us to have builds that support macOS' dark layout.
=> Update to Qt 5.15.1 on Windows

picard/acoustid/manager.py
Avoid showing success message if errors occurred during submission.
* This is a…
After fingerprint submission Picard was always displaying the message "AcoustIDs successfully submitted.", even if an error occurred. 
* JIRA ticket (_optional_): PICARD-1932
Keep track of errors during the submission process. Show different submission finished message depending on whether an error occurred or not.
=> PICARD-1932: Better error message after AcoustID submission

picard/browser/filelookup.py, picard/ui/itemviews.py, picard/ui/searchdialog/__init__.py, picard/ui/searchdialog/album.py, picard/ui/searchdialog/artist.py, picard/ui/searchdialog/track.py, picard/webservice/api_helpers.py
This allows dragging release-group URLs into Picard or entering them in the search field. The release search dialog will be shown filtered by the release-group MBID.
* This is a…
* JIRA ticket (_optional_): PICARD-1908
Show the AlbumSearch dialog with an advanced query to filter by release group. Extend the search dialogs to force using advanced query syntax without changing the users preferences.
We could extend this to other entities (e.g. work URL -> search for matching recordings, artist URL -> search for matching releases). But release group was the most obvious to me, especially as I have seen users trying to load release group URLs instead of release URLs more than once. Thoughts?
=> PICARD-1908: Show release search dialog for release-group URLs

picard/cluster.py, picard/tagger.py
* This is a…
* JIRA ticket (_optional_): PICARD-1956
If one selects an album and files inside this album and drags them onto the cluster item, the created cluster contains the selected files twice. This leads to further confusion of the UI, as moving the cluster files to an album will still leave the cluster with a reference to the duplicated files.
Prevent adding the same file twice to a cluster.
=> PICARD-1956: Prevent the same file being added to a cluster more than once

picard/tagger.py
* This is a…
When files currently attached to tracks are dragged to the Cluster list, they get clustered with their new metadata from the tracks. Ensure they get their original data reset prior to doing the clustering.
* JIRA ticket (_optional_): PICARD-1888
Remove the files from the track prior to clustering them.
=> PICARD-1888: Cluster files attached to tracks with original metadata

picard/ui/edittagdialog.py, picard/ui/widgets/editablelistview.py, picard/ui/widgets/scriptlistwidget.py
* This is a…
Allow using insert key on various lists (editable list views, scripts list and tag editor).
* JIRA ticket (_optional_): PICARD-1960
=> PICARD-1960: Enable insert key on lists

picard/album.py, picard/cluster.py, picard/tagger.py, picard/util/__init__.py
* This is a…
Refactor iterations using QCoreApplication.processEvents to not run this on every iteration.
EventProcessingIterator acts as a wrapper around another iterable to allow running QCoreApplication.processEvents.
Instead of running processEvent on every iteration it is done in steps.
This allows us to weight responsiveness against total processing time.
=> Add process_events_iter to allow iteration while processing events

picard/tagger.py
* This is a…
Fix Picard crashing when loading directories without read permission.
* JIRA ticket (_optional_): PICARD-1988
The issue was introduced when `os.walk` got abondoned in https://github.com/metabrainz/picard/commit/2c06a625da370f8e48dafe978bdf7fab28db3f18. `os.walk` ignores all scandir errors.
Catch all exceptions thrown by os.scandir when loading directories, log them as warnings. Avoids crashes e.g. when attemtping to load directories without permission.
=> PICARD-1988: Fix crash on errors reading directories

picard/album.py
* This is a…
* JIRA ticket (_optional_): PICARD-1987
After the refactoring for running scripts on file metadata the three special hidden variables `~multiartist`, `~pregap` and `~datatrack`, as those did get set after running `File._finalize_loading_track` and are hence not set in the `File.orig_metadata`.
Set the variables `~pregap` and `~datatrack` as part of `File._finalize_loading_track`. `~multiartist` is still set afterwards, but ensure it is also set to `File.orig_metadata`.
=> PICARD-1987: Fix ~multiartist, ~pregap and ~datatrack variables not set for files

picard/tagger.py, picard/ui/mainwindow.py
* This is a…
Command line option to disable built-in media player completely.
* JIRA ticket (_optional_): PICARD-1995
On some systems the player causes stability issues and segmentation fauls for reasons outside our control. As these crashes happen early when  we probe QMultimedia for availability we cannot easily avoid them.
Add a command line parameter --no-player to intentionally disable the media player functionality completely.
=> PICARD-1995: Add command line parameter --no-player

.github/workflows/pypi-release.yml, picard.spec, setup.py
* This is a…
* JIRA ticket (_optional_): PICARD-1999
Picard is available for install from PyPI, but requires building for source. This requires build tools that might not always be installed on Windows or macOS.
Provide binary distributions on PyPI for those platforms. Also add an entry point for Windows so an actual picard.exe will be available.
This allows even on Windows to run the following on the command prompt or from powershell:
```
pip install picard
picard
```
=> PICARD-1999: Provide binary distributions for Windows and macOS on PyPI

picard/tagger.py
* This is a…
Fix dropped files not showing up in UI if getting dropped on other files.
* JIRA ticket (_optional_): PICARD-2001
It is possible to drag and drop files from the file browser onto invalid drop targets. If those drop targets do not allow adding files the files will be added to the tagger but won't show up in the UI.
Always move added files to a valid target in the UI. If no drop target is given or the drop target does not support adding files always drop to unclustered files.
=> PICARD-2001: Ensure dropped files are moved to a valid target

picard/album.py
* This is a…
Fix metadata of asynchronous metadata processor plugins getting lost when files are matched to tracks.
* JIRA ticket (_optional_): PICARD-2004
If a plugin does load additional metadata asynchronously, such as the AcousticBrainz or Wikidata plugins, these metadata changes were not saved as part of track.orig_metadata.
Populate `track.orig_metadata` after plugins have finished and all outstanding requests are done.
=> PICARD-2004: Fix plugin metadata changes getting lost after file match

picard/coverart/__init__.py, picard/coverart/image.py, picard/i18n.py, picard/pluginmanager.py, picard/util/filenaming.py, test/test_util_filenaming.py
* This is a…
Since Python3, IOError is an alias to OSError
```python
>>> FileNotFoundError.mro()
[<class 'FileNotFoundError'>, <class 'OSError'>, <class 'Exception'>, <class 'BaseException'>, <class 'object'>]
>>> IOError.mro()
[<class 'OSError'>, <class 'Exception'>, <class 'BaseException'>, <class 'object'>]
>>> PermissionError.mro()
[<class 'PermissionError'>, <class 'OSError'>, <class 'Exception'>, <class 'BaseException'>, <class 'object'>]
```
Remove or rename.
=> Use OSError instead IOError

picard/tagger.py, picard/ui/itemviews.py, picard/util/__init__.py
* This is a…
Fix crash when trying to load an inaccessible network share on Windows.
* JIRA ticket (_optional_): PICARD-2022
os.path.realpath can raise an exception if the path is not accessible. In the concrete case I had a folder shared publicly from my Linux machine via samba, but had not granted public permissions (on Linux file system). Windows showed the shared folder, but could not access it. Trying to load the folder into Picard lead to the crash
Handle os.path.realpath with more care, introduce a picard.util.normpath for the common combination of os.path.normpath(os.path.realpath(...))
=> PICARD-2022: Fix crash when loading network share without access rights on Windows

picard/metadata.py, test/test_metadata.py
`MultiMetadataProxy::pop` modifies the tags, so is a WRITE_METHOD.
* This is a…
* JIRA ticket (_optional_): PICARD-2036
=> PICARD-2036: Add MultiMetadataProxy::pop to WRITE_METHODS

picard/ui/metadatabox.py
* This is a…
Refactorings as discussed in #1692
=> Refactor MetadataBox to flag readonly tags, introduce column constants

picard/ui/metadatabox.py
* This is a…
Integrate the metadatabox clipboard with system text clipboard, but maintain the ability to directly copy list values inside Picard.
* JIRA ticket (_optional_): PICARD-2038
Picard allows copy and pasting metadata values with Ctrl+C / Ctrl+V. But in the past this was a local clipboard only. It is not possible to paste a text value from the system clipboard (e.g. copied in another application) or have values copied in the metadata box available in the system clipboard.
Previously likely only few people even knew copy and pasting was possible there. But with #1692 this functionality is now more discoverable, so people might actually notice it does not fully work with system clipboard.
When copying values, also copy them to the system …
=> PICARD-2038: Integrate metadata box clipboard with system clipboard

picard/util/icontheme.py
* This is a…
The `icontheme` uses `XDG_DATA_DIRS` to look for icons, but does not consider that `XDG_DATA_DIRS` can contain multiple directories
Split `XDG_DATA_DIRS` properly
=> Support XDG_DATA_DIRS containing multiple directories

picard/ui/itemviews.py
* This is a…
* JIRA ticket (_optional_): PICARD-2044
Make the date and originaldate tags available as columns in the item views.
=> PICARD-2044: Add date and originaldate to available itemview columns

picard/acoustid/manager.py, picard/oauth.py, picard/webservice/__init__.py, picard/webservice/api_helpers.py, test/test_acoustidmanager.py
* This is a…
In certain cases, AcoustID submission could fail with Payload Too Large error.
Batch size was limited to a number of items, but do not take in account actual size of items.
* JIRA ticket (_optional_): PICARD-2046
Rework AcoustID fingerprints submission to handle payload limits
- approximate payload of each submission
Calculating exact payload would add extra complexity, so we do an approximation with safety margin
- limit batch to a maximum payload
- handle AcoustID server HTTP 413 (Payload too large), retrying with a smaller batch
- limit the number of attempts for each submission to 5
- improve logging
=> PICARD-2046: improve AcoustID submission process, better handling of maximum payload

picard/album.py, picard/cluster.py, picard/file.py, picard/track.py, picard/ui/searchdialog/track.py
* This is a…
* JIRA ticket (_optional_): PICARD-2062
To reproduce:
Have an album where only a single track has exactly one matched files, but there are also unmatched files
Use "Search for similar tracks..." on the track with the file
In the search result select an album different from the existing one
Result: The new album gets loaded, the file gets moved there and the old album gets removed
Expected result: The old album is kept, as it contains unmatched files
This also fixes the album file count that broke with https://github.com/metabrainz/picard/pull/1700
=> PICARD-2062: Do not remove files with unmatched tracks after track search

.github/workflows/package.yml, requirements-build.txt
=> PICARD-2067: Fix crash on Windows startup

picard/util/imageinfo.py
=> Use classes for image type identification code

picard/mbjson.py, picard/track.py, test/data/ws_data/recording.json, test/data/ws_data/release.json, test/test_mbjson.py
* This is a…
* JIRA ticket (_optional_): PICARD-204
This is an alternative implementation of https://github.com/metabrainz/picard/pull/1732
Provide variables `%_recording_firstreleasedate%` and `%_releasegroup_firstreleasedate%` and set `originaldate` / `originalyear` for non-album tracks. For releases the tag variables for `originaldate` and `originalyear` will still be set from the release group's first release date, but the user can choose to use the recording date instead.
E.g. things like this are possible:
```
$set(originaldate,$if2(%_recording_firstreleasedate%,%_releasegroup_firstreleasedate%))
```
```
$set(originaldate,$if($inmulti(%releasetype%,compilation),%_recording_firstreleasedate%,%_releasegroup_firstreleasedate%))
```
=> PICARD-204: Support for recording-level original release date in scripting

picard/cluster.py, picard/ui/scriptsmenu.py
* This is a…
Manually run scripts can modify the display of the "Unclustered Files" / "Unmatched Files" special cluster entries.
* JIRA ticket (_optional_): PICARD-2113
Prevent manually run scripts modifying the special "Unclustered Files" / "Unmatched Files" clusters.
=> PICARD-2113: Do not run scripts on special clusters

picard/ui/mainwindow.py
* This is a…
In case both clusters and other items where selected this could fail. The assumption that the first selected object is always a cluster was wrong. 
* JIRA ticket (_optional_): PICARD-1528
Get the first actual cluster from the selected objects
=> PICARD-1528: Fix crash on "search similar albums"

picard/album.py, picard/mbjson.py, test/data/ws_data/release.json, test/test_mbjson.py
* This is a…
* JIRA ticket (_optional_): PICARD-2124
Make the release annotation available to scripting using the `%_releaseannotation%` variable.
Include the annotation in the WS response and fill the variable.
=> PICARD-2124: Add and fill _releaseannotation variable

picard/browser/browser.py, picard/tagger.py
* This is a…
Refactor browser integration to use `http.server` instead of the custom HTTP implementation and implement CORS support to fix PICARD-715 and PICARD-2126
The integration has been tested with Firefox, Google Chrome and MS Edge. It has also been tested with [MB auto tagger user script](https://github.com/phw/musicbrainz-auto-tagger-button).
* JIRA ticket (_optional_): PICARD-2126, PICARD-715
* #1752
For future proof browser integration Picard should handle CORS requests. The current custom HTTP implementation makes this harder to do and maintain as we start to implement more HTTP features.
Replace the custom HTTP implementation with `http.server` and add CORS handling on top of it.
=> Refactor browser integration to use http.server and implement CORS support

requirements-macos-10.14.txt, requirements-win.txt
* This is a…
Most importantly this brings "Fixed a number of potential deadlocks in QSettings and QLibraryInfo.location().", which would also solve PICARD-2088. We have a workaround for this, but can this way prepare to maybe have the workaround optional in the future.
=> Use PyQt 5.15.3 for Windows and macOS 10.14 builds

picard/ui/filebrowser.py
* This is a…
* JIRA ticket (_optional_): PICARD-2136
By default on a fresh install the file browser is supposed to start in the user's home directory. This does not work on macOS.
The cause is that the file browser shows the contents of `/Volumes`, which contains a list of all mounted drives / partitions. One of those is the current boot volume, let's call it `System`. *The name can be different, e.g. it might be "Macintosh HD", not sure what the current default value is on new macOS installs. Anyway, mine is called "System" for some reason, so let's use that as an example.* This boot volume is actually mounted at `/` and `/Volumes/System` is a symlink to `/`.
Now the home directory via `$HOME` is reported as e.g. `/Users/theuser`, but the …
=> PICARD-2136: Fixed file browser using correct home folder on macOS

.github/workflows/run-tests.yml, INSTALL.md, setup.py
* This is a…
Some of the features that might be interesting for us:
- [PEP 498](https://www.python.org/dev/peps/pep-0498/) f-strings (be careful and don't use for translations, though)
- [PEP 519](https://www.python.org/dev/peps/pep-0519/) file system path protocol
In addition:
- Python 3.6 would also have been beneficial in https://github.com/metabrainz/picard/pull/1761 for `Enum._missing_`.
- The bdist packages we build for Windows and macOS are already for 3.6 and later only (because of some issue with the required build tools not supporting 3.5, I currently don't remember the details)
- Even Ubuntu 18.04 already had Python 3.6, but it does not have the required Qt 5.10. Older Linux versions still on 3.5 likely don't fulfill the Qt …
=> Python 3.6 is now the minimum supported version

.github/workflows/package.yml
* This is a…
Fix macOS app automatically detecting dark mode.
* JIRA ticket (_optional_): PICARD-2144
While automatic dark mode detection was running in theory, because Qt5 supports it, it was not working for our binary builds. The reason is that macOS only activates this for an app if it was build for macOS 10.14 or later, but the default PyInstaller bootloader is compatible with older versions.
Use a custom build of PyInstaller. For the resulting binary macOS now assumes that it does support dark mode.
=> PICARD-2144: Fix automatic dark mode detection on macOS

picard/ui/options/interface.py, picard/ui/theme.py
* This is a…
Add descriptive tooltips to theme selector (combo box), and move code specific to user interface to where it is used.
=> Add tooltips to theme combo box items, providing a description

picard/ui/mainwindow.py
to close [PICARD-216](https://tickets.metabrainz.org/browse/PICARD-2164)
* This is a…
=> PICARD-2164: Adding shortcut for search similar track : crtl+T

picard/ui/theme.py
* This is a…
Seems like I've forgotten to force a theme once loaded when the Default option was selected, allowing for on-the-fly theme changes. However, some palettes get initialized before the theme itself, leading to the reported issue.
* JIRA ticket (_optional_): PICARD-2160
Enforce current Mac Appearance during the MacTheme setup, locking it to either the Light or the Dark theme.
=> PICARD-2160: Dark Mode switching does not change list elements leading to mix of light and dark mode.

picard/util/imagelist.py
* This is a…
Make selection updates faster by comparing less stuff.
When the selected items change, the metadatabox triggers an update of the coverart box, which compares and selects unique images to display.
* JIRA ticket (_optional_): PICARD-2162
Replace the comparison of sets of images by a dictionary update. If the dictionary grows, new images were found and the 'changed' flag is set. If size remains the same, nothing changes.
=> PICARD-2162: Improve performance of coverart box when selecting multiple files

picard/script/functions.py, test/test_script.py
* This is a…
* **Describe this change in 1-2 sentences**:  This adds a new scripting function `$uniquemulti()` to remove duplicate items from a multi-value variable.
Duplicate items can be created in a multi-value variable when combining lists such as genres.  There is no easy way to remove duplicate entries.
* JIRA ticket (_optional_): PICARD-2161
Add a new scripting function `$uniquemulti()` to remove duplicate entries.  Include an option to do case-sensitive comparisons.
Note to update the Picard documentation to include this new function.
=> PICARD-2161: Add function to remove duplicate entries from multi-value variable

picard/ui/mainwindow.py
* This is a…
* JIRA ticket (_optional_): PICARD-2173
Disable "Search for similar tracks" by default, as it is done with other actions that get activated only on selection changes.
Also update action callbacks that handle exactly one item to return if not item is selected. This prevents similar bugs in the future should an action be accessible without selection for some reason.
=> PICARD-2173: "Search for similar tracks" is enabled by default, causes crash if used without selection

picard/ui/mainwindow.py
* This is a…
* JIRA ticket (_optional_): PICARD-2150
The metadata view can take quite a lot of space, especially on small screens. While it can be resized sometimes it would be good to have it out of view. In the past users could completely hide it by dragging it down. We disabled this as users accidentally lost access to this view without a proper UI hint how to get it back.
Add an action to the View menu to show/hide the metadata view, together with a keyboard shortcut.
=> PICARD-2150: Allow user to hide metadata view

picard/const/__init__.py, picard/coverart/image.py, picard/ui/options/cover.py
=> Define default cover art filename in DEFAULT_COVER_IMAGE_FILENAME

installer/picard-setup.nsi.in
* This is a…
* JIRA ticket (_optional_): PICARD-2184
Running the Windows installer with the /S flag will now not show any dialog and perform all default actions, including uninstalling the previous version.
Detect whether the installer runs in silent mode. Set defaults for MessageBox and for uninstall of previous version also run the uninstall in silent mode.
See https://nsis.sourceforge.io/Docs/Chapter4.html#silent for technical background.
=> PICARD-2184: Allow completely silent Windows installer

picard/album.py, picard/cluster.py, picard/file.py, picard/track.py, picard/ui/item.py
=> Cover art number column rework

picard/const/__init__.py, picard/ui/tagsfromfilenames.py
* This is a…
* JIRA ticket (_optional_): PICARD-2201
Add a help button to the "Tags from file names" dialog that opens the documentation at https://picard-docs.musicbrainz.org/en/usage/tags_from_file_names.html
=> PICARD-2201: Add a help button to "Tags from file names" dialog

picard/album.py, picard/config.py, picard/ui/itemviews.py, picard/ui/mainwindow.py
* This is a…
Please check carefully
=> Remove unused stuff

picard/const/__init__.py
* This is a…
* **Describe this change in 1-2 sentences**:  Update the default file naming script to automatically pad the disc number if %totaldiscs% is greater than nine.
* JIRA ticket (_optional_): PICARD-563
Update the default file naming script to automatically pad the disc number if %totaldiscs% is greater than nine.
=> PICARD-563: Pad disc number if more than nine discs

picard/ui/widgets/scripttextedit.py
* This is a…
* JIRA ticket (_optional_): PICARD-2207
This shows a function's documentation or the Unicode character name for a Unicode escape sequence as a mouse over tooltip in the script editor.
Listen to mouse move events in the script editor. Determine the document position for the mouse cursor and check whether there is a matching entity (function or unicode escape) at that position by backtracking until either `$`  or `\u` is being found. Then handle getting proper tooltip depending on the entity.
Functions will show the documentation:
For control characters it will show the Unicode name and if it is a printable character also the character itself:
For control characters only the name is shown:
=> PICARD-2207: Show script editor tooltips for functions and Unicode escapes

picard/ui/scripteditor.py
* This is a…
* JIRA ticket (_optional_): PICARD-2179
Persist the state of the scripting docs in the script editor dialog.
=> PICARD-2179: Persist state of scripting docs pane

picard/ui/options/renaming.py, picard/ui/scripteditor.py
* This is a…
* JIRA ticket (_optional_): PICARD-2179
As discussed in #1816 also preserve the window geometry of the script editor, including the state of the splitters.
Make use of save/restore geometry provided by base class PicardDialog
=> PICARD-2179: Preserve script editor window state

.github/workflows/codeql-analysis.yml
Warning: 1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
* This is a…
Warning: 1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
Remove useless stuff
=> Fix and simplify CodeQL workflow

requirements.txt, setup.py
* This is a…
- We frequently forget to update setup.py if we have changes in requirements, leading to broken builds
- We do not currently specify version restrictions in setup.py, which might cause incompatible depedencies being used by pip
- Redundancy
Read requirements.txt and use it for install_requires
I considered putting some of the dependency into extra_requires. But this is only about discid and markdown, and I think it is preferable to have both installed. Also I think it is an unneeded complication.
=> Use requirements.txt for pip package install_requires

.remarkrc, NEWS.md
=> Added configuration for remark-lint

picard/script/parser.py, test/test_script.py
* This is a…
* JIRA ticket (_optional_): PICARD-2214
A script ending with a backslash raises a `TypeError` instead of a `ScriptError`
If the script ends with a backslash (open escape sequence) raise `ScriptEndOfFile`, added tests.
Also some small refactoring to place the escape sequence parsing in a separate method, as it has started to become more complex recently.
=> PICARD-2214: fix script error

picard/script/functions.py, test/test_script.py
* This is a…
* **Describe this change in 1-2 sentences**:  Adds a new function to return the country name for a specified country code.
Release country information is provided by country code, but there is no way to get the name of the country corresponding to the code.
* JIRA ticket (_optional_): PICARD-2215
Add a new function to return the country name for a specified country code.
=> PICARD-2215: Add script $countryname() function.

picard/file.py, picard/util/__init__.py, test/test_file.py, test/test_utils.py
* This is a…
Make `tracknum_and_title_from_filename()` returns a named tuple and use Python `sets` features to find out which field is missing.
Add related tests.
=> Refactor File._guess_tracknumber_and_title() and add tests

picard/ui/options/renaming.py, picard/ui/scripteditor.py
* This is a…
* **Describe this change in 1-2 sentences**: Refactor the Script Editor to correct issue with window display on mac systems.  Also correct issue with logic when saving changes to script metadata.
The Script Editor object was being created before the Options > File Naming screen was being displayed, causing the Script Editor window to open behind the Options window on mac systems.  Also, saving script metadata always resulted in an "Unsaved Changes" dialog.
Refactor the Script Editor to correct issue with window display on mac systems.
Correct issue with logic when saving changes to script metadata.
Miscellaneous changes to reduce code duplication.
=> Refactor script editor

.github/workflows/package.yml
=> Build with Python 3.9.5 on macOS

.github/workflows/package.yml
* This is a…
* JIRA ticket (_optional_): PICARD-2231, PICARD-2230
Try to build the Windows packages with Python 3.8 again. This caused issues in PICARD-2067, but either those are now resolved or we should investigate deeper.
Not using Python 3.9, as this would drop Win 7 support. For now we can maintain Win 7 support, at least as long as there is a supported Python version and we have no other requirement forcing us to update. We still seem to have quite some users on Win 7.
=> PICARD-2231: Build with Python 3.8 on Windows

picard/browser/browser.py
* This is a…
* JIRA ticket (_optional_): PICARD-2230
An unexpected, arbitrary error in browser integration such as reported in PICARD-2230 would cause Picard not to start.
The actual core issue of PICARD-2230 is resolved by updating Python to version 3.8.10 for our Windows builds, which fixes https://bugs.python.org/issue26227.
But the general issue of bugs in browser integration will prevent Picard to start should also be addressed. After all we are dealing with setting up a local web server here, and there is all kind of stuff out of our control that can go wrong here.
=> PICARD-2230: Do not crash if browser integration fails to start or stop

picard/ui/options/renaming.py, picard/ui/scripteditor.py
* This is a…
* **Describe this change in 1-2 sentences**:  Correct the bug introduced with the changes in PR #1840 
PR #1840 changed the structure of the argument passed to the File Naming Script Metadata Editor dialog, but the processing in the dialog was not updated accordingly.
Update the processing in the File Naming Script Metadata Editor dialog to accommodate the changes to the argument provided.
Also includes one minor style cleanup that should have been included in PR #1840.
=> File naming script metadata editor bug

picard/formats/apev2.py, picard/formats/asf.py, picard/formats/id3.py, picard/formats/mp4.py, picard/formats/vorbis.py, picard/ui/options/tags.py, picard/ui/ui_options_tags.py, test/formats/common.py, test/formats/coverart.py, test/formats/test_apev2.py, test/formats/test_vorbis.py, ui/options_tags.ui
* This is a…
* JIRA ticket (_optional_): PICARD-257
Enabling "clear existing tags" removes all tags, including images. Many want to clear all textual tags, but not embedded images. This has been a recurring request over the years.
Add an option to exclude cover art from getting cleared.
=> PICARD-257: Add option to exclude embedded images from clear_existing_tags

picard/ui/options/general.py, picard/ui/options/renaming.py
=> Remove multiple declarations of options

picard/ui/mainwindow.py, picard/ui/options/renaming.py
* This is a…
There is no quick and easy way to select a file naming script to use from the main menu.
Add a new menu item under the "Options" section to select the file naming script to use.  The available scripts are listed as sub-menu items, and the currently selected script is indicated with a check mark.
=> Add naming script selector to main window menu bar

picard/config.py, picard/ui/__init__.py
* This is a…
* **Describe this change in 1-2 sentences**: Add a check for dynamically set Options (window size and splitter settings) to avoid errors when trying to define multiple times.
Dynamically set Options (window size and splitter settings) register errors when the same window is opened from different paths.  An example is the File Naming Script Editor.
Add an Option class method to check if an option exists.  Use this to check before setting window size and splitter setting Options to avoid duplicate Options.
=> Add class method to check if Option exists.

picard/config.py
* This is a…
* **Describe this change in 1-2 sentences**:  Force the profile settings key to update when a profile's settings have changed.
Changes to profile settings were not being saved to the ini file.
Force the profile settings key to update when a profile's settings have changed, and show the key as "dirty" to force the changes to be written to the ini file.
=> Force update of profile settings key

picard/ui/mainwindow.py, picard/ui/scripteditor.py
* This is a…
* **Describe this change in 1-2 sentences**: Update menu bar after profile editor closes.
Changes made in the profile editor, such as enabling/disabling profiles which changed the active file naming script, were not being reflected in the main screen menu bar.
Update menu bar settings to reflect any changes to enabled profiles when the profile editor is closed.
=> Update menu bar settings to reflect any changes to enabled profiles

picard/ui/scripteditor.py
* This is a…
* **Describe this change in 1-2 sentences**: Check is naming script is used in a profile before deleting.
There was no check, so a user could delete a file naming script that was set for use in a profile.
Check is naming script is used in a profile before deleting.
=> Check is naming script is used in a profile before deleting

picard/ui/mainwindow.py
* This is a…
* **Describe this change in 1-2 sentences**: Check the Profiles and Profile Settings values and repair if required.
It's possible that some of the profile settings in the INI file could be made invalid through some external process, which could cause issues with Picard retrieving user settings.
Check the Profiles and Profile Settings values and repair if required.
=> Clean up missing or invalid profile settings.

picard/ui/mainwindow.py, picard/ui/profileeditor.py
* This is a…
* **Describe this change in 1-2 sentences**: Change title of profile editor dialog
See discussion in the [Community Forum](https://community.metabrainz.org/t/introducing-user-profiles-in-picard/540379/11).
Change the name of the dialog.
=> Change title of profile manager dialog

picard/ui/profileeditor.py
* This is a…
* **Describe this change in 1-2 sentences**: Connect to proper signals
The profile settings tree expanded state was not being properly updated because the method was connected to the wrong signal.
Connect to the proper signals to trigger updating the list of expanded items.
=> Connect to proper signals for settings tree expand / collapse updates

picard/const/__init__.py
* This is a…
* **Describe this change in 1-2 sentences**: Correct the link to the options profile help page.
The link to the options profile help page was not updated when the name was changed from "User Profiles" to "Option Profiles".  In addition, the path was incorrect.
Fix the path and update the file name to the help page.
=> Correct link for option profiles help

picard/script/functions.py, test/test_script.py
* This is a…
* **Describe this change in 1-2 sentences**:  Add new `$year()`, `$month()` and `$day()` functions.
* JIRA ticket (_optional_): PICARD-2151
Request for helper functions to extract the different parts of a date string.
Add new `$year()`, `$month()` and `$day()` functions.
Reminder to update the documentation on https://github.com/rdswift/picard-docs/pull/104
=> PICARD-2151: Add $year(), $month() and $day() helper functions to extract date info

picard/script/functions.py
* This is a…
* **Describe this change in 1-2 sentences**:  Add a new `$is_multi()` function.
* JIRA ticket (_optional_): PICARD-2165
There is no way to check if a variable is a multi-value.  See discussion at https://community.metabrainz.org/t/function-variable-to-tell-whether-a-tag-containts-multiple-values/526594
Add a new `$is_multi()` function to check if a variable is a multi-value with more than one element.
Reminder to update the documentation.
=> PICARD-2165: Add `is_multi()` function

test/test_script.py
* This is a…
* **Describe this change in 1-2 sentences**:  Add tests for `$is_multi()` script function.
Somehow in the course of rebasing https://github.com/metabrainz/picard/pull/1868 the tests were lost and were not merged.
Add tests for `$is_multi()` script function.
=> Add tests for `$is_multi()`

picard/config.py, picard/profile.py, picard/ui/options/dialog.py, test/test_profiles.py
* This is a…
* **Describe this change in 1-2 sentences**:  Add highlighting of options manged by the selected profile in the Options dialog.
* JIRA ticket (_optional_): PICARD-2246
From the discussion:
> * The attached profiles dialog is not easy to understand. Great would be if we would have a UI that makes it clear inside the dialogs which options are being changed.
Add highlighting of options manged by the selected profile in the Options dialog.
Reminder to update the documentation.
=> PICARD-2246: Highlight items in Options dialog when profile is selected for output

picard/ui/__init__.py
* This is a…
* **Describe this change in 1-2 sentences**: Catch exception
When the automatic parent change code was added in PR #1852 it introduced a bug that would crash Picard when opening the scripting documentation from the tagging script options dialog.  The exception was:
```
File ".\picard\ui\options\scripting.py", line 111, in show_scripting_documentation
ScriptingDocumentationDialog.show_instance(parent=self)
File ".\picard\ui\__init__.py", line 155, in show_instance
if 'parent' in kwargs and instance.parent() != kwargs['parent']:
TypeError: 'ScriptingOptionsPage' object is not callable
```
Catch the exception generated.
=> Catch exception when re-parenting SingletonDialog instance

picard/ui/mainwindow.py
* This is a…
* **Describe this change in 1-2 sentences**: Process the script editor close confirmation before closing the main window.
Closing the main window with:
1. the script editor dialog open, and
2.  unsaved changes to the current script, and
3.  "Cancel" is selected in the unsaved changes confirmation dialog
causes the script editor dialog to remain open as an orphan.
Process the script editor close confirmation before closing the main window.  Abort the main window close if "Cancel" is selected from the script editor dialog.
=> Process script editor close confirmation before closing main window

picard/ui/widgets/scriptlistwidget.py
* This is a…
* **Describe this change in 1-2 sentences**:  Replace blank tagging script names with default name.
* JIRA ticket (_optional_): PICARD-2253
When renaming a tagging script, Picard allows the new name to be blank.
After a change is made, check if the tagging script name is blank and replace the blank name with the default name.
=> PICARD-2253: Replace empty script name with default after edit.

picard/script/functions.py
* This is a…
* JIRA ticket (_optional_): PICARD-2254
Wrong split if the performance tag contained more than one colon.
Fixed call to split, the number is not the count of expected parts, but of the splits to perform.
=> PICARD-2254: Fixed crash in $performer

picard/ui/filebrowser.py
* This is a…
* JIRA ticket (_optional_): PICARD-2248
Currently the file browser always gets initialized, even if the user does not use it and it never gets displayed.
Lazily initialize the file browser on first display.
Trigger for this was one reported instance were the file browser hang on reading the file system. While this was in the end an issue with the filesystem setup and very specific, it was still surprising that it triggered even without the file browser being shown.
=> PICARD-2248: Initialize filebrowser model lazily on first view

picard/ui/scripteditor.py
* This is a…
* **Describe this change in 1-2 sentences**:  Add context menu item on script title to open the metadata editor.
The file naming script editor does not currently allow changing the title of a script from the main screen, but there was no indication to the user how the title could be changed.
Add options for editing the script title.  Also fix the title display of the metadata editor window.
- Add double click action to open the script metadata editor
- Add right click context menu to open the script metadata editor
- Fix title display of script metadata editor window
Remember to update the documentation.
=> Add options for editing the script title

picard/script/serializer.py, picard/ui/options/scripting.py, picard/ui/scripteditor.py
* This is a…
There was code duplication for the script import/export functionality between the tagging and file naming script editor dialogs.
Move the script import/export functionality into the `PicardScript` class.
=> Refactor to use common code for script import/export

picard/ui/options/dialog.py, picard/ui/options/profiles.py
* This is a…
In the course of changing the profile editor from a stand-alone dialog to an options page, the tooltips showing the current value for a profile option setting were lost.
Also, the persistent settings were no longer being updated because the dialog close event was not being triggered.
Re-implement the profile option settings tooltips, and move saving the persistent settings to the `save` method on the page.
=> Add profile option setting tooltips and fix saving persistent settings

picard/ui/options/cover.py
* This is a…
When reloading the list of CA providers after making changes to profiles, the items would be appended to the existing list (creating multiple copies of the items).
Clear list before adding providers when loading.
=> CA providers list shows multiple copies of the items after making changes to profile settings

picard/ui/scripteditor.py
* This is a…
1. The titles of the preset file naming scripts were not being translated when added to the script selector combo box.
1. The titles displayed on the script editor and script metadata editor windows were not being translated.
1. There were some unused constants remaining after the refactoring of the script import/export code.
1. Translate the titles of the preset file naming scripts when they are added to the script selector combo box.
1. Translate the titles displayed on the script editor and script metadata editor windows.
1. Remove the unused constants.
=> Script editor miscellaneous cleanup

picard/formats/id3.py, test/formats/test_id3.py
* This is a…
* JIRA ticket (_optional_): PICARD-2263
Tags "performer" (without role) do not get saved to TMCL (or TIPL for ID3v2.3), instead a separate TXXX:performer is created. "performer:" (colon, but empty role) did not get saved at all.
Save to TMCL with a role of "performer".
=> PICARD-2263: Save performers without role to TMCL / TIPL

picard/ui/options/acousticbrainz.py
* This is a…
* JIRA ticket (_optional_): PICARD-2265
AcousticBrainz extractor path should not be None, but it can happen if the extractor is not in the PATH.
If None, just continue with the placeholder instead of trying to check the version of a non-existing extractor.
=> Picard-2265: Prevent None from being fed to ab_check_version

picard/acousticbrainz/__init__.py, picard/acousticbrainz/extractor.py, picard/ui/options/acousticbrainz.py
- do not output error when this feature was never set
- display a tooltip on download button
- (always) set a translatable place holder for path input field
- let user edit the path directly
- ensure extractor validity is checked after browsing for it
* This is a…
=> Simplify AcousticBrainz extractor settings

picard/ui/aboutdialog.py
* This is a…
* **Describe this change in 1-2 sentences**: Add a line to the "About" dialog showing the path and filename of the current configuration file.
* JIRA ticket (_optional_): PICARD-2278
There is no way to see which configuration file is currently being used, or any (easy) way for the user to find out the location of the configuration file.
Add a line to the "About" dialog showing the path and filename of the current configuration file.
Possibly update the Troubleshooting section of the documentation.
=> PICARD-2278: Show path to config file in About dialog.

.github/workflows/package.yml, requirements-build.txt, scripts/package/macos-package-app.sh
=> Build with PyInstaller 4.5.1

picard/formats/id3.py, test/formats/test_id3.py, test/test_compatid3.py
* This is a…
Add a `Id3Encoding` enum to replace the hardcoded magic numbers used in `picard.formats.id3`.
See also discussion at https://github.com/metabrainz/picard/pull/1912
=> Add Id3Encoding enum

.github/workflows/package.yml, scripts/package/macos-setup.sh
* This is a…
* JIRA ticket (_optional_): PICARD-1734
The official binaries for the Essentia extractor offered by AcousticBrainz cannot be used because they are build with an SDK older than SDK 10.9 and hence cannot be notarized. See also https://github.com/metabrainz/picard/commit/d9d748e423c37b18095d8340573c1a2b49253677
Use the for now unofficial builds from https://github.com/phw/essentia-extractor-builds/releases/tag/v2.1_beta2_1 which are compiled with newer SDK.
=> macOS: Build with newer essentia extractor binary

installer/i18n/nshutil.py, picard/cluster.py, picard/formats/apev2.py, picard/formats/asf.py, picard/formats/id3.py, picard/formats/mp4.py, picard/formats/mutagenext/compatid3.py, picard/formats/vorbis.py, picard/mbjson.py, picard/metadata.py, picard/script/functions.py, picard/track.py, picard/ui/coverartbox.py, picard/ui/edittagdialog.py, picard/ui/itemviews.py, picard/ui/metadatabox.py, picard/ui/widgets/editablelistview.py, picard/ui/widgets/scripttextedit.py, picard/util/__init__.py, picard/util/icontheme.py, picard/util/imageinfo.py, picard/version.py, scripts/tools/fix-header.py, setup.py, test/formats/common.py, test/formats/test_apev2.py
* This is a…
In conditionals instead of comparing a value against multiple values in a list or tuple use sets. It doesn't make much difference in practice overall, but it technically makes sense. Also in my tests using  `x in {'foo', 'bar', 'baz'}` is 8% faster then `x in ['foo', 'bar', 'baz']` or `x in ('foo', 'bar', 'baz')`. There is no difference in using tuples or lists.
See also discussion at https://github.com/metabrainz/picard/pull/1933
=> Check in sets

test/test_file.py
=> Add tests for File._compile_move_additional_files_pattern()

picard/file.py, test/test_file.py, test/test_filesystem.py
=> Rework additional files methods

picard/util/__init__.py, test/test_utils.py
* This is a…
* JIRA ticket (_optional_): PICARD-2327
Picard uses picard.util.is_hidden to check whether a file is hidden. This is used in some places, e.g. Picard by default skips loading hidden files, unless explicitly added.
This works on Windows (with Windows hidden file attribute). On other platforms dot files are considered hidden. But on macOS it does not honor the hidden file attribute.
Use macOS API to query hidden state of files. As there are multiple ways why a file can be considered hidden this provides an up-to-date solution even in case of changes. See also https://stackoverflow.com/questions/284115/cross-platform-hidden-file-detection
Added a macOS specific test.
=> PICARD-2327: Detect hidden files on macOS

picard/i18n.py
* This is a…
Apply some refactoring to `picard.i18n`  to reduce code complexity and make it more readable.
=> Simplify i18n.setup_gettext

picard/file.py, test/test_file.py
=> File.update() rework & testing

picard/ui/mainwindow.py
* This is a…
* **Describe this change in 1-2 sentences**: Update the script quick selector after enabling/disabling profiles from the quick selector.
* JIRA ticket (_optional_): PICARD-2329
When profiles are enabled or disabled from the quick selector on the main screen menu, the selected file naming script shown as being enebled in the quick selector is not being updated.
Update the script quick selector after enabling/disabling profiles from the quick selector.
None.
=> PICARD-2329: Update naming script quick selector after enabling/disabling profiles

picard/util/cdrom.py, test/test_util_cdrom.py
* This is a…
Refactor and simplify `picard.util.cdrom`.
- Reduce code complexity
- Remove dependency on Qt by using Python standard file operations
- Add tests
=> Refactor picard.util.cdrom

picard/util/cdrom.py
- iterate through f directly, no need of readline()
- look for 'drive name:' prefix first, and if found, look for 'Can play audio:'
- break ASAP
- do not split lines, use startswith() and splice on length
* This is a…
=> _parse_linux_cdrom_info(): optimize a bit

picard/ui/options/renaming.py
* This is a…
* **Describe this change in 1-2 sentences**: Synchronize changes between script editor and Options dialog
* JIRA ticket (_optional_): PICARD-2330
See the discussion in the ticket.
Pending changes to file naming scripts were not being displayed if the script editor was closed and then re-opened from the Options settings dialog.
Synchronize changes between script editor and Options dialog.
=> PICARD-2330: Synchronize changes between script editor and Options dialog

picard/acoustid/__init__.py
=> Acoustid tasks

picard/album.py, picard/util/__init__.py, test/test_utils.py
* This is a…
Optimize find_best_match(): use max() instead of sort_by_similarity()
- drop unused `num_results` from `BestMatch` namedtuple
- use `max()` along its `key` and `default` arguments, it is much simpler and faster
Optimize _match_files(): move threshold matching to candidates()
- whatever is the best match, it is discarded if it doesn't match the threshold
- `best_match` will be `no_match` if none of the candidates matches
- removing candidates based on threshold reduces the number of iterations to find best match
=> Album matching optimizations

picard/acoustid/__init__.py
* This is a…
- it was logged more than once
- move outside the loop
- add the number of found recordings
=> Fix AcoustID succesful lookup debug logging

picard/acousticbrainz/__init__.py, picard/tagger.py, picard/ui/mainwindow.py, picard/ui/options/acousticbrainz.py, test/test_acousticbrainz.py
- use a cache to prevent useless version & sha calculations
- based cache key on stat.st_mtime_ns + path
- declare ab_extractor as a property of tagger class
- pass tagger to all methods that needs it
* This is a…
=> Introduce new class ABExtractor in order to get extractor dynamically

picard/album.py, picard/track.py
=> Album cleanup

picard/util/script_detector_weighted.py, test/test_util_script_detector_weighted.py
=> Fix typo: threshhold -> threshold

picard/cluster.py
=> Cluster match cleanup

picard/cluster.py, picard/tagger.py, test/test_clustering.py
* This is a…
* JIRA ticket (_optional_): PICARD-2339
The existing clustering code is using the Levenshtein distance to calculate similarity, which caused a O(n^2) performance. But since only exactly similar matches are being used (similarity threshold 1.0) this was is not strictly necessary.
If we don't use a threshold (and Picard never did) then we can simplify the code.
This new implementation uses simple comparison for string equality and performs in O(n).
Added tests to verify consistent behavior.
There is a small change in behavior: Previously if there were multiple different spelling for what is considered the same album title the last encountered spelling would be used. The new implementation uses the first one.
See …
=> PICARD-2339: Faster clustering implementation

picard/cluster.py
=> cluster(): simplify even more

picard/album.py, picard/cluster.py, picard/track.py
* This is a…
Small simplifications and harmonization of the methods to query the core entities abilities (mostly the `can_*` and `is_*`  methods).
=> Simplify / harmonize Item ability methods.

picard/album.py
=> Album minor simplifications

picard/file.py, picard/formats/id3.py, picard/ui/metadatabox.py
=> Use Counter instead of defaultdict where applicable

installer/i18n/nshutil.py, picard/coverart/image.py, picard/coverart/providers/__init__.py, picard/coverart/utils.py, picard/formats/apev2.py, picard/formats/asf.py, picard/formats/id3.py, picard/formats/mp4.py, picard/formats/vorbis.py, picard/formats/wav.py, picard/releasegroup.py, picard/script/parser.py, picard/track.py, picard/ui/aboutdialog.py, picard/ui/edittagdialog.py, picard/ui/infodialog.py, picard/ui/item.py, picard/ui/options/plugins.py, picard/util/__init__.py, picard/util/imageinfo.py, picard/util/imagelist.py, picard/util/progresscheckpoints.py, picard/util/textencoding.py, picard/util/versions.py, setup.py, test/formats/test_midi.py, test/test_config.py, test/test_coverartprovider_caa.py
* This is a…
Minor code cleanup
- Use generator comprehension where possible
- Prefer dict comprehension over dict([...])
- General code cleanup
=> Various minor code cleanups

picard/dataobj.py, picard/track.py, test/test_dataobj.py, test/test_taggenrefilter.py, test/test_track.py
=> Convert DataObject.genres to Counter, simplfify _convert_folksonomy_tags_to_genre()

picard/mbjson.py, test/test_mbjson.py
=> Rework release_dates_and_countries_from_node() & countries_from_node()

picard/mbjson.py, test/test_mbjson.py
=> Introduce _node_skip_empty_iter() to reduce code redundancy

picard/ui/options/scripting.py
* This is a…
* **Describe this change in 1-2 sentences**:  Add a check for an empty list of selected scripts to avoid an exception when trying to get the selected script in the list.
* JIRA ticket (_optional_): PICARD-2345
When changing profile settings in the Options dialog, it is possible to cause an exception from the Scriping page due to there not being a script selected.
Add a check for an empty list of selected scripts to avoid an exception when trying to get the selected script in the list.
=> PICARD-2345: Check for empty list to avoid exception

picard/profile.py
* This is a…
* **Describe this change in 1-2 sentences**:  Add additional settings to option profiles.
* JIRA ticket (_optional_): PICARD-2344
There are additional settings that could be managed using option profiles.
Add (appropriate) selected settings to those managed by an option profile from the following Options pages:
- General settings
- User Interface settings
- Advanced settings
Review documentation to see if an update is required.
**EDIT:** The documentation text still seems okay, but 3 images need to be updated.
=> PICARD-2344: Add more settings to option profiles

picard/webservice/__init__.py, test/test_webservice.py
* This is a…
Move the request task queue handling of the `WebService`  class to a separate `RequestPriorityQueue` class.
This simplifies testing of the functionality and reduces complexity of the `WebService` itself. Also applied some minor additional refactoring.
=> Refactor webservice queue

scripts/package/macos-package-app.sh
=> Workaround hdiutil: create failed - Resource busy with a loop/delay

picard/file.py, test/formats/test_id3.py
* This is a…
Fixes a regression introduced in a5fcde to optimize display of format specific metadata, see PICARD-2174. This removed comparing against format specific metadata, see https://github.com/metabrainz/picard/commit/a5fcde1dd3d54e7970efcef816aa24f8efc983fe#diff-8e9e6145ecc7e912b2d643f5064e6f196d3668bd010ffa6037775232c2aba236L633
Restore comparing to format specific metadata by calling `File.format_specific_metadata`  in `File.update`.
=> PICARD-2346: Fix ID3v2.3 files showing changes with identical tags

picard/similarity.py, test/test_similarity.py
- we mainly use this method to match tracks & files, and the common case is perfect match
- astrcmp() call is expensive (even for the C version)
- if lengths are identical, and lists are perfectly identical, just return 1.0
- we don't need total, as it is equal to len(alist) when exiting the loop
- with test `if not alen or not blen` we are sure a division by zero cannot occur
The gain is marginal on random strings, but in practice we compare much more identical strings than different strings.
* This is a…
=> Add more tests and optimize similarity2()

picard/tagger.py, picard/ui/mainwindow.py
* This is a…
* JIRA ticket (_optional_): PICARD-2353
Due to running the clustering in a thread the code to update the selection no longer was guaranteed to run after the clustering.
Run relevant code in a callback
=> PICARD-2353: Fix updating selection after clustering

picard/log.py, picard/ui/logview.py
* This is a…
* JIRA ticket (_optional_): PICARD-2352
Incorrect initial value of `_prev_logitem_level` after clear or verbosity change.
Properly reset `_prev_logitem_level` after a clear or a verbosity change.
The best way to ensure it is correct, is to overload `display()`
In the process, I also converted `log.contents()` to a generator, that makes much more sense as it is used only in a `for`.
=> PICARD-2352: Fix log view colors after clear

picard/ui/mainwindow.py
=> Mainwindow cleanup: cosmetic changes

picard/tagger.py
=> cluster(): get_files_from_objects() -> iter_files_from_objects()

picard/ui/itemviews.py
=> dropMimeData(): use iter_files_from_objects()

picard/ui/mainwindow.py
=> Mainwindow cleanup: get rid of get_files_from_objects()

picard/tagger.py
* This is a…
* JIRA ticket (_optional_): PICARD-2367
Dragging an album to the "Clusters" item triggers a crash with 
```
File "/home/phw/devel/musicbrainz/picard/./picard/tagger.py", line 528, in move_files
self.cluster(files)
File "/home/phw/devel/musicbrainz/picard/./picard/tagger.py", line 910, in cluster
if len(objs) <= 1 or self.unclustered_files in objs:
TypeError: object of type 'generator' has no len()
```
That's caused by the change in #1991, where the dropped files are now passed as an iterator instead of a list.
Make tagger.cluster be able to handle an iterator instead of a list
=> PICARD-2367: Fix crash when moving album to cluster

picard/cluster.py, picard/file.py, picard/tagger.py
* This is a…
* JIRA ticket (_optional_): PICARD-2366
Auto analyze / auto cluster only works when files are added via drag and drop, but not if added via Add files / Add folder dialogs. That's because in this case there is not drop target, but Tagger.move_files still did consider them having been moved to a proper target.
Handle `None`  target.
Also ensure the real target the file has been moved to is considered, as files might get moved to different target for various reasons. E.g. dropping a file onto a file will move the file to the target file's parent. If that is unclustered files the real target is unclustered files and the auto features should trigger.
=> PICARD-2366: fix auto analyze

.github/workflows/package.yml, scripts/package/macos-setup.sh
* This is a…
As we are downloading third party components that we then code sign and bundle in our macOS builds, verify we got the right binaries by checking their SHA256 hash.
=> packaging: verify checksums for macOS downloaded dependencies

picard/album.py, picard/dataobj.py, picard/track.py, picard/webservice/api_helpers.py, test/test_dataobj.py
=> Use set+tuple for inc, and tuple for path_list, instead of lists

picard/webservice/api_helpers.py, test/test_api_helpers.py
=> Test mb api ratings xml

picard/webservice/api_helpers.py, test/test_api_helpers.py
- add batch size as parameter
- use range() step and do not modify passed releases argument
- add test
* This is a…
=> Simplify & test MBAPIHelper._collection_request()

picard/webservice/api_helpers.py, test/test_api_helpers.py
=> Rework AcoustIdAPIHelper and add few tests

picard/file.py, test/formats/common.py, test/test_file.py
- add a test for File._copy_file_info_tags()
* This is a…
=> Move FILE_INFO_TAGS to File class and reduce code redundancy

picard/album.py
- move parts of the code to new `_finalize_loading_album()` and `_load_tracks()`
- re-order code a bit: move `_finalize_loading_track()` above `_load_tracks()` (where it is used)
- reduce code indentation
* This is a…
=> Album._finalize_loading(): split in smaller methods

picard/formats/mp4.py
* This is a…
* JIRA ticket (_optional_): PICARD-2388
MP4 files sometimes come with the .m4r file extension, indicating iTunes Ringtone files.
Just like with other MP4 specific file extensions like .m4a or .m4v this extension is just for indicating the content and intended use. The file itself is just in MP4 format.
See also:
- https://www.lifewire.com/m4r-file-2621960
- https://en.wikipedia.org/wiki/MPEG-4_Part_14#Filename_extensions
Add `.m4r` to known MP4 file extensions
=> PICARD-2388: Support .m4r file extension for iTunes Ringtone files

picard/tagger.py
=> Generate plugin directories, simplify code

picard/i18n.py
* This is a…
* JIRA ticket (_optional_): PICARD-2389
On Windows 10 and 11 (not tested on older versions) Picard logs an "unsupported locale settings" error when starting with a specific language configured.
The issue is that it tries to set the locale with encoding using locale.getpreferredencoding().
But this the encoding returned here might actually not be valid for the locale. E.g. on my systems it returns "cp1252". But locale.setlocale('de_DE.cp1252') fails. Only locale.setlocale('de_DE.UTF-8') or locale.setlocale('de_DE') would work (the latter without encoding would fail on Linux and likely macOS).
The result is that Picard will show in different language (because this is handled by gettext separately), but the locale settings will be set …
=> PICARD-2389: Fix setting locale from UI language on Windows

picard/oauth.py, picard/tagger.py, test/test_oauth.py
=> Oauth code tidy up

picard/tagger.py, picard/ui/mainwindow.py
=> Move (copy|paste)_files() to ui mainwindow as they are only used there

scripts/package/macos-package-app.sh
* This is a…
* JIRA ticket (_optional_): PICARD-2395
This is a regression on PICARD-1943
Revert "Removed Qt translations workaround no longer needed with current PyInstaller"
This reverts commit 5f0e59838568e5b9000a94d4a3f825f03300bf5f.
=> PICARD-2395: Fix macOS 10.13 app signature issues

picard/ui/ui_options_script.py, ui/options_script.ui
* This is a…
* **Describe this change in 1-2 sentences**: Add clarification text to scripting options ui.
* JIRA ticket (_optional_): PICARD-2379
It is not intuitive what the check boxes signify on the scripting options page.
Add clarification text to scripting options ui.  Example showing proposed changes:
As I understand the plans, changes requiring additional translation will be held until the Picard 2.8 release.
Update screen shot in the documentation.
=> PICARD-2379: Add clarification text to scripting options ui

picard/ui/ui_options_releases.py, ui/options_releases.ui
* This is a…
* JIRA ticket (_optional_): PICARD-2369
As noted in PICARD-2360 the naming "Preferred release formats" is misleading, as it actually checks the formats of the individual mediums the matched track appears on.
Rename "Preferred release formats" to "Preferred medium formats"
Hold merge until preparing for Picard 2.8 release.  Once merged, update documentation.
=> PICARD-2369: Rename "Preferred release formats" to "Preferred medium formats"

picard/ui/mainwindow.py
=> Mainwindow actions: split code in smaller bits

picard/acousticbrainz/extractor.py
* This is a…
* JIRA ticket (_optional_): PICARD-2401
Increase timeout for executing the AB streaming extractor to 10 seconds.
=> PICARD-2401: Increase timeout for check_extractor_version

picard/script/functions.py, test/test_script.py
* This is a…
* **Describe this change in 1-2 sentences**: Make 'end' argument optional for `$substr()` function.
* JIRA ticket (_optional_): PICARD-2402
There has been some confusion with users about the optional 'end' parameter to the `$substr()` function, not understanding that they still need to include the parameter as an empty string.  See this [post in the Community Forum](https://community.metabrainz.org/t/plug-ins-dont-seem-to-work/568394/6) for example.
Make the 'end' argument truly optional for `$substr()` function, such that you no longer need to include a blank value.
Update documentation.
=> PICARD-2402: Make 'end' argument optional for `$substr()` function

picard/album.py
* This is a…
* JIRA ticket (_optional_): PICARD-2398
This is an extension to #2036, which handled the loading of recording relationships for large releases, where the MB API omits the per recording relationships for performance reasons.
In the previous commit these separately loaded relationships where not available to plugins registering an album metadata processor, because those were run before the relationship loading. This PR fixes this.
Call `run_album_metadata_processors` after the web service calls to load the album's recordings.
This requires that the separately loaded recording relationships need to get merged into the loaded `self._release_node`  earlier, handling this merging in `_finalize_loading_track` is too late.
It is also …
=> PICARD-2398: Ensure recording relationships are available to album metadata processors

picard/mbjson.py
* This is a…
Avoid repeated calls to `get_config` in mbjson, also reworked `_relation_attributes`  to use a tuple.
=> mbjson minor cleanups

picard/browser/addrelease.py
PICARD-2407, MBS-12179
When you Add cluster as release, the tport is lost on MBS and Green Tagger buttons disappear.
My code here does certainly not compile.
I need help finalising this PR.
I know nothing about Python.
I saw `self.local_port` from here https://github.com/metabrainz/picard/blob/14ce07756eb101d62100fb6ab8800ae644c372a2/picard/browser/filelookup.py#L77
But it certainly does not work in this context, here, unfortunately.
However, I did some tests on how to send tport=8000:
It does not work when it is sent with the other `POST` parameters.
> <ins>[action="/release/add" + POST parameters include tport=8000](http://jesus2099.gitlab.io/forward-request.html?_method=post&_action=https%3A%2F%2Fmusicbrainz.org%2Frelease%2Fadd&tport=8000&name=Tutu&artist_credit.names.0.artist.name=Toto …
=> PICARD-2407: Send tport with Submit cluster as release

picard/ui/widgets/scripttextedit.py
* This is a…
The `%_musicbrainz_tracknumber%` variable was missing from the scripting autocomplete list.
Add to the list.
None.
=> Add `_musicbrainz_tracknumber` to scripting variables list

picard/ui/ui_exception_script_selector.py, picard/ui/ui_options_metadata.py, picard/ui/ui_options_renaming.py, picard/ui/ui_options_script.py, picard/ui/ui_scripteditor_details.py, ui/exception_script_selector.ui, ui/options_metadata.ui, ui/options_renaming.ui, ui/options_script.ui, ui/scripteditor_details.ui
* This is a…
* **Describe this change in 1-2 sentences**: Clarify the script types in the UI files
The word "script" is used in a few places in the Picard UI, but refers to different things which could lead to confusion.  For example, it could refer to a tagging script, file naming script, or the script used for a selected locale.
Clearly identify the type of script (i.e.: "tagging script", "file naming script" and "language script") in the UI.  This should help clarify for the translations.
=> Clarify script types in strings in the UI files

picard/mbjson.py, test/data/ws_data/artist_arabic.json, test/test_mbjson.py
=> Translate artist node cleanup

picard/util/__init__.py, test/test_utils.py
* This is a…
* JIRA ticket (_optional_): PICARD-2414
Test some more real world examples and ignore cases like UB40 where a no. follows directly on alphanumeric characters.
=> PICARD-2414: Added some additional tests for tracknum_and_title_from_filename

picard/album.py
* This is a…
* JIRA ticket (_optional_): PICARD-2421
Improve the matching of files tagged with MBIDs to tracks of a recording.
Instead of only matching by recording ID also consider the track ID. In case of ambiguity use the track duration to find the better match. This gives better results if recordings for tracks got changed.
See discussion at https://community.metabrainz.org/t/picard-confused-when-recordingids-swap-around-in-a-release/572514/ for more details.
When matching also include the `musicbrainz_trackid`  in the track cache and use duration for similarity score.
=> PICARD-2421: Consider MB track ID when matching tagged files to albums

picard/browser/addrelease.py
* This is a…
* JIRA ticket (_optional_): PICARD-2430
Fixes issues with picard.util.htmlescape not escaping quotation marks.
Use `html.escape`  directly.
=> PICARD-2430: addrelease: Use html.escape directly

.github/workflows/package.yml, requirements-build.txt
* This is a…
Update to latest PyInstaller 4.10. This should fix recent build issues (see https://github.com/pyinstaller/pyinstaller/issues/6704)
=> Build with PyInstaller 4.10

.github/workflows/package.yml, setup.py
Build macOS packages with Python 3.9.12
=> macOS Python 3.9.12

picard/pluginmanager.py, picard/ui/itemviews.py, picard/ui/options/plugins.py, requirements.txt, test/formats/test_mp4.py, test/test_bytes2human.py
* This is a…
Minor refactoring to replace some lists with either a tuple, set or iterator, depending on usage.
=> Replace some list usages with tuples, sets or iterators

picard/file.py
* This is a…
* JIRA ticket (_optional_): PICARD-2461
After saving a file the icon resets to "changed" if an error occurred during saving, instead of showing the error. This is a regression, but I have not fully checked when this was introduced.
In `File.update`  do not calculate a new state if the file has errors.
=> PICARD-2461: Keep error icon on file update in case of errors

picard/ui/coverartbox.py
* This is a…
* JIRA ticket (_optional_): PICARD-2464
Sizes where applied wrong when the pixel ratio > 1.0 was used, resulting in too small thumbnails inside the stack:
Solved by using logical pixel coordinates in the QPainter and setting the pixel ratio of the underlying QPixmap correctly. That way all painting can use logical pixels and the painter takes care to upscale everything accordingly. The only places where we need to consider the scaling ourself is when setting the size of a QPixmap (on creation or when scaling it) and when accessing `width()` and `height()` of a QPixmap.
Result now renders properly:
=> PICARD-2464: Fix rendering of cover art stack on HiDPI displays

picard/ui/mainwindow.py
* This is a…
* JIRA ticket (_optional_): PICARD-2473
On Windows systems if there is not CD drive detected the CD lookup gets completely disabled. This lead to the "Lookup from ripper log" action to not be available at all.
This behaved a bit different on Linux where CD lookup was enabled regardless, and would always attempt to lookup the default "/dev/cdrom".
Make the lookup disc ID action always enabled. If there is not drive make the ripper log file lookup the default.
=> PICARD-2473: EAC log disc lookup must be available on systems without CD drive

picard/album.py
* This is a…
* JIRA ticket (_optional_): PICARD-2491
After loading an album that leads to an MBID redirect _parse_result would be False, but since 8fa8bd8 (PICARD-2398) this would trigger advanced relationship reload for the tracks. This would trigger finalizing the loading without data being parsed.
Introduce ParseResult enum to separate the different results of parsing (parsed, not parsed because of redirect, parsed but missing track relationships that need loading).
=> PICARD-2491: Handle crash when loading albums with MBID redirect

picard/album.py
=> Album load_tracks(): reduce code redundancy

picard/tagger.py, picard/util/pipe.py
* This is a…
* JIRA ticket (_optional_): PICARD-2471
Some minor tweaks for the pipe handling introduced in https://github.com/metabrainz/picard/pull/2116
- Change the pipe path for Haiku. While this is a Unix system, it expects a different structure for files in user's home folder
- Raise the main window to the front after receiving messages on the pipe
=> PICARD-2471: Small pipe improvements

picard/album.py
* This is a…
* JIRA ticket (_optional_): PICARD-2539
`Album._finalize_loading` is supposed to be called only once after all requests have finished. But wrong usage, e.g. by plugins, can cause additional calls.
Make sure the method exits early if called after loading the album has finished and log this event for further debugging.
I was unable to fully reproduce the situation as it happened on PICARD-2539. But I could easily trigger it by adding an additional call to `Album._finalize_loading`, which is something that can easily happen in a plugin. It makes sense to have this function be more fault tolerant.
The additional logging of the caller should make it easier to find and fix causes for these additional calls. We can't rule out currently …
=> PICARD-2539: Avoid crashes on repeated calls to Album._finalize_loading

picard/tagger.py, test/test_parsing_files_with_commands.py
* This is a…
It would be useful to keep command pipeline in a reusable file
Some operations are repeatable so using such file can greatly automate the workflow
1. Added the command that takes a file path and iterates all over its lines to process the commands
Should be squashed on merge
=> Added command: FROM_FILE

picard/tagger.py
* This is a…
The command was not handled properly after being read.
We passed an unparsed string to a function requiring parsed one.
Changed the execution stack so the read command is parsed correctly. 
ping @rdswift
=> `FROM_FILE` command fixed

picard/tagger.py, picard/ui/logview.py
* This is a…
A command allowing to clear Picard logs.
TBD
=> `CLEAR_LOGS` command

picard/tagger.py
* This is a…
A commands to write logs into a file
Added `WRITE_LOGS`
@zas @phw please take a look if you like the approach :)
=> Added configurable way to dump Picard logs into a file

picard/album.py
* This is a…
* JIRA ticket (_optional_): PICARD-2539
Fixes extra calls to `album._finalize_loading()` happening when cover art saving is enabled but all providers are disabled and huge releases get loaded with recording ARs enabled.
This fixes the root cause for the crash already fixed in #2140
Ensure that `self._requests -= 1` always happens after `self._run_album_metadata_processors()`. This is also what happens for the normal (non-huge releases) loading. See https://tickets.metabrainz.org/browse/PICARD-2539?focusedCommentId=63951&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-63951 for a more in-depth explanation.
The self._requests handling is still an awkward API, and this should be refactored. But we have …
=> PICARD-2539: Always call _run_album_metadata_processors before lowering album._requests

requirements-macos-10.12.txt, requirements-macos-10.14.txt, requirements-win.txt
Upgrade all pip dependencies, tested locally.
=> Upgrade pip dependencies

picard/coverart/image.py, test/test_coverart_image.py
* This is a…
* JIRA ticket (_optional_): PICARD-2565
Saving cover art files uses script_to_filename and applies the special character replacement for Windows compatibility and ASCII conversion. But it ignores the changes for max. file path length ("make_short_filename") and the general "make_save_path" that does make some generic sanitizing of the final path.
Call both `make_short_filename`  and `make_save_path` when saving images.
=> PICARD-2565: Apply make_short_filename and make_save_path to saved image files

picard/tagger.py
* This is a…
* JIRA ticket (_optional_): PICARD-2608
Stop outstanding web service requests *before* stopping threads
Otherwise threads might wait for web service requests to finish before they exit.
=> PICARD-2608: Stop outstanding web service requests *before* stopping threads

picard/file.py, test/picardtestcase.py
* This is a…
PICARD-2609
As observed in https://github.com/metabrainz/picard/pull/2172 loading a lot of files into Picard can lead to the UI stuttering a lot and becoming unresponsive during processing of the files.
Doing some analysis I found that the metadata comparison in `file.update`  has a major impact here.
Doing this part inside a thread hugely impacts the responsiveness of the UI in my tests. Loading my 4.4k test files the UI kept updating and responding to user input.
This patch also removes an additional call to `file.update` directly after loading. This is not necessary here as an update will happen once the file gets moved to the proper parent. 
As far as I can tell making the update here async should not have any negative impact …
=> PICARD-2609: Threaded file update

.github/workflows/package.yml, scripts/package/macos-setup.sh, scripts/package/win-setup.ps1
Package libdiscid 0.6.3 for Windows and macOS builds
=> libdiscid 0.6.3

picard/plugin.py, picard/ui/options/plugins.py
* This is a…
* **Describe this change in 1-2 sentences**: Allows plugins to link a user guide.
As mentioned in the [plugins upgrade proposal](https://github.com/rdswift/picard-plugins/wiki/Picard-Plugins-System-Proposal) plugins could optionally provide a PLUGIN_USER_GUIDE_URL as part of their manifest which is currently not visible to users.
* JIRA ticket (_optional_): [PICARD-1649](https://tickets.metabrainz.org/browse/PICARD-1649)
Added a `user_guide_url` property to the plugins object to read the URL from the manifest. Added the link to the UI as well as a small helper function to make the link clickable.
=> PICARD-1649: Allow plugins to link to documentation

picard/ui/options/metadata.py
From ticket:
I think the option "Use standardized artist names" should be turned on by default. If the option is turned off, then organizing audio files into artist folders has unexpected results. As an example, you typically wouldn't want to have both "The Prodigy" and "Prodigy" as two different folders for the same artist, just because some of the releases of [this release group](https://musicbrainz.org/release-group/ac9138ce-6331-3f8d-86d7-69f13e4ab4f4) happen to be credited to "Prodigy" (and not to "The Prodigy").
* This is a…
* JIRA ticket (_optional_): PICARD-2634
Switch option default from False to True.
It only changes the default value (from False to True), so it has no impact on existing configurations.
=> PICARD-2634: Use standardized artist names by default

picard/formats/id3.py, test/formats/common.py, test/formats/test_id3.py
* This is a…
* JIRA ticket (_optional_): PICARD-2616
Add tests for change sin #2206
=> PICARD-2616: Add tests for releasedate tag

picard/mbjson.py
=> _relations_to_metadata(): split in smaller bits and reduce code redundancy

picard/mbjson.py
Use try/except as the key should be always there, and that's the fastest in such case. Except is there to prevent any issue if the API does something weird.
* This is a…
=> Simplify _relation_attributes()

picard/dataobj.py, picard/mbjson.py
=> Tidy up mbjson a tad more

.github/workflows/package.yml
* This is a…
* JIRA ticket (_optional_): PICARD-2624
Fixes writing IFF (WAVE / AIFF) files with truncated trailing null bytes.
For the Windows / macOS packages include mutagen with the patch at https://github.com/quodlibet/mutagen/pull/517 applied. The branch being pulled from (https://github.com/phw/mutagen/tree/release-1.46-picard) contains the 1.46 release of mutagen with only that patch applied.
For the final release of Picard I hope there will be a new version of mutagen available we will upgrade to. But since this is an important fix it warrants some special handling.
=> PICARD-2624: Use mutagen 1.46 with IFF file patch for macOS / Windows packages

.github/workflows/pypi-release.yml
* This is a…
PyPI stopped supporting PGP code signing, see
https://blog.pypi.org/posts/2023-05-23-removing-pgp/
Remove the code in Github Actions that did the signing
=> Remove PGP code signing for PyPI release

picard/const/__init__.py, picard/mbjson.py, test/data/ws_data/artist_ended.json, test/data/ws_data/media.json, test/data/ws_data/release_5medias.json, test/test_mbjson.py
=> Tidy up mbjson (pass 3)

picard/webservice/__init__.py, test/test_webservice.py
Introduce WSRequest url parameter in order to simplify code.
This is a move I wanted to do since a long time.
WSRequest can now accept a QUrl directly, so we don't need to pass host, port, path, queryargs individually.
It helps to simplify the code because it avoids conversion from QUrl to individual parts, then from parts to QUrl.
Url can be passed as a QUrl or as a string (it will be converted to QUrl in constructor).
The whole class is covered by tests.
* This is a…
=> Webservice tidy up (pass 2)

picard/log.py
Set logging.propagate to False for `main_logger`
* This is a…
Running Picard in debug mode outputs 2 similar log lines on console.
```
D: 23:15:34,394 /home/zas/src/picard/picard/tagger._init_:308: Starting Picard from '/home/zas/src/picard/picard/tagger.py'
DEBUG:/home/zas/src/picard/picard/tagger:Starting Picard from '/home/zas/src/picard/picard/tagger.py'
```
Those are from 2 different formatters (each attached to 2 different handlers).
* JIRA ticket (_optional_): PICARD-2651
Set [logging.propagate](https://docs.python.org/3/library/logging.html#logging.Logger.propagate) to False for `main_logger`.
=> PICARD-2651: fix duplicate messages on console

picard/disc/eaclog.py, picard/disc/utils.py, scripts/tools/fix-header.py
- use logging
- better aliases matching
- handle new fix-header: nolicense to avoid adding our license to a file already licensed
=> Fix header help script improvements

picard/log.py
* This is a…
* JIRA ticket (_optional_): PICARD-2651
=> PICARD-2651: do not propagate history logger either

picard/ui/ratingwidget.py
- a message is written to status bar and history, translatable
- another message is sent via log.error()
It also ensures we have an handler for this request.
* This is a…
* JIRA ticket (_optional_): [PICARD-2654](https://tickets.metabrainz.org/browse/PICARD-2654)
=> PICARD-2654: Display a message when rating submission fails due to server error

picard/releasegroup.py
* This is a…
Some minor code cleanup for `releasegroup.py`. Just a small change I had prepared some while ago but never submitted.
=> Minor code cleanup for ReleaseGroup._parse_versions

picard/log.py
* This is a…
Depending on the way Picard is executed, paths in log can be long without giving much infos.
Before:
```
D: 09:14:09,382 /home/zas/src/picard/picard/webservice/ratecontrol.decrement_requests:146: ('ia601602.us.archive.org', 80): Decrementing requests to: 0
D: 09:14:09,383 /home/zas/src/picard/picard/webservice/__init__._handle_reply:523: Received reply for http://ia601602.us.archive.org/14/items/mbid-0bb956a7-da2e-4083-861a-0dbd5e839cdf/mbid-0bb956a7-da2e-4083-861a-0dbd5e839cdf-35878421569_thumb1200.jpg: HTTP 200 (OK)  (CACHED)
D: 09:14:09,384 /home/zas/src/picard/picard/coverart/image.__init__:91: Saving image data 11463660cbc8ad7ac28c974a51e9e086 to '/tmp/picardxpe_9zn7.jpg'
D: 09:14:09,384 …
```
=> Improve records name & path in log output

picard/const/sys.py, picard/log.py, tagger.py.in
* This is a…
Fix the relative log path handling for PyInstaller packages
=> Fix logging module path for PyInstaller packages

picard/album.py, picard/const/__init__.py, picard/coverart/__init__.py, picard/coverart/image.py, picard/coverart/providers/caa.py, picard/oauth.py, picard/pluginmanager.py, picard/track.py, picard/ui/coverartbox.py, picard/ui/options/plugins.py, picard/ui/searchdialog/album.py, picard/util/__init__.py, picard/util/checkupdate.py, picard/webservice/__init__.py, picard/webservice/api_helpers.py, picard/webservice/ratecontrol.py, picard/webservice/utils.py, test/test_api_helpers.py, test/test_utils.py, test/test_webservice.py
=> Introduce WebService (get|post|put|delete|download)_url() methods

.github/workflows/run-tests.yml, picard/i18n.py, test/picardtestcase.py, test/test_bytes2human.py, test/test_coverart_utils.py, test/test_i18n.py, test/test_releaseversions.py
* This is a…
Add basic test cases for i18n
=> Refactor loading of locales in i18n module, extended logging and added tests

picard/album.py
=> Album tidyup: minor changes

picard/releasegroup.py, picard/ui/searchdialog/album.py, picard/ui/searchdialog/track.py, picard/util/__init__.py
* This is a…
When releases have a very long list of countries, the search dialog is barely usable.
* JIRA ticket (_optional_): PICARD-2481
Use limited_join() as we do elsewhere to limit the size of the list to something usable.
Before:
After:
=> PICARD-2481: shorten country long lists in search results

INSTALL.md
=> Add notes about packages to install for discid & embedded player

picard/webservice/api_helpers.py
* This is a…
* JIRA ticket (_optional_): PICARD-2659
Attempting to do authenticated calls against HTTP on musicbrainz.org leads to authentication errors. Enforce all calls to use HTTPS.
This is a regression introduced by recent webservice refactoring.
=> PICARD-2659: Fix endless login loop

NEWS.md
* This is a…
I originally found this typo at https://picard.musicbrainz.org/changelog/ so I guess that page also has to be regenerated.
=> Correct release date of v2.9 in NEWS.md

picard/file.py, picard/ui/itemviews.py
=> Make flake8 happier

picard/tagger.py
* This is a…
* JIRA ticket (_optional_): PICARD-2710
If Picard is started on a system with 2 or less CPU cores then the main thread pool only has 1 or 2 threads available.
In the current implementation of the single instance mode one thread is required to run the pipe server, one is required for processing incoming commands.
Ensure the thread pool provides at least 3 threads. This way Picard is able to process tasks like file load / save.
Additionally this PR changes the behavior of the run_commands loop. It avoids the run_commands loop constantly looping in the background. Instead the thread terminates if there are no more commands to handle and gets started again on demand if there are new commands to process.
For the majority of users the …
=> PICARD-2710: Fix no loading files on low CPU systems

picard/mbjson.py, picard/util/tags.py
* This is a…
Support the new "Audio Director" AR as "director" tag
=> PICARD-2705: Support the new "Audio Director" AR as "director" tag

picard/tagger.py
* This is a…
* JIRA ticket (_optional_): PICARD-2688
On Windows if there is no console attached to the GUI application Picard can crash when run with "-h".
Show the output in a dialog on Windows in case there is no console attached to `sys.stdout`. This applies to output in case of call with wrong arguments or explicit usage of the `-h`, `-v`, `-e HELP` in related switches.
I tested this on Linux and Windows. No change in behavior on Linux, as expected. On Windows it now behaves differently depending on the build and scenario. I tested with  `-h`, `-v`, `-e HELP` and with an invalid argument such as `--foo`.
A straightforward way to test this behavior from source tree is to start it with `pythonw.exe` instead of `python.exe`. `pythonw.exe` is …
=> PICARD-2688: Show command line help messages in dialog on Windows

picard/util/pipe.py
* This is a…
* JIRA ticket (_optional_): PICARD-2717
When launching Picard without commands and processing goes over to an already running instance do pass the SHOW command by default.
=> PICARD-2717: Send SHOW command by default to existing instance

CONTRIBUTING.md
* This is a…
* **Describe this change in 1-2 sentences**:  Adds a note about contributing to the user documentation in the CONTRIBUTING section.
This helps inform potential contributors to the project that there is also an opportunity to contribute to the user documentation.
Add a note about contributing to the user documentation in the CONTRIBUTING section.
None.
=> Add note about contributing to user documentation

picard/ui/ui_options_cover.py, ui/options_cover.ui
=> Fix trailing space after colon

picard/pluginmanager.py, picard/script/__init__.py, picard/script/serializer.py, picard/track.py, picard/ui/collectionmenu.py, picard/ui/infodialog.py, picard/ui/options/genres.py, picard/ui/options/maintenance.py, picard/ui/options/plugins.py, picard/ui/options/scripting.py, picard/ui/playertoolbar.py, picard/ui/searchdialog/__init__.py
* This is a…
Some translation strings contain multiple placeholders like 
```python
"%s (%i release)" % (name, size)
```
This requires translations to maintain the order of the placeholders. Some strings might be better or only properly translated in a different order.
Use named placeholders.
For multiple placeholders this allows changing the order in translation. The name also generally makes it easier for the translator to understand the string.
After this has been merged I'll update the translation template and translations themselves. Actually we should be able to fully keep existing translations by changing the placeholders only.
Weblate has a check "[Multiple unnamed variables](https://translations.metabrainz.org/checks/unnamed_format/)" …
=> Use named placeholders in translated strings

.github/workflows/package.yml, requirements-macos-10.12.txt, requirements-macos-10.14.txt, requirements-win.txt
* This is a…
Build release packages with latest mutagen 1.47.0 and remove workaround to install patched mutagen.
=> Build with official mutagen 1.47.0 release

picard/coverart/providers/__init__.py, picard/ui/options/cover.py
* This is a…
Minor changes in order to simplify code.
=> CAA providers code tidyup

.github/workflows/codacy-analysis.yml, .github/workflows/codeql-analysis.yml, .github/workflows/package.yml, .github/workflows/pypi-release.yml, .github/workflows/run-tests.yml
* This is a…
See discussion at https://github.com/metabrainz/picard/pull/2298#discussion_r1316765065
=> Restrict default permissions of Github Actions

picard/ui/scripteditor.py
* This is a…
Revert use of qlistwidget_items for getting the script list, as this is a QComboBox and not QListWidget.
=> Fixed regresson in script editor

picard/coverart/providers/caa.py
=> Tidy up caa image types code

picard/coverart/image.py, test/test_coverart_image.py
Also add matching tests
* This is a…
=> TagCoverArtImage(): properly set _repr() and _str() for this subclass

picard/coverart/__init__.py
=> Caa tidyup 3

.markdownlint.json, CONTRIBUTING.md, INSTALL.md, po/README.md, resources/README.md, scripts/tools/run_codacy_analysis.sh
=> Markdownlint config

picard/const/__init__.py, picard/ui/edittagdialog.py, picard/ui/options/interface.py, picard/ui/options/metadata.py, picard/ui/options/releases.py
Add a TODO about removing imports from `const/__init__.py`
* This is a…
See discussion on https://github.com/metabrainz/picard/pull/2329
=> Import RELEASE_* directly from respective files

picard/util/__init__.py, test/test_utils.py
=> Make `get_qt_enum()` a generator and extend tests

.github/dependabot.yml
=> Create dependabot.yml and check github actions versions

.github/workflows/package.yml, .github/workflows/pypi-release.yml, .github/workflows/run-tests.yml, .github/workflows/validate-xdg-metadata.yml, INSTALL.md, picard/util/webbrowser2.py, setup.py
* This is a…
Update the used Python versions:
- Bump the minimum to 3.8
- Use stable Python 3.12 in CI
- Use Python 3.12 for not version critical CI steps
For now keep the release builds for macOS and Windows on Python 3.11 as there still seem to be some issues with this.
=> PICARD-2784: Update Python version, minimum is now 3.8

.github/workflows/package.yml, installer/picard-setup.nsi.in, picard/ui/options/interface_colors.py, requirements-build.txt, scripts/package/macos-package-app.sh, scripts/package/win-common.ps1
* This is a…
Fixes the macOS build with Qt6 by using latest PyInstaller.
Also replaced deprecated style override "macintosh" with "macos"
=> Qt6 mac fixes

.github/workflows/pypi-release.yml, .github/workflows/run-tests.yml, requirements-macos-10.14.txt, requirements-win.txt
* This is a…
Build with PyQt 5.15.10 (for Picard 2.x).
This might allow us to re-enable WebP support, at least for macOS 10.14+.
=> PyQt 5.15.10

requirements-build.txt
* This is a…
Build with PyInstaller 6.3, see https://pyinstaller.org/en/v6.3.0/CHANGES.html for the changes since 6.1
=> Build with PyInstaller 6.3

.github/workflows/package-macos.yml, .github/workflows/package-windows.yml, requirements-macos-11.txt, requirements-win.txt, requirements.txt
* This is a…
Update PyPI requirements and build the Windows and macOS packages with latest Python 3.12
=> Requirements update

picard/metadata.py, test/test_metadata.py
* This is a…
* JIRA ticket (_optional_): PICARD-2805
If a loaded track has no length (length is `None`) the metadata compare throws an exception.
Handle the None case for metadata compare. Also handle the theoretical case that the `release-group`  might also miss for the releases loaded for a track.
=> PICARD-2805: Handle the None case for metadata compare

picard/file.py, picard/util/tags.py, test/formats/common.py, test/test_file.py
It reduces the size of objects, and it doesn't seem we ever needed to change it.
* This is a…
=> Move `FILE_INFO_TAGS` from class `File` to module `picard.util.tags`

picard/config.py, picard/ui/options/metadata.py, test/test_config.py
=> Option class improvement

picard/config.py
Introduced by https://github.com/metabrainz/picard/commit/92b09036e9ee67062816a31f6547797789323668
* This is a…
=> Fix "dictionary changed size during iteration" in upgrade hooks loop

picard/collection.py, picard/ui/collectionmenu.py
=> Collections cleanup

picard/collection.py, test/data/ws_data/collection_list.json, test/picardtestcase.py, test/test_collection.py
* This is a…
As discussed in PR #2389 this adds tests for `picard.collections`.
Improve testability of the module and add tests
=> Testable collection

picard/log.py, test/test_log.py
=> Add tests for `log.name_filter()`

picard/debug_opts.py, picard/tagger.py, picard/ui/logview.py, picard/webservice/__init__.py, test/test_debug_opt.py
* This is a…
Web service replies can be very long, and it makes debug output rather hard to read.
A debug option mechanism is now added, it is controlled by a new class
`DebugOpt`.
A command-line option `--debug-opts` allows selection of extra debug
output, for now the sole option is `ws_replies`.
A matching menu was added in View Debug Log dialog.
It is important to note those aren't saved in config file, as they are
meant to be disabled by default and only enabled when needed.
=> Add a way to select extra debug output

picard/ui/options/interface.py, picard/ui/options/interface_colors.py, picard/ui/util.py
* This is a…
- display all changes as a list (it fixes an issue where if you changed both theme and language only warning about theme was displayed)
- reformat using richtext
- use an actual warning dialog
- modifies the API so we can pass multiples warnings and notes
- make title and last sentence fixed
- since we detect changes in options not need to write to them if unchanged
=> Improve changes applied on restart dialog

picard/debug_opts.py, picard/log.py, test/test_log.py
* This is a…
* JIRA ticket (_optional_): [PICARD-2856](https://tickets.metabrainz.org/browse/PICARD-2856)
=> PICARD-2856: Introduce DebugOpt.PLUGIN_FULLPATH and shorten plugin paths in logs 

picard/ui/options/dialog.py
=> Fix Attached Profiles Dialog after setting title changes

requirements.txt
=> Requires PyQt>=6.6.1

picard/ui/colors.py, picard/ui/options/dialog.py
* This is a…
Profile highlight colors aren't configurable
* JIRA ticket (_optional_): [PICARD-2858](https://tickets.metabrainz.org/browse/PICARD-2858)
Use InterfaceColors for profile highlight colors, making them configurable.
=> PICARD-2858: Make profile highlight colors configurable

picard/ui/options/profiles.py
=> Profiles cleanup

picard/ui/scripteditor.py
=> Scripteditor cleanup

picard/ui/options/dialog.py
=> UI profiles cleanup

picard/ui/searchdialog/track.py
=> Search cleanup

picard/dataobj.py, picard/track.py
* This is a…
* JIRA ticket (_optional_): [PICARD-2866](https://tickets.metabrainz.org/browse/PICARD-2866)
When refreshing a standalone recording, genres weren't cleared properly causing various issues (like preserving genres after options related to genres changed)
Actually clear `DataObj.genres` when loading a NonAlbumTrack.
It is done for Album, but this one was forgotten.
Also make `DataObj.genres` a property, using internally `_genres` private property.
=> PICARD-2866: Fix standalone track genres

scripts/package/macos-package-app.sh
* This is a…
* JIRA ticket (_optional_): PICARD-2192
I accidentally pushed parts of this fix to master already with 08588465639bc0136a0310816d69cf53ac932391. This was supposed to build in a branch so I can test the CI result locally. 
This commit fixes the previous incomplete change.
=> PICARD-2192: Fix macOS app bundle creation

picard/tagger.py, picard/ui/options/maintenance.py, test/picardtestcase.py
=> Drop remaining bits of QtCore.QObject.config and QtCore.QObject.log

.github/workflows/run-tests.yml
=> Python 3.9 isn't available anymore with macos-latest, stick to macos-12

picard/options.py
=> Add header & comment to new options.py

picard/const/__init__.py, picard/ui/options/__init__.py, picard/ui/options/dialog.py
- without this patch, Picard crashes, and/or the options display gets corrupted
- with this patch, a fake page is loaded instead, displaying the message, but avoiding a crash
- it will be important for pages created by plugins
* This is a…
=> Better handling of exceptions while loading option pages

INSTALL.md
=> Add a note about Qt6 installed from pip and libxcb errors

picard/const/defaults.py, picard/util/cdrom.py, picard/util/macos.py, test/test_util_macos.py
=> Cleanup defaults

picard/ui/options/interface_toolbar.py
- use namedtuples
- get rid of babel415 workaround (since namedtuple remove the need of dict string keys)
- remove `_get_icon_from_action_id()`, use namedtuple property `icon` instead
- AddActionDialog.get_selected_action() now returns selected action or None
- add a title to the Add action dialog (it was just "Picard" before)
- simplify AddActionDialog using item data instead of indexes
- let the user resize this dialog (it was fixed size), since that's a PicardDialog size is preserved
* This is a…
=> Simplify toolbar editor

requirements-build.txt
* This is a…
* *Describe this change in 1-2 sentences**:
Build with PyInstaller 6.6.0
Changelog: https://pyinstaller.org/en/v6.6.0/CHANGES.html
=> Build with PyInstaller 6.6.0

picard/ui/itemviews.py
It removes dependency on subclass FileTreeView
* This is a…
=> BaseTreeView, FileTreeView: introduce property `default_drop_target`

picard/formats/vorbis.py, test/formats/test_vorbis.py
* This is a…
* JIRA ticket (_optional_): PICARD-2896
Some applications write Ogg files with the .ogx extension. See [PICARD-2895](https://tickets.metabrainz.org/browse/PICARD-2895) for an example.
Wikipedia (https://en.wikipedia.org/wiki/Ogg) says: "Other Ogg applications use media type application/ogg with file extension .ogx; this is a superset of video/ogg."
Add .ogx as valid file extension for OggContainerFile
=> PICARD-2896: Support .ogx extension for Ogg container

picard/releasegroup.py, picard/ui/itemviews/__init__.py
* This is a…
The number displayed is limited by the max number of results, it isn't the number of releases in the release group.
* JIRA ticket (_optional_): [PICARD-2899](https://tickets.metabrainz.org/browse/PICARD-2899)
Retrieved and store the number of releases in the release group, use it for display.
=> PICARD-2899: Other versions: display the actual number of versions from release-count

picard/debug_opts.py, picard/webservice/__init__.py
POST DATA was logged in debug mode unconditionally, now it can be enabled if needed.
* This is a…
=> Add a DebugOpt for POST data

CONTRIBUTING.md
- some files were ignored, but there's no reason anymore
- use git diff --diff-filter=ACM to avoid to check removed files or so
* This is a…
=> Update pre-commit example

picard/ui/metadatabox.py
Properly initialize `tag_diff` and check if it's `None`.
* This is a…
Pressing Shift+Alt+A (Add tag) raises an exception when there's nothing to edit
```
File "/home/zas/src/picard/./picard/ui/metadatabox.py", line 459, in edit_tag
EditTagDialog(self.parent, tag).exec()
File "/home/zas/src/picard/./picard/ui/edittagdialog.py", line 109, in _init_
set(list(TAG_NAMES.keys()) + self.metadata_box.tag_diff.tag_names))
AttributeError: 'NoneType' object has no attribute 'tag_names'
```
* JIRA ticket (_optional_): PICARD-2901
Check if MetadataBox.tag_diff is None before trying to open the edit dialog.
=> PICARD-2901: Only try to open edit tag dialog if there are tags to edit

picard/ui/infodialog.py
=> Infodialog cleanup

picard/coverart/image.py, test/test_coverart_image.py
It fixes a minor issue where back cover could appear before front cover in dialogs showing those
* This is a…
`normalized_types()` was just sorting types (so back comes before front).
Still sort types, but ensure front is first in any case.
Also take support_types in account.
Matching tests were added.
=> normalized_types(): ensure front type is first and the rest sorted

picard/ui/colors.py, picard/ui/coverartbox.py, picard/ui/tablebaseddialog.py
* This is a…
Few colors aren't configurable yet and hardcoded.
Make them configurable.
=> Make few more colors configurable

picard/ui/colors.py, picard/ui/options/interface_colors.py
* This is a…
It isn't possible to restore only one color to default in Interface Colors
* JIRA ticket (_optional_): [PICARD-2904](https://tickets.metabrainz.org/browse/PICARD-2904)
Add a button to let user restore default for one color only.
=> PICARD-2904: Interface colors: Let the user restore only one color to default

picard/coverart/image.py, picard/coverart/utils.py, picard/ui/infodialog.py, test/test_coverart_image.py
=> Infodialog cleanup2

picard/ui/collectionmenu.py
=> Collection menu cleanup

picard/ui/coverartbox.py
Forgotten from cca828c7b76db8452cae38be5f09dc88cdc699ee
* This is a…
=> Add missing self.tagger initializations

picard/tagger.py
=> Clustering: use tuple and improve debug logging 

installer/i18n/nshutil.py, picard/cluster.py, picard/script/functions.py, picard/ui/coverartbox.py, picard/ui/options/plugins.py, picard/ui/tagsfromfilenames.py, picard/util/__init__.py, picard/util/tags.py, picard/version.py, test/test_metadata.py
It doesn't really conflict with variable name but it confuses syntax highlighters (if they are Python 3.10+ aware ofc)
* This is a…
=> match -> match_: match is a statement in Python 3.10+

picard/ui/widgets/scripttextedit.py
* This is a…
* JIRA ticket (_optional_): PICARD-2912
=> PICARD-2912: Script editor syntax highlighting fixes and improvements

picard/tagger.py, picard/ui/itemviews/__init__.py, picard/ui/mainwindow/__init__.py, picard/ui/metadatabox.py, picard/util/__init__.py, test/test_utils.py
=> Improve IgnoreUpdatesContext and use it for MainWindow sorting

picard/script/__init__.py, picard/ui/widgets/scripttextedit.py
* This is a…
* JIRA ticket (_optional_): PICARD-2912
This builds on #2492 and ads a special tooltip for missing functions to the script editor.
=> PICARD-2912: Show a tooltip for missing functions in script editor

picard/ui/colors.py, picard/ui/theme.py, picard/ui/widgets/scriptdocumentation.py, picard/ui/widgets/scripttextedit.py
* This is a…
Script syntax highlighting colors are hardcoded.
* JIRA ticket (_optional_): [PICARD-2913](https://tickets.metabrainz.org/browse/PICARD-2913)
Let the user configure them in Options > Interface > Colors
=> PICARD-2913: Let user configure syntax highlighting colors

picard/album.py, picard/config_upgrade.py, picard/script/__init__.py, picard/script/serializer.py, picard/track.py, picard/ui/itemviews/basetreeview.py, picard/ui/options/profiles.py, picard/ui/options/scripting.py, picard/ui/scripteditor.py, picard/ui/scriptsmenu.py, picard/ui/widgets/scriptlistwidget.py, test/test_script_serializer.py
=> Introduce TaggingScriptSetting and few associated methods

picard/ui/colors.py, picard/ui/options/interface_colors.py
- properly sort colors in each group (locale-aware)
- use group boxes
- add ColorDescription class with 2 fields: title & group
* This is a…
=> Options > Interface > Colors: Separate colors in different groups

picard/album.py, picard/item.py, picard/ui/coverartbox.py
It just enable/disable update_metadata_images_enabled
* This is a…
=> Introduce MetadataItem.suspend_metadata_images_update context manager

picard/webservice/__init__.py
Issue is the data downloaded is QtCore.QBytesArray object, and it wasn't convert to bytes. So ensure it is converted before passing it to image detection methods.
* This is a…
GIF image detection fails when data was downloaded (it works on the same file if run from tests).
The downloaded data is returned as `QtCore.QByteArray` but image detection functions are expecting Python `bytes`.
* JIRA ticket (_optional_): PICARD-2919
Convert `QCore.QByteArray` to bytes before anything.
=> PICARD-2919: fix download of GIF images (and maybe others)

picard/coverart/image.py
* This is a…
Due to possible race condition `delete_file()` may raise an exception on exit
* JIRA ticket (_optional_): [PICARD-2918](https://tickets.metabrainz.org/browse/PICARD-2918)
- set _datafiles[self._hash] ASAP
- log errors
- revamp code to limit the risk of race condition
- revamp delete_file() code to be more reliable in case of unexpected errors
=> PICARD-2918: avoid exception if hash isn't found in _datafiles on exit

picard/script/serializer.py, picard/tagger.py, picard/ui/coverartbox.py, picard/ui/logview.py, picard/ui/mainwindow/__init__.py, picard/ui/options/fingerprinting.py, picard/ui/options/interface.py, picard/ui/options/interface_toolbar.py, picard/ui/options/maintenance.py, picard/ui/options/plugins.py, picard/ui/options/renaming.py, picard/ui/util.py
=> Filedialog wrappers

picard/album.py, picard/coverart/__init__.py, picard/extension_points/event_hooks.py, picard/extension_points/metadata.py, picard/file.py, picard/metadata.py
=> Move last register_* methods to extension_points

picard/extension_points/event_hooks.py, picard/extension_points/metadata.py, picard/plugin.py, test/test_plugins.py
- Only default value was used in the code
- having an enum for that is rather limiting its use
- add tests for PluginFunctions class
* This is a…
=> Drop PluginPriority in favor of a simple integer and add tests

.github/workflows/package-macos.yml, .github/workflows/package-pypi.yml, .github/workflows/run-tests.yml, test/test_coverart_processing.py
* This is a…
Github Actions deprecated the macos-11 runner. Use macos-12 instead.
=> Build on macos-12 image

.github/workflows/validate-xdg-metadata.yml
* This is a…
Use `appstreamcli` instead of `appstream-util`. This catches more issues and is the same utility also used by flatpak for validation.
=> Validate appstream metadata with appstreamcli

picard/util/thread.py, test/test_util_thread.py
* This is a…
Add a class `TaskCounter` to count tasks currently running and wait for them to finish.
Picard does not have a general way to run code after a bunch of threads has finished.
The advantage of `TaskCounter` is that it's independent of thread pools.
In my case, it allows to run all image processing tasks in the default thread pool for background tasks, but add a way to wait for all of the relevant tasks to finish. 
I tested this with the changes I am making to cover art processing. I saw there are no threading unit tests, but I could add those if y'all wish.
=> Add a general way to count the number of tasks currently running

picard/ui/options/releases.py
* This is a…
This is a small refactoring to simplify the code for filling the selection lists in the preferred releases options  UI.
=> Simplify code to fill preferred release countries/formats lists

picard/ui/coverartbox.py
* This is a…
* JIRA ticket (_optional_): PICARD-2921
Added an option in the cover art box context menu.
The new dialog look like this:
The logic behind is the same as when dragging and dropping.
=> PICARD-2921: Allow manual setting of cover art from web url

requirements-macos-10.12.txt, requirements-macos-10.14.txt, requirements-win.txt
* This is a…
Build macOS and Windows builds with latest PyQt 5.15.11
=> PyQt 5.15.11 for Picard 2.x

.github/workflows/package-pypi.yml, .github/workflows/package-windows.yml, .github/workflows/run-tests.yml, picard/util/__init__.py, requirements.txt, setup.py, test/test_utils.py
* This is a…
* JIRA ticket (_optional_): PICARD-3022
This merges the necessary changes for Python 3.13 support into the 2.x branch.
Rationale: If we release this distributions already running Python 3.13 want to be able to package Picard.
=> PICARD-3022: Python 3.13 support for 2.13

.prospector.yml, picard/coverart/__init__.py
=> Codacy fixes

picard/formats/id3.py, test/formats/test_id3_load.py
=> Refactor id3._load()

picard/disc/__init__.py, test/test_disc.py
- use generated urls rather than hardcoded ones for testing
- add tests for picard.disc.Disc._submission_url
* This is a…
=> Disc: introduce _submission_url() static method and improve tests

picard/formats/id3.py
=> Refactor id3 save

picard/ui/edittagdialog.py
=> Edittagdialog refactor

picard/formats/id3.py, test/formats/common.py
* This is a…
* JIRA ticket (_optional_): PICARD-3043
TODO: Improve tests
=> PICARD-3043: Fix deleting performer tag without role from ID3

picard/ui/edittagdialog.py
* This is a…
Some of the changes made in previous refactor are incorrect.
=> Edittagdialog refactor fixes

picard/ui/edittagdialog.py, picard/util/__init__.py, test/test_utils.py
=> Temporary disconnect helper

picard/ui/metadatabox/__init__.py
=> TableTagEditorDelegate: add docstrings and use class constants

picard/ui/metadatabox/__init__.py, picard/ui/metadatabox/tagdiff.py, test/test_tagdiff.py
=> Refactor MetadataBox

picard/ui/metadatabox/tagdiff.py, test/test_tagdiff.py
- it makes the code easier to extend with special handling of tags
- max_length_delta_ms isn't needed as property, replaced by tag_ne_handlers
- __tag_ne() is generic
* This is a…
=> TagDiff: introduce tag_ne_handlers

picard/ui/cdlookup.py, picard/ui/columns.py, picard/ui/itemviews/columns.py, test/test_ui_columns.py
=> UI Columns can be used outside itemviews

picard.spec, scripts/package/macos-package-app.sh
* This is a…
Current versions of PyInstaller support code signing on macOS. Use this functionality
-  Replace custom code signing code with proper PyInstaller configuration
- Always perform the notarization if app got signed (we no longer support older versions of macOS that would not require notarization)
- Always test run the built executables. This is now possible as PyInstaller will ad-hoc sign the app bundle even if we didn't explicitly specify a `CODESIGN_IDENTITY` (which is still optional, as not all CI builds have the required secrets)
- Additionally remove unused upload code in the macos packaging script.
=> Use PyInstaller code signing on macOS

picard/ui/cdlookup.py, picard/ui/formattedtextdelegate.py
* This is a…
* JIRA ticket (_optional_): PICARD-3042
Show medium format in disc ID lookup result table.
While this most often is CD, there are also some audio CD variations that provide valid disc IDs. Showing these can help disambiguate multiple results.
Check for the medium which actually matches the found disc ID and use the format in the result table.
=> PICARD-3042: Include format in disc ID lookup result table

picard/ui/coverartbox/__init__.py, picard/ui/coverartbox/coverartsetter.py
* This is a…
* JIRA ticket (_optional_): PICARD-3049
=> PICARD-3049: improve debugging and do not append the same image twice to FileList 

.gitignore
=> Add Byte-compiled / optimized / DLL files to .gitignore

picard/tagger.py, picard/ui/theme.py
=> Theme debug logging improvement

picard/tagger.py
See https://tickets.metabrainz.org/browse/PICARD-3066?focusedId=75962&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-75962
Partially revert a2dd9df9ee75332958ed63e65ae90eaba31f7c4d
* This is a…
=> Move theme.setup() call sooner

picard/log.py, picard/tagger.py, picard/ui/logview.py, test/picardtestcase.py
- handle incorrect value (possible if from config file)
- use effective level for comparaison & storage
- introduce `log.set_verbosity()`, which can optionally save it to config
- drop `tagger._debug` and use new method `log.is_debug()` instead
- drop `tagger.set_log_level()` in favor of `log.set_verbosity()`
* This is a…
=> Rework setting log verbosity

picard/tagger.py
=> Tagger class initialization tidyup

picard/ui/columns.py, picard/ui/itemviews/__init__.py, picard/ui/itemviews/basetreeview.py, picard/ui/itemviews/columns.py, picard/ui/searchdialog/album.py, picard/ui/searchdialog/artist.py, picard/ui/searchdialog/track.py, picard/ui/tablebaseddialog.py, test/test_ui_columns.py
=> Refactor Columns stuff a bit

picard/ui/columns.py, picard/ui/itemviews/__init__.py, picard/ui/itemviews/basetreeview.py, picard/ui/itemviews/columns.py, picard/ui/searchdialog/__init__.py, picard/ui/searchdialog/album.py, picard/ui/searchdialog/artist.py, picard/ui/searchdialog/track.py, picard/ui/tablebaseddialog.py, picard/ui/widgets/configurablecolumnsheader.py, test/test_ui_columns.py
=> Columns & Search Dialog improvements & tidy up

picard/ui/searchdialog/album.py, picard/ui/tablebaseddialog.py
* This is a…
* JIRA ticket (_optional_): PICARD-3073
=> PICARD-3073: Fix loading of cover art for non-visible cells

picard/ui/searchdialog/__init__.py
* This is a…
* JIRA ticket (_optional_): PICARD-3074
=> PICARD-3074: Fix search box QLineEdit focus unexpected behavior

picard/tags/__init__.py, picard/tags/tagvar.py, test/test_tags.py
* This is a…
* **Describe this change in 1-2 sentences**:  Add new generators for hidden, visible and filterable tags.  Add tests.
There may be a need for generating a list of hidden, visible or filterable tags only.  This may be the case in https://github.com/metabrainz/picard/pull/2668.
Add new `filterable` TagVar attribute.  Add generators and tests.
=> Add new generators and tests

picard/tagger.py, picard/ui/mainwindow/__init__.py
- it can be extended using `register_suspend_while_loading()`
- it removes the need to call `MainWindow.set_sorting()` directly (it was a leftover when we implemented the context manager)
* This is a…
=> Generic suspend while loading mechanism

picard/file.py, picard/formats/mutagenext/ac3.py
* This is a…
Picard in some cases extends mutagen and needs to access its private API. But if possible use the public imports.
=> Use public imports for mutagen, when possible
