metabrainz/picard

picard/album.py

* This is a…
* JIRA ticket (_optional_): PICARD-2070
Iterating over files to then move them can change the original list. 
Iterate over a copy of the files list. This is a regression from b0ee615, the previous code did already use a list copy.

PICARD-2070: Fixed lookup only moving half the files

---

picard/ui/itemviews.py

* This is a…
Alternative to https://github.com/metabrainz/picard/pull/1717
* JIRA ticket (_optional_): PICARD-2071
When tracks got loaded while sorting was disabled the tracks ended up in reverse order. Unify the behavior by always disabling sorting while inserting tracks.

PICARD-2071: Fix tracks sometimes sorted in reverse order

---

picard/ui/metadatabox.py

If "self.selected_tags()" returns no tags "tags[0]" will trigger an exception.
* This is a…
With a certain mp3 file picard crashes whenever I do a right click in the lower area where tags are listed.  The traceback is pretty clear I think
File "/usr/lib64/python3.9/site-packages/picard/ui/metadatabox.py", line 356, in contextMenuEvent
editable = self.tag_is_editable(tags[0])
IndexError: list index out of range
…
Local variables in innermost frame:
tags: []
* JIRA ticket (_optional_): PICARD-2074
The code should be pretty obvious. The only minor thing is that "editable" is also accessed later in the function in a different branch. That might be susceptible to triggering an `UnboundLocalError` but the extra …

PICARD-2074: Avoid exception when editing metadata but no tag was selected

---

picard/util/settingsoverride.py

There is a small typo in picard/util/settingsoverride.py.
Should read `temporarily` rather than `temporarly`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, temporarly -> temporarily

---

picard/const/__init__.py

* This is a…
* **Describe this change in 1-2 sentences**: Set the AcoustID port to 443, to use TLS.
Requests to `api.acoustid.org` are sent in plain, unencrypted HTTP, because the port is set to be `80`, while the server does support the port `443` with TLS.
Set the AcoustID port to 443 so that requests are sent using HTTPS.

PICARD-2084: Set the AcoustID port to 443, to use TLS

---

picard/__init__.py
picard/acoustid/__init__.py
picard/config_upgrade.py
picard/ui/options/fingerprinting.py
test/test_config_upgrade.py

* This is a…
Allow having an empty path for fpcalc configured and auto detect the path in this case.
* JIRA ticket (_optional_): PICARD-2083
Currently Picard will use the path to fpcalc as configured in options. In some cases the path can change with each launch. E.g. when packaged with PyInstaller we usually want to use the bundled fpcalc, and the path to it can change (especially for portable Windows build, which gets extracted to a temporary folder with unique name). Same is true for snap installs on Linux, where each new version installed gets a different path under `/snap/picard/`.
As a workaround for the PyInstaller case Picard on launch always resets the fpcalc path to the autodetected value. This has the side effect that the user cannot …

PICARD-2083: Allow empty fpcalc path, auto detect path if empty

---

picard/ui/edittagdialog.py

* This is a…
* JIRA ticket (_optional_): PICARD-2087
Picard crashes when adding a new tag.
`QListWidget.isPersistentEditorOpen` is only available in Qt 5.10 or later.
Check for support of `QListWidget.isPersistentEditorOpen`. This missing doesn't have a huge impact on functionality. We will just start editing again, which makes the current editor close and open again. This gives some flickering when clicking on edit tag with editing already active, but no big deal really.

PICARD-2087: Fix crash with Qt < 5.10 when adding new tag

---

scripts/package/macos-package-app.sh

* This is a…
* JIRA ticket (_optional_): PICARD-1943, PICARD-1763
App bundle's signature gets destroyed on some macOS installs.
Avoid signature being written to extended file system attributes by moving resource files to Contents/Resources. This only affects the Qt translations. For other such files PyInstaller already takes care of this.
This is also what PyInstaller fixed for base_library.zip in https://github.com/pyinstaller/pyinstaller/issues/3550

PICARD-1943: Fix macOS app signature breaking on macOS 10.12/10.13

---

picard/ui/coverartbox.py
picard/util/imageinfo.py
test/test_util_imageinfo.py

* This is a…
PICARD-2091
This started as a small refactoring, but also fixes an actual bug: Fetching remote images was limited to only PNG and JPEG; hard coded in coverartbox by mimetype
- Drop unused `mime` parameter from `CoverArtBox.load_remote_image`
- Try initializing `CoverArtImage` directly instead of probing with `imageinfo.identify` first (`CoverArtImage` will already do this)
- Get list of possible image file extensions from `imageinfo` module

PICARD-2091: Refactor coverartbox and fix loading remote images other then PNG or JPEG

---

picard/config.py

* This is a…
For newly created configs there is no need to run upgrade hooks, the config defaults are already set accordingly.
This also allows having hooks that do changes that apply only on upgrade.

Run upgrade hooks on config upgrade only

---

picard/script/__init__.py
picard/ui/widgets/scripttextedit.py

* This is a…
* JIRA ticket (_optional_): PICARD-2092
The script autocompleter can sometimes be annoying:
- It triggers on all kind of key presses, e.g. simply hitting Shift shows the autocompletion
- Accepting a choice only works with Tab. I personally always try to press return to accept the choice, causing a linebreak and the suggestion to abort
- It only shows fully matching suggestions
- Only trigger on key presses that cause actual text input or removal.
- Allow explicitly opening the completion poput with Ctrl+Space at any time.
- Allow accepting choice with enter.-
- Use UnfilteredPopupCompletion completion mode ("All possible completions are displayed in a popup window with the most likely suggestion indicated as current.").
- Improved …

PICARD-2092: non annoying script autocompletion

---

picard/cluster.py
picard/plugin.py
test/test_utils.py

* This is a…
Just a minor change to use the `yield from` syntax where it can be used. So replacing:
```python
for x in items:
yield x
```
with shorter
```python
yield from items
```

Use yield from syntax where appropriate

---

picard/formats/apev2.py
picard/formats/asf.py
picard/formats/id3.py
picard/formats/mp4.py
picard/mbjson.py
picard/util/tags.py
test/data/ws_data/recording_video.json
test/formats/common.py
test/test_mbjson.py

This adds a tag "director" which is filled with the "video director" AR from MB by default.
* This is a…
* JIRA ticket (_optional_): PICARD-1998
Add the `director` tag and fill it with the `video director` AR from MB.
Map the tag as follows:
* MP4: ©dir (from iTunes Metadata Format Specification)
* ASF: [WM/Director](https://docs.microsoft.com/en-us/previous-versions/ms867702(v=msdn.10)?redirectedfrom=MSDN#wmdirector)
* ID3: TXXX/DIRECTOR
* APE: Director
* Vorbis: DIRECTOR
For ID3, APE and Vorbis this is probably not too relevant, as few people might use this for audio files only. But the mapping follows our usual naming. For MP4 and ASF there are explicit definitions in the respective specs. For Matroska there would be as well, but we don't …

PICARD-1998: Add "director" (for videos) tag

---

picard/ui/options/renaming.py

* This is a…
Add originaldate and originalyear to file naming examples. Those might be commonly used in file naming scripts.
* JIRA ticket (_optional_): PICARD-2110

PICARD-2110: Add originaldate and originalyear to file naming examples

---

picard/ui/itemviews.py
picard/ui/mainwindow.py

* This is a…
After clustering completed, if there is no selection or only Unclustered files is selected without any files, automatically select the Clusters item. This allows for easier workflow as the user can now directly use actions like Lookup on the new clusters.
* JIRA ticket (_optional_): PICARD-2102
Update the selection after clustering.

PICARD-2102: After cluster action select the Clusters item

---

picard/ui/cdlookup.py

* This is a…
When looking up CD's, the window that pops up to present the choices to "Load into Picard" or to "Submit disc ID" does not show the release disambiguation, which makes it hard to tell which one is wanted.
* JIRA ticket (_optional_): PICARD-2114
Add a column for the disambiguation comment to the CD lookup dialog

PICARD-2114: Show disambiguation comment in cdlookup dialog

---

requirements-build.txt

* This is a…
Build with latest PyInstaller 4.2
Apart from various bugfixes those two changes are interesting for us:
- Fixes with invalid code signatures with newer Python versions on macOS (but we already work around this by forcefully codesigning the binaries with our own signature at 293c2c7)
- On Windows the app manifest gets set the longPathAware attribute. This is a part of the puzzle to fully support long path names on Windows 10, see PICARD-2076 
See https://pyinstaller.readthedocs.io/en/stable/CHANGES.html

Build with PyInstaller 4.2

---

picard/ui/options/cover.py

* This is a…
As discussed in #1743 enable the CaaReleaseGroup cover art provider by default, but keep its position.
* JIRA ticket (_optional_): PICARD-2125
* See also #1743
The CAA Release Group cover art provider is a useful fallback in case there is no cover art for a release. It might also satisfy users which otherwise would want to add a wrong cover art to the release just to get some result.
Change default config for new installs

PICARD-2125: Enable CaaReleaseGroup by default

---

picard/ui/metadatabox.py

* This is a…
* JIRA ticket (_optional_): PICARD-2127
Using "lookup in browser" in the metadata box (from the context menu of a MBID tag) does not pass on the browser tport parameter. That is because it is using a separate browser integration instance.
Use global `BrowserIntegration` instance

PICARD-2127: Fixed passing tport parameter in metadatabox browser lookup

---

picard/config.py

* This is a…
Fix a regression of config file not getting written to on Windows after #1747
When locking the config file itself writing to it fails on Windows.
* JIRA ticket (_optional_): PICARD-2088
* #1747
Use a separate lock file.
Choose a name that is distinct from Qt's default lock file name. Also make it hidden on Unix systems.

PICARD-2088: Fix Windows not writing to settings file

---

picard/script/functions.py

* This is a…
Improve descriptions by making some function definitions with optional arguments less technical, make functions with variable arguments more consistent and add a couple of examples to clarify.
Some script functions do not have examples and description is technical in nature e.g. $delprefix says `$delprefix(text,*prefix="a","the")`. For the non-technical it suggests that you need to use a *prefix and put quotes around the text items, neither of which is true.
This PR just improves some of these descriptions.
* JIRA ticket: PICARD-2105
Changes to description text strings only

PICARD-2105: Improve script function popup descriptions

---

picard/browser/browser.py

* This is a…
* JIRA ticket (_optional_): PICARD-2131
On Firefox the tagger button request blocks for > 4 seconds before succeeding since recent refactoring of the browser listener code. Closer investigation reveals that before the actual request there is kind of a ghost request received on the socket, but which blocks on reading. The exact cause is not clear to me, it does not happen on other browsers or when invoking the Picard URL in any other way from within Firefox.
Apply a timeout to the request socket. That makes the initial ghost request fail quickly and not block the actual processing.
An alternative approach that also worked for me:
```
def handle(self):
self.request.setblocking(False)
super().handle()
```

PICARD-2131: Workaround for slow reaction of tagger button in Firefox

---

picard/formats/id3.py
test/formats/test_id3.py

* This is a…
`license` and `website` tags can get duplicated when saving and cannot be deleted completely.
* JIRA ticket (_optional_): PICARD-2135
Handle deletion and updating of `license` and `website` tags in ID3, added tests.

PICARD-2135: Fixed saving and deleting license and website to ID3

---

picard/ui/mainwindow.py

* This is a…
* JIRA ticket (_optional_): PICARD-2138
On macOS the toolbar is set to be non-movable for the UI to better blend into native look and feel. But after saving the options the toolbar gets recreated but set to be movable.
Update the toolbar properties in the respective functions so they are applied consistently also on recreation.

PICARD-2138: Do not change toolbar to be movable after saving options on macOS

---

picard/ui/mainwindow.py

* This is a…
* JIRA ticket (_optional_): PICARD-2156
On macOS ⌘+H is a system shortcut to hide the window, it conflicts with the default shortcut Picard uses for showing the history Window. 
Use Use ⌘+Shift+H on macOS instead. This is also consistent with other shortcuts that we combine with Shift, e.g. for Tags from filenames or Lookup in browser.

PICARD-2156: Use ⌘+⇧+H as shortcut for history window on macOS

---

picard/log.py
picard/ui/logview.py
test/test_log.py

* This is a…
Calculate the starting position of log entries to print in the log window instead of comparing individual positions.
* JIRA ticket (_optional_): PICARD-2157
The logging window drastically slows down Picard on Windows (at least on debug mode). The cause of the slowdown is the comparison of positions of entries that should be printed in the queue log. 
Instead of comparing each item, calculate the starting position and copy everything available after that.

PICARD-2157: Reduce comparison overhead of logging window

---

picard/ui/widgets/scripttextedit.py

* This is a…
* JIRA ticket (_optional_): PICARD-2168
The default shortcut to toggle the auto completion in script editors is set to Command+Space on macOS, but this conflicts with the system wide shortcut to trigger Spotlight search.
Command+Space is reserved for Spotlight search. Control+Space is also what is used by XCode for autocompletion.

PICARD-2168: Use Control+Space for script edit autocompletion on macOS

---

picard/file.py

* This is a…
* JIRA ticket (_optional_): PICARD-2170
When title / tracknumber are not present in the file's tags and are guessed from filename they should show up as changed tags.
Store original metadata before the guessed values get set.

PICARD-2170: Guessed title / tracknumber should show up as changed tags

---

picard/config.py

* This is a…
This adds the config caching introduced in 18c4e93cf1073e21857e4e39d311eb28d9d8f76f as part of #1555 again. This was lost in the refactoring of the config for Picard 2.6
Apply the test again, removed some obsolete code.
See also my comment at https://github.com/metabrainz/picard/pull/1780#issuecomment-815536274 for some measurements of how this can affect performance.

Re-enable config memoization

---

picard/script/functions.py
test/test_script.py

* This is a…
This is a simple patch to add a "$replacemulti" script function. It was originally implemented as a plugin for a user who was asking in IRC if it was possible to change/replace genres:
* [Community post](https://community.metabrainz.org/t/trying-to-standardize-genres-other-tags/527069/13)
* [Plugin gist](https://gist.github.com/atj/2333e8279bfa194b9ab624c9b637df65)
Happy to create a JIRA ticket if required.

PICARD-2177: Add script function to replace entries in multi-value variables

---

picard/__init__.py
picard/plugin.py
requirements-macos-10.12.txt
requirements-macos-10.14.txt
requirements-win.txt

* This is a…
* JIRA ticket (_optional_): PICARD-2181
* https://github.com/metabrainz/picard-website/pull/229
Many plugins try to come with a more comprehensive description, including some markup. So far those plugins contained HTML tags. Allowing markdown will allow easier and better readable (in source) formatting.
Use the already used python-markdown module to render the plugin descriptions. As this module is considered optional provide a fallback that only ensures newlines are preserved.
Rendering with Markdown:
Without Markdown, using fallback:
As HTML is allowed in markdown existing descriptions continue to render properly. Likewise pure markdown still remains readable without conversion to HTML.
For the listing of downloadable plugins …

PICARD-2181: Allow Markdown for plugin descriptions

---

picard/script/functions.py
test/test_script.py

* This is a…
Previously,
> $replacemulti(%foo%,A,,)
failed with
> "Expected str instance, ScriptExpression found"
* JIRA ticket (_optional_): PICARD-2182
Eval the ScriptExpression to get the real value.

PICARD-2182: Fix the no-op codepath of $replacemulti

---

picard/script/functions.py
picard/script/parser.py
test/test_script.py

* This is a…
The `$map()` function does not remove empty elements.  This is inconsistent with other multi-value variable processing.
* JIRA ticket (_optional_): PICARD-2185
Automatically remove empty elements from `$map()` output.

PICARD-2185: Remove empty elements from $map() output

---

picard/album.py
picard/cluster.py
picard/file.py
picard/metadata.py
picard/track.py
picard/ui/item.py
picard/ui/itemviews.py

* This is a…
This add  a cover columns in album, tracks, files and cluster to be able to order by presence or abscence of cover art.
* JIRA ticket (_optional_): PICARD-2176
added a method in picard.metadata wich is use by the 4 module to retrive cover art information
Because the ouptu of this method have to be a number, or a string (when it used for the title colum of the album module), I create a argument "forcount". But not shure this is the best way to go. 
this is my first piece of programming in python, hope it not to dirty o/

PICARD-2176: Add column to see if cover art is present 

---

picard/ui/options/plugins.py

* This is a…
* JIRA ticket (_optional_): PICARD-2188
Avoid plugin API fetch old version from network cache. Still allow caching, but make sure each versions gets cached separately.
I noticed this when installing the happidev_lyrics plugin directly before our last website update, and then trying to update afterwards. The plugin list would show the update from 2.0 -> 2.1 being available, but after updating 2.0 got installed. Likewise when uninstalling the plugin it would show the 2.1 version being available, but install would fetch the ZIP from cache, resulting in 2.0 being installed.
Make the URL version aware by appending the version to the parameter. We could consider making use of this parameter server side, but for now that's not necessary. …

PICARD-2188: Fix plugin update fetching outdated version

---

.github/workflows/package.yml
requirements-build.txt

* This is a…
Use latest PyInstaller 4.3, see https://pyinstaller.readthedocs.io/en/stable/CHANGES.html#id1 for details.
For us interesting is the fix for https://github.com/pyinstaller/pyinstaller/issues/5579:
> Windows: Set EXE checksums. Reduces false-positive detection from antiviral software.
Having anti virus software detecting Picard or other PyInstaller based software as false positive is a recurring scheme. If this change reduces it that'd be great.

Upgrade to PyInstaller 4.3

---

picard/file.py

* This is a…
* JIRA ticket (_optional_): PICARD-2170
With PICARD-2170 the title and tracknumber fields guessed from filename when empty are treated as modified metadata.
The reasoning was that this data is not present in the file's tags and hence should not show up as original metadata.
However, the previous behavior was more useful. One can argue that this is still data from the files. Having this available for comparison when tagging the files with actual new metadata from MusicBrainz is useful. See e.g. the issue report at https://community.metabrainz.org/t/musicbrainz-picard-2-6-is-now-available/526853/23
The proposal here is to revert this change for the 2.6 series and instead provide an option to disable the tracknumber and title guessing …

Revert "PICARD-2170: Guessed title / tracknumber should show up as changed tags"

---

picard/file.py
picard/ui/options/metadata.py
picard/ui/ui_options_metadata.py
picard/util/__init__.py
test/test_utils.py
ui/options_metadata.ui

* This is a…
* JIRA ticket (_optional_): PICARD-2171
If tracknumber and title are not present in tags, Picard will guess those from the filename. Not all users might always want this automation, see PICARD-2170
Add an option to enable/disable guessing title and tracknumber from filename, enabled by default.

PICARD-2171: Optional guess title and tracknumber

---

picard/coverart/providers/caa.py
picard/ui/__init__.py
picard/ui/mainwindow.py
picard/ui/options/dialog.py
picard/ui/options/fingerprinting.py
picard/ui/tagsfromfilenames.py
picard/util/webbrowser2.py

* This is a…
Move code common to open a help page, with keyboard shortcut handling, to PicardDialog. This will make it easier to add similar functionality to other dialogs.

Add common functionality to open help to PicardDialog

---

picard/script/__init__.py
picard/script/parser.py
picard/ui/widgets/scripttextedit.py
test/test_script.py

* This is a…
* JIRA ticket (_optional_): PICARD-2204, PICARD-2200
This adds support for Unicode escape sequences in the form of `\uFFFF` to tagger script.
Rationale:
- This would allow explicitly inserting special characters and makes it easier to define some characters the user cannot write
- Allows making invisible control characters visible (see PICARD-2200)
Extend the tagger script parser for support of Unicode escape sequences. The Unicode escape sequences always start with `\u` followed by a four digit hexadecimal number representing the Unicode code point. E.g. to get the character 湖 one can also use `\u6e56`. To explicitly insert a thin space a user can write `\u2009`.
This also extends the script editor for proper syntax highlighting …

PICARD-2204: Support unicode escape sequences in tagger scripts

---

picard/ui/widgets/scriptdocumentation.py

* This is a…
* JIRA ticket (_optional_): PICARD-2200
This is another mitigation for people accidentally copying the Unicode left-to-right marks that we place in the inline documentation into the scripting. The previous https://github.com/metabrainz/picard/pull/1806 is a generic improvement, making it easier for users to deal with this and similar situations, and improving handling of Unicode characters in scripts in general.
This change now limits the use of the Unicode left-to-right mark U+200E only to actual right-to-left UI language. In other cases it is not needed, so the majority of users will not encounter this at all.
Add the Unicode left-to-right mark U+200E only when UI language is a RTL language. This mitigates the issue of users …

PICARD-2200: Add unicode left-to-right marks only for RTL languages

---

picard/script/parser.py
picard/ui/widgets/scripttextedit.py

The scripting syntax definition and parser implementation allow such functions.
* This is a…
* JIRA ticket (_optional_): PICARD-2205
According to the tagger script grammar [1]  and the actual implementation a function name can consist of the characters [a-zA-Z0-9_], without restriction on placement.
Thus the following examples are all valid function names: `$_`, `$123`, `$_a_`, `$_1a`
But the syntax highlighting assumes function names must start with [a-zA-Z].
https://github.com/metabrainz/picard/blob/master/picard/script/parser.py#L202-L212
Update the syntax highlighting to properly highlight those functions.

PICARD-2205: Update syntax highlighting to allow functions starting with _ or 0-9

---

picard/__init__.py
scripts/picard.in
tagger.py.in

* This is a…
* JIRA ticket (_optional_): PICARD-1718
This is another submission of https://github.com/metabrainz/picard/pull/1466
Overall I'm actually for now finally merging this. If Picard suddenly crashes we and the users are usually flying in the dark. It is difficult to get users to start Picard from command line to get a proper exception stack trace, and depending on circumstance and setup (e.g. Windows portable or store versions) even impossible.
The patch as is I had now several times applied locally to narrow down a reported crash.
As I mentioned in #1466 there are still cases that might not be caught, but given that it improves the debugging a lot for the majority of cases let's merge this.
I reduced code duplication a bit compared to …

PICARD-1718: crash handler

---

picard/tagger.py
picard/util/thread.py

* This is a…
This aims to replace QThread with concurrent.futures to reduce dependency on Qt for core functionality outside of actual UI.
The implementation uses concurrent.futures, but maintains the existing API interface exposed by `picard.util.threads.run_task`. For normal usage of the threading feature (as this is currently being used by Picard itself and from the plugins we host) this should be backward compatible.
Differences:
- If a caller provides its own value for the `thread_pool` parameter this now needs to be a concurrent.futures.Executor. So if a plugin makes use of this (existing plugins do not) by passing a `QThreadPool` instance it would be incompatible.
- `run_task` now returns an instance …

Replace QThread with Python threads using concurrent.futures

---

picard/ui/scripteditor.py
picard/ui/widgets/scripttextedit.py

* This is a…
* JIRA ticket (_optional_): PICARD-2197, PICARD-2207
This adds a context menu to the script text editor to toggle line wrapping and display of tooltips.
Overall this brings the following improvements:
- "Word wrap script" is now also available in Options > Scripting via context menu
- "Word wrap script" gets persisted
- "Word wrap script" uses <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>W</kbd> instead of <kbd>Ctrl</kbd>+<kbd>W</kbd>. That's because <kbd>Ctrl</kbd>+<kbd>W</kbd> is already the default for closing a dialog
- A new action "Show help tooltips" has been added, which is available both via context menu and script editor dialog "Display" menu
Move word wrap action to `ScriptTextEdit`, implement context menu.

Script editor context menu to toggle line wrap and tooltips

---

picard/ui/__init__.py
picard/ui/aboutdialog.py
picard/ui/cdlookup.py
picard/ui/edittagdialog.py
picard/ui/infodialog.py
picard/ui/mainwindow.py
picard/ui/options/dialog.py
picard/ui/options/scripting.py
picard/ui/scripteditor.py
picard/ui/tablebaseddialog.py
picard/ui/tagsfromfilenames.py

* This is a…
The autorestore feature of the `PreserveGeometry`  helper class can mostly not be used, as most classes intiialize the UI later. Instead `PreserveGeometry.restore_geometry` should be called for a dialog just before it is shown for the first time.
Handle calling `restore_geometry` in `PicardDialog`. Introduce a new signal `ready_for_display` that is also emitted exactly once, just before the dialog gets shown for the first time.

Automatically restore geometry of PicardDialog instances

---

picard/ui/mainwindow.py

Otherwise this can lead to performance issues if the user minimizes / maximizes the main window multiple times, causing multiple DesktopStatusIndicator getting registered.
* This is a…
* JIRA ticket (_optional_): PICARD-2209
When the user toggles the main window between minimized and maximized Picard will register the DesktopStatusIndicator multiple times. Doing this repeatedly can cause slow downs due to multiple registered indicators. 
Remember whether showEvent was already called or not. We cannot move this into e.g. __init__, as for Windows the window must actually exist before you can access the taskbar button's API.
Would QWidget provide another place to call this, but only once the widget has been fully created?

PICARD-2209: Ensure DesktopStatusIndicator is registered only once

---

.github/workflows/run-tests.yml
picard/__init__.py
picard/tagger.py
scripts/package/macos-package-app.sh

* This is a…
This is mainly for running Picard in CI environments and debugging. E.g. on CI we sometimes run `picard --version`  just to verify the build package is working. But if that fails without graphical environment this fails hard when trying to show the error dialog with an error message unrelated to the original issue. See e.g. https://github.com/phw/picard/runs/2594991408:
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
>
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, …

Allow disabling graphical crash handler with --no-crash-dialog

---

picard/file.py
test/test_file.py

* This is a…
* JIRA ticket (_optional_): PICARD-2219
A renaming script evaluating to an empty name would cause files to be renamed to e.g. "_mp3", breaking the file extension. Now the original filename will be kept.
Keep original filename if naming script evaluates to an empty name. Added tests.

PICARD-2219: Fix empty renaming script breaking the filename

---

picard/script/functions.py
picard/track.py
picard/util/__init__.py
test/test_script.py
test/test_utils.py

* This is a…
* JIRA ticket (_optional_): PICARD-2218, PICARD-2217, PICARD-2216
As discussed in PICARD-2216 the `$performer(pattern)` function is not very flexible if you want to access a specific instrument. The pattern will always match anywhere in the string, e.g. `$performer(vocals)` will match both "performer:vocals" and "performer: background vocals". You have no way to match only exactly "performer:vocals". This is partly intentional (`$performer` is supposed to match a substring),  but also not very flexible. Having it support regular expressions would allow for e.g. `$performer(^vocals$)` for exact match.
While looking at that an actual bug was detected: Currently the pattern is matched against the full tag name (e.g. …

PICARD-2218: Allow regular expressions in $performer(pattern)

---

picard/config.py
test/picardtestcase.py
test/test_config.py

* This is a…
* JIRA ticket (_optional_): PICARD-2226
Syncing between those instances does not work [as advertised](https://doc.qt.io/qt-5/qsettings.html#accessing-settings-from-multiple-threads-or-processes-simultaneously), which causes missing updates on config changes where a config change is not reflected in tags.
Get rid of the multiple config instances, one per thread.
We added this in the hope it would resolve our deadlock issue. But the root cause was different, and is both fixed by recent PyQt5 and as well by our locking workaround at https://github.com/metabrainz/picard/blob/master/picard/config.py#L164-L186 , which makes sure this does not happen even with older versions.
While …

PICARD-2226: Removed config object per thread again

---

picard/ui/scripteditor.py

* This is a…
* **Describe this change in 1-2 sentences**: Correct the logic for checking for unsaved changes when selecting a new script in the script editor
There is an error in the logic that caused the unsaved changes check from being performed when switching the selected script in the combo box.
Correct the logic so that the check is properly completed.

Fix unsaved changes confirmation check when changing selected script

---

INSTALL.md
picard/browser/addrelease.py
picard/browser/browser.py
picard/cluster.py
picard/tagger.py
picard/ui/item.py
picard/ui/itemviews.py
picard/ui/mainwindow.py
picard/ui/options/network.py
requirements-macos-10.12.txt
requirements-macos-10.14.txt
requirements-win.txt
requirements.txt
test/test_browser_addrelease.py

* This is a…
* JIRA ticket (_optional_): PICARD-2203
This integrates the functionality to submit cluster as a release / submit a file as a recording as it is currently found in the [addrelease plugin](https://github.com/metabrainz/picard-plugins/blob/2.0/plugins/addrelease/addrelease.py).
Rationale:
- The addrelease plugin is broken in recent versions of Firefox, see PICARD-2202. This can be best solved by serving the intermediate HTML form via an actual local web server instead of loading it as a local HTML file. This can be better done from within Picard, especially as it already provides a built-in webserver for the browser integration feature.
- Originally the addrelease plugin was quite a hack. But since the [release editor …

PICARD-2203: Integrate addrelease functionality into Picard

---

picard/__init__.py
picard/config_upgrade.py
picard/const/__init__.py
picard/file.py
picard/script/__init__.py
picard/script/serializer.py
picard/ui/options/renaming.py
picard/ui/scripteditor.py
test/formats/test_apev2.py
test/test_file.py

* This is a…
* **Describe this change in 1-2 sentences**:  Refactor to remove the duplicate "file_naming_format" setting information, and provide a helper function to retrieve the file naming script text based on the user's "selected_file_naming_script_id" setting.
Information is (potentially) duplicated in the user configuration settings, specifically the currently selected file naming script which shows up in the "file_naming_format" settings as well as one of the elements of the "file_naming_scripts" list.
Remove the "file_naming_format" setting and provide a helper function to look up the file naming script from the list of scripts stored in the user settings, based on the "selected_file_naming_script_id" setting.  To improve the lookup …

Refactor to reduce duplication of file naming script text in user settings

---

picard/browser/addrelease.py
picard/disc.py
picard/ui/options/general.py
picard/ui/ui_options_general.py
picard/util/mbserver.py
test/test_disc.py
test/test_util_mbserver.py
ui/options_general.ui

* This is a…
* JIRA ticket (_optional_): PICARD-2232, PICARD-1645
The new add cluster / files functionality added in #1839 always submits to main servers, regardless of what server has been configured. Likewise disc ID submission always submits to musicbrainz.org as well, see PICARD-1645.
In the majority of cases that is the wanted behavior. But sometimes they might want to submit to their local mirror, either for testing/debugging or because they actually want the submissions only to have locally.
The default behavior is that the main database is being used. As long as the user has configured the official servers (musicbrainz.org or beta.musicbrainz.org) those are used for submission of addrelease and discid as well.
But if the user enters an …

PICARD-2232: Allow add cluster/files and disc ID submission to unofficial servers

---

picard/config.py

Example of output:
```
E: 09:54:33,561 config.__init__:324: Option setting/file_renaming_scripts already declared
at ./picard/ui/options/renaming.py:92: in RenamingOptionsPage
Option("setting", "file_renaming_scripts", {}),
```

Log multiple Option declarations

---

picard/config.py

Ensure logging is working, even if stack cannot be retrieved or has no code context

Make duplicated option declaration logging more reliable

---

picard/ui/mainwindow.py
picard/ui/scripteditor.py

* This is a…
* **Describe this change in 1-2 sentences**: Enable opening the file naming script editor from the main window.
The file naming script editor could only be opened from the "File Naming" section of the "Options" ==> "Options..." screen.  This should also be available directly from Picard's main screen to accommodate quick changes to go along with the ability to quickly select the file naming script to be used.
Provide a new "Options" ==> "Open script editor..." menu item.
In order to avoid possible issues with multiple copies of the script editor open simultaneously (one from the main screen and a second from the "File Naming" section of the "Options" ==> "Options..." screen), when it is opened from the main screen, the command to open …

Show script editor from main screen menu

---

picard/ui/profileeditor.py

* This is a…
* **Describe this change in 1-2 sentences**:  Display profile setting override values as tooltips.
There was no easy way of seeing what the settings override values were for a profile.
Provide the current override value for the profile as a tooltip on the setting in the settings tree.
This currently uses tooltips, but could easily be converted to display the settings in a text box on the dialog when the setting is selected if that is preferred.

Display profile setting items as tooltips

---

picard/ui/profileeditor.py

* This is a…
* **Describe this change in 1-2 sentences**: Disallow entering a blank profile title.
When changing the title of a user profile, the title could be entered as a blank (empty string).
Implement a check when the profile title is changed to disallow entering a blank profile title.  Also remove any leading or trailing whitespace.

Disallow entering a blank profile title

---

picard/ui/widgets/scripttextedit.py

* This is a…
* JIRA ticket (_optional_): PICARD-2204
On Windows the existing QMimeData object cannot be modified, if the data was copied from outside the app itself. That meant replacing control characters with Unicode escape sequences on copy and paste did not work.
Create a new QMimeData. Also generally ignore formatting, we only care about plain text. I have not verified, but it could help fix some issues were users had experienced external formatting being applied to the script window after copy and paste, such as smaller font sizes.

PICARD-2204: Fixed unicode escape sequences on Windows copy paste

---

picard/ui/coverartbox.py
picard/ui/itemviews.py
picard/util/__init__.py

* This is a…
Fix `TypeError: arguments did not match any overloaded call` that occurs when running Picard with Python 3.10.
Hi,
I tried running Picard with Python 3.10.0rc1, all tests pass but the GUI doesn't open because of errors such as:
```
File "./picard/ui/coverartbox.py", line 74, in __init__
self.shadow = self.shadow.scaled(w, h, QtCore.Qt.KeepAspectRatio, QtCore.Qt.SmoothTransformation)
TypeError: arguments did not match any overloaded call:
scaled(self, int, int, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: Qt.TransformationMode = Qt.FastTransformation): argument 1 has unexpected type 'float'
scaled(self, QSize, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: …
```

PICARD-2269: Fix "TypeError: arguments did not match any overloaded call" with Python 3.10

---

picard/acoustid/__init__.py

* This is a…
Users are frequently confused if there are existing AcoustIDs that match a file's fingerprint, but the AcoustIDs are not linked to any recording. Users expect the AcoustID tag still to be filled, even if Picard failed to find a recording linked to this AcoustID.
Having the ID can also help the user to identify more details about the file, e.g. by looking up the AcoustID online they might be able to identify the file and then manually match it to a proper MB recording.
If acoustid.org finds a matching AcoustID for a fingerprint, always set the acoustid_id tag.

PICARD-2273: Always set acoustid_id, even if not linked to MB recordings

---

picard/acousticbrainz/__init__.py
picard/ui/options/acousticbrainz.py

* This is a…
This fixes a some issues encountered during testing:
1. Update the action status in main window if AcousticBrainz gets enabled / disabled
2. Fix submission failing if no recording ID is stored in the tags
The second issues requires some discussion. The issue I encountered was a KeyError exception in https://github.com/metabrainz/picard/blob/master/picard/acousticbrainz/__init__.py#L198 if the features file did not extract a recording ID from existing tags.
But the fix changes more. Previously the submission would not be done if the recording ID stored in tags differs from the currently matched recording ID. I think this is not very clear, because submission would fail, but the user would just assume they have the files matched and …

AcousticBrainz fixes

---

picard/ui/itemviews.py

* This is a…
* JIRA ticket (_optional_): PICARD-2274
In some situations items from the tree views get updated without being attached to the tree widget. Avoid exceptions in this situation.
Picard can crash when updating widget items in the main tree view under some circumstances, see PICARD-2274 for how to reproduce.
Generally be aware that a `QTreeWidgetItem` is not always attached to a `QTreeWidget`, hence `treeWidget()`  might return `None`. Handle this case without crashing.

PICARD-2274: Fix crashes when updating items without tree widget

---

picard/acousticbrainz/__init__.py
picard/file.py

* This is a…
This is an extension to the discussion in https://github.com/metabrainz/picard/pull/1895 . There I fixed the issue of submission crashing when a file did not have a recording ID saved in the tags. In the fix I changed the behavior to always submit with currently matched files, that means overwriting the metadata the streaming extractor had read from the file with our currently matched recording ID.
But the original intention of the code was to ensure a file has been properly matched to only allow clean submissions. Similar to how the current AB submission tools are supposed to be run on files already properly tagged with MB tags.
- Only allow submission of saved files
- Restore the original …

Only allow AB submission for saved files

---

picard/file.py
picard/ui/options/fingerprinting.py
picard/ui/ui_options_fingerprinting.py
test/test_file.py
ui/options_fingerprinting.ui

* This is a…
* JIRA ticket (_optional_): PICARD-2279
Picard supports reading existing fingerprints from the `acoustid_fingerprint` tag, but it has no option to save calculated fingerprints there.
While usually this was considered to be not needed, as the fingerprint can always be calculated again from the audio and can add rather long data to the file, there are some use cases and some users using this. E.g. one user on the forums described a workflow where they add this tag directly after ripping to avoid having to redo the calculation later on.
See e.g. also discussions on the forums like https://community.metabrainz.org/t/picard-2-3-option-to-generate-fingerprints-automatically-to-submit-it/464069/5
Add an option for saving the fingerprint …

PICARD-2279: Allow saving AcoustID fingerprint in acoustid_fingerprint tag

---

picard/const/__init__.py
picard/const/appdirs.py
picard/webservice/__init__.py
scripts/pyinstaller/portable-hook.py
test/test_const_appdirs.py

* This is a…
* JIRA ticket (_optional_): PICARD-2189
The cache location previously was wrong because it was created before app and org name had been set. The new module fixes this and allows more flexible replacement of the implementation.
- Fix cache location by ensuring `QCoreApplication.setApplicationName` and `QCoreApplication.setOrganizationName` get called before QStandardLocations are being used
- Introduce an new `picard.const.appdirs` module, to centralize the place where we deal with these directories. This makes it easier to test and to exchange the implementation in the future.
- Added platform specific tests, this will allow us to change implementation 
At it's core this PR only deals with fixing the cache location. But there are …

PICARD-2189: Add appdirs module to fix getting proper cache location

---

picard/util/textencoding.py
test/test_textencoding.py

* This is a…
* JIRA ticket (_optional_): PICARD-2236
A full width slash U+FF0F, e.g. in イニシエノウタ／デボル, in combination with replace non-ascii gets turned into an ASCII slash, leading to a directory being created.
Have `unicode_simplify_compatibility` honor the pathsave and win_compat settings.

PICARD-2236: Fullwidth slash is treated as directory separator

---

picard/track.py

* This is a…
* JIRA ticket (_optional_): PICARD-2261
Fixes e.g. breaking tags with ending newlines, like e.g. some iTunes specific tags like `itunnorm`.
Do not run `Metadata.strip_whitespace` after applying scripts to tags.
I am actually not sure if there is a need to run this at all. I kept the stripping when applying the scripts to the track metadata, because this is also done in https://github.com/metabrainz/picard/blob/master/picard/album.py#L383-L398 . But I'm not sure if this really is something that should be done.
It also means my change might cause slightly different results when scripts get applied to files, and this might cause differences in scripts having unintentional additional whitespace. It might even mean that in case of …

PICARD-2261: Do not strip whitespace from file tags

---

picard/formats/id3.py
test/formats/test_id3.py

* This is a…
* JIRA ticket (_optional_): PICARD-2199
If you configure Options > Metadata > Ratings > E-mail to include characters that cannot be encoded as latin-1 saving a file triggers an exception.
Use `id3text` helper function to ensure data stored in the file is encodable in latin1.

PICARD-2199: Fix saving ratings to ID3 with non-latin1 characters in email

---

picard/formats/apev2.py
picard/formats/asf.py
picard/formats/id3.py
picard/formats/mp4.py
test/formats/common.py
test/formats/test_asf.py
test/formats/test_mp4.py

* This is a…
* JIRA ticket (_optional_): PICARD-2314
Those values are taken from technical format information and are not part of the tags. This also fixes ~length getting written to MP4 as `----:com.apple.iTunes:~length` (PICARD-2314).
Having `supports_tag(~length)` return True should never be the case, as this is not considered a proper metadata tag. This was originally added in https://github.com/metabrainz/picard/commit/c39384c7074e5e66483c8b905f29ec87abd2a6d6, to address a regression where the Length field did not show up in the metadatabox. But this is no longer necessary, the metadatabox deals with length separately.

PICARD-2314: Fix ~length getting written to MP4 ----:com.apple.iTunes:~length

---

picard/album.py
picard/track.py
picard/ui/coverartbox.py
picard/util/imagelist.py
test/test_imagelist.py

* This is a…
* JIRA ticket (_optional_): PICARD-2321, PICARD-2322
- On tracks with attached files cover art changes are not reset in cover art box when using "Keep original cover art"
- An album loaded with already matched files does not indicate cover art changes correctly
- Fix updating tracks in d6435a894135db779e2b56a026a6623b0b690ef2 by remembering the original cover art for a file. This was important to not regress on the fix from 1cb8c77d6ed4737e34bdbeec48581d687531afe8 (after removing all files a track had no cover art attached anymore).
- Albums update their cover art after matching all files (5d2bde5b7a16638af454a23a66fd1c230d81d4fa)
- A small optimization of `imagelist.add_metadata_images` in d4ad11addf8806c18ed6041f27b80aaaf2cc3a8a …

PICARD-2321: Fix keep coverart for tracks and display of cover art changes for albums

---

picard/file.py
picard/formats/apev2.py
picard/util/filenaming.py
test/formats/test_apev2.py
test/test_filesystem.py
test/test_util_filenaming.py

* This is a…
* JIRA ticket (_optional_): PICARD-2324
Renaming / moving WavPack files is supposed to also rename / move a WavPack correction file (with the same filename, but .wvc extension). This broke with the changes for PICARD-1715 due to https://github.com/phw/picard/commit/bcc81d86eb1cfcbe1f72043feec8d50a9accc1f5#diff-8e9e6145ecc7e912b2d643f5064e6f196d3668bd010ffa6037775232c2aba236R357
Re-implement renaming the .wvc file by using the actual new filename of the .wv file. This avoids the entire scripting logic to construct the filename, and hence avoids issues with using the `~extension` from metadata. Also avoids issues where a script might cause different naming due to e.g. extension checks.
Also extended the test so it actually fails with …

PICARD-2324: Fix renaming of WavPack correction files

---

picard/ui/itemviews.py

* This is a…
* JIRA ticket (_optional_): PICARD-2328
This adds another instance of the "arguments did not match any overloaded call" error with Python 3.10, for which we already had fixes in PICARD-2269.
Ensure integer values for

PICARD-2328: Fix "arguments did not match any overloaded call" error with Python 3.10

---

picard/album.py

This reverts commit 672c2c0733000ee30de0db4c657a1c0b99f68960.
This causes a bug when adding files to album in certain cases
* This is a…

Revert "_match_files(): conversion to list isn't strictly needed"

---

picard/cluster.py
picard/tagger.py

* This is a…
* JIRA ticket (_optional_): PICARD-2339
Further improve on #1963 by moving the call to `Cluster.cluster` into a separate thread. This also removes the need to call `QCoreApplication.processEvents` (by `process_events_iter`)  in between to keep the UI responsive.
The raw execution time of `Cluster.cluster` and turning the result into a list is now again lowered. In my tests on my system it takes ~ 50ms for 4257 files.
In my tests this works well, I did not notice a regression to previous behavior.

PICARD-2339: Perform file clustering in thread

---

picard/cluster.py
picard/util/__init__.py
test/test_utils.py

* This is a…
`album_artist_from_path` is called by the clustering, which removes the Windows drive letter from the path to avoid that the drive gets detected as artist or album name.
This functionality should be part of `album_artist_from_path` itself. It also only applies to Windows, not for other systems, even in Windows compatibility mode (see discussion at https://github.com/metabrainz/picard/pull/1963#discussion_r755199555)
Extend `album_artist_from_path` to use `ntpath.splitdrive` on Windows. Add tests.

Have album_artist_from_path strip the Windows drive letter

---

picard/ui/options/scripting.py
picard/ui/widgets/scriptlistwidget.py

* This is a…
* **Describe this change in 1-2 sentences**: Add `has_error` attribute to `ScriptListWidgetItem` class.  Check for error when selecting a new script and revert selection if current script has an error.
* JIRA ticket (_optional_): PICARD-2335
If you create a tagging script with an error, clicking "Make It So!" does nothing – it correctly doesn't allow saving the script with the error.  However; if you select a different script that doesn't have an error, "Make It So!" will save the script with the error.
Add `has_error` attribute to `ScriptListWidgetItem` class.  Check for error when selecting a new script and revert selection if current script has an error.  This effectively blocks the user from executing "Make It So!" if there is an error in a tagging script.
None.

PICARD-2335: Disallow saving a tagging script with errors

---

picard/formats/asf.py
picard/formats/mp4.py
test/formats/coverart.py

* This is a…
* JIRA ticket (_optional_): PICARD-2342
Saving MP4 or ASF files failed if the files do not have existing embedded cover art and both "clear existing tags" and "keep embedded images when clearing tags" are active.
Add a test for this specific case (for all formats) and fix the issue.

PICARD-2342: Fix saving MP4 and ASF files with "clear tags" and "preserve images"

---

picard/i18n.py

* This is a…
* JIRA ticket (_optional_): PICARD-2351
System language detection for Windows broke in Picard 2.7.0b3 with https://github.com/metabrainz/picard/commit/0816eb61bfac1928611ce3b8c29b23479929560f
It turns out that the call to `locale.setlocale(locale.LC_ALL, current_locale)` on Windows did not work most of the time because of the encoding. E.g. on a German Windows 11 the locale we used was `de_DE.cp1252`, but passing this to `locale.setlocale`  raises an `locale.Error`  with "unsupported locale setting".
So let's just set the locale based on the language alone, only `de_DE`.
The reason why language selection worked anyway is because prior to 0816eb61bfac1928611ce3b8c29b23479929560f we set the `de_DE.cp1252` in `os.environ['LANGUAGE']` …

PICARD-2351: Fix system language detection on Windows

---

picard/cluster.py
picard/tagger.py
test/test_clustering.py

* This is a…
* JIRA ticket (_optional_): PICARD-2361
Removing files while clustering can keep those files available, both confusing the file count and general file behavior. See PICARD-2361 for details.
Only use files for clusters if they are not marked as removed. Handle the check if there are valid files into the cluster on the main thread when creating the final cluster for the UI.

PICARD-2361: Fix clustering using removed files

---

picard/file.py

* This is a…
* JIRA ticket (_optional_): PICARD-2363
Copying the new metadata over to the original metadata after saving must consider format specific conversions.
This was caused by a5fcde1 as part of PICARD-2174. This PR here actually complements the fix done in #1982.
When copying new metadata to original metadata after saving apply the format conversions.
I chose this approach as it might avoid some other similar issues, and it matches the behavior before a5fcde1 . The alternative would be to have https://github.com/phw/picard/blob/40b2b76ce7f150321d40bdf8e2051023d97a8a6a/picard/file.py#L689 also use `self.format_specific_metadata()`, but that would add additional calls every time update is being called, something we should avoid. Doing …

PICARD-2363: Fix ID3v2.3 showing as changed after saving

---

picard/album.py
picard/cluster.py
picard/file.py
picard/track.py

* This is a…
Some of the `Item.can_*()`  implementations did not return boolean value. In combination with #1986 this has become an issue.

All Item.can_* methods must always return boolean values

---

requirements.txt

* This is a…
* JIRA ticket (_optional_): PICARD-2365
While PyYAML 6 has bumped major version due to some API changes, this does not affect usage in Picard, and it stays compatible.
This is also required for packaging in the upcoming Fedora 36
Allow PyYAML 6 in requirements.txt. Keep the versions specified for the mac and win builds, as we should build with same versions for the 2.7.1 release. Just provide more flexibility for packagers.

PICARD-2365: Allow PyYAML 6 in requirements.txt

---

scripts/tools/fix-header.py

* This is a…
fix-headers.py uses the default encoding for reading / writing the source files, but this can differ based on the platform. E.g. on my Windows setup it defaults to cp1252
The default encoding can be different based on the platform, but we expect UTF-8 for our source files. To stay flexible, make the default encoding UTF-8, but add a command line parameter to change it.

Support --encoding parameter in fix-header.py

---

picard/ui/options/dialog.py

* This is a…
* JIRA ticket (_optional_): PICARD-2372
Saving options does not always save settings to profiles. That's because the profiles can get updated after other settings
Always save profiles first before other settings.
Ensures the profiles are up to date and all saved settings end up in the profiles without getting overwritten later.

PICARD-2372: Always save profiles first before other settings

---

picard/script/functions.py
test/test_script.py

* This is a…
* **Describe this change in 1-2 sentences**: Make the `$slice()` 'end' parameter optional.
* JIRA ticket (_optional_): PICARD-2373
The documentation for the `$slice()` scripting function is incorrect because it shows the `end` parameter as optional.  The parameter can be left empty, but it still requires that it be included (thus requiring an additional comma in the call).  In discussing corrections to the documentation on https://github.com/metabrainz/picard-docs/pull/141 it was decided to correct the operation of the function to make the `end` parameter truly optional.
Make the `$slice()` 'end' parameter optional.  Update tests.
Update documentation.

PICARD-2373: Make `$slice()` 'end' parameter optional

---

picard/ui/infostatus.py

* This is a…
* JIRA ticket (_optional_): PICARD-2375
If there are only pending network requests but no file requests the loading progress stays near 0%.
The issue is caused by https://github.com/metabrainz/picard/blob/master/picard/ui/infostatus.py#L96-L101
There the starting time gets reset on each call if there are no more pending files to load, ignoring any requests. So once there are only pending requests it always has basically 100% progress still to do.
Consider both file and network requests and only reset if they both reached zero.

PICARD-2375: Fix progress indicator staying at 0% for pending network requests

---

picard/util/emptydir.py

* This is a…
* JIRA ticket (_optional_): PICARD-2377
If one of the QStandardPaths pointed to a no longer available location Picard would crash on startup
Handle the exception. The actual exception thrown was a `FileNotFoundError`, but https://docs.python.org/3/library/os.path.html#os.path.realpath documents it as throwing `OSError` (which is the superclass of `FileNotFoundError`), so handle that instead.

PICARD-2377: Fix potential crash on emptydirs initialization

---

picard/coverart/providers/caa.py
picard/webservice/api_helpers.py

* This is a…
* JIRA ticket (_optional_): PICARD-2374
Fetching cover art from cover art archive involves both requests to coverartarchive.org for the webservice and archive.org for the actual image downloads.
Picard currently does remove the default rate limit for coverartarchive.org, but keeps the 1 second ddefault delay for archive.org.
As archive.org does not apply a rate limit, we should remove this delay as well
Set rate limit for archive.org to 0. This also applies to subdomains. While the ratecontrol module keeps the adjusted delays separate for each subdomain, it copies the minimum delay from the main domain.
Also moved setting the limit to the CAA implementation, as I think knowledge of which hosts get queried should be kept close to …

PICARD-2374: Remove rate limit for archive.org

---

picard/acousticbrainz/__init__.py

* This is a…
* JIRA ticket (_optional_): PICARD-2378
AB submission on Windows submits the entire file path. It's essentially a bug in the extractor binary (https://github.com/MTG/essentia/issues/1209). But as this can reveal more information about the files than the user is comfortable with let's handle that on Picard side.
Set the `file_name` based on File.base_filename
If we choose to allow submission without saving (just matched files) then we would need to override the entire `.metadata.tags` dict anyway.

PICARD-2378: Ensure AB submission submits only base filename

---

.github/workflows/package.yml
scripts/package/win-setup.ps1

* This is a…
Same as #2012, but for Windows.
As we are downloading third party components that we then code sign and bundle in our Windows builds, verify we got the right binaries by checking their SHA256 hash.

packaging: Verify SHA256 hashes of downloaded Windows dependencies

---

picard/ui/ratingwidget.py
picard/webservice/api_helpers.py
test/test_api_helpers.py

* This is a…
MBAPIHelper._xml_ratings does not handle encoding the input parameters.
Properly XML encode provided data for rating submission. Also ensure rating is an integer as expected.
In the current implementation both should already be guaranteed. `track.id`  is always a MBID as given by MB service, and the rating widget's `self._rating`  is always an integer. But for a complete implementation in the context of `MBAPIHelper`  and to avoid potential issues both should be handled.

Ensure rating submission XML is valid

---

picard/ui/itemviews.py

* This is a…
* JIRA ticket (_optional_): PICARD-2386
Columns in main list which were not using natural sorting had all characters with diacritics sorted after Z. 
Use `locale.strxfrm` for locale aware sorting instead. This is still cheaper then the full natsort (which also uses strxfrm).
If we use `strxfrm` we should also not need the lower conversion.
Before:
After:

PICARD-2386: Fix sorting of characters with diacritics

---

picard/profile.py
picard/ui/options/metadata.py
picard/ui/ui_options_metadata.py
test/test_script.py
ui/options_metadata.ui

* This is a…
* **Describe this change in 1-2 sentences**: Standardize on "Standalone recordings" rather than "Non-album tracks"
* JIRA ticket (_optional_): PICARD-2349
For historical reasons Picard uses both the terms "standalone recording" and the older "non-album tracks". We should unify this.
This requires updates to existing translations, even though some translations might end up being unchanged because they maybe already use consistent terms.
Standardize on "Standalone recordings" rather than "Non-album tracks".

PICARD-2349: Use consistent terminology for "standalone recordings"

---

picard/script/functions.py
test/test_script.py

* This is a…
* **Describe this change in 1-2 sentences**:  Add an option to the `$copymerge()` function to allow keeping duplicates.
* JIRA ticket (_optional_): PICARD-2382
There is no (easy) way in Picard scripting to append one multi-value to another to keep the order without removing duplicates.
Add an option to the `$copymerge()` function to allow keeping duplicates.
Hold merge until Picard v2.8 to avoid additional translation requirements.
Update documentation.

PICARD-2382: Add option to keep duplicates in `$copymerge()` function.

---

picard/cluster.py
picard/metadata.py
test/data/ws_data/release_multidisc.json
test/test_metadata.py

* This is a…
* JIRA ticket (_optional_): PICARD-2368
tracktotal in a file is supposed to have the total number of tracks on the specific medium. Comparing to the total tracks of a release across all medium hence gives wrong results.
This PR replaces #1996

PICARD-2368: When comparing metadata to a release consider the actual medium track count

---

picard/ui/options/general.py

* This is a…
* JIRA ticket (_optional_): PICARD-2399
When the user closes the options dialog directly after entering the login auth token Picard crashes as it tries to update a deleted widget.
Use the `OptionsPage.deleted`  flag (which we added for a similar issue in plugins) to detect this situation and skip the UI update.

PICARD-2399: Avoid crash if options get closed directly after login

---

picard/album.py
picard/webservice/api_helpers.py

* This is a…
* JIRA ticket (_optional_): PICARD-2398
The MB API for performance reasons does not include recording level relationships if an release contains too many tracks. This leads to missing data if the user has enabled track relationships.
Detect the case of missing recording relationships and issue separate requests to load the recordings for a release. Since these requests are limited to 100 results multiple requests with offsets need to be done.

PICARD-2398: Load recording relationships separately for huge releases

---

test/formats/test_vorbis.py
test/picardtestcase.py

* This is a…
Log output was not shown in failing tests, making some issues hard to figure out. See https://github.com/metabrainz/picard/pull/2038 for background.
Lower log level for tests to `DEBUG`. This allows pytest to capture the log output and display it in context of the test.

Set log level in tests to DEBUG

---

picard/metadata.py
picard/script/functions.py
test/test_script.py

* This is a…
* **Describe this change in 1-2 sentences**:  Allow empty strings in multi-value variables.
* JIRA ticket (_optional_): PICARD-2392
Picard currently does not allow keeping empty strings in a multi-value variable, and automatically strips them out.  This can lead to problems for example if the user is trying to manage a list of artist join phrases, where the resulting multi-value may have elements removed so that it no longer matches the metadata.  This is the case with the changes to the ***AdditionalArtistsVariables*** plugin in https://github.com/metabrainz/picard-plugins/pull/320 requiring a non-blank placeholder to be substituted which would have to be removed by the user when processing the variable in a script.
The change includes the following:
- Keep empty strings in …

PICARD-2392: Allow empty strings in multi-value variables

---

picard/acoustid/manager.py
picard/webservice/api_helpers.py
test/test_acoustidmanager.py
test/test_api_helpers.py

* This is a…
* JIRA ticket (_optional_): PICARD-2396
Picard currently submits the AcoustID fingerprint in combination with a recording MBID, to link the AcoustID and recording. This submission currently makes no further validation of the data.
The discussion at https://community.metabrainz.org/t/report-showing-acoustids-likely-to-be-bad-link-to-musicbrainz-recordings/551047 has identified that recordings linked to AcoustIDs with clearly wrong durations are a clear indication of wrong matching. This is something Picard can easily detect.
If the duration difference between the MB recording and the fingerprint is larger than 30 seconds, than do not submit the MBID. Still submit the AcoustID fingerprint, but combine it with textual metadata only. …

PICARD-2396: Do not link AcoustIDs to recordings if there is a large difference in length

---

picard/mbjson.py
test/data/ws_data/recording_multiple_works.json
test/test_mbjson.py

* This is a…
* JIRA ticket (_optional_): PICARD-2292
Since PICARD-1117 the language is set to "zxx" (no lyrics) for all recordings being linked to a work with the "instrumental" flag. Also in this case the lyricist tag is being cleared.
But if a recording is linked to multiple works, e.g. a medley like https://musicbrainz.org/recording/91b7e04e-529b-4119-bc30-867db56fd400, then this should only happen for the specific work relations. Currently a single instrumental link to a recording unsets the languages and lyricists for all other work relationships.
If a work relationship is instrumental then add the language "zxx" and only omit the lyricist for this work. All other languages and lyricist for non instrumental performances are kept.
Also …

PICARD-2292:  Fix setting "no lyrics" for recording with mixed instrumental works

---

picard/track.py

The translation mapping was originally added as part of the last.fm
plugin in commit 99dc3e54, which was later used as the basis of the
initial folksonomy genre implementation.
This change fixes a bug where a track tagged with the "electronic" and
"electronica" genres would end up with "electronic" twice.
* This is a…
Removed the genre translation dict as per the commit message. I've been unable to find any reasons to explain why this behaviour was added in the first place - my assumption is that it was to match the Last.fm tag schema?
Note that this change will cause tag changes for all tracks with the following genres:
* hip hop
* synth-pop
* electronica
This could cause some user confusion but I don't see any other reasonable option...

Remove legacy genre tag translation

---

picard/browser/filelookup.py
picard/disc/__init__.py
picard/ui/cdlookup.py
test/test_browser.py
test/test_disc.py

* This is a…
* JIRA ticket (_optional_): PICARD-2409
Searching for or drag and dropping a disc ID URL (such as https://musicbrainz.org/cdtoc/vtlGcbJUaP_IFdBUC10NGIhu2E0-) should trigger the CD lookup dialog
Handle this URL and show the CD lookup dialog.
One difference to a regular disc ID lookup is, that submission does not work. In this case we only have the disc ID, e.g. 
"vtlGcbJUaP_IFdBUC10NGIhu2E0-". For submission also the full TOC details would be needed. Hence the CD lookup dialog hides the submission buttons.
Also added tests for this and other untested methods in `FileLookup`.

PICARD-2409: Search for cdtoc URL triggers CD lookup

---

picard/disc/eaclog.py
picard/disc/utils.py
picard/disc/whipperlog.py
picard/tagger.py
picard/ui/mainwindow.py
test/data/whipper.log
test/test_disc_utils.py
test/test_disc_whipper.py

* This is a…
* JIRA ticket (_optional_): PICARD-2410
Similar to the EAC / XLD log file support added in #2048 allow generating the disc ID from Whipper log files
Extend the existing ripping log file reading with an additional check for the Whipper log format. Whipper's logs are YAML based and hence especially easy to handle.
Note: There is also a EAC log output plugin for whipper, which mimics the format of the EAC log. This of course also works and it captured by the EAC / XLD log file implementation.

PICARD-2410: Disc ID from Whipper log file

---

picard/util/__init__.py
test/test_browser.py
test/test_disc.py
test/test_util_mbserver.py
test/test_utils.py

* This is a…
URLs constructed by `picard.util.build_qurl`  always contain the port, e.g. `https://musicbrainz.org:443/`. This is not necessary if the default ports 80 for http or 443 for https are being used.
Skip setting the port if the default is being used. Only set the scheme.

Omit standard ports in URLs constructed by build_qurl

---

picard/formats/vorbis.py
picard/profile.py
picard/ui/options/tags.py
picard/ui/ui_options_tags.py
test/formats/common.py
ui/options_tags.ui

This is to fix problem with Kodi which is unable to load files
that have empty SeekTable, so by default a single SeekPoint is added.
An error message is logged if the file has no samples.
* This is a…
* JIRA ticket (_optional_): PICARD-2411

PICARD-2411: Add option to fix seektable for flac files

---

picard/formats/vorbis.py
test/formats/test_vorbis.py

* This is a…
* JIRA ticket (_optional_): PICARD-2411
This is an additional fix for #2059. The original code did not handle the case where the seektable was missing completely. Also further tests with lolek on IRC showed that removing the seektable also fixes the issues Kodi has with an empty seek table, so this is better than adding fake entries.
- Remove empty seektable from FLAC
- Moved the seektable removal code to separate function
- Added tests

PICARD-2411: FLAC fix seektable changes

---

picard/tagger.py

* This is a…
* JIRA ticket (_optional_): PICARD-2417
On macOS only in tree views the LEFT ARROW key does not move the selected item to the parent. This is a Qt5 issue. While this is default behavior it is always disabled on macOS. For details see https://bugreports.qt.io/browse/QTBUG-100305
Force enabling the `SH_ItemView_ArrowKeysNavigateIntoChildren` style hint on all platforms.
This change also enables on macOS the behavior that on RIGH ARROW press the first child item gets selected. This is Qt default behavior on other platforms, but since this is not common behavior on macOS Qt5 tries to disable it on macOS. But this is part of the same style hint `SH_ItemView_ArrowKeysNavigateIntoChildren`

PICARD-2417: Fix collapsing tree view items with LEFT key on macOS

---

picard/acoustid/manager.py

* This is a…
* **Describe this change in 1-2 sentences**: Fix crash introduced by https://github.com/metabrainz/picard/pull/2045 (PICARD-2396), specifically 62da04f831ca64e755ffdf76ac46956b4059c221.
On loading some files, Picard crashes with the following message: 
```
File "/home/user/picard/picard/acoustid/manager.py", line 53, in <genexpr>
return int(sum((len(key) + len(value) + 2 for key, value in self.args.items())) * 1.03)
TypeError: object of type 'NoneType' has no len()
```
After some investigation, it seems that files with an ACOUSTID_FINGERPRINT tag cause this. To reproduce use e.g. this [testfile.zip](https://github.com/metabrainz/picard/files/8056446/testfile.zip) (public domain, see https://kimikoishizaka.bandcamp.com/album/bach-well-tempered-clavier-book-1) or take a random …

Fix crash on loading files with ACOUSTID_FINGERPRINT tag.

---

picard/acoustid/manager.py
test/test_acoustidmanager.py

* This is a…
Implementing __bool__ avoids checks like `if submission` to use __len__. Checking `len(submission)` does not really tell about the object being considered True.
This is related to the dscussion on #2063

Implement __bool__ and __repr__ for AcoustID Submission

---

picard/album.py
picard/cluster.py
picard/file.py
picard/ui/searchdialog/track.py
picard/util/__init__.py
test/test_utils.py

* This is a…
The utility functions `sort_by_similarity` and `find_best_match` currently expect as parameter a callable that returns an iterable. I think it is a cleaner API if they accept an iterable directly.
Make the functions work on the iterable, move calling of the functions to the outside.

Refactor similarity utils

---

picard/ui/itemviews.py

* This is a…
* JIRA ticket (_optional_): PICARD-2423
If you have loaded an album and attached multiple files to a track and drag the entire album back on unmtached files, only half of the files attached to a track get moved over.
This was caused by https://github.com/metabrainz/picard/commit/8f90884aed2da4d42e2267d821093660e9a23b05
@zas I remember we discussed this and were unsure but thought we could get away with passing the generator. But once this iterates over the tracks the moves modify the iterated file list and hence we loose every second file.
Pass a list instead of a generator to `tagger.move_files`

PICARD-2423: Fix moving all files from album to unclustered

---

picard/file.py
picard/ui/coverartbox.py
picard/util/__init__.py
picard/util/filenaming.py

* This is a…
* JIRA ticket (_optional_): PICARD-2425
`os.path.realpath` can throw `OSError`  for different reasons. E.g. PICARD-2425 reports an issue with drives mounted via SSHFS-Win. In general on Windows this can cause exceptions if drives are mounted without mount manager. https://github.com/billziss-gh/sshfs-win/issues/243 has some more info about this.
Due to missing exception handling this can cause crashes when saving files or when generating filename previews in options.
Handle `OSError`  on `os.path.realpath`  calls. If it makes sense use `picard.util.normpath`, which already handles this.
Note that we still log warnings in these cases, which I think makes sense.

PICARD-2425: Handle possible exceptions with os.path.realpath

---

picard/util/filenaming.py

* This is a…
Just a small refactoring to turn the constants used in `picard.util.filenaming` for the different path shortening modes into an enum `ShortenMode`.

Use an enum for ShortenMode in util.filenaming

---

picard/tagger.py
picard/util/__init__.py
picard/util/filenaming.py
test/test_utils.py

* This is a…
* JIRA ticket (_optional_): PICARD-1570
On traditional Windows API the file path length is limited to 259 characters (+1 null character). Picard cannot read or write longer paths.
The Windows API however supports accessing longer paths, if the path gets prefixed with `\\?\`. This internally enables long path handling.
Extend `picard.util.normpath`  to extend paths with the long path prefix `\\?\` on Windows if the path exceeds 259 characters in length. This enables both reading and writing to such files
Please note a few things about this:
1. This solution works independent of the new long path support that can be enabled in Windows 10. If that is enabled Picard already can handle reading and writing long paths. But this change …

PICARD-1570: Allow accessing files with long paths on Windows

---

picard/ui/ui_edittagdialog.py
ui/edittagdialog.ui

* This is a…
* JIRA ticket (_optional_): PICARD-2437
Use a Ok button instead of Save in tag edit dialog. Avoids misunderstanding that the changes are actually saved to the file

PICARD-2437: Use a Ok button instead of Save in tag edit dialog

---

picard/formats/vorbis.py

* This is a…
* JIRA ticket (_optional_): PICARD-2440
When loading FLAC picture blocks as cover art also save the ID3 cover art type so it gets preserved on saving.
This was forgotton in #1931

PICARD-2440: Preserve ID3 image type in FLAC picture

---

picard/ui/edittagdialog.py

* This is a…
A `QComboBox`  which is set to being editable automatically sets up a `QCompleter` for the values in the combo box. No need to initialize a new completer, we just need to configure it for using popup auto completion (instead of default inline completion).

An editable QComboBox automatically sets up a QCompleter

---

CONTRIBUTING.md

* This is a…
Add a list of links to various metadata related specifications and tag mapping tables for different software to CONTRIBUTING.md. This is based on the list I privately maintained at https://gist.github.com/phw/12a487590c95ae8c849a688a9c7782ae , but it should be really part of Picard's repository to be more useful.

Add links to relevant metadata specs in CONTRIBUTING.md

---

picard/config.py
picard/profile.py
test/test_profiles.py

* This is a…
On every settings read / write access the list of profile setting names got compiled again. This list does not change on runtime, so instead compute it only once.

Optimize access to profile settings

---

picard/file.py

* This is a…
* JIRA ticket (_optional_): PICARD-2420
If one adds a file to Picard that has an existing `acoustid_fingerprint` and an existing `musicbrainz_recordingid` tag, that file will be loaded and assigned to the corresponding recording. This immediately will enable the fingerprint submission, because the file originally gets added to the AcoustId manager without recording ID, then gets assigned to the recording. This makes this a new combination.
The patch changes the behavior so on loading the file gets added to the AcoustId manager with the recording ID already assigned. That way it counts as already submitted.
I'd like to put this up for discussion, because I am unsure what expected behavior is. The current behavior can lead to a …

PICARD-2420: Fix AcoustID submission getting enabled for files with fingerprint in tags

---

picard/browser/addrelease.py

* This is a…
* **Describe this change in 1-2 sentences**: Allow submitting a catalog number without an associated label when adding a cluster as a release.
When adding a cluster as a release, Picard would only submit a catalog number if there was a corresponding label set.  MusicBrainz allows catalog numbers without a label.
* JIRA ticket (_optional_): PICARD-2453
Allow submitting a catalog number without an associated label when adding a cluster as a release.
None.

PICARD-2453: Allow submitting a catalog number without a corresponding label

---

picard/util/filenaming.py
test/test_util_filenaming.py

* This is a…
* **Describe this change in 1-2 sentences**: Removes unicode zero-width spaces from renaming file output path.
As discussed in https://github.com/metabrainz/picard-plugins/pull/326 it is currently possible for Picard to create an output path which includes a unicode zero-length space character (\\u200B).  This can lead to unexpected consequences for the user.
* JIRA ticket (_optional_): PICARD-2451
Automatically strip out the zero-width space character.  If there is a valid use case to keep the character in the output path, perhaps a setting can be added to the File Renaming Options to allow keeping the character.
None.

PICARD-2451: Remove unicode zero-width space characters from file path

---

picard/ui/searchdialog/album.py

* This is a…
* JIRA ticket (_optional_): PICARD-2457
Loaded album art got updated based on row number, which could change on sorting
Instead of remembering the row and getting the widget to update from the row, remember the widget directly

PICARD-2457: Fix album search cover art getting loaded into wrong row

---

picard/ui/coverartbox.py
picard/ui/mainwindow.py

* This is a…
* JIRA ticket (_optional_): PICARD-2463
The cover art box considers the screen scaling to render the cover art in the proper resolution. E.g. on a High DPI / retina display with a scaling factor of 2 it will render the images in twice the displayed size.
But this code does not consider multiple screens with different scaling factors. If there are multiple screens the scaling factor of the primary will be used for all screens. This can result in pixelated cover art display if the Picard window is on a a screen with different scaling factor. E.g. the attached screenshot shows the Picard window on a screen with scaling factor set to 1.25, but rendered with a scaling factor of 1.0 (from primary screen). If the primary screen is changed …

PICARD-2463: Fix coverart per screen pixel ratio

---

picard/coverart/image.py
picard/tagger.py
picard/util/periodictouch.py

* This is a…
* JIRA ticket (_optional_): PICARD-2459
macOS cleans up temporary files if they haven't been accessed for three days. If Picard is left running for a longer period of time the files became missing.
Add a module `picard.util.periodictouch` which sets up a timer to periodically touch a list of files. Register the cover art temp files there.

PICARD-2459: Prevent macOS from removing temporary cover art files

---

picard/ui/mainwindow.py
picard/ui/searchdialog/album.py
picard/ui/searchdialog/track.py
picard/webservice/api_helpers.py
test/test_api_helpers.py

* This is a…
Refactor `AlbumSearchDialog.show_similar_albums`  and  `TrackSearchDialog.show_similar_tracks()` 
- De-duplicate code
- Reuse existing `search` method
- Set the dialog to have forced advanced search. Previously the search would initially be performed as an advanced search, but if the user had simple search active the search string was filled as only a simple title search. That meant if the user hit the search button there would be different results. In forced mode the dialog uses advanced search independent of user settings (and does also not alter user settings)
- Removed duplicated code by introducing `build_lucene_query`
- Added tests for API helpers `build_lucene_query` and `escape_lucene_query`

Simplify album and track similarity search

---

picard/browser/filelookup.py
picard/mbjson.py
picard/ui/itemviews.py
picard/ui/mainwindow.py
picard/ui/searchdialog/album.py
picard/ui/tablebaseddialog.py
test/test_browser.py

* This is a…
* JIRA ticket (_optional_): PICARD-2415
This is something I wanted to add for a long time: Add the ability to open the "Other versions selection" in a dialog. This allows for better comparison and allows showing much more information without being restricted by the limitations of a menu. It also allows adding a keyboard shortcut for this
- Have a dedicated action to open a album search dialog to show and select other versions of an album
- Inside the dialog also show the currently selected album, but highlight it
- Keep the "Other versions" submenu, but add an entry "Show more details..." to open the dialog
I have kept the submenu, as this keeps the functionality of quickly switching between different versions, so users used to …

PICARD-2415: Show other release versions in search dialog

---

picard/file.py

* This is a…
* JIRA ticket (_optional_): PICARD-2474
The changes in [PICARD-2420](https://tickets.metabrainz.org/browse/PICARD-2420) / #2081 actually break the use were users have the AcoustID fingerprint in file tags that already also have been assigned MBIDs, but then want to use Picard to submit them
The assumption in PICARD-2420  was that this case would indicate the fingerprints have likely already been submitted, but this assumption is wrong. See discussion at
See https://community.metabrainz.org/t/picard-2-8-release-candidate/583657/2
This reverts commit 40877f6e227a348ffba05c2154d5e8abbeed1466.

PICARD-2474: Revert "PICARD-2420: Fix AcoustID submission getting enabled for files with fingerprint in tags"

---

picard/browser/filelookup.py
picard/tagger.py
test/test_browser.py

* This is a…
* JIRA ticket (_optional_): PICARD-2475
If the search in the dialog contained a MBID, the "Lookup in browser" button would attempt to load this MBID as album / recording instead of opening the browser.
`Tagger.search`   did call `FileLookup.search_entity`, but did not pass the `force_browser`  parameter. Because `FileLookup.search_entity` can again decide to handle the search inside Picard (e.g. loading release or opening a dialog) this could fail and ignore the original intention to force search in browser.

PICARD-2475: Fix "Lookup in browser" in search dialogs

---

picard/cluster.py
picard/tagger.py

* This is a…
* JIRA ticket (_optional_): PICARD-2472
Clustering will apply to files selected in the right pane, which is rather unexpected. It should only apply to unclustered files. Furthermore the cluster action only is activated if there is at least one unclustered file, so only under this condition the user can also apply it to matched files.
Limit clustering to unclustered files
@zas can you test this and see if this meets your expected behavior?

PICARD-2472: Cluster only unclustered files

---

requirements-macos-10.12.txt
requirements-macos-10.14.txt
requirements-win.txt

Update builds to PyJWT 2.4, mainly to address the CVE in https://pyjwt.readthedocs.io/en/stable/changelog.html#v2-4-0
It's worth noting that Picard is even without this patch not affected by this issue, as it explicitly sets the algorithm.
Tested locally.

Build releases with PyJWT 2.4.0

---

picard/i18n.py

* This is a…
* JIRA ticket (_optional_): PICARD-2493
If for the configured UI language any of the locale files (picard, picard-countries, picard-attributes) is missing, Picard will completely fail to load the translations and will fall back to no translation for all three translation domains.
Fail loading each domain individually and only set `NullTranslations` for that domain. That way if e.g. translations for attributes are missing the translations for the UI and for countries will still be used.

PICARD-2493: Ensure translation domains get used even if some translation files are missing

---

picard/ui/collectionmenu.py
picard/ui/itemviews.py
picard/ui/options/interface.py
picard/ui/options/releases.py
picard/util/__init__.py
picard/util/natsort.py

* This is a…
* JIRA ticket (_optional_): PICARD-2489
locale.strxfrm can raise OSError on some systems. Handle this gracefully to avoid Picard crashing.
Add a function `picard.util.strxfrm` that wraps `locale.strxfrm`, but never raises `OSError` but only returns the original string (converted to lowercase for some normalization). Worst case strxfrm will fail on a string and sorting will not be fully correct, but Picard continues to function. OSError will be logged.

PICARD-2489: Handle strxfrm raising OSError

---

picard/album.py

* This is a…
* JIRA ticket (_optional_): PICARD-2494
The "[standalone-reccordings]"  special album instance shown to hold the standalone recordings does have the info dialog, which just opens an empty dialog.
Implement `NatAlbum.can_view_info`

PICARD-2494: The view info dialog is not needed for NatAlbum

---

picard/ui/options/plugins.py
test/test_ui_options_plugins.py

* This is a…
* JIRA ticket (_optional_): PICARD-2498
Currently all plugin metadata can potentially contain HTML which gets rendered when displaying the plugin details in options. This is not intentional, the only field that can currently contain HTML is the description.
This was revealed because the author list in the acousticbrainz plugin uses the format "Author Name <email>".
HTML escape all plugin metadata fields except for the description.
For authors also try to detect the "Author Name <email>" and convert the author names into mailto links.

PICARD-2498: HTML escape plugin metadata before display in options

---

.github/workflows/codacy-analysis.yml
.github/workflows/codeql-analysis.yml
.github/workflows/package.yml
.github/workflows/pypi-release.yml
.github/workflows/run-tests.yml

* This is a…
This PR bumps GitHub Actions (and others) to their latest major versions:
-   Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
-   Changelog for `github/codeql-action` actions can be [found here](https://github.com/github/codeql-action/blob/main/CHANGELOG.md)
-   Releases for `actions/setup-python` can be [found here](https://github.com/actions/setup-python/releases)
-   Releases for `actions/cache` can be [found here](https://github.com/actions/cache/releases)
-   Releases for `actions/download-artifact` can be [found here](https://github.com/actions/download-artifact/releases)
-   Releases for `actions/upload-artifact` can be [found …

Update GitHub Actions

---

picard/coverart/image.py

* This is a…
* JIRA ticket (_optional_): PICARD-2505
Fixes accidental folder creation for types "matrix/runout" or "raw/unedited" when saving cover art images of those types with the option "Always use the primary image type as the file name for non-front images" enabled.
Call `sanitize_filename`  on the cover art types before using them for the file name.

PICARD-2505: Sanitize cover art type before using it as filename

---

.github/workflows/run-tests.yml

* This is a…
Use timeout in workflows for unit tests to prevent tests from going into an infinite loop. Admins won't need to cancel tests themselves, contributors will receive a quicker feedback.
My GSoC PR made me think that timeout in the tests is a useful feature so here it is :)
`timeout-minutes` set to 30, the exact value is a subject of discussion.

timeout added to pytest

---

picard/acoustid/__init__.py
picard/util/__init__.py
test/test_utils.py

* This is a…
* JIRA ticket (_optional_): PICARD-2506
Calls to fpcalc on Windows 10 / 11 fail, if the path to the audio file exceeds the 259 character path name limit and Windows is configured for long path support. The reason is that on Windows with long path support Picard keeps the path as is. But fpcalc (due to ffmpeg, see https://trac.ffmpeg.org/ticket/8885) does not support long paths yet and hence fails.
The solution is to enforce the Windows long path prefix `\\?\` whenever passing paths to fpcalc.
On Windows always add the long path prefix \\?\ if the path exceeds this limit, independent of the OS configuration for long path supports. This fixes ffmpeg currently not being able to handle long paths.
Added util method …

PICARD-2506: Fixed calling fpcalc with long path filename

---

picard/mbjson.py
test/data/ws_data/media_pregap.json
test/test_mbjson.py

* This is a…
* JIRA ticket (_optional_): PICARD-2507
A medium's pregap track is not considered for the `totaltracks`  count of that medium.
Increase `totaltracks`  by 1 if there is a pregap track.

PICARD-2507: Include pregap track in medium's totaltracks count

---

picard/ui/scripteditor.py

* This is a…
* **Describe this change in 1-2 sentences**:  Use a copy of the original file metadata to avoid processing multiple script changes when using the file naming script editor.
Tagging scripts are executed whenever updating the file naming examples in the file naming script editor.  This could result in changes being applied multiple times unexpectedly.
* JIRA ticket (_optional_): PICARD-2508
Use a copy of the original file metadata to avoid processing multiple script changes when using the file naming script editor.
None.

PICARD-2508: Unexpected script execution results when using file naming script editor

---

.github/workflows/package.yml
.github/workflows/pypi-release.yml
.github/workflows/run-tests.yml

* This is a…
Seems like I've missed quite a lot of tests in my previous commit so here's the full refactored codebase (I really hope I haven't missed anything this time).
Even if tests fail, they might get stuck and won't end themselves (despite timeouts in code) after Errors, so we have to create shorter timeouts in the workflow files.
Timeouts added
Nope

Timeouts added to all the unit tests

---

picard/tagger.py

* This is a…
Since the variable wasn't used anywhere (wasn't even stored as `Tagger`'s attribute), I'd suggest to remove it, unless you have some reason to still keep it there.
Unused variable returned, stored and passed to the `Tagger`'s constructor just to be left untouched
* JIRA ticket (_optional_): *None*
I've safely removed all the `unparsed_args`'s ocurrences.

unparsed_args removed from `tagger.py`

---

picard/script/functions.py
test/test_script.py

* This is a…
* **Describe this change in 1-2 sentences**: Adds new text-based comparison scriping functions.
The current scripting comparison functions `$gt()`, `$gte()`, `$lt()` and `$lte()` operate on interger values only. This does not support things like date comparisons. See the discussion at https://community.metabrainz.org/t/how-set-date-to-minimum-of-recording-firstreleasedate-and-originaldate/585648 and https://community.metabrainz.org/t/feature-request-numeric-functions-min-and-max-in-picards-scripting-language/585669 for more information.
* JIRA ticket (_optional_): PICARD-2486
~Adds four new text-based comparison scripting functions `$textlt()`, `$textlte()`, `$textgt()` and `$textgte()`, plus text-based `$textmin()` and `$textmax()` functions.~
Adds an optional argument to …

PICARD-2486: Add text-based comparison script functions

---

.github/workflows/package.yml
.github/workflows/pypi-release.yml
.github/workflows/run-tests.yml
picard.spec
requirements-build.txt
scripts/package/win-package-portable.ps1

* This is a…
- Github has deprecated the macOS-10.15 package and will completely remove support for it soon, see https://github.com/actions/virtual-environments/issues/5583
- macOS packaging is currently failing with some issue building pyinstaller, see e.g. https://github.com/metabrainz/picard/runs/7447653204 . It's unclear whether this is related to the macOS-10.15 deprecation
Check whether the build packages are still usable on older macOS.

Use macos-11 image for Github actions, upgrade to latest PyInstaller

---

picard/tagger.py
picard/util/pipe.py

* This is a…
The single instance mode via named pipes got merged and works almost perfectly. Almost... because when the pipe file gets deleted (outside of the Picard, e.g. `rm`), Picard cannot exit properly and gets stuck during the exit function's call.
* JIRA ticket (_optional_): PICARD-2521
1) save the tagger's exit code
2) check whether the pipe file was removed unexpectedly (new `Pipe` attribute)
- if yes: `os._exit(exit_code)`
- if no: `sys.exit(exit_code)`
(https://github.com/metabrainz/picard/pull/2133) included since they're both about fixing the exit process, so they could be in a single PR

PICARD-2521: Cannot exit properly after removing the pipe file

---

README.md
picard/tagger.py
test/test_tagger_message_parsing.py
test/test_util_pipe.py

* This is a…
Currently Picard supports passing file paths on command line to open the respective files. Picard also supports handling some URL patterns by drag and drop, e.g. MusicBrainz recordings, releases, release group and cdtoc URLs.
Extend Picard to also handle these supported URLs when passed via command line.
* JIRA ticket (_optional_): PICARD-2519
call urllib.parse.urlparse on each argument marked as FILE to determine whether it's a file or URL, then pass it to the actual Tagger.

PICARD-2519: Allow passing supported URLs on command line

---

requirements-build.txt

setuptools made some changes, causing the error `[AttributeError: module '_distutils_hack' has no attribute 'ensure_shim'](https://github.com/pypa/setuptools/issues/2983#)`  when trying to install the old version of setuptools during build.
Try building with the latest setuptools instead.

Build with latest setuptools again

---

picard/util/__init__.py
test/test_utils.py

* This is a…
* JIRA ticket (_optional_): PICARD-2520
When a audio file contains unexpected null bytes in the tag values this can cause Picard to crash when sorting by this tag value. This is due `strxfrm`  not allowing null bytes as part of the input.
strxfrm fails if a string contains a null char. Sanizize the input strings for strxfrm by removing any null chars.

PICARD-2520: Null bytes in tag values can cause crashes when sorting

---

picard/album.py
picard/tagger.py

* This is a…
Users will be able to pass some commands to the existing instance with `-e`/`--exec` flag.
It would be useful to tell the existing Picard instance what to do, e.g. QUIT, useful in combination with the other single-instance mode improvements
* JIRA ticket (_optional_): PICARD-2526
- add command:// prefix to the commands
- send them as any other arg
- parse with urlparse, split by ";"
- execute

PICARD-2526: Allow starting processing actions from the command line

---

picard/tagger.py

* This is a…
A command that allows to load files as a part of the command pipeline
It would be useful to load a file after some commands have already been executed as a part of the pipeline. The `load` command extends positional arguments' functionality.
Added the needed command
Should be squashed on merge

Added command: LOAD

---

picard/tagger.py

* This is a…
Another batch of useful commands + patch to keep it strictly related to the removal procedure.
The commands were left to do later but seemed useful to us
1. Added commands to remove empty clusters and albums & to remove unclustered files
2. Started using Tagger's removal methods to fix unexpected behavior I have encountered during development
May be squashed imo

`REMOVE_*` commands enhancements

---

test/test_util_pipe.py

* This is a…
* JIRA ticket (_optional_): PICARD-2544
As suggested by zas in PICARD-2544 use UUID for the pipe name in the tests.

PICARD-2544: Use UUID for pipes in tests

---

picard/album.py

* This is a…
* JIRA ticket (_optional_): PICARD-2548
Cover art box is for performance reasons disabled during album loading (similar to metadata box updates). But if a loading album is selected and after it has fully loaded the metadata box updates with the new information, but cover art box stays empty until selection changes.
Trigger an update of the cover art box if the currently loaded album is selected

PICARD-2548: Trigger cover art box update for selected albums after loading

---

picard/file.py
test/test_file.py

* This is a…
* JIRA ticket (_optional_): PICARD-2549
If a file is moved to a track where the metadata matches perfectly but only cover art is different, then the similarity score of this file was not recalculated. That means the file retains the similarity of the previous (probably bad) match.
Reset the similarity to 1.0 in all cases when metadata match was successful. This matches the existing behavior when such files would be matched directly to the perfect match: The file shows as changed, but with metadata similariry set to 100%.
We could consider showing a lower score in all cases where only cover art does not match. But given that we have many cases where the cover art known for the file does not match the loaded cover art (see e.g. …

PICARD-2549: Fixed similarity not getting updated if only difference is cover art

---

picard/ui/widgets/__init__.py

* This is a…
* JIRA ticket (_optional_): PICARD-2556
Under Wayland the player toolbar popover dialogs, used for audio volume and playback speed settings, are
1. causing a crash due to wrong data type of coordinates
2. not properly positioned
1. Ensure position and slider value are set as integer
2. Add custom handling for calculating the popover position on Wayland
Note that there is a small difference in behavior: On systems other then Wayland the code makes sure the popover is shown centered above / below the parent widget if possible, but repositions it to ensure it is on screen. This is relevant if the parent is near the screen edges.
On Wayland that's no possible, because the position relative to the screen cannot be determined. Hence …

PICARD-2556: fix player popover dialogs on Wayland

---

picard/ui/edittagdialog.py

* This is a…
* JIRA ticket (_optional_): PICARD-2557
The edit tag dialog's auto completion for the tag name will show the currently typed value as the first suggestion in autocomplete, which is not helpful for the user and always requires an extra button press to skip it.
This was caused by removing the custom QCompleter implementation and using the default QComboBox  completer implementation.
This reverts commit e0d58d50987a3f9c7cf52e23d728f1f2cf0a153f and restores the custom implementation.

PICARD-2557: Revert "An editable QComboBox automatically sets up a QCompleter"

---

picard/tagger.py
picard/ui/mainwindow.py
picard/ui/widgets/__init__.py

* This is a…
* JIRA ticket (_optional_): PICARD-2558
Floatable toolbars are not fully supported by Qt, see https://bugreports.qt.io/browse/QTBUG-92191 . The user can make a toolbar floating, but it will always be displayed in the middle of the screen and cannot be moved by the user anymore (and also not docked again).
On Wayland set `QToolBar.floatable`  to `False`

PICARD-2558: Disable floatable toolbars on Wayland

---

picard/disc/eaclog.py
test/data/freac-datatrack.log
test/data/freac.log
test/test_disc_eaclog.py

* This is a…
* **Describe this change in 1-2 sentences**: Slightly relax the EAC ripping log parsing code so it can parse logs from fre:ac.
fre:ac's ripping logs contain a TOC table with only minor differences from EAC's format (times always use two digits for each field, and small spacing differences).  However fre:ac prefixes most log lines with a timestamp, so the existing EAC log parsing code cannot parse fre:ac logs.
* JIRA ticket (_optional_): PICARD-2567
Removing the `^` anchor from the TOC table line regular expression and using `search` instead of `match` is sufficient to allow the EAC log parser to parse the TOC table from fre:ac logs.  The line regex already handles the differences in spacing and leading zeroes in start times and lengths.  The line regex does not match data …

PICARD-2567: Generate disc ID from fre:ac ripping log

---

picard/script/functions.py
test/test_script.py

* This is a…
* JIRA ticket (_optional_): PICARD-2568
`$cleanmulti`  does not write back hidden variables properly, instead creates a new visible tag starting with underscore.
Fix tag name when writing back the changed values, updated tests.

PICARD-2568: Fix $cleanmulti with hidden variables

---

.github/workflows/pypi-release.yml
.github/workflows/run-tests.yml
INSTALL.md
requirements-macos-10.12.txt
requirements-macos-10.14.txt
requirements-win.txt
setup.py
test/formats/test_wav.py

* This is a…
Use latest mutagen 1.46.0 for official builds.
Also drop official support for Python 3.6, just like mutagen did. We need to do this for PyQt6 (#2154) anyway.

Upgrade to mutagen 1.46

---

.github/workflows/pypi-release.yml
.github/workflows/run-tests.yml

CI: Build and test with Python 3.11

---

.github/workflows/package.yml
.github/workflows/run-tests.yml
pyproject.toml
requirements-build.txt
setup.py

* This is a…
* JIRA ticket (_optional_): PICARD-2582
Picard's `setup.py` was still importing some legacy distutils components to achieve some functionality.
Also these distutils imports are imported before setuptools gets imported, which is actively discouraged as setuptools might provide modified distutils.
Replace all distutils imports with proper replacements (see also [PEP 632](https://peps.python.org/pep-0632/))
This needs a newer setuptools which provides the `build` command implementation (was added sometime in August this year).

PICARD-2582: Get rid of legacy distutils imports in setup.py

---

picard/tagger.py

* This is a…
The recently added `LOOKUP` executable command indicated in the help text that it would "Lookup all clusters in the cluster pane", but in fact it actually would "Lookup all unclustered files in the cluster pane".  There was no executable command that would "Lookup all clusters in the cluster pane."
Change the help text on the existing `LOOKUP` command, and add a new `LOOKUP_CLUSTERS` command.
If accepted, the documentation will need to be updated to reflect the changes.

Fix executable `LOOKUP` command text.  Add `LOOKUP_CLUSTERS` command.

---

picard/ui/mainwindow.py

* This is a…
With Qt6 `QAction.setMenu`  will get removed. Instead directly place the CD lookup `QMenu` in the menu and on the toolbar button.
This is a part of the PyQt6 port in PICARD-2331 (see #2154). But I think this is one partial aspect we can merge separately in preparation and just consider `QAction.setMenu` deprecated.

Refactor CD lookup submenu

---

picard/file.py
picard/tagger.py
picard/util/thread.py

* This is a…
* JIRA ticket (_optional_): PICARD-2588
This declares 96f492c357457f60504ebf75b0ab1a5b8747edd7 to be a stupid idea and reverts back to using QThread for all threads. Mixing threading between Qt and Python's is going to cause all kinds of incompatibility issue, see PICARD-2588 for a bit. As we are running a Qt app we must rely on Qt's event loop.
This reverts commit 96f492c357457f60504ebf75b0ab1a5b8747edd7 and fixes PICARD-2588.
Also reintroduces the priority parameter, using the values initially set for the various operations. I just wen with using the Qt enum instead of its integer values (something that I think will be mandatory for Qt6 anyway).

PICARD-2588: Revert "Replace QThread with Python treads using concurrent.futures"

---

picard/coverart/image.py
test/test_coverart_image.py

* This is a…
* JIRA ticket (_optional_): PICARD-2590
Picard 2.8.4 broke saving coverart files if the coverart naming was specifying a relative path. In this case the path portion of the generated file name got ignored and the file was directly saved into the target directory.
Fix the handling of relative paths and add tests to ensure proper working if the file name generation for cover art files.

PICARD-2590: Fix saving cover art images with relative paths

---

picard/ui/options/interface.py

* This is a…
When saving options the toolbar buttons style always changes to buttons without labels, independent of setting

PICARD-2593: Fix toolbar button style resetting when saving options

---

picard/tagger.py
picard/util/remotecommands.py
picard/util/thread.py
test/data/test-command-file-1.txt
test/data/test-command-file-2.txt
test/test_parsing_files_with_commands.py

* This is a…
* **Describe this change in 1-2 sentences**:  Process commands through a queue object.  Track threads created during command processing.  Add a blocking `to_main()` function.
As noted in PICARD-2546, commands are processed in separate threads so they cannot be sequenced.
* JIRA ticket (_optional_): PICARD-2546
Process command line executable commands through a queue object:
- Implement a queue object to hold the executable command queue
- Implement a command processor thread to parse the command queue
- Implement command file tracking to avoid circular references
- Do not queue additional commands after a `QUIT` has been queued
Track threads created during executable command processing for consideration before marking the command as having been completed:
- Add a new blocking …

PICARD-2546: Sequential processing of executable commands

---

.github/workflows/validate-appstream.yml

* This is a…
Validate the AppStream metadata XML with Github Actions using appstream-validate. Currently using `validate-relax`, as the screenshots we currently provide barely miss the minimum size requirements of 624px width. Once we have updated them we can be more strict and use the `validate` command.

CI: Validate AppStream metadata on Linux

---

picard/ui/options/plugins.py

* This is a…
* JIRA ticket (_optional_): PICARD-2599
Picard can crash on plugin install or upgrade if the network request takes longer and returns after the options dialog has already been closed.
Abort plugin installation if dialog has already been closed

PICARD-2599: Avoid crash when options close before plugin download ends

---

scripts/pyinstaller/win-startup-hook.py

* This is a…
* JIRA ticket (_optional_): PICARD-2605
PyInstaller 5.4 changed the location of the Qt5 DLLs. This bypassed our prioritization of packaged DLLs.
Add install dir `PyQt5/Qt5/bin`  to `PATH`.

PICARD-2605: Ensure packaged Qt5 DLLs get loaded

---

picard/mbjson.py
test/test_mbjson.py

* This is a…
Adds two new variables `_writersort` and `_lyricistsort`.
* Picard only provides the sort names of composers but not of lyricists and writers, probably because only `composersort` has a specified tag mapping for various tag formats.
* JIRA ticket (_optional_): PICARD-2606
Instead of defining non-standard tag mappings for `writersort` and `lyricistsort`, this PR only provides them as hidden variables, which can still be mapped to custom tags by the users or be used in filenaming scripts.
In my original implementation as a Picard plugin, I had also [defined display names](https://github.com/kellnerd/picard-plugins/blob/0ea52b5a55658f6e0ed9c1f7f72799fde4375439/plugins/additional_sort_names/additional_sort_names.py#L50-L54) for the …

PICARD-2606: Add writer and lyricist sort names as variables

---

picard/tagger.py

* This is a…
* JIRA ticket (_optional_): PICARD-2611
As this was combined with process_events_iter all user evens where still processed during clustering, which can lead to actions (e.g. save) being performed on the previous instead of current selection.
See https://community.metabrainz.org/t/all-files-are-saved-instead-of-just-the-one-album-i-select-when-picard-was-still-busy-clustering/619241
Remove the `ignore_selection_changes`
In my testing not using ignore_selection_changes made no significant difference in perceived performance.

PICARD-2611: Do not ignore selection changes during clustering

---

picard/util/remotecommands.py

* This is a…
* **Describe this change in 1-2 sentences**: Add a period to the end of the `LOOKUP_CD` command help text to make the format consistent with all of the other executable commands.
The format of the `LOOKUP_CD` executable command help text is inconsistent with all of the other executable commands.  It does not end with a period while all others do.
Add a period to the end of the `LOOKUP_CD` command help text to make the format consistent with all of the other executable commands.
None.

Make LOOKUP_CD help text format consistent with other commands

---

picard/const/__init__.py
picard/file.py
picard/util/tags.py

* This is a…
* **Describe this change in 1-2 sentences**:  Adds new `_file_created_timestamp` and `_file_modified_timestamp` file variables.
Please refer to the discussion in the ticket, which requests the creation of file variables to be able to add date tracking information into the file metadata for use in scripting.
* JIRA ticket (_optional_): PICARD-2617
Add new `_file_created_timestamp` and `_file_modified_timestamp` file variables.
Update documentation to include the new file variables.

PICARD-2617: Add file variables for file creation and modification timestamps

---

picard/tagger.py
picard/util/remotecommands.py

* This is a…
* **Describe this change in 1-2 sentences**: Have `QUIT` command do unsaved files check, with option to bypass the check.
When the 'QUIT' command is executed, Picard exits without performing the unsaved files check.
* JIRA ticket (_optional_): PICARD-2615
Update the `QUIT` command processing to perform the unsaved files check, allowing the command to be cancelled by the user.  Modify the command to allow an optional argument to force Picard to bypass the unsaved files check.
Update documentation.

PICARD-2615: Picard does not check for unsaved files when using the QUIT command

---

picard/config_upgrade.py
test/test_config_upgrade.py

* This is a…
* JIRA ticket (_optional_): PICARD-2630
Fix a potential crash on config upgrade for `preserved_tags`.
I don't know how the reporting user's configuration ended up in this state. But by checking the existing type of the value this crash can be avoided.

PICARD-2630: Fix potential crash on config upgrade

---

picard/formats/vorbis.py
test/formats/test_vorbis.py

* This is a…
* JIRA ticket (_optional_): PICARD-2535, PICARD-2534
Remove trailing null chars in Vorbis / FLAC tags when loading and saving. This fixes specifically the reported issue with loading dates with trailing null char (PICARD-2534), but might also help in other cases.
Remove trailing null char when loading and saving Vorbis comments.
I for now limited this to Vorbis, as all reported cases involved FLAC files. I was thinking about adding this to the `Metadata`  class in general, but was hesitant. For MP4 and ID3 we have some very specific values, e.g. the iTunes values, and I'm not fully sure we might break something here.

PICARD-2535: Strip trailing null chars for Vorbis / FLAC

---

picard/browser/addrelease.py

* This is a…
PICARD-2642
The old implementation would open on 0.0.0.0 if browser_integration_localhost_only was disabled.

PICARD-2642: Open "submit cluster" always on 127.0.0.1

---

picard/album.py
picard/browser/filelookup.py
picard/coverart/__init__.py
picard/coverart/image.py
picard/coverart/providers/caa.py
picard/disc/__init__.py
picard/file.py
picard/formats/apev2.py
picard/formats/asf.py
picard/formats/id3.py
picard/formats/mp4.py
picard/formats/util.py
picard/formats/vorbis.py
picard/plugin.py
picard/pluginmanager.py
picard/script/serializer.py
picard/tagger.py
picard/ui/__init__.py
picard/ui/cdlookup.py
picard/ui/coverartbox.py
picard/ui/mainwindow.py
picard/ui/options/maintenance.py
picard/ui/options/plugins.py
picard/util/checkupdate.py
picard/util/remotecommands.py
setup.py

* This is a…
For log output Picard often does variable substitutions in the logging strings. In many cases these used the string formatting options provided by Python (all of % operator, `.format()`  and f-strings are used).
This means that the string substitutions are applied even if due to the log level the string never gets outputted. This is especially true for debug log messages in normal operation. This ads an unnecessary overhead.
Rely on the string substitutions of the logging module to avoid unnecessary substitutions if log output never gets written.

Refactor log string substitution

---

picard/ui/options/tags_compatibility_id3.py

* This is a…
* JIRA ticket (_optional_): PICARD-900
Folks, it's time. It has been 6 years since this was attempted the last time in #559 . But I think in 2023 it is finally time to change Picard to default to ID3v2.4.
Since the last discussion Windows has gained ID3v2.4 support. All Windows version not supporting it are officially no longer supported (which includes older Windows 10 versions).
Also there are more issues discussed were ID3v2.3 is the problem, not the solution. In regards to user support it seems to me it is easier to tell those few people having issues with ID3v2.4 on older devices to change to v2.3 than it is to explain users why they should better use v2.4 and trying to argue why Picard still considers 2.3 the default.
One of …

PICARD-900: Use ID3v2.4 UTF-8 by default

---

picard/tagger.py
picard/util/pipe.py

* This is a…
* JIRA ticket (_optional_): PICARD-2627
It can happen that `Tagger.pipe_server` hangs waiting getting data from the pipe. If this happens when Picard is closing the `pipe_server` thread keeps running in the background until it reveives data, which likely won't happen.
To fix this write a MESSAGE_TO_IGNORE to the pipe when closing. This causes the pipe read call to return and the loop inside `Tagger.pipe_server`  will stop properly.

PICARD-2627: Ensure pipe listener threads closes on quit

---

picard/tagger.py

…mand
* This is a…
* JIRA ticket (_optional_): PICARD-2645
Sending the QUIT command to Picard with "picard -e QUIT" wrongly handles the quit confirmation dialog. If there are no files to save, the QUIT is ignored. If there are files to save the QUIT is only acknowledged if the user cancels, not confirms, the quit.
Properly handle the return value of `show_quit_confirmation` (`True`  means do quit Picard, `False`  don't). Also refactor `Tagger.handle_command_quit` for readability.

PICARD-2645: Fix handle the quit confirmation when reveiving QUIT command

---

picard/album.py
picard/mbjson.py
test/data/ws_data/release.json
test/test_mbjson.py

* This is a…
* JIRA ticket (_optional_): PICARD-711
Adds support for series variables for release group, release, recording and work series. 
Make the series name, id, disambiguation comment and number available as variables. The following variables are getting set:
- ~recording_series
- ~recording_series_id
- ~recording_seriescomment
- ~recording_seriesnumber
- ~release_series
- ~release_series_id
- ~release_seriescomment
- ~release_seriesnumber
- ~releasegroup_series
- ~releasegroup_series_id
- ~releasegroup_seriescomment
- ~releasegroup_seriesnumber
- ~work_series
- ~work_series_id
- ~work_seriescomment
- ~work_seriesnumber
The variable names are modeled after https://github.com/kellnerd/picard-plugins/blob/release_series/plugins/release_seri …

PICARD-711: Add support for series variables

---

setup.py

* This is a…
For Windows store we combine the patch version with the build number to ensure continuously growing version numbers for upgrades. Only this allows upgrades also for the development builds of the .msix package.
Currently the patch version gets multiplied by 10000, which means Picard version 2.9.2 becomes 2.9.20000. As Windows  limits the patch number to max. 65535 this means we can only release Picard 2.9.6 and not 2.9.7.
Reduce the version numbers to be multiplied to 1000 to allow for two digit patch version numbers. This still leaves us 999 build numbers. As the build numbers are counted as commits since last release tag this should mostly give us enough room (worst case we get stuck at build version 999, which only affects …

Update calculation of patch versions for Windows store

---

picard/util/pipe.py

* This is a…
Before this patch, Picard is logging a warning before anything else that looks like:
`W: pipe.send_to_pipe:276: Couldn't send: '\x00'`
At this point, the pipe isn't fully functional, and this message is expected, as Picard sends a message to pipe to see if it's the owner or not (in `AbstractPipe.__init__()`). The behavior is normal, the warning isn't.
To fix it, check if the pipe is marked as running before logging such warning.

Avoid a warning on Picard start-up about send_to_pipe

---

.github/workflows/package.yml
scripts/package/macos-notarize-app.sh

* This is a…
Apple has deprecated using `altool`  for the app notarization. Instead the new `notarytool`  should be used. See https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool for background.
Perform the notarization with the new `notarytool`. This also has the advantage that there is now a clear way to specify the MetaBrainz team by specifying the team ID. In addition we can get rid of the polling because `notarytool`  supports a [`--wait` parameter](https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool#Submit-a-file).
The entire process is also faster.
Tested successfully on my repo phw/picard . See …

Use notarytool for macOS notarization

---

.github/workflows/validate-appstream.yml
org.musicbrainz.Picard.appdata.xml.in

* This is a…
The AppStream metadata was invalid (multiple `<recommends>` , should be only one).
We have AppStream validation already. But it was using the older ` appstream-util` which did not catch that issue. Replaced this with `appstreamcli`.

Fix appstream XML and use appstreamcli for validation

---

picard/ui/options/metadata.py

* This is a…
* JIRA ticket (_optional_): PICARD-2665
As discussed in PICARD-2665 and [on the forums](https://community.metabrainz.org/t/artist-aliases-for-past-names-vs-picards-use-standardized-artist-names-option/642755) this commit reverts enabling the artist name standardization. This avoids the issues coming with this change for the 2.9 release.
For a future release a more sophisticated handling of artist aliases as suggested in PICARD-2673 should be attempted instead.
This reverts commit 5a9d6b9581abd31cdb340444c6066a722f354374.

PICARD-2665: Revert "PICARD-2634: Use standardized artist names by default"

---

requirements-macos-10.12.txt

* This is a…
* JIRA ticket (_optional_): PICARD-2658
The macOS 10.12 build of Picard 2.9.0b1  does not show the main window. It's some issue with PyQt 5.13.2. Downgrade to 5.12.1 again (which is the newest usable version still running on macOS 5.12 and 5.13.

PICARD-2658: fix macos 10.12 build

---

picard/ui/infodialog.py
picard/ui/mainwindow.py
picard/ui/options/maintenance.py
picard/ui/options/plugins.py
picard/util/__init__.py

* This is a…
* JIRA ticket (_optional_): PICARD-2679
If Picard is installed via Snap all "Open folder" actions do not work. This is for example the case for "Open containing folder" for loaded files, but also for opening the plugin folder or config folder in options.
This is supposed to work via xdg-desktop-portal automatically, and it does work for the Flatpak install. But there seems to be an issue with this on Snap, see https://forum.snapcraft.io/t/xdg-open-or-gvfs-open-qdesktopservices-openurl-file-somelocation-file-txt-wont-open-the-file/16824/14 and https://bugreports.qt.io/browse/QTBUG-83939
When running as a Snap use xdg-open instead of QDesktopServices. Introduce picard.util.open_local_path helper to wrap this functionality.

PICARD-2679: Fix open folder for Snap install

---

picard/util/pipe.py

* This is a…
@zas: This ads back the thread pool instance to the pipe implementation that we removed in #2247 . The reasoning is that currently a new thread pool is created on every call to `send_to_pipe` to then only use a single thread. This is quite some overhead and not how a pool of threads should be handled.
Furthermore the thread pool is no longer used at all in `read_from_pipe`. It's not needed as the pipe server already runs in a separate thread. This allows us to keep reading from the pipe without timeout, avoiding the constant looping (which only consumes CPU for no good reason). We also don't need any workarounds to close the timed out thread but just need closing the reader thread on application exit.
This change should also avoid …

Pipe refactor thread pool

---

picard/file.py

This reverts commit 8a3a3424b913635bd36302a8b67d9901c3fc040e.
* This is a…
The threaded file update for PICARD-2609 causes wrong status icons to displayed for files in rare cases. Revert the change for now to ensure correctness. Introducing more threading requires a more intensive refactoring

PICARD-2669: Revert "PICARD-2609: Run metadata comparison on file.update in a thread"

---

picard/ui/mainwindow.py
picard/ui/newuserdialog.py
picard/ui/savewarningdialog.py

* This is a…
* JIRA ticket (_optional_): PICARD-2680
When starting Picard or saving the new warning dialogs might open dislocated from the main window and on some system even show up behind the main window.
Make the dialogs application modal and transient to the main window. This is how most of Picards dialogs are being opened already, specifically those message boxes.

PICARD-2680: Modal first use and save confirmation dialogs

---

picard/profile.py
picard/ui/ui_options_interface_top_tags.py
ui/options_interface_top_tags.ui

* This is a…
* **Describe this change in 1-2 sentences**:  Add new options to profile settings.
New options were added or reorganized in #2177, #2179 and #2181 but the profile manager was not updated to reflect the changes.
Update the profile manager to include the newly added options, and reorganize the display order to match the order in which the option settings are shown in the Configuration pages.  Renamed one of the objects in the "Top Tags" page to make it unique to prevent incorrect highlighting.

Add new options to profile settings

---

picard/config.py
picard/metadata.py
picard/util/__init__.py

* This is a…
* JIRA ticket (_optional_): PICARD-2011
The `Metadata`  class is not thread safe. If it is accessed in a thread this can lead to errors. E.g. the metadatabox can throw "RuntimeError: dictionary changed size during iteration" when iterating over the metadata while another thread changes it.
Similar `ConfigSection.as_dict()` can throw if `Object.registry` changes. 
- Make `Metadata` thread safe by introducing a read / write lock
- Have `ConfigSection.as_dict()` operate on a copy of `Object.registry`

PICARD-2011: Avoid "RuntimeError: dictionary changed size during iteration" errors

---

.github/workflows/pypi-release.yml

* This is a…
Installing openssl for the macOS PyPI builds is no longer needed since the code signing got removed. This solves build issues on latest Github Actions images.

CI: Remove openssl install for macOS PyPI packaging

---

picard/ui/itemviews.py

* This is a…
Fixes issues with an empty rectangle being shown during dragging of items if the first selected item is not visible.
* JIRA ticket (_optional_): PICARD-2689
https://community.metabrainz.org/t/possible-bug-found-dragn-dropping-items-from-the-right-pane-results-in-a-white-box-if-they-are-outside-the-visible-part/646711
Instead of taking the first selected element take the currently active one. The item becomes active when clicking on it while starting the drag. This is probably even more intuitive for the user, as it shows the actual dragged element.

PICARD-2689: Render the actually dragged element instead of the first selected

---

picard/file.py
picard/util/tags.py
test/test_file.py

* This is a…
* JIRA ticket (_optional_): PICARD-2685
1. Have files loaded matched to a track
2. Generate AcoustID fingerprint or ReplayGain tags (with the replaygain2 plugin)
3. Move the file to another track or unmatched files
Result: The AcoustID fingerprint or ReplayGain tags get removed
Expected result: As these tags are generated from audio content it would be expected that they move with the file instead of being replaced by the new track's data.
For the `acoustid_id` tag this is already handled.
Preserve calculated AcoustID fingerprint and ReplayGain tags set on a file
object when that file object gets moved between tracks.
This generalized the mechanism already in place for `acoustid_id`  and extends it to `acoustid_fingerprint` and all …

Picard-2685:  Preserve calculated from audio file tags when moving files

---

installer/i18n/sources/de.json
installer/i18n/sources/en.json
installer/picard-setup.nsi.in

* This is a…
* JIRA ticket (_optional_): PICARD-2693
On Windows when installing Picard with the installer package we trigger the uninstaller in order to completely remove the previous version. This avoids issues with leftover files, especially DLLs for dependencies, from previous install causing version conflicts.
However, it was possible for the user to cancel the uninstall and continue with the installation anyway.
When the user cancels the uninstall also abort the installer. Show a prompt informing the user.
Note: As an alternative I had thought about making the uninstaller run automatically non-interactive. However, NSIS does not support runnning non-interactive with UI. If you launch the uninstaller in automatic mode it just would run …

PICARD-2693: Do not continue Win installation if uninstall got cancelled

---

picard/ui/__init__.py

* This is a…
* JIRA ticket (_optional_): PICARD-2694
If the ScriptingDocumentationDialog gets closed not explicitly but because its parent (the OptionsDialog) gets closed and destroys child widgets then reopening it again crashes Picard.
Clear the instance of `SingletonDialog` on `destroyed` instead of `finished`
That fixes issues where the dialog does not get closed as a dialog but the widget just get cleared because the parent gets removed.

PICARD-2694: Clear instance of SingletonDialog if destroyed

---

picard/ui/widgets/scripttextedit.py

* This is a…
* JIRA ticket (_optional_): PICARD-2695
For some code points, e.g. \u0000, unicodedata.name does not return a name but raises a ValueError.
Catch the ValueError and as an alternative just output the unicode code point in the format "U+0000" (as it is common).

PICARD-2695: Fix crash in script editor on some unicode escape tooltips

---

picard/const/__init__.py
picard/ui/options/__init__.py
picard/ui/options/dialog.py
picard/ui/options/general.py

* This is a…
*Restore all Defaults* button doesn't have same effect as *Restore Defaults* button on *General* page.
When *Updates to check* is set to anything but the default value, pressing and accepting *Restore Defaults* will reset it to default value, but that's not the case for *Restore all Defaults*.
One of the call comes from `update_from_profile_changes()` which calls `update_from_profile_changes()` which in turn calls General Option Page `load()` method.
* JIRA ticket (_optional_): PICARD-2697
Calling `OptionPage.load()` multiple times actually cancels the reset to default value for some options, so ensure it is called only once.

PICARD-2697: fix Restore all Defaults for General option page

---

picard/ui/coverartbox.py
picard/ui/itemviews.py

* This is a…
* JIRA ticket (_optional_): PICARD-2696
When dropping while pressing shift on Windows the files get sent as a "move" event to the application. Accepting this results in file deletion. Picard must always handle such events as "copy" to avoid this.
This replaces #2269
For itemview override the acceptance done in `QAbstractItemView.dropEvent` and only do a "copy" if the drop originates from outside Picard (no source widget) or is providing URLs.
For the cover art box generally handle all drops as copy.

PICARD-2696: Fix file deletion when shift-dropping files on Windows

---

picard/util/pipe.py

* This is a…
* JIRA ticket (_optional_): PICARD-2713
Starting Picard with the `--stand-alone-instance` parameter has no affect. Picard starts normally with the main instance.
The pipe server ignored the provided identifier.

PICARD-2713: Fix --stand-alone-instance handling

---

installer/picard-setup.nsi.in

* This is a…
* JIRA ticket (_optional_): PICARD-2186
The Windows installer attempts to detect the Picard Window to stop installation / uninstallation while Picard is running. This detection was broken since Qt at some point changed from a static window class name of "Qt5QWindowIcon" to a version specific one like "Qt512QWindowIcon".
The Qt window class name changed from a generic one to a version specific one. Use a function to search for partial matches.
Compare:
https://nsis.sourceforge.io/Enhanced_FindWindow_for_variable_window_title_names
https://nsis.sourceforge.io/Check_whether_your_application_is_running#Using_a_window_class_or_title

PICARD-2186: Fix detection of running app in Windows (un)installer

---

picard/ui/coverartbox.py
picard/ui/itemviews.py
picard/ui/options/plugins.py

* This is a…
In places where Picard handles drag and drop handle the Qt `IgnoreAction`. See discussion at https://github.com/metabrainz/picard/pull/2270#pullrequestreview-1575294513

Handle Qt drag and drop IgnoreAction

---

.github/workflows/package.yml
.github/workflows/pypi-release.yml

* This is a…
* JIRA ticket (_optional_): PICARD-2691
Since PyPI stopped providing signed source files we did no longer provide signed sources automatically.
Also we always relied on source files automatically generated by Github for our official release. This causes two source files to exist for Picard (on PyPI and official download). Also the Github generated source files are not stable. They can get regenerated later resulting in changed checksum.
- Re-activate GPG source file signing in the PyPI builds
- Extend the build to generate both tar.gz and zip
- Make the release-pypi workflow a dependency of the package workflow and publish the resulting artifacts (source archives .tar.gz and .zip + their signatures) on Github release
I did perform …

PICARD-2691: provide signed source archives

---

picard/ui/options/general.py

* This is a…
The new plugin update feature is something that I think we can ship in the 2.9.1 release. But as we want to get this release out soon due to the important bug fixes I would feel better if we could make this disabled for now by default.
That way we can ship the feature to interested users and hopefully can get feedback on it, but don't cause unexpected interruption for existing users.
Once we have extended the feature and improved the UI we can consider making it the default.

Disable plugin updates by default

---

picard/tagger.py

* This is a…
* JIRA ticket (_optional_): PICARD-2718
*.log files where ignored with the "All supported log files" filter
Qt file dialog filters must separate the extensions only by space.

PICARD-2718: Fix file filter for ripper log file picker

---

picard/pluginmanager.py
picard/ui/mainwindow.py

* This is a…
* **Describe this change in 1-2 sentences**:  Adds list of plugin updates available and a button to open the Options -> Plugins screen directly from the plugin update notification dialog
The plugin updates available notification dialog did not provide any details or allow easy updating.
* JIRA ticket (_optional_): PICARD-2715
Add a list of plugin updates available and a button to open the Options -> Plugins screen directly from the plugin update notification dialog.  Examples:
Note that the displayed list is limited to a maximum of 3 plugins, with a note indicating if there are more.
None.

PICARD-2715: Show plugins with updates and add button to open plugin options window

---

org.musicbrainz.Picard.desktop

* This is a…
* JIRA ticket (_optional_): PICARD-2720
XDG desktop entries allow specifying additional actions as alternative ways to launch an application.
We can use this to add a new option to explicitly open a new standalone window / instance of Picard.
See https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions
Add a new action to launch `picard --stand-alone-instance`.

PICARD-2720: Add .desktop file action to explicitly open new window

---

picard/util/__init__.py
test/test_utils.py

* This is a…
* JIRA ticket (_optional_): PICARD-2712
Sanitize date cleared zero values in between, such turning "YYYY-00-DD" into "YYYY-DD", which would be a completely different date.
Fix this by keeping empty values if they are not the last element.
It changes the behavior for some strings with e.g. double slashes, as the empty string in between those is now considered a valid value and treated as `0`.

PICARD-2712: Fix sanitize date removing 0 values

---

picard/mbjson.py

* This is a…
* JIRA ticket (_optional_): PICARD-2724
Fix potential crash in artist alias translation
This crash requires very specific circumstances:
- Option `translate_artist_names` must be enabled
- Option `translate_artist_names_script_exception` must be set
- The track search dialog must be opened on a file
- The search result must contain artist aliases
- An artist alias must:
- be in a script not catched by `translate_artist_names_script_exception` 
- be set to "primary"
- have a "locale" set
- have no type set
In this case the result does not contain the `type-id` key but Picard still tries to read it.
Make the code around reading the alias node more robust:
- handle non existent `type-id`
- handle non-existent `primary` (should not …

PICARD-2724: Fix potential crash in artist alias translation

---

test/test_util_pipe.py

* This is a…
The test_pipe_protocol is extremely slow. Without it the full test suite runs on my system with pytest in ~8 seconds. With  test_pipe_protocol enabled in runs 71 seconds.
- Only test a single message. As there is no message processing here we just need to ensure the sent message gets read
- Reduce timeouts. The timeouts helped with Windows tests. But try to reduce them.
- The check for `if message` in `pipe_listener` might help with macOS tests. On macOS sometimes the read seems to return an empty string. In normal use in Picard that is ok. The empty string is not a processed message and the loop will just read the next one. Do the same in tests

Speed up test_pipe_protocol test

---

picard/mbjson.py
test/test_mbjson.py

* This is a…
* JIRA ticket (_optional_): PICARD-2700
When refreshing series are added once again (and so on), because of the use of `Metadata.add()` over same tags.
Call `Metadata.unset()` for series before adding first tag value.
This fix is limited to `*series` tags, but the issue is perhaps concerning more, the whole process of refreshing will need to be reviewed.

PICARD-2700: fix accumulating series metadata on refresh

---

.gitignore
.pylintrc
picard/config_upgrade.py
picard/i18n.py
picard/ui/options/general.py
picard/ui/options/interface.py
picard/ui/options/metadata.py
picard/ui/options/profiles.py
picard/ui/scripteditor.py
picard/ui/widgets/profilelistwidget.py
picard/ui/widgets/scriptlistwidget.py
picard/util/__init__.py
picard/util/checkupdate.py
po/constants/constants.pot
po/picard.pot
requirements-build.txt
setup.cfg
setup.py
test/test_i18n.py

* This is a…
* JIRA ticket (_optional_): PICARD-2690
The `picard.const` module contains longs lists, most specifically for locales and written scripts.
This makes translating much harder, as half the strings to translate are from these lists, but they are essentially only used for very few UI elements.
Also it makes it difficult to assess how complete a translation of Picard is. A translations that translates all the UI texts except for the locale list has a low completion percentage on Weblate, but actually it is a very complete translation. Likewise a translation that solely translates the locales list shows with the same or higher completion, but actually the application can hardly be described as being localized.
Move translations of the …

PICARD-2690: move const translations

---

picard/util/time.py

* This is a…
The function `get_timestamp()` in `picard.util.time` uses parametered strings like `%.2dh %.2dm`. For translation it is hard to see for what purpose those are being used for and how to replace them. Also order cannot be easily changed (should this be necessary in the target language), even though this is unlikely in this specific case.
Use named parameters like `%(hours).2dh %(minutes).2dm`

Use named parameters in get_timestamp() time formatting strings

---

picard/util/bytes2human.py

This partially reverts 3d50184, but still ensures that the partial string in _(...) does not get extracted. Also use named parameter to make the usage of the string more clear.

Fix bytes2human using localized strings.

---

scripts/package/win-common.ps1

* This is a…
* JIRA ticket (_optional_): PICARD-2736
Removed an old workaround that no longer applies for current PyQt5 and/or PyInstaller. The OpenSSL DLLs should be kept in the main install folder in order to be prioritized over system libs.

PICARD-2736: Fix Windows system wide libssl conflicting with bundled libssl

---

picard/util/pipe.py

* This is a…
* JIRA ticket (_optional_): PICARD-2722
Closing Picard on Windows can lead to an exception when closing the pipe while also have the pipe server thread still running. The reason is a race condition when sending the close message to the pipe. As the pipe gets recreated after it was read from it could happen that the pipe was running again before the application closed.
Only re-create the pipe if it was not marked as stopped. Also avoid exceptions when attempting to close the handle.
The second commit of this PR also solves a smaller problem, where on starting Picard under Windows there would always be a log output
```
E: 18:54:33,314 util/pipe.send_to_pipe:274: pipe sender exception: (2, 'CreateFile', 'The system cannot find the …
```

PICARD-2722: Avoid pipe thread respawning on exit on Windows

---

picard/config.py
picard/ui/options/profiles.py

`profile_id` is explicit.
`id()` is a built-in function, see https://docs.python.org/3.10/library/functions.html#id
* This is a…

Rename id to profile_id where applicable

---

picard/coverart/providers/caa.py
picard/ui/options/cover.py
picard/ui/options/interface_toolbar.py
picard/ui/options/metadata.py
picard/ui/options/profiles.py
picard/ui/options/releases.py
picard/ui/options/scripting.py
picard/ui/scripteditor.py
picard/ui/util.py

Introduce method to iterate Qlistwidget items

---

picard/log.py

* This is a…
* JIRA ticket (_optional_): PICARD-2749
With Python 3.12 the `find_module` method gets removed from importlib.
Update the `picard.log` module to use `find_spec instead.
**Note:** This does not provide full Python 3.12 compatibility as for now. We need to solve [PICARD-2354](https://tickets.metabrainz.org/browse/PICARD-2354) and [PICARD-2355](https://tickets.metabrainz.org/browse/PICARD-2355)) for this as well. See #2134

PICARD-2749: Avoid deprecated importlib APIs in log module

---

scripts/package/win-common.ps1

* This is a…
* JIRA ticket (_optional_): PICARD-2736
Copy all Qt5 DLLs to the main installation folder next to `picard.exe`.
Avoids import errors if a system wide, incompatible Qt5 installation is present on the system.

PICARD-2724: Move all Qt5 DLLs into main directory on Windows

---

.github/workflows/pypi-release.yml
.github/workflows/run-tests.yml
picard/pluginmanager.py
picard/tagger.py
test/test_plugins.py

* This is a…
* JIRA ticket (_optional_): PICARD-2751, PICARD-2354, PICARD-2355
Picard's plugin loading system must be updated to avoid long deprecated and inf Python 3.12 finally removed APIs of the importlib and zipimport modules.
This PR replaces #2134
At the core the change is to use `find_spec` in combination with `exec_module` to load the modules. A large benefit is that both the normal module loading via importlib as well as the zipimporter can now use the exactly same API.
Unfortunately for zipimporter we need to maintain the legacy loading code with `find_module` + `load_module` for compatibility with Python < 3.10.
This PR maintains full compatibility with the existing plugin systems. Overall there is likely a lot that we could further …

PICARD-2751: Avoid deprecated importlib APIs, full Python 3.12 compatibility

---

picard/pluginmanager.py

* This is a…
* JIRA ticket (_optional_): PICARD-2751
With the changes in #2307 the plugin system's ability to load plugins that only exist as compiled bytecode (`.pyc`) files got lost.
Consider all possible file extensions again when trying to load the spec.

PICARD-2751: Restore the ability to load compiled .pyc plugins

---

picard/pluginmanager.py
picard/ui/mainwindow.py
picard/ui/pluginupdatedialog.py

* This is a…
Thns pluginmanager module mixes the plugin logic with update UI. 
Factor out the dialog to a separate module `picard.ui.pluginupdatedialog` and handle the UI creation in mainwindow. This will make it easier to refactor pluginmanager and reuse plugin update notification in different context.

Refactor plugin update UI

---

picard/tagger.py

* This is a…
* JIRA ticket (_optional_): PICARD-2754
If Picard gets called with a relative path but cwd is invalid (e.g. removed before actual launch) resolving the path lead to a crash.
Handle this error now by the file loading code

PICARD-2754: Handle launch with relative path and without valid cwd

---

picard/coverart/providers/caa.py
picard/ui/caa_types_selector.py

Move CAA provider type selector code to its own file

---

picard/coverart/image.py
test/test_coverart_image.py

* This is a…
There was a typo leading to potentially incorrect support_multi_types value in `__repr__()` output.
Fix the typo, refactor a bit, and add matching tests.

Fix CoverArtImage repr

---

picard/util/__init__.py
test/test_utils.py

* This is a…
* JIRA ticket (_optional_): PICARD-2756
For Windows UNC paths (e.g. for network shares) the long path support did not work and lead to invalid paths.
While for local paths the file path needs to be preficed with `\\?\`, e.g. `\\?\C:\somelongpath...`, for UNC paths in the form of `\\servername\path` the long path must be defined as `\\?\UNC\servername\somelongpath...`.
See also:
- https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation
- https://en.wikipedia.org/wiki/Path_(computing)#Universal_Naming_Convention
Extend `picard.util.win_prefix_longpath`  to handle UNC paths.

PICARD-2756: Windows long path support for UNC paths

---

picard/coverart/image.py
picard/tagger.py

It is faster, and more secure.
* This is a…
`hashlib.md5()` is now quite old, and it raises few warnings (even though our use isn't risky).
Since a while `hashlib.blake2b()` is a good alternative, it is even slightly faster than `md5()`

Replace hashlib.md5() with hashlib.blake2b()

---

.github/workflows/package.yml
scripts/package/win-common.ps1
scripts/package/win-package-appx.ps1
scripts/package/win-package-installer.ps1
scripts/package/win-package-portable.ps1

* This is a…
* JIRA ticket (_optional_): PICARD-2760
Enable timestamping when code signing for Windows. Signed binaries with a timestamp will remain valid even after the certificates have expired as long as they get signed before expiration of the certificates.
For details see:
- https://learn.microsoft.com/en-us/windows/win32/seccrypto/time-stamping-authenticode-signatures
- https://www.ssl.com/how-to/using-your-code-signing-certificate/#ftoc-heading-10
Use the timestamp server provided by ssl.com with SignTool

PICARD-2760: Timestamp the Windows binaries when codesigning

---

CONTRIBUTING.md

Add a section about string quoting to CONTRIBUTING

---

picard/config.py
test/test_profiles.py

* This is a…
* **Describe this change in 1-2 sentences**: Add test for invalid `profile_id` keys
* JIRA ticket (_optional_): PICARD-2748
See the discussion in PICARD-2748.
Add checks for invalid keys.

PICARD-2748: Add check for missing profile_id keys

---

picard/ui/options/dialog.py

* This is a…
* **Describe this change in 1-2 sentences**: Add mapping from option setting pages to the controlling option profile category
When you try to display the "Attached Profiles" dialog from an option settings sub-page Picard prints a "KeyError" exception to the terminal but does not record the exception in the log.
Steps to reproduce:
1. Open "Options..."
2. Select the "Option Profiles" options page.
3. Create a new profile and enable the "Advanced" settings for the profile.
4. Select the "Advanced" > "Network" options page.
5. Click the "Attached Profiles" button.  The dialog is not displayed and the exception is written to the terminal.
* JIRA ticket (_optional_): PICARD-2764
Get the option group from the parent option page if applicable.
None.

PICARD-2764: Attached profiles dialog does not display on option sub-pages

---

picard/profile.py

* This is a…
* **Describe this change in 1-2 sentences**: Add highlight to label for options not properly displaying the highlight.
Some settings in the option settings pages do not properly display highlighted when associated with an option profile.
Add highlight to label for options not properly displaying the highlight.
None.

Highlight associated labels for items not showing highlight

---

picard/tagger.py

It might be useful as many QT_ env vars modify the behavior of Qt and therefore Picard's behavior.
Example of output:
```
D: 16:50:10,035 tagger.__init__:325: Qt Environment: QT_ACCESSIBILITY='1' QT_QPA_PLATFORMTHEME='qt5ct'
```
* This is a…

In debug mode, log QT_* env vars

---

picard/track.py

* This is a…
* JIRA ticket (_optional_): PICARD-2768
Series variables are not available for standalone recordings.
Include `series-rels` in recording request.

PICARD-2768: Fix loading series relationships for recordings

---

picard/metadata.py

* This is a…
In metadata track comparison the video flag check was not performed if no releases where set.
Perform the video flag check earlier

Fix track metadata compare ignoring video check if there is no release

---

picard/ui/coverartbox.py
scripts/package/macos-package-app.sh
scripts/package/win-common.ps1

* This is a…
A libwebp vulnerability allows arbitrary code execution when loading a manipulated image. CVE-2023-4863
Disable the Qt webp imageformat plugin for binary builds for macOS and Windows for now. WebP images still can be loaded and saved, but they will not be displayed.

PICARD-2775; Disable Qt WebP plugin for Windows and macOS binary builds

---

picard/coverart/image.py
test/test_coverart_image.py

* This is a…
* JIRA ticket (_optional_): PICARD-2774
Files containing embedded cover art with invalid ID3 image type fail to load.
Load files even with invalid type. Assume type "other" in this case.

PICARD-2774: Do not fail loading files with invalid ID3 image types

---

picard/metadata.py
test/data/ws_data/recording_video_null.json
test/data/ws_data/release_no_type.json
test/test_metadata.py

* This is a…
* JIRA ticket (_optional_): PICARD-2781, PICARD-2780
This PR fixes two issues with search result comparison for found recordings:
- If a release + release group had no type set at all the search score got really low as this was treated as a total mismatch with score 0.0
- If a recording had the video flag not set on MB, the API can return `"video": null` (not sure if always or only sometimes). The matching code only expected `true` or `false`, and hence non-video recordings always mismatched, lowering the score
See also discussion at https://community.metabrainz.org/t/similar-track-with-score-100-will-not-match/661856
- If no release type is set apply the weight for "Other" type
- Fix the video flag check by explicitly converting …

PICARD-2781: fix releasetype weights

---

picard/log.py
picard/ui/logview.py

* This is a…
* JIRA ticket (_optional_): PICARD-2795
The log view's verbosity selection just shows the static string "Verbosity" instead of the actually selected level.
Also the level names where not extracted for translation.
Set the displayed label to the selected level.

PICARD-2795: display log view verbosity

---

picard/tagger.py
picard/util/versions.py

* This is a…
On startup the following error message is printed:
```
qt.core.qobject.connect: QObject::connect(QObject, Unknown): invalid nullptr parameter
```
This is caused by the call to `QSslSocket.sslLibraryVersionString()` in `picard.util.version`, which expects an initialized Qt application but was called before this exists.
- Fill the version list on demand.
- When running with "-V" CLI flag initialize a QCoreApplication.

Prevent QObject::connect nullptr warning on startup

---

picard/acoustid/__init__.py
picard/acoustid/json_helpers.py
picard/metadata.py
test/data/ws_data/acoustid_no_metadata.json
test/test_acoustid.py
test/test_metadata.py

* This is a…
* JIRA ticket (_optional_): PICARD-2792
In PICARD-2792 and the forum discussions at https://community.metabrainz.org/t/worse-results-in-picard-2-10/663668/34 two issues with the metadata matching were identified:
1. For AcoustID recordings without metadata a high submission score led to disproportional high scoring. This happens for example if recordings get merged without the AcoustID server having applied this merge yet.
2. Generally matching recordings without any releases (standalone-recordings) scored higher on average. This is because as soon as release data gets compared it usually leads to lower score (as a 100% score is seldom).
For 1) ignore AcoustID recordings without additional metadata when determining the submission …

PICARD-2792: fix matching for AcoustID results without metadata and standalone-recordings

---

.github/workflows/package-macos.yml
.github/workflows/package-pypi.yml
.github/workflows/package-windows.yml

* This is a…
Replaces #2355 . There is a backward incompatible change where it is no longer possible to upload to the same file multiple times to update the uploaded archive file. That means the Python bdist packages now are separated by Python version.
For details see https://github.com/actions/upload-artifact/tree/v4/#v4---whats-new

Bump actions/upload-artifact from 3 to 4

---

picard/acoustid/__init__.py
picard/acoustid/json_helpers.py
picard/acoustid/recordings.py
test/test_acoustid.py

* This is a…
* JIRA ticket (_optional_): PICARD-2584
AcoustID can sometimes contain no MB metadata for linked recordings. This happens if:
1. recordings have been merged and this merge was not yet handled by the AcoustID server
2. recordings have been deleted and the AcoustID server has not yet cleaned up
AFAIK both should be handled by AcoustID, but currently this does not seem to work correctly (e.g. https://github.com/acoustid/acoustid-server/issues/114). There can always be some time frame where this has not been done as there is some delay in AcoustID database synchronizing., though
In case of 1) this can lead to recording data not being available and files getting matched to standalone recordings instead. It also messes with submission …

PICARD-2584: Load recording if AcoustId metadata is missing

---

picard/acoustid/__init__.py

* This is a…
* JIRA ticket (_optional_): PICARD-2813
If fpcalc encounters a decoding error for which it still was able to generate a result it will return the special return code 3. Continue receiving results if this code was returned. See https://github.com/acoustid/chromaprint/blob/master/src/cmd/fpcalc.cpp#L403-L408 and https://github.com/acoustid/chromaprint/commit/3f07ceef8438058d14a1d479009cb66779cf3594
Example for such a call:
```
% fpcalc "/home/phw/Musik/Library/Deep Purple/The Platinum Collection/01-12 Flight of the Rat.mp3" -json              
ERROR: Error reading from the audio source (Invalid data found when processing input)
{"duration": 471.75, "fingerprint": "AQABRU5CaQ2DfsO--qi1oFQ0-D16oruQ7ikSMiiVBj8VoZeFKXnw4zr-I5xZiPWD8MqB_5i …
```

PICARD-2813: Ignore fpcalc errors if there was still a result.

---

.github/workflows/package-pypi.yml
.github/workflows/package.yml

* This is a…
This eliminates the need to provide permanent access tokens for PyPI in the CI and instead uses temporary tokens issued by OpenID Connect (OIDC)
The metabrainz/picard repository has been setup as a trusted publisher on the PyPI picard project. The Github action now uses pypa/gh-action-pypi-publish@release/v1 instead of unvoking twine.
Once this has been merged (including the 2.10.x branch) we could remove PYPI_UPLOAD_TOKEN from the Github Actions environment.
Generally this is difficult to test as we need to perform our first release with this to see how it goes. But the risk is low. If everything fails twine can be run locally.

Do PyPI deployment with Trusted Publisher Management

---

picard/file.py
picard/formats/wav.py
picard/ui/infodialog.py
picard/ui/itemviews.py
po/nl.po
test/formats/common.py
test/formats/test_aac.py
test/formats/test_ac3.py
test/formats/test_apev2.py
test/formats/test_asf.py
test/formats/test_id3.py
test/formats/test_midi.py
test/formats/test_mp4.py
test/formats/test_vorbis.py
test/formats/test_wav.py

Add ~filesize variable
* This is a…
Provide the file size in bytes as a hidden file variable ~filesize (similar to the existing file variables like e.g. ~bitrate and ~length). 
* JIRA ticket (_optional_): PICARD-1685
I have added the "~filename" variable which stores the size of the file in bytes using "os.path.getsize" and passing the "self.filename" in it. also I have used this variable in infodialog.py to show Size. Modified test cases for '~filsize'. Add '~filesize' to metadata in wav.py since it doesn't uses mutagen. 
I don't know if you want to also add size option in itemviews.py (since it was mention in the old discussion "https://community.metabrainz.org/t/current-file-size/453338/5"). If yes, then please specifiy how to add it in UI, …

PICARD-1685 : Add ~filesize variable

---

picard/file.py
picard/formats/wav.py

* This is a…
* JIRA ticket (_optional_): PICARD-2826
The `~filesize` variable added in #2361 does not update after saving.
Move the filesize update into `File._add_path_to_metadata`, which is specifically called after file save. Also rename this to `File._update_filesystem_metadata` due to changed scope.
PICARD-2826 is broader. We have other info metadata that is not being updated properly. I think it is only about `~format`, but e.g. for ID3 this cane change from v2.3 to v2.4 (or vice versa). And for e.g. AC3 it indicates whether APE tags are present or not, which can also change after save.
Fixing this is more difficult, especially if we want to avoid re-reading the entire file (which would be a straightforward solution). I'll look into this …

PICARD-2826: Update ~filesize after saving file

---

picard/ui/options/interface.py

* This is a…
* **Describe this change in 1-2 sentences**: Adds a warning dialog when the "Select multiple directories" configuration option is enabled.
As discussed in https://tickets.metabrainz.org/browse/PICARD-2829 it is possible for Picard to not recognize external drives when the "Allow selection of multiple directories" option setting is enabled.  This is unexpected behavior for the user.
* JIRA ticket (_optional_): PICARD-2832
This PR adds a warning dialog that is presented to the user to inform them of the potential consequence (external drives not being recognized by Picard) when the "Allow selection of multiple directories" option setting is enabled.
This should be considered an interim measure until the issue is resolved in the Qt library.
If this is acceptable, it might be …

PICARD-2832: Add warning when select multiple directories option is enabled

---

picard/ui/util.py

* This is a…
* JIRA ticket (_optional_): PICARD-2829
As discovered in PICARD-2829 when using the "multi dir" directory selection dialog on macOS the user cannot select mounted volumes other than the main volume. That's because by default the dialog only shows the root volume and macOS hides the `/Volumes/` folder.
Customize the sidebar of the Qt file dialog to list all mounted volumes. As this is generic and also improves the dialog on other platforms the implementation is not macOS specific. By default on all platforms there were only two entries in the sidebar: "Computer" and the user's home directory.
Extend this to always include:
- Root volume
- User's home
- Primary "Music" folder
- All additionally mounted volumes (on Linux this get …

PICARD-2829: make volumes available in MultiDirsSelectDialog sidebar

---

picard/file.py
picard/ui/itemviews.py

* This is a…
Some minor tweaks to the "Size" column added in #2361 to the main view:
- use bytes2human to format the value
- ensure sorting happens by actual byte size
- right aligned column

Human readable filesize column

---

picard/file.py
picard/ui/infodialog.py

* This is a…
This is a bit of an edge case, but should `~filesize` be non-numeric `bytes2human` would throw a `ValueError`. This makes sure Picard keeps functioning.

Handle exceptions if ~filesize is not numeric

---

picard/ui/options/releases.py

* This is a…
Using a source code install (i.e. `pip install .`) I ran into this exception when modifying the release preference sliders: 
```
File "/home/joncrall/.pyenv/versions/3.11.2/envs/pyenv3.11.2/lib/python3.11/site-packages/picard/ui/options/releases.py", line 97, in show_tip
rectHandle = self.style.subControlRect(self.style.CC_Slider, self.opt, self.style.SC_SliderHandle)
^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QCommonStyle' object has no attribute 'CC_Slider'
```
I was able to determine what the correct values should be and I modifed them (while still allowing old values to work in case this is a PyQt 6.6 thing versus a 6.5 thing)
The slider breaks in my Python environment (not sure if it would work if …

Fix Sliders in PyQt 6.6

---

.github/workflows/package-pypi.yml
.github/workflows/run-tests.yml
INSTALL.md
picard/i18n.py
setup.py

* This is a…
By the time Picard 3 will be released official support for Python 3.8 will be already or nearly at its end. Also pygit2 dropped support for Python 3.8, and we might want to use that for the new plugin system.
This PR also removes some gettext workaround for missing pgettext in Python 3.7 and lower.

Drop python 3.8

---

.github/workflows/package-pypi.yml
.github/workflows/package-windows.yml
.github/workflows/run-tests.yml
scripts/package/win-common.ps1
scripts/package/win-setup-gettext.ps1
scripts/package/win-setup.ps1

* This is a…
On Github action the provided gettext tools (in particular `msgfmt` where gettext commands shipping with git for Window. Since git 2.44.0 these are no longer bundled and hence the builds started failing.
Fix this by explicitly downloading and installing gettext for Windows.
Unfortunalety there are no official binary packages and many binary packages offered online are outdated. In particular there are no recent gettext packages available for automatic installation via Win-Get or chocolatey.
But https://github.com/vslavik/gettext-tools-windows is maintained by the Poedit author and provides up-to-date packages. Hence this PR downloads the latest release from there and unzips it locally.

CI: Install gettext for Windows

---

picard/util/tags.py
test/test_util_tags.py

* This is a…
Picard no longer creates a duplicate `COMM` frame with the incorrect language when using `lang='XXX' + desc=''`.
Previously, a `COMM` frame with `lang='XXX' desc=''` would be saved as a separate frame with `lang='eng' desc='XXX'`. This is due to Picard supporting both `comment:desc` and `comment:lang:desc` syntax for comment tags.
* JIRA ticket (_optional_): PICARD-2468
A special case was added for `lang='XXX', desc=''`. I could not think of a better solution for the problem, as Picard normalizes all metadata keys. It would be more elegant if trailing colons were preserved.
Possibly explore storing these comments as `comment:XXX:`, leaving the trailing colon as a marker for an empty description. This solution is not perfect. In the …

PICARD-2468: Properly handle unspecified languages in ID3v2 comments

---

picard/formats/apev2.py
picard/formats/id3.py
picard/formats/mp4.py
picard/formats/vorbis.py
picard/util/tags.py
test/formats/test_id3.py
test/test_util_tags.py

* This is a…
* **Describe this change in 1-2 sentences**: 
Allow to preserve the SYLT tag. Also add support for reading and writing the SYLT tag of ID3.
* JIRA ticket (_optional_): [PICARD-1092](https://tickets.metabrainz.org/browse/PICARD-1092)
Like @phw said in the comments of the ticket, besides preserving the SYLT tag, it would be nice if Picard could both read and write this tag.
As it was suggested, this solution converts the SYLT tag to the LRC format for display, and it converts the LRC format back into the SYLT tag when saving.

PICARD-1092: Add support for preserving the SYLT tag

---

picard/version.py
test/test_versions.py

* This is a…
Old code leads to unexpected results with strings like `1.1.1xxx2`, as it matches only from end of string, it would consider this as a valid version, equivalent to ... `2.0.0final0`.
AFAIK, this "feature" isn't used anywhere anyway.
Be stricter, and match the full string.
With this change, `1.1.1xxx2` will raise a `VersionError`.
Tests were updated accordingly.

Make `Version.from_string()` stricter, matching from start of string

---

picard/cluster.py
picard/file.py
picard/ui/searchdialog/track.py
test/test_metadata.py

- it reduces the size of Cluster and File objects
- those are constant
It doesn't seem any plugin uses this.

Move cluster & file comparison weights at module level

---

picard/releasegroup.py
test/data/ws_data/release_group_5.json
test/test_releaseversions.py

- reduce size of the method, moving part of the code outside the class
- use constants at module level
- code cleanup

Refactor ReleaseGroup._parse_versions()

---

picard/log.py
test/test_log.py

`picard_module_path` can be a file path or a dir path. When it's a frozen package, that's always a directory, and when running from source it is always a file path.
Ensure it is always a directory (that is the parent of the file path if it happens)
* This is a…

Fix inconsistency in picard_module_path

---

picard/ui/coverartbox.py

* This is a…
* JIRA ticket (_optional_): PICARD-2580
Added a new shortcut which connects to existing `show_cover_art_info()` method

PICARD-2580: Add keyboard shortcut for Artwork/Show more details

---

picard/log.py
test/test_log.py

* This is a…
Further to the discussion in https://github.com/metabrainz/picard/pull/2397 this PR modifies the way that plugin paths are displayed in the logs.
Shorten the path by making it relative to the path stored in the `picard.const.USER_PLUGIN_DIR` variable if possible.
None.

Update plugin path shortening logic

---

picard/ui/searchdialog/track.py

* This is a…
When loading the result for a track search Picard crashes.
Steps to reproduce:
1. In search toolbar select "track" and type "3 Bier"
2. Select and load result for "3 Bier" by "Mehnersmoos" (https://musicbrainz.org/recording/c2813cfb-8be5-4d7f-baff-0d9cde2710bc)
3. "Load in Picard"
I get following exception with latest master on linux:
```
File "/home/zas/src/picard/./picard/ui/tablebaseddialog.py", line 206, in accept
self.accept_event(selected_rows_user_values)
File "/home/zas/src/picard/./picard/ui/searchdialog/track.py", line 180, in accept_event
self.load_selection(row)
File "/home/zas/src/picard/./picard/ui/searchdialog/track.py", line 215, in load_selection …
```

PICARD-2868: don't try to move a non-existing file after search

---

picard/__init__.py

* This is a…
* JIRA ticket (_optional_): PICARD-2869
Register a handler on sys.excepthook and have it call the global crash_handler(). This allows to show the exception dialog in otherwise unhandled exceptions, e.g. has happened in PICARD-2868

PICARD-2869: Register a global exception handler

---

picard/script/serializer.py
picard/ui/options/maintenance.py

The code is invalid in PyQt6 and also just was supposed to set the standard options being set anyway.
* This is a…
Invalid call to get default QFileDialog options. This is unneeded anyway, as the dialog will use the default options regardless.

Fixed calls to QFileDialog options

---

picard/__init__.py
picard/tagger.py

* This is a…
Without this patch, when running tests the crash message box may be displayed. 
The issue appeared in https://github.com/metabrainz/picard/commit/d796b1ec295b9c2030510e83e3c1a9db4f9192fd
With those changes, it will be displayed only if the app was actually started.

Only register sys.excepthook if the app actually started

---

org.musicbrainz.Picard.appdata.xml.in

* This is a…
Currently, flathub's build are failing as they don't allow releasing builds with invalid appdata (even if it's just a warning). Running `appstreamcli validate` do raise this warning: `W: org.musicbrainz.Picard:318: relation-display-length-value-invalid medium` currently.
According to https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-relations-display_length, display length's value must be an integer value corresponding to logical pixels.
I took `768`px as value because it corresponds to the recommended referenced size for laptops and tablets, which should match imho the previous incorrect `medium` value.

metainfo: fix recommended display length definition

---

picard/config_upgrade.py
test/test_config_upgrade.py

* This is a…
Options must only be registered once. This includes upgrade hooks, which must only access declared options or for removed options access their raw value.
Rewrite upgrade hooks to not declare Option instances during runtime. Added tests.
Tested with old configuration backups for various development and final versions of 2.5, 2.6 and 2.7.

Fix upgrade hooks re-declaring options

---

picard/ui/searchdialog/album.py
picard/ui/tablebaseddialog.py

* This is a…
In Album Search Dialog, scrolling table causes missing cover art images to be fetched, but it doesn't work if the dialog is resized and those cells made visible.
No signal is associated with this event, and therefore no code leading to fetching missing images is executed when it happens
* JIRA ticket (_optional_): PICARD-2873
- create a new `resized` signal emitted every second
- call `AlbumSearchDialog.fetch_coverarts()` when it happens

PICARD-2873: Fetch Search dialog cover art images after it was resized

---

picard/tagger.py
scripts/picard.in
tagger.py.in

* This is a…
* JIRA ticket (_optional_): PICARD-2869
For some exceptions the crash dialog got shown twice. This happens because we already catch exceptions around the call of ` main` in the startup scripts. Exceptions catched there would show the crash dialog. Then the exception got re-raised (intentionally, to trigger normal exception handling, including logging and final exit) and catched by the new excepthook introduced in #2436
Run register_excepthook early, don't separately catch exceptions around main.
This prevents the crash dialog to be shown twice for exceptions which are catched by the exception handler already. Early registration is required so that errors early during startup (e.g. import errors) are being catched.

PICARD-2869: Avoid double crash dialog

---

picard/const/defaults.py
picard/ui/filebrowser.py
picard/util/macos.py
test/test_util_macos.py

* This is a…
* JIRA ticket (_optional_): PICARD-2879
If the user has selected a starting directory in Opions > User interface that is not under the /Volumes/ path, this starting directory is not being used in the file browser on startup.
Extend all paths in filebrowser with /Volumes/
This ensures that selected starting directory gets resolved correctly, as the filebrowser only supports paths under /Volumes/, not directly under /. On saving drop the /Volumes/ prefix for paths on the root volume. This gives the nicer shorter paths the user is more familiar with (e.g. `/Users/phw/Music`  instead of the long `/Volumes/System/Users/phw/Music`).

PICARD-2879: macOS: Extend all paths in filebrowser with /Volumes/

---

picard/util/__init__.py
test/test_utils.py

* This is a…
This is something up for discussion. At its core this PR addresses the issue that running the DetectUnicodeEncodingTest tests failed if chardet is installed instead of charset_normalizer. This is because chardet detects `b'\00'` as ASCII, but charset_normalizer as `UTF-8`.
```
test/test_utils.py F...                                                                                                                                         [100%]
============================================================================== FAILURES ===============================================================================
_______________________________________________________ DetectUnicodeEncodingTest.test_detect_file_encoding_bom …
```

Always detect_file_encoding ASCII as UTF-8, fix tests with chardet

---

picard/script/serializer.py
setup.py
test/test_script_serializer.py

* This is a…
datetime.utcnow is deprecated since Python 3.12, see https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow

Replace deprecated datetime.utcnow() with datetime.now(datetime.UTC)

---

picard/ui/logview.py

Use setFontFamilies() instead.
https://doc.qt.io/qt-6/qtextcharformat-obsolete.html#setFontFamily https://doc.qt.io/qt-6/qtextcharformat.html#setFontFamilies
* This is a…

QTextCharFormat.setFontFamily() is deprecated since Qt6.1

---

.github/workflows/run-tests.yml
test/test_disc_eaclog.py

* This is a…
Some of Picard's dependencies are optional or have alternatives (e.g. discid|python-libdiscid or charset-normalizer|chardet). CI testing currently only insufficiently tests for these scenarios.
Run tests with specific combination of required packages
This tests for tests passing with optional packages and alternative packages.

Run tests with specific combination of required packages

---

picard/oauth.py
test/test_oauth.py

* This is a…
* JIRA ticket (_optional_): PICARD-2882
The existing MusicBrainz OAuth2 implementation implements PKCE (Proof Key for Code Exchange) and "strongly recommends" using it, see https://musicbrainz.org/doc/Development/OAuth2
This is also useful for but independent from supporting the upcoming MetaBrainz OAuth endpoints.
Implement PKCE according to https://datatracker.ietf.org/doc/html/rfc7636#section-4.1
The examples for the tests of the `s256_encode` and `base64url_encode`  helper functions are taken directly from the examples at https://datatracker.ietf.org/doc/html/rfc7636#appendix-B

PICARD-2882: Support OAuth2 PKCE

---

picard/ui/itemviews.py

* This is a…
* JIRA ticket (_optional_): PICARD-2883, PICARD-2884
This enhances the tooltips for file / track icons:
- Show match status icon tooltips also for files, not only for tracks. Fixes PICARD-2883
- Show tooltips for more icons, specifically for unmatched tracks, tracks matched to multiple files and file errors (PICARD-2884)
Refactor determining icon and tooltip for file items by combining both in the same function (similar to how the icon / tooltip for the fingerprint column is implemented).
Add additional tooltips.

PICARD-2884: Show tooltips for more file / track icon types

---

picard/oauth.py
picard/tagger.py
picard/ui/options/general.py

* This is a…
* JIRA ticket (_optional_): PICARD-2886
When logging out Picard so far was only removing the locally stored OAuth2 tokens (access and refresh tokens). This removed the tokens from the local system, but the tokens themselves were still present on the MB server and could potentially be used.
MB's OAuth2 implementation supports token revocation, see https://musicbrainz.org/doc/Development/OAuth2#Revoking_a_token. This PR makes use of this to revoke the tokens on the server.
Implement support for calling `POST /oauth2/revoke` in `OAuthManager.revoke_tokens`. Refactor this method to work asynchronously with a callback similar to  the login process.
In Options > General implement a dialog that is shown in case of an error during logout. …

PICARD-2886: OAuth2 token revocation

---

picard/browser/browser.py
picard/oauth.py
picard/tagger.py

* This is a…
* JIRA ticket (_optional_): PICARD-736
So far Picard supported the OAuth2 login to MusicBrainz only via the out-of-band flow for token exchange, which requires the user to manually copy the code used to exchange the access token.
This PR updates the implementation to use a callback URL on localhost, making use of Picard's built-in web server.
The built-in webserver provides a new `/auth` endpoint to be used as a callback URL. If the built-in webserver is running, this is used on localhost as the redirect URI for the OAuth2 authorization URL, and the auth endpoint handles exchanging the provided code for the access token.
The old OOB workflow is used as a fallback in case the browser integration is turned off.
Note: This will also …

PICARD-736: OAuth2 login with local callback URL

---

picard/ui/mainwindow/__init__.py
picard/ui/widgets/editablelistview.py

* This is a…
Calling `setFocus(True)` is incorrect
* JIRA ticket (_optional_): PICARD-2889, PICARD-2890
Call `setFocus()` with proper Qt.FocusReason

PICARD-2889, PICARD-2890: Fix set focus calls

---

picard/track.py

* This is a…
This was only retained for some plugin compatibility. Track.files should be used instead.

Remove deprecated Track.linked_files

---

picard/webservice/__init__.py
test/test_webservice.py

* This is a…
We can remove the deprecated request methods in favor of the newer *_url methods. The old ones are not in use in the codebase anymore and we just kept them around for plugin compatibility.

Removed deprecated webservice methods

---

picard/album.py
picard/cluster.py
picard/file.py
picard/formats/midi.py
picard/tagger.py
picard/track.py
picard/ui/coverartbox.py
picard/ui/item.py
picard/ui/itemviews.py
picard/ui/mainwindow/__init__.py
picard/ui/metadatabox.py

* This is a…
Newer ones, like `can_link_fingerprint` or `can_show_coverart` already got defined as properties. This changes make it consistent for older ones as well.

Turn item capability methods into properties

---

picard/cluster.py

* This is a…
* JIRA ticket (_optional_): PICARD-2891
When dragging files already matched to tracks on the right pane directly back to the left pane "Clusters" item the files get clustered by the new metadata from the matches releases. This is confusing, as the user likely wants to drag mismatched files back and retry with new clustering.
After clustering the files get their metadata reset to original anyway (because this happens when moving away a file from a track), which makes the cluster result even less understandable. 
Note that using the new metadata is actually wanted when clustering files already on the left pane.
During clustering check the parent of the file. If it is a track, then use the original metadata for clustering.

PICARD-2891: When clustering files attached to a Track use orig_metadata

---

picard/__init__.py
picard/config_upgrade.py
picard/ui/itemviews.py
picard/ui/widgets/tristatesortheaderview.py
test/test_config_upgrade.py

Itemviews headers refactoring

---

picard/webservice/__init__.py

* This is a…
* JIRA ticket (_optional_): PICARD-2895
Setting an empty authorization header can lead to request errors if the server tries to validate the header if present. In the reported ticket this is the case with the Deezer API, which expects a valid token in case the authorization header is present.
Only set the authorization header, if login has been set.

PICARD-2895: Web service requests must set Authorization header only when required

---

picard/ui/itemviews.py

Itemviews basetreeview cleanup

---

picard/extension_points/formats.py
picard/formats/util.py
test/formats/common.py
test/formats/test_asf.py
test/formats/test_mp4.py
test/formats/test_util.py

* This is a…
* JIRA ticket (_optional_): PICARD-2897
Picard currently tries load files based on the file extension. Only if the file has no extension or if loading causes an error it falls back to guess format by file content.
Picard should also guess format by file content if the extension was unknown.
- If detection of file format by extension fails, try guessing by content instead of returning `None`
- Added tests for `format.open_`
- Refactor `format.open_` to simplify the code. This also changes `extension_points.formats.ext_to_format`, which now expects the extension with leading dot. This avoid the need to remove the dot in every place where `ext_to_format` got called.

PICARD-2897: Load supported file formats with unknown / uncommon extension

---

picard/ui/checkbox_list_item.py
picard/ui/options/cover.py

* This is a…
This is something I came across while debugging my PySide branch: The current implementation of `CheckboxListItem` does replace the `QListWidgetItem.data()` method with a string. This can lead to unintended side effects, as Qt might expect a function there.
Also Qt already provides data handling with  `QListWidgetItem.setData()` and `QListWidgetItem.data()`, so use this instead of the custom implementation. Have `CheckboxListItem` focus on checkbox handling.

Fixed CheckboxListItem hiding QListWidgetItem.data()

---

picard/ui/caa_types_selector.py

* This is a…
The `QListWidget.Clicked` signal expects a slot which accepts a single index parameter. In `CAATypesSelectorDialog` the signal gets connected to a function without parameters. See https://doc.qt.io/qt-6/qabstractitemview.html#clicked
While PyQt does handle this, we should still provide callbacks following the expected signature. I came across this while testing with PySide (which is less forgiving).
I chose to set the parameter to `*argc`  here, as we don't care about the actually passed parameter.

Fixed callback for click signal in CAATypesSelectorDialog

---

picard/ui/edittagdialog.py
picard/ui/metadatabox.py
test/test_metadatabox.py

Metadatabox cleanup

---

picard/coverart/__init__.py
picard/coverart/image.py
picard/coverart/processing/__init__.py
picard/coverart/processing/filters.py
picard/coverart/providers/caa.py
picard/extension_points/cover_art_filters.py
picard/options.py
picard/ui/forms/ui_options_cover_processing.py
picard/ui/forms/ui_provider_options_caa.py
picard/ui/options/cover_processing.py
picard/ui/options/dialog.py
test/test_coverart_processing.py
test/test_coverartprovider_caa.py
ui/options_cover_processing.ui
ui/provider_options_caa.ui

* This is a…
Adds a setting to discard downloaded cover art images if they are below a given width and height.
* JIRA ticket (_optional_): PICARD-2926
The options page looks like this:
I plan to add settings for resizing and converting formats also to this page.
I created an extension point for adding image filters. I'm aware this is bound to change for Picard 3, but I was thinking that I can use this for now, until the new plugin apis are defined, and change it later in the last couple of weeks of gsoc.
I'm still working on adding another extension point for filtering functions that use the image metadata, since outsidecontext suggested I should add a way for providers to filter images before actually downloading them, if they can.
Additional …

PICARD-2926: Add option to filter out images below a given size

---

picard/ui/coverartbox.py

* This is a…
`MetadataItem.suspend_metadata_images_update` is a context since #2500 and must not be assigned directly.
If metadata update notifications should be disabled for a list of objects use a ` contextlib.ExitStack` to handle holding and freeing the context for all of them.

Fix suspend_metadata_images_update being assigned to in CoverArtBox

---

picard/coverart/image.py
picard/coverart/processing/__init__.py
picard/ui/infodialog.py
test/test_coverart_processing.py

* This is a…
Now the table looks like this:
(Both embedding images to tags and saving to external file)
(Same as above but with no pre-existing cover art)
(Saving only to an external file, not embedding to tags)
I modified the `run_image_processors` function so that the tags and file queues run only if their result is actually used to either embed into tags or save to external file.
Also now the external `CoverArtImage` object is created only if the option to save to an external file is selected. This way it's not shown in the `infodialog`, so the resulting table in this case is the same as before.

Add new column for external images to artwork infodialog

---

picard/track.py
test/test_taggenrefilter.py
test/test_track.py

* This is a…
* JIRA ticket (_optional_): PICARD-2935
The genre filter options can give unexpected results, where less genres are used then the maximum number of genres configured, even though more genres are available that would match the criteria. There are two distinct issues:
1. The genre list is reduced to the maximum allowed number of items before filters are applied.
2. The max. count (used to filter out genres by minusage threshold) is taken over the entire list. It better should ignore filtered out genres.
**Examples case 1:**
You have the following tags with counts:<br>
Pop: 5, Blues: 7, Rock: 5, Psychedelic: 4
You have a filter "-pop"<br>
Number of genres is limited to max. 3.
Picard takes the first most used tags (Blues, Pop, Rock), …

PICARD-2935: apply genre filters and threshold before selecting minimal usage

---

picard/coverart/image.py

* This is a…
* JIRA ticket (_optional_): PICARD-2918
This backports the fix from #2505 to the Picard 2.x branch.

PICARD-2918: avoid exception if hash isn't found in _datafiles on exit (2.x)

---

picard/coverart/providers/caa.py
picard/ui/caa_types_selector.py

* This is a…
* **Describe this change in 1-2 sentences**: This change allows the default instructions text to be overridden in the CAA Types Selector dialog.  This allows the dialog to be used in other cases such as the new cover art processing settings.
The original CAA Types Selector dialog has fixed instructions, and as such cannot be reused for other (similar) cases.
This change allows the default instructions text to be overridden in the CAA Types Selector dialog.  This allows the dialog to be used in other cases such as the new cover art processing settings.

Update caa types selector to allow replacement instructions text

---

picard/track.py
test/test_taggenrefilter.py

* This is a…
* JIRA ticket (_optional_): PICARD-2939
`TagGenreFilter.filter` raises an exception if the filtering leads to an empty genre list.
Return an empty result if the filtered list is empty.

PICARD-2939: Fix exception when genre filtering results in empty genre list

---

picard/metadata.py

* This is a…
* **Describe this change in 1-2 sentences**: Change `Metadata.__iter__` implementation in `metadata.py` to acquire and hold the lock for the full lifetime of the iterator (until it is exhausted or falls out of scope).
Previously the lock was being acquired and then released immediately when the iterator was returned. This meant that when the iterator was being iterated by the consumer, the lock was not held.
* JIRA ticket (_optional_): PICARD-2940
This change ensures that the lock is held until the iterator is exhausted or goes out of scope.
This change makes the behavior equivalent to the iterator returned by the `Metadata.items` method.
See PICARD-2940 for further info.

PICARD-2940: Fix prematurely releasing lock in `Metadata.__iter__`

---

picard/album.py
picard/cluster.py
picard/coverart/image.py
picard/file.py
picard/item.py
picard/track.py
picard/ui/itemviews/columns.py

* This is a…
Adds a column to display front image dimension to the basetreeview
* JIRA ticket (_optional_): PICARD-2122
I liked the reporter's idea to add an optional column, instead of showing the dimensions under the cover art box. This is what it looks like:
These are the tags front image dimensions.
I think this can be useful for people who are resizing cover art to check everything went right, rather than clicking "show more info" on each album individually.

PICARD-2122: Display cover dimensions in an optional column

---

picard/i18n.py
test/test_i18n.py

* This is a…
* JIRA ticket (_optional_): PICARD-2953, PICARD-2955
On Windows `QCollator.sortKey` is broken and results of wrong ordering of numbers, both in numeric and normal alphabetic mode.
This results in both the below conditions failing unexpectedly:
```python
assert(i18n.sort_key("1") < i18n.sort_key("C"))
assert(i18n.sort_key("99", numeric=True) < i18n.sort_key("100", numeric=True))
```
See also [QTBUG-128170](https://bugreports.qt.io/browse/QTBUG-128170).
Use `locale.strxfrm` for sorting on Windows again. We replaced this with `QCollator` in PICARD-2914 due to `strxfrm` segfaulting on macOS frequently. But since we did not get the crashes on Windows it seems safe to move back to strxfrm for Windows again.

PICARD-2953: Use strxfrm for sorting on Windows again

---

picard/ui/itemviews.py

* This is a…
* JIRA ticket (_optional_): PICARD-2958
Calling _("") causes gettext to show the header of the PO file for the current locale. This causes the tooltip for unmatched files to show this header.
Only affects the 2.x branch, master is fine.
Call `_()`  explicitly for each item. This code is similar to what is currently in the master branch

PICARD-2958: Fix PO file header showing up as file tooltip

---

picard/i18n.py
test/test_i18n.py

* This is a…
* JIRA ticket (_optional_): PICARD-2958
Calling gettext("") by default returns the header of the PO file for the current locale. This is unexpected. Return an empty string instead.
While PICARD-2958 effectively only happens on the 2.x branch due to recent refactorings of itemviews, the behavior of gettext itself is unexpected and can easily cause similar issues.
Update the gettext wrapper to return an empty string if the input was an empty string.

PICARD-2958: Handle gettext being called with empty string

---

picard/__init__.py
picard/config_upgrade.py
picard/ui/options/renaming_compat.py
test/test_config_upgrade.py

* This is a…
* JIRA ticket (_optional_): PICARD-2960
It must not be possible to configure the replacement for directory separators to be a separator itself.
Add a validator to the dir separator option input to disallow `os.sep` and `os.altsep`. Also validate on form close. While theoretically users can no longer configure this it can happen on upgrade and also when moving config from a platform without `os.altsep`  (e.g. Linux) to one with (Windows where altsep is a backslash), or in general if separators differ between platforms.

PICARD-2960: Prevent dir separator replacement being set to dir separator

---

picard/__init__.py
picard/config_upgrade.py
picard/ui/options/renaming_compat.py
test/test_config_upgrade.py

* This is a…
* JIRA ticket (_optional_): PICARD-2960
Same as https://github.com/metabrainz/picard/pull/2541 , but backported to 2.x branch.

PICARD-2960: Prevent dir separator replacement being set to dir separator (2.x backport)

---

picard/ui/mainwindow/__init__.py
picard/ui/scripteditor.py

* This is a…
* JIRA ticket (_optional_): PICARD-2989
The `ScriptEditorDialog` uses `SettingsOverride` for locally changed settings. On repeated example file updates the `SettingsOverride` would recursively reference itself. As there are many example updates on selection change this could lead to a deep recursion depth until max recursion would trigger an error. 
Fix SettingsOverride always referencing base settings only.
Also avoid example update calls if the script editor dialog is not visible. The edittor will update anyway once it becomes visible or gains focus.

PICARD-2989: fix settings override recursion

---

test/picardtestcase.py
test/test_debug_opt.py
test/test_mbjson.py
test/test_metadata.py
test/test_plugins.py

I reviewed the code and checked all `setUp()` and `tearDown()` definitions, some were missing parent method call, and some were useless.
* This is a…
Related to https://github.com/metabrainz/picard/pull/2547

Add missing unittest setup calls

---

.github/workflows/package-macos.yml
.github/workflows/package-pypi.yml
.github/workflows/run-tests.yml

* This is a…
Github deprectaed the macos-12 package since 2024-10-07 and will fully remove it on 2024-12-03. Use macos-13 instead.

CI: Replace deprectaed macos-12 image with macos-13

---

.github/workflows/package-pypi.yml
.github/workflows/package.yml
.github/workflows/run-tests.yml

* This is a…
Github deprectaed the macos-12 package since 2024-10-07 and will fully remove it on 2024-12-03. Use macos-13 instead.
This is for the 2.x branch.

CI: Replace deprecated macos-12 image with macos-13 (2.13)

---

picard/ui/scripteditor.py
picard/util/filenaming.py

* This is a…
* JIRA ticket (_optional_): PICARD-2991
`make_short_filename` runs `_get_filename_limit` on the basedir, which in turn tries to get filename limits by calling `statvfs`. `statvfs` can fail with `FileNotFoundError` or `PermissionError`.
To reproduce:
- In Options > File naming set the target dir to something on which `os.statvfs` fails. On my Linux system this is e.g. `/run/user/1000/doc`
- Save options and reopen the options dialog
=> File naming failed to load, exception is logged
1. If in `_get_filename_limit` the call to `os.statvfs` fails, retry on the parent path
2. Do not fail to load the options dialog on `FileNotFoundError` or `PermissionError` when updating the examples

PICARD-2991: Handle statvfs errors on file rename

---

picard/browser/browser.py
picard/oauth.py
picard/tagger.py
picard/ui/options/general.py
test/test_oauth.py

* This is a…
* JIRA ticket (_optional_): PICARD-2882, PICARD-736, PICARD-2886
This PR backports the OAuth improvements from the master branch to 2.x:
- PICARD-2882: Support OAuth2 PKCE (#2446)
- PICARD-736: OAuth2 login with local callback URL (#2451)
- PICARD-2886: OAuth2 token revocation (#2449)
This is in preparation of finishing the work to support the new MetaBrainz OAuth, which I will provide next and also backport to 2.x. The goal is to be able to make a 2.15 release to offer a release without deprecated MB login.

2.x OAuth improvements

---

setup.py

~~Dropped utf-8 compat line for Python 2.~~
Added 3.13 Python as explicitly supported.
~~Converted the file description to an appropriate docstring.~~
---
PR irrelevant side note - It would be nice if there could be a new release, as the lack of [this change](https://github.com/metabrainz/picard/commit/cbbf53dee4c7e0de201daddc096941a4c822d5fc) breaks installation for us.

Mark Python 3.13 as supported

---

picard/file.py
picard/util/__init__.py
test/test_file.py

* This is a…
* JIRA ticket (_optional_): PICARD-3013
Fix case-only renaming on case-insensitive filesystems. This broke when fixing PICARD-2076 (allow long filenames) in commit https://github.com/metabrainz/picard/commit/5037ce993551d739689095fbea323bcc4ac6c3f0#diff-8e9e6145ecc7e912b2d643f5064e6f196d3668bd010ffa6037775232c2aba236L520 .
Make calling `os.path.realpath` optional in `normpath`. It is not needed here if we assume the new filename does not exist and we want to move a file to a new name.
Generally keep calling of `os.path.realpath` enabled as standard, as in many cases we call `normpath` on existing paths

PICARD-3013: Fix case-only renaming on case-insensitive filesystems

---

.github/workflows/package-pypi.yml
.github/workflows/run-tests.yml
INSTALL.md
picard/util/webbrowser2.py
requirements.txt
setup.py

* This is a…
Python 3.7 is no longer supported on our build pipeline. Given that 3.8 has reached EOL it makes sense to at least drop 3.7 support now also on the 2.x branch.

2.x drop python 3.7

---

picard/ui/scriptsmenu.py

* This is a…
When manually running scripts by right-clicking on a file and choosing "Run Scripts", Picard crashes. I could not find a JIRA ticket.
Initialised the `tagger` field in the `ScriptsMenu` class.

Fix run scripts manually

---

picard/formats/id3.py
test/formats/test_id3.py

* This is a…
When saving an ID3 file with LRC synced lyrics, it only accepted a very narrow definition of timestamps (two-digit minutes, two-digit seconds, and three-digit milliseconds). While this is fine for preserving the field (as in PICARD-1092), some plugins may import or download LRCs with different timestamps, and people can edit the field manually and change as well.
No JIRA ticket was open for this problem, and there was no LRC support at all in the previous release.
I changed the regular expressions that are used for LRC decoding (`ID3File.__lrc_*_re_parse`), and the corresponding timestamp parsing at `ID3File._parse_lrc_text`. I also added new test cases for the new timestamps.

Support more LRC timestamps

---

.github/workflows/package-macos.yml
.github/workflows/package-pypi.yml
.github/workflows/package-windows.yml
.github/workflows/package.yml
.github/workflows/run-tests.yml
.github/workflows/validate-xdg-metadata.yml
picard/log.py
picard/util/__init__.py
requirements-build.txt
test/test_log.py
test/test_utils.py

* This is a…
Test with Python 3.13 in CI builds, package for Windows and macOS using Python 3.13
This also contains a fix for PICARD-3016 to fix relative plugin path logging on Windows. This being broken was already the case, but now exposed by the CI tests failing with Python 3.13 due to differences in absolute path handling.

Run CI tests and package builds with Python 3.13

---

picard/config.py
test/test_config.py

* This is a…
* **Describe this change in 1-2 sentences**:  Adds a signal when file naming related settings are changed
File naming related settings can be changed in a number of places, and there is no consolidated way to capture whether a setting has been changed.  Something like this is required for https://github.com/metabrainz/picard/pull/2563
This PR adds a signal to the config settings class to determine when a file naming related setting has been updated.

Add signal when file naming related settings are changed

---

picard/ui/metadatabox.py
picard/util/tags.py

* This is a…
Adding File Path to metadata view
* JIRA ticket (_optional_): PICARD-2025
* JIRA ticket to update documentation: PICARD-3017
Add a Path tag in the metadatabox for a single file (for efficiency reasons) with original value from `file.filename`, new value from `file.make_filename` only when `move_files` or `rename_files` is enabled.

PICARD-2025: Add file path to metadatabox

---

picard/i18n.py
test/test_i18n.py

* This is a…
* JIRA ticket (_optional_): PICARD-3014
Sorting on macOS is failing to sort empty string properly. This issue was introduced by PICARD-2914, but PICARD-2914 specifically was addressing macOS crashes with collation functions and hence cannot be reverted.
This applies the workaround of treating empty string as a single space.

PICARD-3014: Fix macOS not sorting empty values before other entries

---

picard/config.py
picard/ui/mainwindow/__init__.py
picard/ui/metadatabox.py
picard/ui/options/renaming.py
picard/ui/options/tags.py
test/test_config.py

* This is a…
This makes use of @rdswift's recent settings changed signal (#2567) to handle updating the filenaming toggles in Options menu
There are additionally issues with the profiles. When switching profiles via menu the toggles don't update accordingly. This issue is also present on the current 2.x release.
I started looking into this, but encountered additional profile issues on the master branch:
1. Profile specific settings are not available directly after startup, hence the toggles don't show the settings properly. The profile groups are only properly initialized after the option dialog has been opened the first time. This is due to #2433 moving the initialization of profile groups to the option pages constructors.
2. When opening the …

Use settings changed signal to update file move / rename toggles

---

picard/album.py
picard/item.py
picard/mbjson.py
picard/track.py
test/test_mbjson.py

* This is a…
Adds a custom field for folksonomy tags and genre.
There was no custom field for folksonomy tags. User was forced to either set all genre as genre tags or all folksonomy tags as Genre. 
This PR aims to resolve it by introducing two new tags _folksonomy_tag and _genre.  
* JIRA ticket (_optional_): PICARD-2607
To get both _genres and _folksonomy tags from the MusicBrainz server, I removed the 'use_folksonomy` check in picard/items.py and stored the tags in respective variables. Then for writing the metadata, I added two new functions in picard/track.py that would update the metadata with _genre and _folksonomy_tag. And before writing genre into the file, check whether genre should be set to _folksonomy_tag or _genre itself.   
Check …

PICARD-2607: Add a “_genre” variable

---

picard/config.py
picard/extension_points/options_pages.py
picard/options.py
picard/ui/mainwindow/__init__.py
picard/ui/options/__init__.py
picard/ui/options/advanced.py
picard/ui/options/cdlookup.py
picard/ui/options/cover.py
picard/ui/options/cover_processing.py
picard/ui/options/fingerprinting.py
picard/ui/options/general.py
picard/ui/options/genres.py
picard/ui/options/interface.py
picard/ui/options/interface_colors.py
picard/ui/options/interface_toolbar.py
picard/ui/options/interface_top_tags.py
picard/ui/options/maintenance.py
picard/ui/options/matching.py
picard/ui/options/metadata.py
picard/ui/options/network.py
picard/ui/options/ratings.py
picard/ui/options/releases.py
picard/ui/options/renaming.py
picard/ui/options/renaming_compat.py
picard/ui/options/scripting.py
picard/ui/options/tags.py
picard/ui/options/tags_compatibility_aac.py
picard/ui/options/tags_compatibility_ac3.py
picard/ui/options/tags_compatibility_id3.py
picard/ui/options/tags_compatibility_wave.py

* This is a…
* JIRA ticket (_optional_): PICARD-3019
This addresses several issues with option profiles.
1. PICARD-3019: Changing profile using the menu is not persisted and does not update the other quick setting toggles in the Option menu. This issue is also present in the current release version 2.13.3.
2. Option profiles are not initialized properly on startup until the Options dialog got opened the first time, as settings being part of profiles are registered late in the profile page constructors since https://github.com/metabrainz/picard/pull/2433
See also comment in https://github.com/metabrainz/picard/pull/2569
1. The first issue is addressed by generalizing the the new `setting_changed` signal and using it to listen to profile changes. …

Fix option profiles

---

picard/ui/metadatabox.py

* This is a…
* JIRA ticket (_optional_): PICARD-3021
Add the ability to merge new and old values of a tag in the metadatabox.
Add a context menu entry "Merge Original Values" that will combine the original and new values of selected tags into a single list. No duplicates are added.

PICARD-3021: Context menu action to merge original and new metadata values

---

picard/album.py
picard/track.py
test/test_item.py
test/test_track.py

* This is a…
* JIRA ticket (_optional_): PICARD-2607, PICARD-489
This is a follow up for #2545, which added the genre and folksonomy tags variables. During testing I found some issues with the behavior. The new variables were not properly created as hidden variables. Also the merging of variables from different levels was not applied consistently and setting the `genre` tag from the genre and folksonomy values was only fully applied on album reload.
- Save `~folksonomy_tags` and `~genres` as hidden variables
- Fix merging tags from different levels
- Fix excluding genre tags from `~folksonomy_tags`

Fix loading of folksonomy tags / genres

---

picard/ui/metadatabox.py

* This is a…
* JIRA ticket (_optional_): PICARD-3030
This refactors the change from PICARD-3021 to address a crash when selecting more then one changed tag in the metadatabox and then open the context menu.
Avoid the crash by implementing merge originals similar to the existing use originals.
Also refactor use original values a bit to reduce code duplication and harmonize the implementation of both merge and use originals.

PICARD-3030: Fix crash when merging original values for multiple tags

---

.github/workflows/package-windows.yml
scripts/package/win-build-fixes.ps1

* This is a…
* JIRA ticket (_optional_): PICARD-3034
This fixes packaging issues on Windows, where system wide Qt and libssl related libraries would be loaded over the bundled ones.
This was originally fixed in PICARD-2736. But the change in PICARD-3002 moved the cleanup code to a separate helper script `win-build-fixes.ps1`, which was forgotten to be called.
Call `win-build-fixes.ps1`

PICARD-3034: Fix win-build-fixes.ps1 not being called

---

picard/formats/vorbis.py
test/formats/test_vorbis.py

* This is a…
libopus expects width, height and depth to all be zero or all be non-zero
As depth is not easily available, do not set width and height either

PICARD-2909: Do not write image width / height for Opus files

---

.github/workflows/package-macos.yml
picard.spec
scripts/package/macos-package-app.sh
scripts/package/macos-setup.sh

* This is a…
* JIRA ticket (_optional_): PICARD-2192
This is an alternative attempt to provide ARM64 packages for macOS. 
Instead of building a single universal2, as attempted in #2423, this builds two separate packages for the x86_64 and arm64 architectures.
The reason for now is that the PyQt6-Qt6 package is only available as separate packages as well. 
While it would be nicer to have a single package, this approach will solve PICARD-2192 as well. If we want to provide a combined package in the future there would be two approaches:
- Download the separate binary packages of PyQt6-Qt6 and have the individual dynamic libraries from each package combined in a single universal2 one by a script.
- Build Qt6 ourselves as part of the build pipeline.

PICARD-2192: For macOS build separate x86_64 and arm64 packages

---

picard/album.py
test/test_trackscache.py

Introduce TracksCache and simplify _match_files(), add test

---

picard/album.py

Refactor parse release

---

.github/workflows/package-pypi.yml
.github/workflows/run-tests.yml
INSTALL.md
RELEASING.md
scripts/package/run-sdist-test.sh
setup.py

* This is a…
Attempt to reduce the direct calls to `setup.py`.
Remove `setup.py test` completely and replace the calls with `pytest`.
Build sdist / bdist packages with `python -m build`.
**Note:** As a side effect this removes the source builds in zip format, as PEP 517 only specifies .tar.gz as format. Do we need the zip source distribution? I think with public availability of the source in git and wide availability of extraction tools for .tar.gz even on Windows this is not really needed.
If we want to provide it we could add a CI step to also create a zip file.

Use pytest and PEP 517 build

---

.github/workflows/run-tests.yml
org.musicbrainz.Picard.appdata.xml.in
pyproject.toml
setup.py

* This is a…
This is one step in the goal to nove package metadata into `pyproject.toml` and reduce code in `setup.py`.
- Define `[project]` section in `pyproject.toml` and declare package metadata there. Remove the corresponding data from `setup.py`
- Remove obsolete code from `setup.py`
- Define setuptools package and extension in `pyproject.toml` and remove custom code from `setup.py`
- Unified the short app description to be the same in Python package metadata and appstream metadata.
Not handled here:
- Requirements are still defined in `requirements.txt` and read from there. This can be changed once we move to e.g. ruff
- Entry points: This is currently highly system dependent and for now handled dynamically by `setup.py`.
- Data files: …

Pyproject metadata

---

scripts/package/constants.py.in
setup.py

* This is a…
Reduce code redundancy in setup.py update_constants command.

Reduce code redundancy in setup.py update_constants command

---

.github/workflows/run-tests.yml
.gitignore
INSTALL.md
picard.spec
picard/tagger.py
pyproject.toml
scripts/picard.in
setup.py
tagger.py.in
test/test_i18n.py

* This is a…
* JIRA ticket (_optional_): PICARD-2003
If picard got installed by `pip install picard` the translations where unavailable. That is because the locale files got included as a data files outside the package folder, and there is no default way to get this data folder.
This PR ensures locales are available also in pip installs by moving the locale as data files into the picard package.
Move the locale directory holding the *.mo files into the picard package and include them as data files in the source package and wheel. Adjust the loading to use this locale dir by default.
This simplifies the code to build the locales, as there are no longer separate build target directories. This also removes the need to run `setup.py build_locales …

PICARD-2003: Include locales as package data inside the main package.

---

setup.py

* This is a…
* JIRA ticket (_optional_): PICARD-3003
When building Picard via PEP 517, e.g. by calling "python -m build", it is currently not possible to pass custom build parameters like `--disable-autoupdate`. This is due to setuptools not passing on `config_settings` to the build backend (otherwise something like `python -m build --wheel -C--disable-autoupdate` could work).
See also https://github.com/pypa/setuptools/issues/2491
As specifically `--disable-autoupdate` is an important option for distributions, allow setting this value via the environment variable `PICARD_DISABLE_AUTOUPDATE`. This will work now:
```
PICARD_DISABLE_AUTOUPDATE=1 python -m build
```
This is also something recommended in …

PICARD-3003: Disable autoupdate during build with PICARD_DISABLE_AUTOUPDATE

---

.github/workflows/package-windows.yml
pyproject.toml
scripts/package/macos-package-app.sh
setup.py

* This is a…
This fixes two issues in the PyPI packages recently introduced with #2588
1. Locales where not included in the wheel if building with e.g. "python -m build". As this is building in a clean environment the locales did not end up in the local source tree and where not used. Locales need to be put into the build-lib dir. For local source builds running `python setup.py build_locales` still works and writes the locales to `picard/locale` as expected.
2. On Windows setuptools complained that "gui-scripts" in pyproject.toml needs to be dynamic. As gui-scripts currently is only used on Windows this was not obvious during testing.

Packaging fixes

---

picard/ui/edittagdialog.py

- use a generator for modified tags and their non-empty values
- drop useless intermediate methods
* This is a…

Simplify modified tags cleanup when exiting the dialog

---

picard/ui/edittagdialog.py

The visual representation could differ from the underlying storage. This could cause index out of range exceptions. Also empty values were omitted in display, causing the wrong indexes to update when editing.
* This is a…
* JIRA ticket (_optional_): PICARD-3038
This change addresses crashes and editing issues in the edit tag dialog. Specifically this fixes two issues:
- When removing all values from a tag, then switching to another tag and back to the original, editing or removing the shown empty row causes an "index out of range" exception.
- When clearing values (empty value, but keeping the row, then switching to another tag and back to the original, editing would update the wrong indexes of the underlying stored data (because empty values …

PICARD-3038: Fix crashes and editing of wrong indexes in edit tag dialog

---

.github/workflows/package-macos.yml
.github/workflows/package.yml
scripts/package/macos-package-app.sh

* This is a…
* JIRA ticket (_optional_): PICARD-2192
Actually build on an arm64 runner. Previously the build pulled the x86_64 binaries for Qt6, which prevented the app to run. Also this way the code to test running the executable can be actually be run during build.
This also changes the install to use Python via actions/setup-python. This is consistent with other builds we have, and it fixes an issue with the system wide installation specifically on ARM refusing to install PyPI packages.
The builds actually should use a venv, but that's another story :D

PICARD-2192: Fix macos arm builds

---

picard/ui/edittagdialog.py

* This is a…
The tag editor removes tags which are not standard and store only a single empty value from the tag selection list. But this does not take into account tags where all values have been removed or where there are multiple empty values (which still counts as an empty tag in the end).
Check if the tag values are fully empty. Also some more refactoring.

Fix empty tags being removed from tag selection

---

picard/ui/metadatabox/__init__.py

* This is a…
* JIRA ticket (_optional_): PICARD-3044
Always set the QTableWidgetItem flags, as items can be reused. If a previously readable QTableWidgetItem was reused the field meant to be readonly was suddenly writable.

PICARD-3044: Fix ~filepath sometimes being editable in metadata list

---

picard/ui/metadatabox/__init__.py
picard/util/__init__.py

* This is a…
Added exception handling for passing bad data to format_time()
Calls to `format_time()` can pass data that cannot be converted to a float, causing a crash.
* JIRA ticket: PICARD-3045
Wrapping
```ms = float(ms)```
With exception handling means that callers can pass non-numerical strings or unexpected datatypes without causing a crash

PICARD-3045: Fail safe if the parameter passed to format_time cannot be converted to a float

---

picard/util/__init__.py
test/test_utils.py

* This is a…
`format_time()` should only expect to work for positive numbers, however it currently handles negative values and returns negative times.
Raise a ValueError if the passed value is a negative.
Added function documentation and tests.

Ensure that format_time() only expects integer values for ms

---

picard/ui/metadatabox/__init__.py
picard/ui/metadatabox/tagdiff.py
test/test_tagdiff.py

* This is a…
`TagDiff` has a `tag_names` member to represent the order that the tags should be displayed. It has some quite involved logic about what order they should be sorted in, though it is deterministic based on the contents of `new` and `old` members of the `TagDiff`
Moved the ordering logic into the `TagDiff` class, so `MetaDataBox.updateTags()` populates the contents of the `TagDiff` and lets the `TagDiff` populate its `tag_names` member.
Added tests for this functionality.

Added utility function to update tag_names in TagDiff

---

picard/mbjson.py
test/data/ws_data/recording.json
test/data/ws_data/recording_multi_artists_1.json
test/data/ws_data/recording_multi_artists_2.json
test/data/ws_data/release.json
test/test_mbjson.py

* This is a…
* **Describe this change in 1-2 sentences**:  Add new artist country variables.
Changes have been made to the MusicBrainz webservice to include country information for all artists.  This is useful information that some users would like to be able to access from scripting within Picard.
* JIRA ticket (_optional_): PICARD-3054
Add the following new variables:
~~**\_albumartistcountry**: A string showing a unique list of the country codes for all album artists.  If a country code is not provided by the webservice the code "XX" will be used.  Examples are "GB" (where all artists are from Great Britain), "GB & US" (where one or more artists are from Great Britain and one or more artists are from the United States), or "GB, US & XX" (where one or more artists are from Great …

PICARD-3054: Add new artist country variables

---

picard/formats/mp4.py
test/formats/test_mp4.py

* This is a…  
* **Description (1-2 sentences):**  
A change has been applied to `mp4.py`, ensuring that `_casemap` is checked before applying pre-mappings. This prevents duplicate tags from being saved in the file.  
---  
Although `_casemap` correctly stores the capitalization of a tag when loading, an issue arises if a stored tag (e.g., `----:com.apple.iTunes:Label`) shares the same internal Picard tag as one of the pre-mapped cases (e.g., `label`). In such cases, the internal tag would be converted to the pre-mapped format (e.g., `----:com.apple.iTunes:LABEL`) when saving. This leads to duplicate tags in the saved file.  
* JIRA ticket (_optional_): [PICARD-3029](https://tickets.metabrainz.org/projects/PICARD/issues/PICARD-3029)  
---  
The fix prioritizes maintaining the original tag …

PICARD-3029: Incorrect mapping of case-variant tags in MP4 files

---

picard/ui/widgets/scripttextedit.py

* This is a…
* **Describe this change in 1-2 sentences**:  Adds the new `%_albumartists_countries%` and `%_artists_countries%` variables to the script editor autocomplete list.
Two new variables `%_albumartists_countries%` and `%_artists_countries%` were added in https://github.com/metabrainz/picard/pull/2627 but were not added to the script editor autocomplete list at that time (because I forgot).
This change adds the new `%_albumartists_countries%` and `%_artists_countries%` variables to the script editor autocomplete list.
None.

Add new `_*artists_countries` variables to autocomplete list.

---

picard/ui/widgets/scripttextedit.py
picard/util/tags.py

Suggested by @phw in https://github.com/metabrainz/picard/pull/2633#pullrequestreview-2767012696
* This is a…

Move EXTRA_VARIABLES to picard/util/tags.py

---

picard/file.py
picard/metadata.py
picard/ui/metadatabox/edittagdialog.py
picard/ui/widgets/scripttextedit.py
picard/ui/widgets/taglisteditor.py
picard/util/tags.py
test/formats/common.py
test/test_file.py
test/test_metadata.py
test/test_util_tags.py

Introduce TagVar & TagVars classes

---

picard/ui/widgets/scripttextedit.py

Script completer minor refactoring

---

picard/const/__init__.py
picard/options.py
picard/profile.py
picard/ui/metadatabox/__init__.py
picard/ui/widgets/scripttextedit.py
picard/util/tags.py
test/test_config.py
test/test_options.py
test/test_profiles.py
test/test_util_tags.py

* This is a…
* **Describe this change in 1-2 sentences**:  Add tooltip descriptions to `PRESERVED_TAGS` and `EXTRA_VARIABLES`
The tooltips shown for the tags and variables in the script editor only showed information for the `TAG_NAMES`.  There were no tooltip descriptions for `PRESERVED_TAGS` and `EXTRA_VARIABLES`.
* JIRA ticket (_optional_): PICARD-3061
Add tooltip descriptions to `PRESERVED_TAGS` and `EXTRA_VARIABLES`.  Add test for tooltips on tags and variables.
Since this change will result in some new and changed string for translation, please review the new and existing tag description strings to ensure that any desired changes are captured prior to merging this PR.

PICARD-3061: Add long descriptions to tags, display them in tooltips

---

picard/formats/id3.py

* This is a…
* JIRA ticket (_optional_): PICARD-3064
After recent refactorings the ID3File class overwrote the File._save_images method, triggering an exception on saving.
The issue was introduced in c36e4a47b66235d2ce4e4bd76a9017a19b564152
Rename `ID3File._save_images` to `ID3File._save_images_to_tags`.

PICARD-3064: Fix ID3File hiding File._save_images

---

picard/ui/scripteditor/__init__.py
picard/ui/widgets/scriptdocumentation.py
picard/util/tags.py
test/test_util_tags.py

* This is a…
* **Describe this change in 1-2 sentences**:  Adds tag and variable documentation to the script editors help system
The script editors (Options > Script and File Naming Script Editor) both provide help documentation regarding available functions (one through a new window and the other as a sidebar).  The available tags and variables help should be added to this.
* JIRA ticket (_optional_): PICARD-3062
Add the full descriptions for the tags and variables to a new panel in the existing help display widget, and provide a button to toggle between the function help and the tags help.
Consider adding a section to the Picard User Guide showing the File Naming Script Editor and how it is used.

PICARD-3062: Add tag documentation to script editor help

---

picard/ui/theme.py

* This is a…
* JIRA ticket (_optional_): PICARD-3066
There are actually two changes in this PR:
1. The first commit is a straight forward fix to the theme being initialized too late since https://github.com/metabrainz/picard/commit/a2dd9df9ee75332958ed63e65ae90eaba31f7c4d . This is fixed by moving the theme setup as early as possible, but after all logging setup.
2. It attempts to have a solution for the link color in dark mode not being readable on Linux on some systems. The color in this case is system defined, so results varies. This change assumes the color for highlighting active UI elements is a good choice as the accent color (because if there was such an accent color defined by the system it would be used as the highlight color).
The …

PICARD-3066: Fix theme initialization and set generic accent color in dark mode

---

picard/script/functions.py
test/test_script.py

* picard/script/functions.py (rsearch): When the first group exists but is None, return the whole match instead.
* This is a…
PICARD-3065
When the pattern has a group, but does not match it, like `foo|(bar)`, `rsearch` will return `None`, even though it should really return `"foo"`.  This is because the current code only catches the situation where a capture group does not exist at all.
If the capture group has not been matched, return the whole match instead.

PICARD-3065: Don't return None in `rsearch` when capture group does not match

---

picard/tagger.py
picard/ui/coverartbox.py

* This is a…
* JIRA ticket (_optional_): PICARD-3506
The file chooser dialogs for local cover art and ripper log don't set the selectable files. Specifically on macOS this leads to directories being selectable. For cover art this can lead to a crash, and generally it is not useful.
This PR fixes the issue for the 2.x branch. Due to recent refactorings there will be a slightly different PR for the master branch.
See also the previous attempt at #2631
- For cover art selection set the file mode to `FileMode.ExistingFiles`. Handle opening multiple images files at once.
- For ripper log selection set the file mode to `FileMode.ExistingFile` (single file).

PICARD-3056: Disallow selection of directories for cover art and ripper log file chooser (2.x)

---

picard/tagger.py
picard/ui/coverartbox/__init__.py

* This is a…
* JIRA ticket (_optional_): PICARD-3056
The file chooser dialogs for local cover art and ripper log don't set the selectable files. Specifically on macOS this leads to directories being selectable. For cover art this can lead to a crash, and generally it is not useful.
This PR fixes the issue for the 3.x branch. This is the changes from the previous attempt in #2631 again, but extended to the ripper log case as well. I reviewed the code and think the approach is correct. Other than in the 2.x branch we now have a generic `FileDialog` subclass of `QFileDialog`. But setting the file mode still needs to be done depending on the specific use case.
- For cover art selection set the file mode to `FileMode.ExistingFiles`. Handle opening …

PICARD-3056: Disallow selection of directories for cover art and ripper log file chooser

---

.github/workflows/package-pypi.yml
.github/workflows/run-tests.yml
INSTALL.md
picard/log.py
picard/pluginmanager.py
picard/util/pipe.py
pyproject.toml
requirements.txt
setup.py

* This is a…
* JIRA ticket (_optional_): PICARD-2784
As Python 3.9 both approaches its EOL and we get into trouble with some newer dependencies which already drop support for it in the plugins-v3 branch, this PR increases the minimum Python version to 3.10.
- Make Python 3.10 the minimum required Python version
- Update tests
- Mutagen 1.43 is now the lowest supported version, as older versions are not Python 3.10 compatible
- Drop Python 3.9 legacy code

PICARD-2784: Drop python 3.9

---

picard/extension_points/__init__.py
picard/plugin.py
picard/pluginmanager.py
test/test_plugins.py

* This is a…
This moves the `ExtensionPoint` class and related code into the new `extension_points` package (see PR 
#2461 and related).
As extension points will be reused in v3 plugins this makes the code better separated. I pulled this change out from my current WIP of implementing the CLI for plugin management (PR coming soon).

Move ExtensionPoint and related code to extension_points package

---

picard/__init__.py
picard/config_upgrade.py
picard/mbjson.py
picard/options.py
picard/ui/forms/ui_options_metadata.py
picard/ui/options/metadata.py
test/test_mbjson.py
test/test_metadata.py
ui/options_metadata.ui

* This is a…
PICARD-1354 added an option to use standardized credit attributes for both instruments and vocals or to use no standardization at all.
I would like to standardize instrument credits, but keep vocals as credited because the vocal credit is often used to name roles of actors in audio dramas and operas.
* JIRA ticket (_optional_): PICARD-2828
- Introduce a new boolean option (checkbox) `standardize_vocals` in all places where `standardize_instruments` appears.
- The old option affects only instrument credits from now on, while the new option does the same for vocal credits independently.

PICARD-2828: Separate options for standardized instrument/vocal credits

---

picard/options.py
picard/ui/filter.py
picard/ui/itemviews/basetreeview.py
test/test_ui_filter.py

* This is a…
* **Describe this change in 1-2 sentences**:  Suggested improvements to the newly added metadata filtering system.
The newly added metadata filtering system provides some unexpected results.
This PR proposes some changes as follows:
1. **Add Persistent Settings**:
- Add persistent settings for selected filters, so that the settings are retained between sessions.
2. **Filter Logic Changes**:
- Return True if no filters selected or no filter text entered.
- Return True if no tags are found for selected filters.
- Return True if tag found in selected filters and filter text in tag value.
- Return False if one or more tags found in selected filters and filter text not in any values of the tags found.
3. **Add Master Selection Checkbox**:
- …

Filter feature proposed changes

---

picard/util/filenaming.py
test/test_util_filenaming.py

* This is a…
* JIRA ticket (_optional_): PICARD-3081
Forbidden names like NUL are replaced with a trailing underscore. Add a new replace_windows_forbidden_names utility function. Call it as part of make_save_path in win_compat mode.

PICARD-3081: Replace forbidden filenames for Windows

---

picard/browser/server.py
test/test_browser.py

* This is a…
This is a fix for potential HTTP Response Splitting, as the Access-Control-Allow-Origin was set from incoming data. In practice this was not a vulnerability, though. For one this data was read from HTTP headers and cannot contain line breaks. But also origins are validated against a known list of valid hostnames.
Fixes security code scanning alerts #2591 and #2592
Introduce a new "clean_header" function that removes new lines and colons from the supplied value.

Sanitize HTTP header values in browser integration

---

picard/ui/theme.py
picard/ui/theme_detect.py
test/test_theme.py

* This is a…
* **Describe this change in 1-2 sentences**:  
This change ensures that Picard correctly detects and applies the system dark mode on Linux when the “System” UI theme is selected, supporting multiple desktop environments and providing comprehensive tests.
Picard did not honor the system’s dark mode setting on Linux when the “System” theme was selected, especially if Qt’s platform theme integration was missing or incomplete. This led to inconsistent user experience for users with dark system themes on GNOME, KDE, XFCE, LXQt, and similar environments.
* JIRA ticket (_optional_): [PICARD-2300](https://tickets.metabrainz.org/browse/PICARD-2300)
- Refactored dark mode detection logic into a dedicated module using the Strategy Pattern.
- Added support for detecting dark mode on …

PICARD-2300: Linux dark theme detection

---

INSTALL.md

* This is a…
* **Describe this change in 1-2 sentences**: Updates INSTALL.md to reflect modern tooling changes from CONTRIBUTING.md, incorporating uv as an optional package manager and improving cross-platform installation instructions.
The INSTALL.md file was outdated and didn't reflect the modern development workflow using uv that was recently added to CONTRIBUTING.md. Users needed updated installation instructions that accommodate both traditional pip workflows and the new uv tooling.
- Added platform-specific gettext installation instructions for Windows, Linux, and macOS
- Introduced uv as an optional but recommended package manager alongside pip
- Added dedicated "Installation using uv" section with proper virtual environment setup
- Updated …

Update INSTALL.md with new tooling and instructions

---

picard/ui/metadatabox/__init__.py

* This is a…
There is a comma missing between items in the `settings_to_watch` set in the `MetadataBox:_on_setting_changed()` method.
Add the missing comma.

Add missing comma

---

.github/workflows/lint.yml
picard/tags/__init__.py
picard/tags/preserved.py
picard/tags/tagvar.py

* This is a…
* Added a CI step to run `ruff format --check` and aligned `ruff-action` to use the Ruff version from `pyproject.toml` by removing `version: "latest"`.
* CI did not enforce code formatting, and pinning `ruff-action` to `latest` could diverge from the repo’s configured Ruff version.
* JIRA ticket (optional): PICARD-XXX
* Add `ruff format --check` to `.github/workflows/lint.yml`.
* Remove `version: "latest"` so `ruff-action` uses the version defined in `pyproject.toml`.  see: https://github.com/astral-sh/ruff-action?tab=readme-ov-file#install-specific-versions
* Ran `ruff format` on the repo, causing changes in `picard/tags/__init__.py`, `picard/tags/preserved.py`, `picard/tags/tagvar.py`.

Run `ruff format` and add ruff format check ci workflow

---

picard/album.py
picard/ui/itemviews/__init__.py
picard/ui/itemviews/basetreeview.py
picard/ui/itemviews/columns.py
picard/ui/itemviews/match_quality_column.py
test/test_album_loading_sorting.py
test/test_itemviews_columns_split.py
test/test_itemviews_match_quality.py

* This is a…
* **Describe this change in 1-2 sentences**: Adds a new "Match Quality" column to the album view that displays match statistics using visual icons and text, showing matched/total tracks, missing tracks, duplicates, and extra files.
* JIRA ticket (_optional_): PICARD-442
Users need a quick visual way to assess the quality of their file-to-track matches in albums. Currently, users must manually inspect each track to understand match status, which is time-consuming and error-prone.
- Added `MatchQualityColumn` class that displays match statistics at the album level
- Implemented custom delegate (`MatchQualityColumnDelegate`) for rendering icons and text
- Column shows format: "matched/total; missing; duplicates; extra; unmatched"
- Uses existing match icons from FileItem for …

PICARD-442: Add match quality column and allow sorting

---

.pre-commit-config.yaml

* This is a…
I personally find the pytest run on every commit a bit annoying. This makes every commit take quite some time, while I can easily run pytest on demand and do so during development anyway. I'd rather prefer to run pytest mandatorily pre-push.
This PR changes the pre-commit configuration to setup both a pre-commit and pre-push hook and run pytest only pre-push. All other tasks will be run both pre-commit and pre-push.
One needs to re-run `pre-commit install` to apply the changes.
This is now a push can look like with this config:
```
(picard) phw@bender ~/devel/musicbrainz/picard % git push phw
trim trailing whitespace.................................................Passed
fix end of …
```

Force pytest to run pre-push instead of pre-commit

---

picard/formats/id3.py
picard/ui/tagsfromfilenames.py
picard/util/cdrom.py
test/formats/test_id3.py
test/test_tagdiff.py

* This is a…
Explicitly set the "strict" parameter for builtin [zip()](https://docs.python.org/3/library/functions.html#zip). This parameter is available since Python 3.10, and Ruff wants it to be used in Python 3.10 mode. Which makes sense to explicitly state the behavior.
Since our current minimum supported version is also 3.10 we should also run Ruff in Python 3.10 mode.
Use strict=True for code we internally control. Use strict=False for external data, where we have no control over the input. Specifically for the case of reading `/proc/sys/dev/cdrom/info` on Linux the input should be equal amount of elements. But if it wouldn't be it would still be better to return all devices that had both entries.
For the ID3 SYLT case we could maybe also …

Explicitly set the "strict" parameter for builtin zip()

---

picard/ui/options/dialog.py
picard/ui/options/profiles.py

* This is a…
Option saving would fail when saving a new enabled profile with settings selected.  Steps to reproduce:
1. Remove all profiles and save the changes by clicking "Make It So!".
2. Re-open the option settings.  Confirm that there are no profiles.
3. Create a new profile with one or more profile settings selected.
4. Enable the new profile.
5. Close the option settings by clicking "Make It So!"
6. The operation will fail with a `KeyError` because the system is trying to save the values to a profile that has not yet been added to the config.settings.
* JIRA ticket (_optional_): PICARD-3109
Save the `profiles` page before any of the other option pages.  This will ensure that the proper profile keys are in place when the other option …

PICARD-3109: Add in missing profile when saving settings

---

picard/ui/enums.py
picard/ui/mainwindow/__init__.py
picard/ui/mainwindow/actions.py
test/test_ui_cover_quick_toggles.py

* This is a…
* Describe this change in 1-2 sentences:
Add two quick toggles to Options menu: “Save images to tags” and “Save images to files”, mirroring existing cover art settings for fast on/off control without opening Options.
Users frequently switch cover art saving behaviors (embed vs file) and want quick toggles akin to “Save Tags/Rename/Move” to avoid navigating the Options dialog.
* JIRA ticket (optional): PICARD-3011
- Add actions to `MainAction`: `ENABLE_SAVE_IMAGES_TO_TAGS`, `ENABLE_SAVE_IMAGES_TO_FILES`.
- Implement actions in `picard/ui/mainwindow/actions.py` and handlers in `picard/ui/mainwindow/__init__.py`.
- Insert both under “Save Tags” in Options menu and keep checked state synced with `save_images_to_tags` and `save_images_to_files`.
- Focused tests in …

PICARD-3011: Add ui quick toggles for cover art

---

picard/__init__.py
picard/config_upgrade.py
picard/ui/options/interface.py
picard/ui/theme.py
test/test_config_upgrade.py
test/test_theme.py
test/test_theme_stylehints.py

* This is a…
Added Qt6 style hints support to theme system and made appearance menu consistent across all platforms by enabling DEFAULT, LIGHT, and DARK themes everywhere except Haiku.
* JIRA ticket (_optional_): PICARD-2300
The theme system was inconsistent across platforms - Linux only had DEFAULT and SYSTEM themes while Windows/macOS had DEFAULT, LIGHT, and DARK. Qt6's style hints provide a better way to handle dark themes with automatic fallback to manual color application.
Added new style hints methods to `BaseTheme`:
- `_get_style_hints()`: Gets QGuiApplication.styleHints()
- `_set_color_scheme()`: Sets color scheme using style hints
- `_apply_dark_palette_colors()`: Manual dark color application
- `_apply_dark_theme_to_palette()`: Uses …

PICARD-2300: Add qt's stylehints to theme.py for a consistent exp. across platforms

---

po/uk.po

Hello!
This is a new pull request for Picard. The translated Ukrainian strings remain untranslated in the Picard application and need to be fixed. Screenshots are attached.
Thanks.

Translated Ukrainian strings not displayed in Picard

---

picard/ui/itemviews/__init__.py
picard/ui/itemviews/custom_columns/__init__.py
picard/ui/itemviews/custom_columns/column.py
picard/ui/itemviews/custom_columns/context.py
picard/ui/itemviews/custom_columns/factory.py
picard/ui/itemviews/custom_columns/protocols.py
picard/ui/itemviews/custom_columns/providers.py
picard/ui/itemviews/custom_columns/registry.py
picard/ui/itemviews/custom_columns/resolve.py
picard/ui/itemviews/custom_columns/script_provider.py
picard/ui/itemviews/custom_columns/shared.py
picard/ui/itemviews/custom_columns/sorting_adapters.py
test/test_custom_columns.py
test/test_custom_columns_context.py
test/test_custom_columns_sorting_adapters.py

- This is a…
- Describe this change in 1-2 sentences:
- Introduces a public API to define and register custom columns for File/Album views, including script-based columns, provider protocols, and extensible sorting adapters.
- JIRA ticket: PICARD-2103
- Users cannot add custom/computed columns; limited sorting and no script-backed values in the views.
- Added `picard.ui.itemviews.custom_columns` package:
- Protocols (`ColumnValueProvider`, `SortKeyProvider`), `CustomColumn` type.
- Factory helpers: `make_field_column`, `make_script_column`, `make_callable_column`, `make_transformed_column`.
- `registry` to register/unregister columns in File/Album views.
- Script evaluation (`ChainedValueProvider`) with caching/perf thresholds and album-loading cache avoidance.
- Context/resolver layers …

PICARD-2103: Add API for custom columns (field ref, scripts, transforms, etc.)

---

picard/const/defaults.py
picard/options.py

* This is a…
* JIRA ticket (_optional_): PICARD-150
This is extending #2668 to add default columns for the tree view filter. I found that starting with a blank config this filtering is confusing to use. Once you enable the filtering in the View menu it shows the search input. But entering text there doesn't do anything, unless you also select some columns to filter by.
I think we need some default, so filtering works by default for the common cases.
By default filter by album, title, albumartist and artist

PICARD-150: Set default filter columns for tree view filters

---

picard/plugin.py
picard/ui/options/dialog.py
picard/ui/options/plugin_execution_order.py
picard/ui/plugin_order_selector.py
picard/ui/ui_options_plugin_execution_order.py
picard/ui/widgets/orderabletableview.py
ui/options_plugin_execution_order.ui

* This is a…
* **Describe this change in 1-2 sentences**:  Adds ability for the user to set the execution order of metadata processing plugins.
Currently each plugin is registered with a priority (1-100) which sets the order of execution.  Most plugin authors (myself included) don't pay sufficient attention to this, which can result in plugins being executed in the wrong order, yielding undesired results.
This is the Picard v2.x version of the change related to PICARD-3104 which is marked for Picard v3 implementation.
I wasn't sure if we wanted to include this new functionality in the final release version of Picard 2.x, but even if we don't it can serve as a possible model for the Picard 3 implementation.
* JIRA ticket (_optional_): PICARD-3121
Provide a new dialog from the Options... > …

PICARD-3121: Allow user to set metadata processor plugin execution order
