metabrainz/picard

picard/cluster.py, picard/ui/infodialog.py, picard/ui/itemviews.py, picard/ui/mainwindow.py
The track list can be copied to MB release editor.
http://tickets.musicbrainz.org/browse/PICARD-680
=> Add Info dialog to clusters, showing track list

picard/ui/mainwindow.py
http://tickets.musicbrainz.org/browse/PICARD-267
=> PICARD-267: Adding descriptive tooltips

picard/mbxml.py
http://tickets.musicbrainz.org/browse/PICARD-730
=> PICARD-730: use credited as name in relationships if any

picard/cluster.py, picard/config.py, picard/coverart/__init__.py, picard/coverart/utils.py, picard/formats/apev2.py, picard/log.py, picard/tagger.py, picard/ui/collectionmenu.py, picard/ui/options/releases.py, picard/webservice.py, setup.py, test/test_textencoding.py
Minor changes, with the help of futurize --stage1
=> Improve python3 compatibility

picard/webservice.py
- get rid of XmlWebService._hosts list, create queues on the fly
- only emit tagger_stats_changed when needed
- recalculate number of pending requests based on actual queues, fix PICARD-751
- ensure replies are removed from from _active_requests dict in any case
- fix a minor issue where few first requests to an host could be sent without honouring delay
- do not store last request time for hosts having no delay set
=> Rework network requests queues and counting

picard/browser/filelookup.py, picard/ui/coverartbox.py
Fix [PICARD-746](http://tickets.musicbrainz.org/browse/PICARD-764)
=> Fix PICARD-746

INSTALL.txt, picard/tagger.py
http://tickets.musicbrainz.org/browse/PICARD-773
Try options `-d -reverse` and `-h`
=> Fix PICARD-773: use argparse instead of getopt and pass options to QtApplication

picard/browser/filelookup.py, picard/const/__init__.py, picard/ui/metadatabox.py
Option added to right click menu to allow for various entities to be searched via the MusicBrainz API and opened in default browser.
=> PICARD-756: Entities should be hyperlinked in Picard

picard/album.py
See [Track renumbering with pre-gap](http://forums.musicbrainz.org/viewtopic.php?id=6095) for discussion.
=>  PICARD-778: Fix pregap not included in absolute track counts

picard/__init__.py, picard/config.py, picard/config_upgrade.py
Conversion implemented  as an upgrade hook.
http://tickets.musicbrainz.org/browse/PICARD-794
=> Use Picard.ini file for config options on all platforms

resources/README.md
As suggested in [this comment](https://github.com/metabrainz/picard/pull/467#issuecomment-205404443).
=> Add readme for updating resources

picard/webservice.py
Related ticket: [#PICARD-814](http://tickets.musicbrainz.org/browse/PICARD-814).
=> Get encoded query from redirect url

picard/const/__init__.py
http://tickets.musicbrainz.org/browse/PICARD-818
=> Use https by default for external links

test/test_util_filenaming.py
Instead of hardcoding the value to 255, fetch the max filename length
from system limits.
Related: Docker limits max filename size to 242
=> Fetch max filename length from system for unix

.travis.yml, Dockerfile
Note: Related PR-510 to fix tests for docker
=> Dockerize the Travis build

picard/config_upgrade.py
I was testing the upgrade function, I'm sorry @zas that I didn't fix it before the merge.
=> Fix upgrade 1_4_0_dev6

picard/ui/metadatabox.py
=> Display shortcut keys in context menu

picard/tagger.py, picard/ui/options/general.py, picard/ui/ui_options_general.py, ui/options_general.ui
Reverts metabrainz/picard#533
PR #533 has a lot of bugs and I think it will be better to revert it and tag it as a WIP.
As discussed I would like to improve on it before it is merged.
Plus, I just noticed I commented the 'if' condition which activates auto clustering only if the setting option is checked. This might cause a lot of usability issues.
=> Revert "PICARD-226: Add option for auto-clustering new files"

INSTALL.txt, NEWS.txt, setup.py
As agreed on in #metabrainz on Freenode IRC.
=> Bump required Python version to 2.7.

picard/ui/options/dialog.py
[PICARD-907](https://tickets.metabrainz.org/browse/PICARD-907)
=> PICARD-907: Broken restore defaults for a particular option page

picard/file.py, picard/formats/__init__.py, picard/formats/mp4.py, picard/ui/options/about.py
https://tickets.metabrainz.org/browse/PICARD-885
=> PICARD-885: Remove unsupported MPEG4 files from tagger

picard/file.py, test/test_formats.py
https://tickets.metabrainz.org/browse/PICARD-357
=> PICARD-357: Fix the way Picard handles filenames with only extensions

picard/ui/options/about.py
https://tickets.metabrainz.org/browse/PICARD-912
=> PICARD-912: Update copyright dates

picard/ui/itemviews.py
https://tickets.metabrainz.org/browse/PICARD-914
=> PICARD-914: Remove existing tooltip on track object update

picard/ui/options/interface.py, picard/ui/options/scripting.py
https://tickets.metabrainz.org/browse/PICARD-919
https://tickets.metabrainz.org/browse/PICARD-921
=> PICARD-919,921: Change Options dialog tree layout

picard/ui/options/scripting.py
https://tickets.metabrainz.org/browse/PICARD-924
=> PICARD-924: Set splitter stretch factors

picard/ui/options/scripting.py
https://tickets.metabrainz.org/browse/PICARD-925
=> PICARD-925: Preserve scripting splitter position

picard/ui/itemviews.py
https://tickets.metabrainz.org/browse/PICARD-931
=> PICARD-931: Fix info dialog opening on double clicking cluster

picard/ui/options/tags.py
https://tickets.metabrainz.org/browse/PICARD-902
=> PICARD-902: Fix load for tags options page

picard/ui/options/tags.py
https://tickets.metabrainz.org/browse/PICARD-898
=> PICARD-898: Change default id3v24 encoding to utf8

picard/script.py, test/test_script.py
https://tickets.metabrainz.org/browse/PICARD-923
=> PICARD-923: Add startswith and endswith script functions

picard/plugin.py, picard/ui/options/plugins.py
https://tickets.metabrainz.org/browse/PICARD-916
=> PICARD-916: Fix type error in initialization of plugin.new_version

picard/ui/mainwindow.py
https://tickets.metabrainz.org/browse/PICARD-937
=> PICARD-937: Clear status bar on selection update

picard/tagger.py
https://tickets.metabrainz.org/browse/PICARD-944
=> PICARD-944: Wait for save thread pool to be finished before exit

picard/file.py
https://tickets.metabrainz.org/browse/PICARD-946
=> PICARD-946: Fix wrong new_file variable assignement due to modified old_file

picard/ui/mainwindow.py
Resolves [PICARD-950](https://tickets.metabrainz.org/browse/PICARD-950)
This will need rebasing after #598 is merged.
=> PICARD-950: Don't open same folder multiple times

picard/formats/__init__.py
Resolves [PICARD-970](https://tickets.metabrainz.org/browse/PICARD-970).
=> PICARD-970 Read files unbuffered in guess_format

picard/album.py
[PICARD-798](https://tickets.metabrainz.org/browse/PICARD-798)
=> PICARD-798: Handle empty collection list

picard/file.py, picard/tagger.py
Resolves [PICARD-973](https://tickets.metabrainz.org/browse/PICARD-973).
=> PICARD-973: process events before exiting

picard/script.py, test/test_script.py
=> Revert "PICARD-922: Fix inmulti behaviour with multi-values"

picard/coverart/image.py, picard/file.py, picard/metadata.py, picard/ui/coverartbox.py, picard/ui/mainwindow.py
Rename branch of #585 
http://tickets.musicbrainz.org/browse/PICARD-258
=> PICARD-258: Visual Feedback for coverart changes 

picard/ui/itemviews.py
https://tickets.metabrainz.org/browse/PICARD-988
=> PICARD-988: Extract file paths from NSURL while drag'n'drop

picard/__init__.py, picard/coverart/providers/local.py, picard/formats/apev2.py, picard/formats/vorbis.py, picard/script.py, picard/similarity.py, picard/ui/tagsfromfilenames.py, picard/util/filenaming.py, resources/makeqrc.py, setup.py, test/test_textencoding.py
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior
=> Python 3.6 invalid escape sequence deprecation fixes

picard/ui/coverartbox.py
https://tickets.metabrainz.org/browse/PICARD-996
=> PICARD-996: Fix cover art box show 

picard/ui/mainwindow.py
https://tickets.metabrainz.org/browse/PICARD-998
=> PICARD-998: Fix toolbar toggle action

picard/cluster.py, picard/tagger.py
https://tickets.metabrainz.org/browse/PICARD-223
=> PICARD-223: Allow Unmatched Files to be removable

picard/ui/coverartbox.py, picard/ui/itemviews.py, picard/util/__init__.py
https://tickets.metabrainz.org/browse/PICARD-1006
=> PICARD-1006: Fix Drag'n'Drops for cover art drops

picard/util/__init__.py
=> Fix circular imports in picard.util

picard/ui/coverartbox.py
Fixes https://tickets.metabrainz.org/browse/PICARD-1010
=> PICARD-1010: Fix display/hide logic for Coverart box

picard/file.py
Resolves https://tickets.metabrainz.org/browse/PICARD-1021.
=> PICARD-1021: Skip file loads if Picard is stopping

picard/mbxml.py
Fixes https://tickets.metabrainz.org/projects/PICARD/issues/PICARD-1029
=> PICARD-1029: Fix typo in artist_credit_to_metadata

NEWS.txt
Mainly because PW shows it weirdly -
=> Minor change in wording

picard/ui/searchdialog.py
=> PICARD-1051: Call setSectionResizeMode instead of setResizeMode

picard/file.py
Fixes https://tickets.metabrainz.org/browse/PICARD-1053
=> PICARD-1053: Fix wrong variable in stop_analyze

picard/ui/coverartbox.py, picard/ui/itemviews.py
It was fixed with Qt5.4.1.
See https://bugreports.qt.io/browse/QTBUG-24379
=> Remove unneeded NSURL code

picard/browser/browser.py
Crash due to unexpected type string.
Bytes/str issue with QT
=> Fix crash on Browser lookups

setup.py
https://tickets.metabrainz.org/browse/PICARD-1064
=> PICARD-1064: Fix verbose tests

setup.py
https://tickets.metabrainz.org/browse/PICARD-1066
=> PICARD-1066: Fix update_constants

setup.py
https://tickets.metabrainz.org/browse/PICARD-1065
=> PICARD-1065: Fix patch_version

picard/album.py
Fixes https://tickets.metabrainz.org/browse/PICARD-1062
=> PICARD-1062: Sort results by similarity 

picard/ui/mainwindow.py
https://tickets.metabrainz.org/browse/PICARD-1052
=> PICARD-1052: Only enable search for similar tracks if the selection contains objects

picard/metadata.py
apply_func currently only used for ascii translation in track.py and album.py.
=> PICARD-1070: 1.4.x Make apply_func work on all metadata

picard/metadata.py
apply_func currently only used for ascii translation in track.py and album.py.
=> PICARD-1070: 2.0 Make apply_func work on all metadata

picard/ui/options/tags.py
Fixes https://tickets.metabrainz.org/browse/PICARD-1077
=> PICARD-1077: Fix update encoding logic on id3 version change

test/test_metadata.py
Resolves https://tickets.metabrainz.org/browse/PICARD-1075
=> PICARD-1075: Add unit tests for Metadata object variables

picard/ui/mainwindow.py
1. Improve menu when more than one CD drive
2. Give warning message if discid not found or no CD drive.
=> Picard 1087: Lookup CD UI improvements

po/picard.pot
This seems to have not been done in a while....
=> python setup.py regen_pot_file

picard/util/icontheme.py
Solves https://tickets.metabrainz.org/projects/PICARD/issues/PICARD-1100
=> PICARD-1100: Remove deprecated gconf and move to gsettings

picard/ui/edittagdialog.py
It has been moved there from QtWidgets
https://tickets.metabrainz.org/projects/PICARD/issues/PICARD-1105
=> PICARD-1105: Use QItemSelectionModel from QtCore

test/test_webservice.py
=> Add more tests for the webservice

picard/webservice/__init__.py, picard/webservice/api_helpers.py
Fixes https://tickets.metabrainz.org/browse/PICARD-807
=> PICARD-807: Add advanced rate limiting to WS

picard/mbjson.py, test/data/ws_data/track.json, test/test_mbjson.py
Fixes https://tickets.metabrainz.org/browse/PICARD-1119
=> PICARD-1119: Fix wrong metadata parsing

picard/album.py, picard/webservice/api_helpers.py
Fixes https://tickets.metabrainz.org/browse/PICARD-1114
=> PICARD-1114: Fix ratings submission

picard/ui/cdlookup.py
Fixes https://tickets.metabrainz.org/browse/PICARD-1142
=> PICARD-1142: Fix crash on CD lookup

picard/plugin.py
Fixes [PICARD-1156](https://tickets.metabrainz.org/projects/PICARD/issues/PICARD-1156)
=> Handle upgrade of plugin directories being symlinks

picard/ui/ui_options_about.py, ui/options_about.ui
This allows to easily copy the version information to tickets.
=> PICARD-1171: Make it possible to select the text in "About"

picard/metadata.py, test/test_metadata.py
* This is a…
In 2f8496e, 1.0 - ... turned into 0.0. 
Fix that.
=> Fix length_score and add tests

picard/ui/searchdialog.py
The idea is to use this dialog as an alternative to releases list in context menu allowing to select others releasesi in a release group
=> SearchDialog: make search edit box at top optional

picard/ui/searchdialog/__init__.py, po/picard.pot
* This is a…
Remove an obsolete command and drop unneeded calls to `_()` on 4 strings.
=> Search dialog code minor cleanup

appveyor.yml, picard.spec, picard/acoustid/__init__.py, picard/util/__init__.py, tagger.py
* This is a…
We were not bundling fpcalc properly while packaging. This PR fixes it.
=> Bundle fpcalc with distributables

appveyor.yml, picard.spec
=> Add discid to windows builds

picard/ui/searchdialog/__init__.py
* This is a…
Alternate row colors in in-app search dialog
=> SearchDialog: alternate row color

picard/const/__init__.py, picard/plugin.py, picard/ui/options/plugins.py
* This is a…
Currently in picard if you click multiple time install plugin button it will behave weird. It shows the upgrade dialog and then updated status
* JIRA ticket : [PICARD-1184](https://tickets.metabrainz.org/browse/PICARD-1184)
Reason for this problem was in picard/plugin.py there is only single option to handle both install a plugin or update a plugin .
Clicking the install a plugin call this function which emits a singal to picard/ui/options/plugins.py.plugin_installed to update the status from install button to "installed", but if in mean time you click install again this function will call picard/ui/options/plugins.py.plugin_updated method as there exist some downloaded data in plugin folder. I made two function one for handling …
=> PICARD-1184: Fix multi click weird issues

.travis.yml, picard.spec, scripts/package-osx.sh, scripts/setup-osx.sh
* This is a…
py2app cannot build valid apps anymore. Thus we are shifting to pyinstaller.
=> Build OSX packages for Picard

.travis.yml, picard.spec, scripts/setup-osx.sh
=> Fix OSX builds by adding libdiscid binaries

picard/ui/mainwindow.py
* This is a…
* JIRA ticket (_optional_): [PICARD-1190](https://tickets.metabrainz.org/browse/PICARD-1190)
Add keyboard shortcut for log messages and history activity.
=> Add keyboard shortcut to enable log messages and history activity

picard/log.py
=> Remove unnecessary code to figure out logger name

picard/acoustid/__init__.py, picard/acoustid/manager.py, picard/album.py, picard/browser/browser.py, picard/coverart/image.py, picard/coverart/providers/caa.py, picard/dataobj.py, picard/disc.py, picard/plugin.py, picard/releasegroup.py, picard/tagger.py, picard/track.py, picard/ui/__init__.py, picard/ui/cdlookup.py, picard/ui/collectionmenu.py, picard/ui/coverartbox.py, picard/ui/edittagdialog.py, picard/ui/filebrowser.py, picard/ui/infodialog.py, picard/ui/itemviews.py, picard/ui/mainwindow.py, picard/ui/metadatabox.py, picard/ui/options/dialog.py, picard/ui/options/scripting.py, picard/ui/passworddialog.py, picard/ui/ratingwidget.py, picard/ui/tagsfromfilenames.py, picard/ui/util.py, picard/util/__init__.py, picard/util/thread.py
=> Use python super function instead of calling by class name

picard/album.py, picard/config.py, picard/metadata.py, picard/plugin.py, picard/tagger.py, picard/track.py, picard/ui/filebrowser.py, picard/ui/mainwindow.py, picard/ui/metadatabox.py
* This is a…
While understanding the picard codebase i am encountering various python2 oriented code. This pr will port them to python3.
=> Use python3 super function instead of calling by class name

picard/util/versions.py
Example: "SSL OpenSSL 1.0.2g  1 Mar 2016"
=> Display SSL version string

picard/ui/infodialog.py
=> InfoDialog: reduce code redundancy, subclassing QWidget

picard/coverart/providers/caa.py
=> Caa minor code cleanup

picard/ui/__init__.py
* This is a…
* JIRA ticket (_optional_): [PICARD-1211](https://tickets.metabrainz.org/browse/PICARD-1211)
=> PICARD-1211: Fix disabled close button in Windows

picard/ui/metadatabox.py
=> Manage preserved tags as a set, with the help of new class PreservedTags

po/README.md
It simply updates documentation according to 8ac7014dfeea6f31cf5b7ec7325768b157da65bf.
=> Update instructions to update attributes strings

picard/ui/options/scripting.py
* This is a…
* JIRA ticket (_optional_): [PICARD-1220](https://tickets.metabrainz.org/browse/PICARD-1220)
In options > Scripting. On pressing delete key, the script will be removed.
=> PICARD-1220: Add keyboard shortcut to delete scripts.

picard/ui/options/plugins.py
PR #829 refactored some of the plugin code and updated the method signature of install_plugin but all the calls to it were not updated causing crashes on drag'n'drop / manual installation of plugins. This fixes that.
* This is a…
* JIRA ticket (_optional_): [PICARD-1234](https://tickets.metabrainz.org/browse/PICARD-1234)
=> PICARD-1234: Update calls to `install_plugin` after method signature update

picard/ui/infodialog.py
* This is a…
Info dialog for clusters is showing a tracklist which isn't sorted by track number correctly in all cases.
=> Fix up tracklist order in info dialog

picard/plugin.py, picard/tagger.py, picard/ui/logview.py, picard/util/__init__.py
=> Clean-up un-used code and errors

picard/mbjson.py
* This is a…
* JIRA ticket (_optional_): [PICARD-1230](https://tickets.metabrainz.org/browse/PICARD-1230)
=> PICARD-1230: Fix TypeError due to None type objects in string join

picard/const/languages.py
* This is a…
* Add Traditional Chinese to UI languages.
=> PICARD-1272: Add Traditional Chinese to UI languages

.travis.yml
See https://github.com/travis-ci/travis-ci/issues/2498
* This is a…
=> Deploy a release on all tagged commits

setup.py
* This is a…
Fixes picard.in getting installed directly in /usr
=> setup: picard.in does not need to get installed

scripts/setup-osx.sh
* This is a…
* JIRA ticket (_optional_): [PICARD-1283](https://tickets.metabrainz.org/browse/PICARD-1283)
=> PICARD-1283: Add fpcalc binaries to OSX builds

appveyor.yml, installer/picard-setup.nsi.in, picard.spec, setup.py
* This is a…
* JIRA ticket (_optional_): [PICARD-1290](https://tickets.metabrainz.org/browse/PICARD-1290)
* JIRA ticket (_optional_): [PICARD-1286](https://tickets.metabrainz.org/browse/PICARD-1286)
=> PICARD-1286, 1290: Improve executable packaging for Windows and OSX

INSTALL.md, setup.py
Improve the packaging metadata
* This is a…
Picard has basically no useful information on PyPI (https://pypi.org/project/picard/), improve that.
Add a few classifiers, use README.md as the long description.
=> Packaging improvements

picard/log.py
* This is a…
* JIRA ticket (_optional_): [PICARD-1300](https://tickets.metabrainz.org/browse/PICARD-1300)
=> PICARD-1300: Use a lock to ensure queue is not mutated while iteration

.travis.yml
Trasifex updates are no longer needed as they are always done manually before a release. Also no need to install or build picard as it is already done in the package-osx script again.
* This is a…
=> Clean up un-necessary steps from Travis

installer/picard-setup.nsi.in
* This is a…
* JIRA ticket (_optional_): [PICARD-1292](https://tickets.metabrainz.org/browse/PICARD-1292)
=> PICARD-1292: Fix default install location for windows

picard/album.py, picard/track.py
Reverts metabrainz/picard#859
Reverting this until a fix for PICARD-1247 is found.
=> Revert "PICARD-259: Allow tagger script to access file metadata"

picard/metadata.py
This commit implements an algorithm to fetch a release
that matches the preffered release types outlined in the
settings page. Further testing is required.
* This is a…
Re-opening this as I cannot seem to rebase the current #899 since the repo was deleted.
=> PICARD-1122: Fix preferred release types not working 

picard/log.py
* This is a…
* JIRA ticket (_optional_): [PICARD-1310](https://tickets.metabrainz.org/browse/PICARD-1310)
=> PICARD-1310: Fix crash on clearing the log, due to wrong var. name

picard.spec
* This is a…
* JIRA ticket (_optional_): [PICARD-1308](https://tickets.metabrainz.org/browse/PICARD-1308)
=> PICARD-1308: fix incorrect version number in Info.plist (macosx)

picard/coverart/providers/caa.py
* This is a…
Same as #932 but for the 2.0.x branch.
* JIRA ticket (_optional_): [PICARD-1323](https://tickets.metabrainz.org/browse/PICARD-1323)
See #932
@zas If you include this it makes sense to also pick #931
=> PICARD-1323: Restore all defaults resets CAA types (2.0.x)

picard/i18n.py
* This is a…
If language is set to "System default" the default locale detection does not work reliable on Windows and always starts in English.
* JIRA ticket (_optional_): [PICARD-1324](https://tickets.metabrainz.org/browse/PICARD-1324), [PICARD-1267](https://tickets.metabrainz.org/browse/PICARD-1267)
This structures the code a bit more logical after the two cases UI language set / not set and different platforms.
Before this change the case that UI language is configured and the Win32 detection where not separated, which lead to the language detection issue ([PICARD-1324](https://tickets.metabrainz.org/browse/PICARD-1324)).
The refactoring also takes care of [PICARD-1267](https://tickets.metabrainz.org/browse/PICARD-1267), thus superseeding …
=> PICARD-1294: Refactor default locale detection.

.travis.yml, appveyor.yml
* This is a…
Run builds against Python 3.7
=> CI: Build against Python 3.7

tagger.py
Same as https://github.com/metabrainz/picard/pull/937 for 2.0.x
* This is a…
* JIRA ticket (_optional_): [PICARD-1216](https://tickets.metabrainz.org/browse/PICARD-1216)
=> [2.0.x] PICARD-1216: Attempt to attach to console on Windows 

picard/formats/id3.py, test/test_formats.py
* This is a…
Same as https://github.com/metabrainz/picard/pull/947 but for 2.0.x
* JIRA ticket (_optional_): [PICARD-1329](https://tickets.metabrainz.org/browse/PICARD-1329)
=> [2.0.x] PICARD-1329: Fix saving iTunNORM tags to ID3

picard/plugin.py
* This is a…
If an exception occurs during plugin installation Picard crashes due to an unhandled exception during exception handling.
* JIRA ticket (_optional_): [PICARD-1331](https://tickets.metabrainz.org/browse/PICARD-1331)
=> PICARD-1331: Fix crash when plugin installation fails

picard/plugin.py
* This is a…
Same as https://github.com/metabrainz/picard/pull/953 but for 2.0.x
* JIRA ticket (_optional_): [PICARD-1331](https://tickets.metabrainz.org/browse/PICARD-1331)
=> [2.0.x] PICARD-1331: Fix crash when plugin installation fails 

picard/formats/id3.py, picard/formats/mutagenext/compatid3.py, test/test_formats.py
* This is a…
The changes in PICARD-1245 introducing the GRP1 tag are not compatible with mutagen 1.37. Actually mutagen 1.38 introduced native support for this non-standard tag, but my previous patch did not take this into account and tried to implement it in compatid3 instead. Obviously this was a failed attempt :)
This PR also fixes PICARD-875 (compatid3 tags are not available to AIFF and DSF files). Without this tests for GRP1 would fail for those formats in mutagen 1.37.
* JIRA ticket (_optional_): [PICARD-1245](https://tickets.metabrainz.org/browse/PICARD-1245)
* JIRA ticket (_optional_): [PICARD-875](https://tickets.metabrainz.org/browse/PICARD-875)
=> PICARD-1245: GRP1 tag compatibility for mutagen 1.37

picard/formats/mp4.py, test/test_formats.py
* This is a…
For MP4 the tag `bpm` was listed as unsupported
* JIRA ticket (_optional_): [PICARD-1336](https://tickets.metabrainz.org/browse/PICARD-1336)
Make sure MP4 integer tags are listed as supported. Added tests
=> PICARD-1336: For MP4 integer tags were not marked as supported

picard/mbjson.py
Load concertmaster as performer:concertmaster
* This is a…
* JIRA ticket (_optional_): [PICARD-1268](https://tickets.metabrainz.org/browse/PICARD-1268)
=> PICARD-1268: Load concertmaster as performer:concertmaster

picard/file.py, picard/metadata.py, test/test_metadata.py
* This is a…
After saving the file the tags marked as deleted were not cleared. That means even when matching the file afterwards to new metadata the previously deleted tags would not be saved, as described in [PICARD-1112](https://tickets.metabrainz.org/browse/PICARD-1112)
* JIRA ticket (_optional_): [PICARD-1112](https://tickets.metabrainz.org/browse/PICARD-1112)
Clear `metadata.deleted_tags` after saving file.
=> PICARD-1112: Clear deleted tags after saving file

picard/script.py
* This is a…
* JIRA ticket (_optional_): [PICARD-1347](https://tickets.metabrainz.org/browse/PICARD-1347)
=> PICARD-1347: reduce code duplication

picard/ui/coverartbox.py
It wasn't working in most cases, mainly due to QByteArray vs bytes mismatch (actually since a long time)
* This is a…
Dropping cover art image on cover art box doesn't work in many cases.
* JIRA ticket (_optional_): [PICARD-1350](https://tickets.metabrainz.org/browse/PICARD-1350)
Tested working cases (linux):
- dropping local file (file://...) png & jpeg
- dropping remote url file (http://...) png & jpeg from Chrome & firefox
- dropping image url from Google Images, works from Chrome, doesn't from Firefox
=> PICARD-1350: fix drag'n'drop on cover art box

picard/tagger.py
* This is a…
When a plugin is buggy it can crash Picard, so user cannot disable it from the UI.
* JIRA ticket (_optional_): [PICARD-1352](https://tickets.metabrainz.org/browse/PICARD-1352)
Adding this command-line option allows one to start Picard without loading any plugin and skipping request to Picard's website to get the list of available plugins.
It may help debugging issues related to plugins, and we can simply ask users having an issue to start picard with -P option in order to exclude plugins as the possible source.
=> PICARD-1352: Add a command-line option (-P) to force Picard ignoring all plugins

picard/mbjson.py, test/data/ws_data/recording_credits.json, test/test_mbjson.py
Fix solo attribute for vocals / instruments
* This is a…
* JIRA ticket (_optional_): [PICARD-1162](https://tickets.metabrainz.org/browse/PICARD-1162)
=> PICARD-1162: Fix solo attribute for vocals / instruments

picard/ui/mainwindow.py
Picard should use delete or ⌘⌫ (Command+Delete) for removing files from Picard in addition to the del key on macOS.
* This is a…
* JIRA ticket (_optional_): [PICARD-1039](https://tickets.metabrainz.org/browse/PICARD-1039)
=> PICARD-1039: Support Forward Delete as alternative to Del on macOS

picard/browser/browser.py
=> PICARD-1359: improve builtin server reliability and debugging output

.gitignore, picard.spec, setup.py, win-version-info.txt.in
* This is a…
`picard.exe` is missing version information. Update the build to include it.
* JIRA ticket (_optional_): [PICARD-1364](https://tickets.metabrainz.org/browse/PICARD-1364)
Include version information for pyinstaller to be included in the .exe file. For such simple metadata this is insanely complicated, but see https://pythonhosted.org/PyInstaller/usage.html#capturing-windows-version-data and https://mborgerson.com/creating-an-executable-from-a-python-script/
Here is how it looks like:
=> PICARD-1364: Write version information to picard.exe

picard/tagger.py, picard/ui/searchdialog/__init__.py, picard/ui/searchdialog/album.py, picard/ui/searchdialog/artist.py, picard/ui/searchdialog/track.py
* This is a…
One of my own favorite most annoying issues when using Picard: Adds a "Search in Browser" button to every search dialog, that allows you to perform the current search in the browser. Useful for having search dialogs enabled, because they are nice to use, but to quickly switch over to website search for more complex research.
* JIRA ticket (_optional_): [PICARD-1367](https://tickets.metabrainz.org/browse/PICARD-1367)
=> PICARD-1367: Open search in browser

appveyor.yml, requirements.txt, setup.py
Fixes building with PyQt 5.11 on Windows. The core change is to use pyinstaller 3.4, which has PyQt related fixes. Also uses the openssl DLLs bundled with PyQt, since we can assume those are compatible with that specific PyQt release.
This needs testing outside my own dev environment, opening a PR to trigger an Appveyor build.
* This is a…
* JIRA ticket (_optional_): [PICARD-1365](https://tickets.metabrainz.org/browse/PICARD-1365)
=> PICARD-1365: Working Windows builds with PyQt 5.11

picard/ui/options/plugins.py
This is a minor bugfix for #976, where the font would stay "bold" after uninstalling an enabled plugin
* This is a…
=> PICARD-1313: Fix setting font to disabled when uninstalling a plugin

.travis.yml
In preparation of the deprecation of the xcode6.4 runtime on Travis also build with xcode6.4. It is just important to remember that we need to use the xcode6.4 for releases as long as it is available.
* This is a…
* JIRA ticket (_optional_): [PICARD-1353](https://tickets.metabrainz.org/browse/PICARD-1353)
=> PICARD-1353: macOS Travis xcode73

installer/picard-setup.nsi.in
* This is a…
The Quick Launch toolbar used to be a small area of fixed application icons shown by default left of the running applications. When Windows moved to a more dock like task bar with Windows 7 the Quick Launch icons were no longer shown by default.
Picard provides an option to add an icon to this Quick Launch list. Since the Quick Launch icons are no longer visible few users will know what this even is. In the best case it is useless, in the worst case people expect that the Picard icon will be pinned to the taskbar (see [this discussion](https://community.metabrainz.org/t/please-test-new-picard-windows-builds/400717/6)).
Hence this PR will remove the Quick Launch shortcut option from the installer. I intentionally left the uninstall …
=> PICARD-1370: Remove Quick Launch shortcut from Windows installer

picard/cluster.py, picard/ui/item.py, picard/ui/mainwindow.py
This is a follow up to #975 which introduces some more improvement how update_metadata_images is handled. The most important change is that for the special `UnclusteredFiles` cluster no metadata update is performed, since it does not show the cover art for the included files anyway.
With these changes I think we can safely close PICARD-1339
* This is a…
* JIRA ticket (_optional_): [PICARD-1339](https://tickets.metabrainz.org/browse/PICARD-1339)
=> PICARD-1339: Further optimizations for update_metadata_images

picard/album.py, picard/file.py, picard/mbjson.py
* This is a…
When unsetting the musicbrainz_recordingid via scripting or a plugin various AcoustId related functions don't work as expected:
- After Scan files are matched by recordingid to tracks, this does not work
- AcoustId submission for tracks without musicbrainz_recordingid does not work
The users can still expect that Picard remembers internally these important IDs even if they don't want to use them for tagging.
* JIRA ticket (_optional_): [PICARD-949](https://tickets.metabrainz.org/browse/PICARD-949)
* JIRA ticket (_optional_): [PICARD-1363](https://tickets.metabrainz.org/browse/PICARD-1363)
Keep a copy of track's original metadata (before passing it to scripting / plugins) and use it for matching and AcoustId submission.
=> PICARD-949: keep recording ids

picard/util/_astrcmp.c, test/test_util_astrcmp.py
* This is a…
Fix deprecation warning during compilation by porting _astrcmp to the new Python Unicode API introduced with Python 3.3, see https://docs.python.org/3/c-api/unicode.html
* JIRA ticket (_optional_): [PICARD-1379](https://tickets.metabrainz.org/browse/PICARD-1379)
=> PICARD-1379: Port _astrcmp to new Python Unicode API

picard/plugin.py, picard/ui/options/plugins.py
* This is a…
When installing or uninstalling a local plugin the plugin list does not refresh. That means after installing a plugin the list will not show it, and when uninstalling a local plugin the plugin will stay in the list and appear as a downloadable plugin, even though it isn't.
* JIRA ticket (_optional_): [PICARD-1244](https://tickets.metabrainz.org/browse/PICARD-1244)
After installing a local plugin refresh the list and highlight this plugin in the list.
After uninstalling a plugin that is not available online, remove it from the list.
=> PICARD-1244: Refresh plugin list after (un)installing local plugin

picard/webservice/__init__.py
* This is a…
When Picard closes running / queued up network requests an exception is thrown "RuntimeError: dictionary changed size during iteration"
* JIRA ticket (_optional_): [PICARD-1391](https://tickets.metabrainz.org/browse/PICARD-1391)
=> PICARD-1391: Avoid exception when closing active requests

picard/disc.py, picard/ui/cdlookup.py, picard/util/__init__.py, test/test_utils.py
* This is a…
When a disc ID lookup contains multiple results picking the correct one can be tricky. We can assist the user by making use of the barcode stored on the disc itself.
* JIRA ticket (_optional_): [PICARD-1383](https://tickets.metabrainz.org/browse/PICARD-1383)
Read the MCN field (containing the EAN as per spec) from the disc when generating the disc ID. Use this barcode to pre-select the release that matches the barcode.
=> PICARD-1383: Select release with matching barcode on disc ID lookup

picard/script.py, test/test_bytes2human.py, test/test_script.py
* This is a…
Creating more flexible title-case function, than function in plugin _titlecase_
* JIRA ticket: [PICARD-1386](https://tickets.metabrainz.org/browse/PICARD-1386)
Added func_title function
=> PICARD-1386: Add $title function

test/test_script.py
* This is a…
Helping to increase the test coverage of picard
* JIRA ticket (_optional_): [PICARD-862](https://tickets.metabrainz.org/browse/PICARD-862)
Added 3 tests for func_pad, func_replace and func_strip from script.py
=> PICARD-862: Improve Test Coverage of Picard

README.md
So it's easy to find for new contributors
* This is a…
* [x ] Minor / simple change (like a typo)
I didn't find how to install. This is not consistent with other METABRAINZ repositories.
Refer to INSTALL.md in README.md
What about having a consistent format on all Markdown files in Metabrainz's repositories.
=> Refer to INSTALL.md in README.md

picard/formats/apev2.py, picard/formats/id3.py, picard/formats/vorbis.py, test/test_formats.py
* This is a…
Currently for the tagging formats which allow to save generic tags, like Vorbis and Ape, but also ID3 to some extend, tags marked as unsupported are saved to the files regardless.
This has some implications:
- Even though the tag is hidden in the metadata view, it still gets written
- Our tests skip unsupported tags, so we have untested behavior here
- We don't have an easy way to really blacklist a certain tag from getting saved to a format (e.g. if a tag is really format specific)
* JIRA ticket (_optional_): [PICARD-1397](https://tickets.metabrainz.org/browse/PICARD-1397)
Use `supports_tag` to check whether a tag should be saved. Add tests for unsupported tags.
=> PICARD-1397: Do not save unsupported tags to files

picard/file.py
When the metadata contains a value explicitly set to be empty (with e.g. `metadata.set("sometag", [])`) saving the file will fail in `file._script_to_filename` on the iteration for filename sanitation. The issue is that the metadata gets updated with  `metadata[]`, which deletes empty items.
* This is a…
* JIRA ticket (_optional_): [PICARD-1375](https://tickets.metabrainz.org/browse/PICARD-1375)
Use `metadata.set` to set the values.
=> PICARD-1375: Handle empty values in metadata sanitation

picard/file.py, picard/metadata.py, test/test_metadata.py
* This is a…
If e.g. the title tag gets changed this is rightly considered a change to the metadata and the file gets highlighted in Picard. If however the title tag gets marked as deleted this currently is not considered a change in metadata.
* JIRA ticket (_optional_): [PICARD-1412](https://tickets.metabrainz.org/browse/PICARD-1412)
When calculating metadata differences take deleted tags into account. A deleted tag compared to an existing tag will always result in a 0 score.
=> PICARD-1412: Consider deleted tags as changed

picard/ui/options/about.py
* This is a…
Me not being listed in About copyright section
=> Add phw to authors in about

picard/ui/options/about.py
* This is a…
On each new year or when adding a new author, the whole About string has to be translated again.
Move variable bits outside of it.
=> Split About text in smaller parts to prevent unneeded re-translation.

.travis.yml
For Travis CI use Ubuntu Xenial for all tests. Simplifies the use of Python 3.7 and tests Python 3.7 against all dependency variations we test other Python versions against.
* This is a…
=> travisci: Run all builds on Ubuntu Xenial

.codacy.yml
This ignores the autogenerated ui_*.py files. See discussion on https://github.com/metabrainz/picard/pull/1047
**NOTE**: Right now this branch is intentionally on top of #1047 to test its functionality, so please do not merge yet. Once I know it is working as expected I will rebase the changes here and leave only the addition of `.codacy.yml`
* This is a…
=> Codacy ignore autogenerated ui files

installer/picard-setup.nsi.in
Currently the Windows installer of Picard will happily install on a 32bit Windows, but since we only provide 64 bit builds the installed application fails to launch with some Windows incompatibility warning.
This patch checks if the installer is running on a 64bit system and if not aborts the installation with an appropriate error message.
* This is a…
=> PICARD-1371: Do not allow installation on 32-bit Windows

.travis.yml, appveyor.yml, scripts/setup-osx.sh
Python 3.7.1 has some bugfixes, especially the one for https://tickets.metabrainz.org/browse/PICARD-1369
Also I think it would be best to have the same Python version used for both the Windows and macOS builds
* This is a…
=> Python 3.7.1 builds for macOS and Windows

picard/ui/metadatabox.py
* This is a…
If a tag exists in the metadata loaded from a file but not in the metadata loaded for the track that tag is shown in the metadata box. But deleting this tag, via contextmenu or by clearing all values, is not possible. This is because when clearing a tag it is checked if it is in the new metadata and only gets deleted if it is.
* JIRA ticket (_optional_): [PICARD-1428](https://tickets.metabrainz.org/browse/PICARD-1428)
When removing explicitly mark tags as deleted instead of just deleting them if they are in metadata.
=> PICARD-1428: Fix deleting tags only in original file metadata

picard/formats/id3.py
When a tag, e.g. `artists` is deleted, also consider tag renames in ID3. E.g. for `artists` delete both `TXXX:ARTISTS` but also the old `TXXX:Artists`. This is a fix for changes introduced in https://github.com/metabrainz/picard/pull/1043
* This is a…
=> When deleting tags also consider renamed tags

picard/album.py, picard/track.py
Fix authentication required field not set on MB.org requests if ratings are disabled.
Bug was introduced in https://github.com/metabrainz/picard/pull/1047/files#diff-e15bfdf3a67e1dbd50edec4895b5a3a2R382
* This is a…
=> Fix require_authentication on album requests

picard/webservice/api_helpers.py
Fix submitting ratings 
* This is a…
Rating submission responded with:
```
E: 16:07:49,517 /home/phw/devel/musicbrainz/picard/picard/webservice/__init__._handle_reply:386: Network request error for https://musicbrainz.org:443/ws/2/rating?client=MusicBrainz Picard-2.1.0.dev1: Error transferring https://musicbrainz.org:443/ws/2/rating?client=MusicBrainz Picard-2.1.0.dev1 - server replied: Unsupported Media Type (QT code 299, HTTP code 415)
```
This is related to recent webservice refactorings. Fixed by setting proper mimetype.
=> Fix rating submission request

picard/formats/apev2.py, picard/formats/id3.py, picard/formats/vorbis.py
* This is a…
This finishes up the work started in https://github.com/metabrainz/picard/pull/1029 and adds full support for the movement tags in ID3, Vorbis and APE. The updated tag mapping is then:
|Internal name|ID3|MP4|Vorbis|APE|
|-|-|-|-|-|
|movement|MVNM|©mvn|MOVEMENTNAME|MOVEMENTNAME|
|movementnumber|MVIN|©mvi|MOVEMENT|MOVEMENT|
|movementtotal|MVIN|©mvc|MOVEMENTTOTAL|MOVEMENTTOTAL|
|showmovement|TXXX:SHOWMOVEMENT|shwm|SHOWMOVEMENT|SHOWMOVEMENT|
This is compatible with how MusicBee and MP3Tag handle those tags. In MusicBee it looks as follows (very similar UI to the iTunes one):
* JIRA ticket (_optional_): [PICARD-1425](https://tickets.metabrainz.org/browse/PICARD-1425)
* JIRA ticket (_optional_): …
=> PICARD-1425: Support all movement tags for APE, Vorbis and MP3

picard/formats/id3.py, test/test_formats.py
* This is a…
Picard saves empty frames to ID3, even if no data is set for them:
v2.3: IPLS  
v2.4: TIPL, TMCL
* JIRA ticket (_optional_): [PICARD-1219](https://tickets.metabrainz.org/browse/PICARD-1219)
=> PICARD-1219: Do not save empty TIPL/TMCL/IPLS frames to ID3

picard/album.py, picard/formats/id3.py, test/test_formats.py
* This is a…
Picard will completely remove the existing TCMP (compilation) frame from the file if `compilation` is not defined in new metadata (which it isn't unless it is a compilation). But Picard does:
1. Do this only for ID3, the equivalent tags in other formats get preserved
2. Does show the tag as unchanged
3. This deviates from the general behavior where existing file tags that do not get explicitly set in Picard get preserved
* JIRA ticket (_optional_): [PICARD-1431](https://tickets.metabrainz.org/browse/PICARD-1431)
Mark compilation tag as deleted if it does not apply instead of sneakily removing it only for ID3.
This makes sense for compilation flags and actually shows the user in the UI (metadatabox) what will happen (tag will be …
=> PICARD-1431: Explicitly mark compilation tag as deleted

picard/album.py, picard/browser/browser.py, picard/cluster.py, picard/coverart/image.py, picard/file.py, picard/script.py, picard/track.py, setup.py, test/test_formats.py
=> Run isort -rc to unify imports

picard/album.py, picard/track.py
* This is a…
Currently the `album` tag for non-album tracks cannot be modified by scripting or plugins, because it gets updated after those are processed. This PR fixes this.
* JIRA ticket (_optional_): [PICARD-1355](https://tickets.metabrainz.org/browse/PICARD-1355)
Set the `album` tag to the preferred non-album track title directly after loading and before applying plugins and scripts.
Take care to still update the title if the default non-album track album title gets changed in options and the track's album title was not customized.
=> PICARD-1355: Allow changing NAT album title by script

picard/tagger.py
* This is a…
Native Qt buttons aren't translated
* JIRA ticket (_optional_): [PICARD-1438](https://tickets.metabrainz.org/browse/PICARD-1438)
Use 'qtbase_' instead of 'qt_' prefix when loading Qt translations
=> PICARD-1438: fix untranslated Qt native buttons

picard/coverart/image.py, picard/file.py, picard/util/scripttofilename.py, test/test_scripttofilename.py
* This is a…
As reported on the forums new line characters in cover art naming can cause file saving errors. Actually the cover art file name generation uses code derived from the file naming, but the file naming code has some fixes for edge cases that never got implemented for cover art.
* JIRA ticket (_optional_): [PICARD-1439](https://tickets.metabrainz.org/browse/PICARD-1439)
Introduce script_to_filename to be used by both file and cover art naming. This:
1. Reduces code duplication
2. Makes it possible to test the file name generation from scripts
3. Provides fixes for handling of various edge cases that where implemented for file naming also for cover art
=> PICARD-1439: Unify filename generation by metadata script

.travis.yml, appveyor.yml, scripts/package-osx.sh
Improve CI artifacts naming and deployment
* This is a…
Different CI builds for Windows and Mac cannot be distingiushed easily.
The following changes are made:
1. Development builds for macOS contain build platform details (e.g. xcode6.4)
2. For Windows development builds the patched version is also created, with details about Python version
3. Github releases for macOS will only deploy a specific version (should be the oldest supported osx_image, currently xcode6.4)
4. Configured deployment for Windows builds, this time with the latest Python version (3.7.1 currently)
=> Improve ci deployments

picard/ui/options/releases.py
* This is a…
The secondary release types in Options > Metadata > Preferred Releases are currently unsorted, which makes it hard to find the correct type. In the release editor on MB.org they are sorted alphabetically, we should do the same.
I would still keep the primary types at the start of the list in their current order. This is again also how the release editor deals with it.
* JIRA ticket (_optional_): [PICARD-1443](https://tickets.metabrainz.org/browse/PICARD-1443)
=> PICARD-1443: Sort secondary release type sliders alphabetically

picard/ui/options/releases.py
The behavior of the preferred release sliders is buggy on Windows. The tooltips are stealing the focus, causing the drag operation to stop. Disabled the tooltips on Windows until we find a better solution.
See the forums: https://community.metabrainz.org/t/please-test-new-picard-windows-builds/400717/42
* This is a…
* JIRA ticket (_optional_): [PICARD-518](https://tickets.metabrainz.org/browse/PICARD-518)
=> Disable the tooltips for sliders on Windows

picard/config_upgrade.py, picard/coverart/__init__.py, picard/plugin.py, picard/ui/options/plugins.py, picard/ui/options/scripting.py, picard/ui/tagsfromfilenames.py, picard/util/__init__.py, picard/util/astrcmp.py, picard/util/checkupdate.py, picard/util/imageinfo.py, setup.py, test/test_util_filenaming.py, test/test_versioncompare.py, test/test_versions.py
=> Minor fixes

picard/webservice/__init__.py
Fixes authentication errors in case of MBID redirects.
* This is a…
In case of a redirect we forget the authentication. That means if:
1. The user is logged into MB
2. Has any option enabled the triggers authenticated calls (user genres, ratings or collections)
3. A MBID URL is requested which redirects to another MBID
Then the redirected call would not carry the users credentials and result in a 401 response.
This can be easily triggered by e.g. entering `release:5ca33564-cdb5-4e70-ae4a-4c968ed14fa2` in Picard's search box.
* JIRA ticket (_optional_): [PICARD-1451](https://tickets.metabrainz.org/browse/PICARD-1451)
Carry over the state of `request.mblogin` on redirect
=> PICARD-1451: Carry over mblogin on redirect

appveyor.yml
Appveyor deployment failed to publish the installer to Github. This is another attempt to fix this. Re-reading https://www.appveyor.com/docs/deployment/github/ this seems to be correct.
Not sure how to best test this, I actually would just go ahead and try it on master.
* This is a…
* JIRA ticket (_optional_): [PICARD-1452](https://tickets.metabrainz.org/browse/PICARD-1452)
=> PICARD-1452: Fix appveyor artifact deployment to Github

picard/ui/infodialog.py, picard/ui/options/interface.py
* This is a…
Undefined variables are used.
* JIRA ticket (_optional_): [PICARD1454](https://tickets.metabrainz.org/browse/PICARD-1454)
Don't use undefined variables.
=> PICARD-1454: Fix use of undefined variables

.travis.yml, scripts/package-osx.sh, scripts/setup-osx.sh
* This is a…
The packaging scripts for macOS currently do not fail on error but continue running and return with success.
* JIRA ticket (_optional_): [PICARD-1382](https://tickets.metabrainz.org/browse/PICARD-1382)
Use `set -e` to have the script terminate if any command fails.
Note: Expected result of this PR is that the build fails due to https://tickets.metabrainz.org/browse/PICARD-1456 . Actually a failing build indicates this PR is a success. If the build succeeds this PR is probably not working as expected ;)
=> PICARD-1382: Fail macOS packaging scripts on error

scripts/package-osx.sh
* This is a…
Address possibility of curl failing during macOS packaging, see https://github.com/metabrainz/picard/pull/1083#pullrequestreview-197696069
* JIRA ticket (_optional_): [PICARD-1382](https://tickets.metabrainz.org/browse/PICARD-1382)
=> PICARD-1382: Fail macOS build on curl errors

installer/picard-setup.nsi.in
With Qt5 the window class changed, hence the installer no longer detects already running instances on upgrade.
* This is a…
* JIRA ticket (_optional_): [PICARD-1460](https://tickets.metabrainz.org/browse/PICARD-1460)
=> PICARD-1460: Fix installer not detecting running instance

picard/ui/options/about.py
* This is a…
In PICARD-1461 Picard crashes due to errors in the translation. The translators had actually translated placeholders like `%(translator-credits)s`. The main issue has already been fixed by updating translations at https://github.com/metabrainz/picard/commit/5b7b29df2ae9dd5b860326fc5260e73fde74d0a5 . But the underlying issue that translators might actually translate those placeholders remains.
* JIRA ticket (_optional_): [PICARD-1461](https://tickets.metabrainz.org/browse/PICARD-1461)
Use underscore instead of hyphen in translation placeholders
This makes Transifex detect those as special tags. This avoids issues with translators actually translating the placeholder.
This ensure placeholders are taken as is.
=> PICARD-1461: Use underscore instead of hyphen in translation placeholders

picard/ui/mainwindow.py
This menu item opens a dialog.
* This is a…
Menu item label has no ellipis though it opens a dialog
* JIRA ticket (_optional_): [PICARD-1458](https://tickets.metabrainz.org/browse/PICARD-1458)
Add …
=> PICARD-1458: add horizontal ellipsis at the end of label

picard/ui/options/__init__.py
Remove unused OptionsPage.info method. It is currently unused and not overridden by any option page (including those of plugins).
* This is a…
* JIRA ticket (_optional_): [PICARD-1459](https://tickets.metabrainz.org/browse/PICARD-1459)
=> PICARD-1459: Remove unused OptionsPage.info method

picard/ui/mainwindow.py
On macOS "Check for update..." should be placed in the app menu, not Help
* This is a…
* JIRA ticket (_optional_): [PICARD-1457](https://tickets.metabrainz.org/browse/PICARD-1457)
=> PICARD-1457: Place "Check update" in app menu on macOS

picard/album.py, picard/mbjson.py, test/data/ws_data/artist.json, test/data/ws_data/artist_null.json
* This is a…
Changes the way Picard handles certain WS JSON, so that we can later fix the output on the MBS side in the distant future.
See the associated commit messages.
See the associated commit messages.
No action needed.
=> JSON WS changes

org.musicbrainz.Picard.appdata.xml.in, setup.py
Generates the release list in appdata XML from NEWS.txt
* This is a…
The appdata release list needs to be updated before every release. This adds another step to the release process that easily gets forgotten.
* JIRA ticket (_optional_): [PICARD-1447](https://tickets.metabrainz.org/browse/PICARD-1447)
Generate the release list in appdata XML on build time using the data from NEWS.txt.
=> PICARD-1447: Generate appdata release list on build

picard/coverart/image.py
Picard is currently hard coded to use port 80 for cover art URLs. This causes issues if someone tries to implement a cover art plugin which uses https URLs.
* This is a…
Found this issue when implementing a TheAudioDB plugin. In this case I patched the `parse_url` method in the plugin as a workaround, see https://github.com/metabrainz/picard-plugins/pull/204/files#diff-46913b7909b972d599d9e30457ff1adeR56
* JIRA ticket (_optional_): [PICARD-1475](https://tickets.metabrainz.org/browse/PICARD-1475)
=> PICARD-1475: Support HTTPS cover art URLs

installer/picard-setup.nsi.in
On Windows uninstall previous Picard install before installing the new version. Also make sure to never default to installing into the "Program Files (x86)" folder, which is reserved for 32 bit applications.
* This is a…
1. Picard just overwrote files in the existing install location. This could potentially lead to left over libraries interfering with the current install. We had reports of crashes that were fixed by clearing the old installation location before a fresh install. So this might be a potential fix for PICARD-1343 and PICARD-1469
2. When updating and choosing a new installation location, Picard would end up being installed twice. An uninstall would only remove the latest install
3. When 32 bit Picard was installed previously an …
=> PICARD-1422: Windows uninstall previous install

picard/tagger.py, picard/ui/metadatabox.py
Make sure the metadata boxes get updated quickly when the selection changes even if the thread pool is busy.
* This is a…
When Picard's default thread pool is kept busy this can prevent update of the metadata box on selection changes. Reason is that calculating the updated tags also runs on the thread pool.
This e.g. happens with the BPM plugin, see https://github.com/metabrainz/picard-plugins/issues/200 and discussion  on https://github.com/metabrainz/picard-plugins/issues/200
* JIRA ticket (_optional_): [PICARD-1476](https://tickets.metabrainz.org/browse/PICARD-1476)
Introduce a priority thread pool
This pool is meant to be used for threads where the user expects a response as fast as possible.
=> PICARD-1476: Introduce a priority thread pool

picard/mbjson.py, test/data/ws_data/recording.json, test/data/ws_data/release.json, test/test_mbjson.py
Fix artist genre fallback if "Fall back on album's artists genres" is active
* This is a…
The artists tags where not read and hence could not be used as a fallback if no tags are set on recording, release or release-group level
* JIRA ticket (_optional_): [PICARD-1288](https://tickets.metabrainz.org/browse/PICARD-1288)
Together with [MBS-9400](https://tickets.metabrainz.org/browse/MBS-9400) this fixes the issue.
=> PICARD-1288: Fix artist genre fallback

picard/webservice/api_helpers.py
* This is a…
Changing the MB server in Options > General requires a restart to take effect.
* JIRA ticket (_optional_): [PICARD-1478](https://tickets.metabrainz.org/browse/PICARD-1478)
Dynamically read the server config on use.
I intentionally did not change the general usage of `APIHelper` as I'm not sure how much we should treat this as public API, after all using this as a base class for other APIs would make sense for some plugins. So you can use it as before with static host + port in the constructor, but `MBAPIHelper` overwrites the properties `host` and `port`.
=> PICARD-1478: Read MB host and port from config

picard/coverart/__init__.py, picard/coverart/image.py, picard/coverart/providers/local.py, test/test_coverart_image.py
Generalized the handling of cover art URLs to also handle file:// scheme.
Follow up to https://github.com/metabrainz/picard/pull/1109
* This is a…
The `CoverArtImageFromFile` class was quite redundant and introduced a new attribute `filepath` that was not present in the base class and needed to be explicitly checked when processing the images. All this can be handled by treating the file path as a URL, then we can rely completely on standard behavior from the base class.
=> Refactored local cover art class

picard/tagger.py
* This is a…
- code was setting files as pending before testing if acoustid was enabled
- test can be done before anything since that's a required condition
- test for enabled acoustid before the loop and returns immediatly if not
=> tagger.analyze(): immediatly return if acoustid is disabled

picard/util/__init__.py, test/test_utils.py
* This is a…
`mbid_validate()` was validating a string starting with a valid mbid but too long as valid.
The reason is the use of `re.match()` and no `$` in the regex, so it was matching only start of string, not full string.
Also the documentation explicitely says it should return None if no match, that's not a problem here, but better test against None.
Tests were lacking.
This issue was very unlikely to be a real life one, since the buggy case shouldn't happen with current code, but still... 
Add tests and refactor / fix
=> Mbid validate fix

picard/tagger.py
- existing code was very hard to follow and a bit redundant
- make it easier to read, and self-documented
* This is a…
=> tagger._file_loaded() cleanup

picard/album.py, picard/tagger.py
- drop useless list + sort
- drop unused use_recordingid parameter
- split the method in two, it should ease testing
- drop match_file, and use modified match_files, reducing code redundancy
* This is a…
=> Rework Album.match_files()

picard/cluster.py
- rename CamelCased words to fit overall style
- simplify code
- minor optimizations
* This is a…
=> Cluster cleanup

picard/file.py, test/test_filesystem.py
Rework File._move_additional_files()
- add tests for hidden files and patterns starting with dot trick
- use faster os.scandir() (since python 3.5)
- change the logic so we don't build list of all files but only list of files to move
- handle OSError, a file or directory could be removed during the process, or have permissions changed
- log such errors
* This is a…
=> Rework File._move_additional_files()

test/test_filesystem.py
Refactor and simplify
* This is a…
=> Test filesystem cleanup

picard/album.py, picard/file.py, picard/mbjson.py, picard/track.py
* This is a…
AcoustId submission for NATs is not available.
This broke in https://github.com/metabrainz/picard/pull/1009/commits/768a873cd10f02b9bfbba9c29cd50e7e8a7cbf56 . Core issue is that this commit introduced using `track.orig_metadata`, but in case of NATs this gets not populated.
This fix was also tested to still work in the case when `musicbrainz_recordingid` gets unset by scripting.
* JIRA ticket (_optional_): [PICARD-1483](https://tickets.metabrainz.org/browse/PICARD-1483)
=> PICARD-1483: Fix submitting AcoustId for non-album tracks

picard/util/__init__.py, test/test_utils.py
Durations of an hour or more will show the hours as HH:MM:SS
* This is a…
* JIRA ticket (_optional_): [PICARD-1485](https://tickets.metabrainz.org/browse/PICARD-1485)
=> PICARD-1485: Format track durations with hours

scripts/package-osx.sh
It causes Travis CI checks to fail far too often
* This is a…
=> Ignore upload failures during osx packaging

picard/plugin.py
* This is a…
The version check for filtering available Picard plugins implemented in PICARD-1417 is too strict.
If a plugin specifies e.g. PLUGIN_API_VERSIONS = ['2.0.0'] this won't match against API version 2.0. This only affects the filtering from the webservice, the version check when loading a local plugin takes care of this properly.
* JIRA ticket (_optional_): [PICARD-1491](https://tickets.metabrainz.org/browse/PICARD-1491)
=> PICARD-1491: Fix plugin version check when loading plugin list

picard/collection.py
=> Collection cleanup

picard/cluster.py
=> Cluster.add_file(): reduce code redundancy, using add_files([file])

picard/file.py, test/test_file.py
* This is a…
* JIRA ticket (_optional_): [PICARD-1494](https://tickets.metabrainz.org/browse/PICARD-1494)
`os.stat()` `st_atime` and `st_mtime` have low resolution, so time preservation doesn't work that well, depending on platform (as bad as 2 seconds delta on windows).
Python3.3 introduces nano seconds resolution times that can be used with utimes() using `ns` parameter
=> PICARD-1494: Improve file times preservation using os.utime() ns parameter 

picard/file.py
- use `@property` and `@property.setter` decorators
- make those more obvious
- drop force_update / update parameters as they were hiding `File.update()` calls
- remove redundant `File.update()` calls
- state property: only emit `tagger_stats_changed` signal when `num_pending_files` actually changed
- simplify tests in `File.update()`, introduced in https://github.com/metabrainz/picard/commit/62c705623666175f81eb18248190d08794675780
* This is a…
=> Cleanup File state, tracknumber, discnumber properties

picard/file.py
=> Make filename fix

picard/file.py, test/test_file.py
- access times are likely to differ, a race condition is possible
- stat() has be done after the change to be able to compare
- comments added
- force sync after modifying test file
- make code easier to understand
See https://github.com/metabrainz/picard/pull/1132#issuecomment-474113665
* This is a…
=> Fix broken preserve times test logic

picard/metadata.py, test/test_metadata.py
=> Metadata cleanup, second pass

picard/album.py, picard/cluster.py, picard/file.py, picard/metadata.py, picard/ui/searchdialog/track.py, picard/util/__init__.py, test/test_utils.py
Try to unify the style a bit, and make the code easier to understand.
* This is a…
=> Clean up various matching iterations, unify a bit

picard/mbjson.py, picard/releasegroup.py, picard/ui/searchdialog/album.py, picard/ui/searchdialog/track.py, test/test_mbjson.py
* This is a…
`country_list_from_node()` was implicitly returning None in case of release without release-events.
It wasn't a real issue because callers are actually testing for emptyness, but this behavior isn't really on par with other methods in the same file.
Also naming is rather inconsistent.
Ensure it returns a list in every case, and rename method to `countries_from_node()` + do a bunch of variables renames.
=> Fix country list

picard/config.py, picard/coverart/providers/caa_release_group.py, picard/formats/mutagenext/tak.py, picard/metadata.py, picard/plugin.py, picard/similarity.py, picard/ui/itemviews.py, picard/ui/util.py, picard/util/bytes2human.py, picard/util/webbrowser2.py, picard/webservice/__init__.py
=> Pylint errors/warnings cleanup

picard/formats/asf.py, test/test_formats.py
`ASFFile._save` did modify the passed `Metadata` object. Fixed this and added a test to make sure this does not happen.
Also simplified `test_formats.py` by using the new ability to pass tags directly to the `Metadata()` constructor.
* This is a…
=> Fix ASFFile._save modifies metadata

picard/ui/itemviews.py
* This is a…
* JIRA ticket (_optional_): [PICARD-PICARD-1496](https://tickets.metabrainz.org/browse/PICARD-PICARD-1496)
=> PICARD-1496: display count of Other versions in menu and refactoring

picard/oauth.py, picard/tagger.py
Use properties to get rid of direct access to config.persist
* This is a…
=> Oauth cleanup: use properties

picard/formats/vorbis.py, test/test_formats.py
* This is a…
When trying to save Vorbis tags with a configured rating e-mail that contains characters that are not valid for Vorbis keys an exception is thrown.
* JIRA ticket (_optional_): [PICARD-1492](https://tickets.metabrainz.org/browse/PICARD-1492)
Remove invalid characters from configured user email before using it as part of the Vorbis rating key. Make sure to do this sanitizing on both save and load to ensure consistent behavior.
=> PICARD-1492: Fix saving Vorbis ratings with invalid chars in user e-mail

picard/album.py, picard/coverart/__init__.py, picard/coverart/providers/__init__.py, picard/coverart/providers/caa.py, picard/coverart/providers/caa_release_group.py, picard/coverart/providers/local.py, picard/coverart/providers/whitelist.py, picard/ui/options/cover.py
The code (mostly mine) is very messy, so time to clean up.
* This is a…
=> Coverart stuff cleanup

picard/ui/metadatabox.py
Those aren't define at module level, but they are still meant to be constants
https://www.python.org/dev/peps/pep-0008/#constants
* This is a…
=> PEP8: Capitalize TagStatus class constants

picard/album.py, picard/file.py, picard/metadata.py, picard/ui/metadatabox.py
- a note was added to it
- not removed, some plugins might rely on it
* This is a…
=> Remove last bits of deprecated Metadata.delete()

picard/formats/apev2.py, picard/formats/vorbis.py, test/formats/common.py, test/formats/test_apev2.py, test/formats/test_vorbis.py
Mark tags which are invalid for Vorbis and Ape tags as unsupported.
* This is a…
For Vorbis and Ape we store all tags, but do not check if the tag would be a valid key in that format. If you e.g. set a tag `$set(\tinvalid,test)` this will be invalid for Vorbis and Ape, but Picard still attempts to save this tag and fails.
* JIRA ticket (_optional_): [PICARD-1497](https://tickets.metabrainz.org/browse/PICARD-1497)
Introduce validation functions `is_valid_key(key)` for both Vorbis and Ape and use them in `supported_tags()`
=> PICARD-1497: Validate tag keys

test/formats/coverart.py, test/picardtestcase.py, test/test_coverart_image.py
Always run `FakeTagger.run_cleanup()` as a cleanup job in `PicardTestCase`
- Hopefully fixes some spurious failing tests, where `QtCore.QObject.tagger` was undefined
- Ensures the cleanup is always run. Cleanup tasks could get registered at different parts of the application, and when writing a test case it might be difficult to decide whether it is needed or not
* This is a…
=> Always run tagger.run_cleanup for PicardTestCase

setup.cfg
Ignore the `ui_*.py` files for calculating testing code coverage.
* This is a…
=> Ignore the ui_*.py files for calculating testing code coverage.

picard/config_upgrade.py, picard/const/__init__.py, picard/coverart/__init__.py, picard/coverart/image.py, picard/formats/id3.py, picard/metadata.py, picard/script.py, picard/ui/options/releases.py, picard/util/__init__.py, picard/webservice/__init__.py, picard/webservice/api_helpers.py, setup.cfg, test/formats/coverart.py, test/test_coverart_image.py
Running flake8 on the code currently complains both about [W503](https://lintlyci.github.io/Flake8Rules/rules/W503.html) "Line break occurred before a binary operator" and [W504](https://lintlyci.github.io/Flake8Rules/rules/W504.html) "Line break occurred after a binary operator". Both are mutually exclusive, so you cannot satisfy flake8.
Ignore W503 according to the recommendation at https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator and fixed the code to follow this style.
* This is a…
=> Flake ignore w503

picard/const/__init__.py, picard/ui/options/renaming.py, picard/ui/options/scripting.py, test/test_script.py
=> Move some constants to picard.const

picard/config.py, test/test_config.py
=> Rework Config / ConfigSection

picard/acoustid/__init__.py
=> Remove redundant code: process is already set few lines before

picard/config_upgrade.py, picard/tagger.py, test/test_config_upgrade.py
=> Add tests for config upgrade functions

CONTRIBUTING.md, HACKING.txt, requirements-dev.txt
=> Add requirements-dev.txt, with working isort version and various tools

picard/coverart/providers/__init__.py, picard/formats/__init__.py, picard/metadata.py, picard/plugin.py, picard/script.py, picard/ui/itemviews.py, picard/ui/mainwindow.py, picard/ui/options/__init__.py
=> Rework ExtensionPoint

picard/tagger.py
Use QApplication.setDesktopFileName to ensure proper app-id on Wayland
* This is a…
* JIRA ticket (_optional_): [PICARD-1502](https://tickets.metabrainz.org/browse/PICARD-1502)
=> PICARD-1502:  Ensure proper app-id on Wayland

org.musicbrainz.Picard.appdata.xml.in, picard.spec, picard/ui/mainwindow.py, setup.py
Use `PICARD_APP_ID` constant instead of hardocding "org.muiscbrainz.Picard" everywhere.
* This is a…
=> Use PICARD_APP_ID constant instead of hardcoded strings

picard/script.py, test/test_script.py
=> Improve wrong number of arguments script error message

picard/util/scripttofilename.py
- it's hard to be sure the caller did a copy or not before
- there's no point in modifying the passed metadata
- no need to copy over images to temporary Metadata object
* This is a…
=> Ensure script_to_filename() doesn't modify passed metadata

picard/util/lrucache.py, test/test_util_lrucache.py
=> LRUCache: inherit from MutableMapping + tests

picard/file.py
- register_file_post_save_processor()
- run_file_post_save_processors() is called in File._save_and_rename() just before returning
* This is a…
* JIRA ticket (_optional_): [PICARD-1130](https://tickets.metabrainz.org/browse/PICARD-1130)
=> PICARD-1130: Add a post save hook

picard/album.py, picard/tagger.py
* register_album_post_removal_processor()
* This is a…
Adds an album-removed hook.
* JIRA ticket (_optional_): [PICARD-1512](https://tickets.metabrainz.org/browse/PICARD-1512)
Plugin API version needs an update I think.
=> PICARD-1512: Add a hook for album removal

picard/file.py, picard/track.py
* register_file_post_addition_to_track_processor() and register_file_post_removal_from_track_processor()
* This is a…
Adds a file-added-to-track hook and a file-removed-from-track hook.
* JIRA ticket (_optional_): [PICARD-143](https://tickets.metabrainz.org/browse/PICARD-143), [PICARD-1510](https://tickets.metabrainz.org/browse/PICARD-1510)
Plugin API version needs an update I think.
=> PICARD-143, PICARD-1510: Add hooks for file addition to and file removal from a track

picard/__init__.py
* This is a…
* JIRA ticket (_optional_): [PICARD-1513](https://tickets.metabrainz.org/browse/PICARD-1513)
=> PICARD-1513: Bump version to 2.2.0dev2 and api version to 2.3

picard/formats/mp4.py
Loading or saving a MP4 without existing tags causes an exception.
* This is a…
For MP4 files without tags `file.add_tags()` is called, but the created tags are never used.
Issue was introduced in https://github.com/metabrainz/picard/commit/aefcef909814bdc9f47c736f35013c7e88da94e6
* JIRA ticket (_optional_): [PICARD-1516](https://tickets.metabrainz.org/browse/PICARD-1516)
I tried to add a test case, but failed to produce a proper test file. The one I used for testing cannot directly be used because it is a copyrighted track.
=> PICARD-1516: Fix loading / saving MP4 without tags

picard/tagger.py
* This is a…
When removing an album and a non-album track, `remove_nat()` will call `remove_album()`.
`remove()` loop over objects to remove, and call `remove_album()` again on the same object
This causes a `KeyError: 'NATS'` exception on `del self.albums[album.id]` execution
* JIRA ticket (_optional_): [PICARD-1522](https://tickets.metabrainz.org/browse/PICARD-1522)
Do not call `remove_album()` for NAT albums, as `remove_nat()` will be called and will take care of NATS pseudo album removal.
=> PICARD-1522: Fix exception caused by an attempt to remove already removed NATS album

picard/ui/logview.py
- override hideEvent() and showEvent() to connect/disconnect log_tail.updated signal
- only update display on showEvent()
* This is a…
* JIRA ticket (_optional_): [PICARD-1525](https://tickets.metabrainz.org/browse/PICARD-1525)
=> PICARD-1525: Only update log/history views when actually displayed

picard/log.py, picard/ui/colors.py, picard/ui/itemviews.py, picard/ui/logview.py, picard/ui/metadatabox.py, picard/ui/options/dialog.py, picard/ui/options/interface_colors.py, picard/ui/ui_options_interface_colors.py, picard/ui/ui_options_interface_theme.py, ui/options_interface_colors.ui
* This is a…
* JIRA ticket (_optional_): [PICARD-1524](https://tickets.metabrainz.org/browse/PICARD-1524)
=> PICARD-1524: Make colours user-configurable

picard/ui/mainwindow.py
* This is a…
* Internal music player has been added
There was not internal music player in this application. It can be useful if user wants to know what is the track that he edits.
I have added the music player feature based on QtMultimedia.
Please check on Windows (maybe I will check by myself later) and MacOS (I can't check by myself)
=> PICARD-1488: Internal music player feature added

picard/ui/logview.py
* This is a…
Closing a log view window (history or debug log) via the window's close button destroys its contents, resulting in empty dialog content (only black, no rendering) when re-opening this dialog.
This issue was introduced in https://github.com/metabrainz/picard/commit/3f2f0f32b2f1452cb2f6ecb660c0c01359f864ce when these dialogs where changed to be permanent instead of getting created/destroyed on demand.
* JIRA ticket (_optional_): [PICARD-1541](https://tickets.metabrainz.org/browse/PICARD-1541)
Hide the dialog instead of closing.
=> PICARD-1541: Hide log dialogs instead of destroying

picard/ui/mainwindow.py
=> Internal player checks

test/test_similarity.py
=> Add tests for similarity2()

picard/metadata.py
* This is a…
The "title in weights" part and the use of only one medium don't make sense, no one is able to explain this code.
* JIRA ticket (_optional_): [PICARD-1552](https://tickets.metabrainz.org/browse/PICARD-1552)
Drop suspicious parts and simplify.
=> PICARD-1552: simplify code and drop a part that makes no sense

picard/file.py
Removes a misleading FIXME comment. The leading dot replacement was primarily added for non-Windows platforms (but it's also useful on Windows).
* This is a…
=> Removed misleading FIXME comment

picard/ui/ratingwidget.py
* This is a…
When manually setting the rating on a track this change is not reflected on the files already matched to this track. It only works if the files get attached to the track afterwards.
Options
* JIRA ticket (_optional_): [PICARD-1558](https://tickets.metabrainz.org/browse/PICARD-1558)
=> PICARD-1558: Apply ratings to matched files

picard/file.py
As we are in the habbit of adding plugin hooks here is another one being run after a file has been loaded.
This allows plugin to extend the file with information loaded from elsewhere, e.g. additional files (e.g. cuesheet) or file system metadata.
* This is a…
* JIRA ticket (_optional_): [PICARD-1560](https://tickets.metabrainz.org/browse/PICARD-1560)
Usage:
```
PLUGIN_NAME = u"Test"
PLUGIN_AUTHOR = u"Philipp Wolfer"
PLUGIN_DESCRIPTION = "Just for testing"
PLUGIN_VERSION = "0.1"
PLUGIN_API_VERSIONS = ["2.2"]
from picard.file import register_file_post_load_processor
def on_file_load(file):
print("on_file_load: %s" % file.filename)
file.metadata["loaded"] = "YEAH"
register_file_post_load_processor(on_file_load)
```
=> PICARD-1560: Added register_file_post_load_processor plugin hook

test/test_file.py
* This is a…
On macOS 10.14 setting the file times with `os.utime` only sets full seconds. This makes our tests fail that test for subsecond accuracy.
* JIRA ticket (_optional_): [PICARD-1561](https://tickets.metabrainz.org/browse/PICARD-1561)
Round values to full seconds before comparing. Only do this on macOS 10.14, earlier versions are not affected and later versions we don't know.
I don't really like this check here, but currently don't see a better way to handle this. I currently can't tell whether this is a bug or feature of macOS 10.14, maybe we can get rid of this again at some point.
=> PICARD-1561: On macOS 10.14 test preserve time only with second accuracy

picard/file.py
* This is a…
When guessing title and track number from filename the title gets overwritten even if it is set in the tags. This happens if the existing title equals exactly the filename. The intention was clearly to only set the title if it is not already in the existing tags.
* JIRA ticket (_optional_): [PICARD-1567](https://tickets.metabrainz.org/browse/PICARD-1567)
Only set the title if it is not already part of the tags.
=> PICARD-1567: Do not overwrite existing title when guessing track no. from filename

picard/ui/itemviews.py
* This is a…
Dragging files from right pane to left pane requires dropping exactly on unclustered or clustered files items. Just dragging to the left pane does nothing.
When dragging albums this behaves differently, it drops to unclustered files by default.
* JIRA ticket (_optional_): [PICARD-1566](https://tickets.metabrainz.org/browse/PICARD-1566)
When dragging files from right pane to left pane default to dropping to unclustered files.
This makes it easier to drop files back from right to left pane. Also dragging individual files now behaves identical to dragging albums.
=> PICARD-1566: Drop files to left pane defaults to unclustered files

.travis.yml, requirements-build.txt, requirements-macos.txt, requirements-win.txt
For now this is just to test builds with latest Qt versions on  macOS and Windows. Specifically I want to test if this makes any difference performance wise on macOS, see [PICARD-1554](https://tickets.metabrainz.org/browse/PICARD-1554)
* This is a…
* JIRA ticket (_optional_): [PICARD-1554](https://tickets.metabrainz.org/browse/PICARD-1554)
* JIRA ticket (_optional_): [PICARD-1527](https://tickets.metabrainz.org/browse/PICARD-1527)
* JIRA ticket (_optional_): [PICARD-1282](https://tickets.metabrainz.org/browse/PICARD-1282)
=> Build with PyQt 5.13

.travis.yml, scripts/package-osx.sh
This improves the macOS build on Travis CI:
- Fix code signing with macOS Sierra and later
- Build with xcode 9 as lowest version to fix a code signing issue with sip.so. This is still using macOS 10.12 (https://docs.travis-ci.com/user/reference/osx)
- Cache homebrew files. In  my tests this reduced build times to 8-9 minutes where it was previously 15-18 minutes.
- Removes a workaround we added for https://tickets.metabrainz.org/browse/PICARD-1456 which is no longer needed
- Some cleanup to `package-osx.sh` by providing variables for some certificate related values that are used several times 
A full macOS build with code signing using this configuration was done at https://travis-ci.org/metabrainz/picard/builds/568826560
* This is a…
* JIRA …
=> Improve macOS build

.travis.yml, appveyor.yml
Test run `pip install .` on CI to ensure it works and is not broken
* This is a…
=> Run pip install on CI

picard/ui/mainwindow.py, picard/ui/playertoolbar.py
I wanted to tackle some of the UI extensions for the media player we had discussed. But the fact that it was implemented completely inside the main window code make it a bit hard to extend
So as a first step I refactored the code so the media player specific code is in a separate file. There are no functional changes yet. I would like to get this refactoring reviewed and merged first, this will make the actual UI changes easier to review.
* This is a…
=> PICARD-1488: Move media player functionality in own classes

picard/file.py, picard/ui/options/renaming.py, picard/ui/ui_options_renaming.py, test/test_file.py, ui/options_renaming.ui
* This is a…
When moving files without renaming currently the renaming script is not used but files are moved to `move_files_to` only. This is probably unexpected, since the other way round, renaming without moving, uses the script for the filename part only. Hence it makes sense to have move files also use the directory part of the script.
* JIRA ticket (_optional_): [PICARD-1559](https://tickets.metabrainz.org/browse/PICARD-1559)
When only move_files without rename_files is active, consider the renaming script but only use the directory part and keep the original filename.
=> PICARD-1559: Create directories from script when moving files without renaming

picard/metadata.py, test/test_metadata.py
`Metadata.apply_func()` can cause tags getting removed (by setting them to empty) during iteration. This caused a crash.
* This is a…
* JIRA ticket (_optional_): [PICARD-1573](https://tickets.metabrainz.org/browse/PICARD-1573)
=> PICARD-1573: Metadata.apply_func() must handle tags getting removed

.travis.yml
Use the apt addon on Travis CI instead of manually calling apt-get. This makes it a bit more readable I think.
See https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-with-the-apt-addon
* This is a…
=> travisci: Use apt addon instead of manually calling apt-get

CODE_OF_CONDUCT.md
Based on the CODE_OF_CONDUCT.md for picard-website project.
* This is a…
As Picard is a MetaBrainz project it should be made explicit that this CoC applies to the Picard project.
I based this on https://github.com/metabrainz/picard-website/blob/master/CODE_OF_CONDUCT.md , but instead of linking to the MusicBrainz CoC I decided to directly link to the MetaBrainz CoC. I dn't think the MusicBrainz related bits really apply to Picard development and the MetaBrainz CoC itself is easier to read and understand.
I even think we should update picard-website to use the MetaBrainz CoC instead.
=> Add Code of Conduct (pointing to MetaBrainz CoC)

picard/ui/coverartbox.py
* This is a…
* JIRA ticket (_optional_): [PICARD-1575](https://tickets.metabrainz.org/browse/PICARD-1575)
This addresses two issues with drag and dropping images from browser to the coverartbox
1. Sometimes servers don't respond with the proper image mime type but only send `application/octet-stream` or `binary/data` (probably in an attempt to trigger the download dialog in the browser). The code now tries to detect the mime type using our imageinfo class.
2. Drag and drop from Bing image search result page works. Same solution as for Google where the real image URL is inside the URL query parameters, this just uses a different parameter name.
=> PICARD-1575: Fixes for cover art drag and drop from browser

tagger.py
PyQt5 5.12.3 and later rely on PATH for finding the Qt5 DLLs. With the previous version it failed to load the DLLs when loaded from the packaged bundle. Also importing picard.const.sys already pulls in PyQt5 and other dependencies which should not happen this early in the startup.
* This is a…
=> Fix launching packaged bundle on Windows

appveyor.yml, picard.spec
=> Fixed Qt SSL packaging on Windows

picard/ui/coverartbox.py
* This is a…
If HTTP request errors happened on cover art drop Picard would not handle it and then crash with something like:
```
E: 16:41:30,579 webservice._handle_reply:387: Network request error for https://xyzzdshjdshsjkhfhfdsksfkj:443/imgresy?imgurl=https%3A%2F%2Fimages.sftcdn.net%2Fimages%2Ft_app-cover-l%2Cf_auto%2Fp%2Fbefbcde0-9b36-11e6-95b9-00163ed833e7%2F260663710%2Fthe-test-fun-for-friends-screenshot.jpg&imgrefurl=https%3A%2F%2Fthe-test-fun-for-friends.de.softonic.com%2Fiphone&docid=bJ0aORcjrBjMnM&tbnid=hj6en-hBZN-VPM%3A&vet=10ahUKEwjEi4S_04zkAhWCZlAKHWhwAE0QMwhQKAEwAQ..i&w=1020&h=574&bih=979&biw=1920&q=test&ved=0ahUKEwjEi4S_04zkAhWCZlAKHWhwAE0QMwhQKAEwAQ&iact=mrc&uact=8: Host xyzzdshjdshsjkhfhfdsksfkj not found (QT code 3, HTTP code …
```
=> PICARD-1575: Handle request errors on cover art drag and drop

appveyor.yml, picard.spec
With this the developer is no longer required to copy those files manually for packaging
* This is a…
=> Load Qt SSL DLLs on Windows directly from Qt install location

picard/ui/playertoolbar.py
* This is a…
This is a small addition to the playback progress slider, which allows the user now to click on any position of the slider and the placback will jump directly to the clicked position. This is more how these sliders behave in other players.
As part of this I refactored the progress slider into it's own widget (including current and total playback time and the media name).
=> PICARD-1488: Player with improved progress slider

picard/coverart/providers/__init__.py, picard/coverart/providers/local.py, picard/ui/options/dialog.py
Clicking on the help button in Picard > Options should ideally directly link to the proper section on https://picard.musicbrainz.org/docs/options/
* This is a…
Clicking on the help button in Picard > Options should ideally directly link to the proper section on https://picard.musicbrainz.org/docs/options/
* JIRA ticket (_optional_): [PICARD-1576](https://tickets.metabrainz.org/browse/PICARD-1576)
Changed the link to directly jump to the anchor based on the option page's name.
I decided to keep the names as they are used in the app as they somewhat are part of the API when plugins add their own option pages.
This requires some changes to the website to work fully, necessary changes are in https://github.com/metabrainz/picard-website/pull/156
=> PICARD-1576: Context sensitive help

picard/ui/playertoolbar.py
* This is a…
This adds some tooltips to the player toolbar and simplifies existing text.
=> PICARD-1488: Updated tooltips for player toolbar

picard/ui/options/releases.py
Picard crashes when closing the option window via window controls (the close X in the window's title bar) while the Preferred Releases page is open.
If the options window gets closed via window controls regsitered signals are already disconnected before the hideEvent gets called.
* This is a…
* JIRA ticket (_optional_): [PICARD-1580](https://tickets.metabrainz.org/browse/PICARD-1580)
=> PICARD-1580: Fixed crash when closing options window

picard/ui/mainwindow.py
* This is a…
Apparently Picard can be unresponsive on Windows when it queries the available CD ROM drives on start while the drive is busy.
This avoids this UI hangup if the drive is busy when detecting the initial drive list by performing the disc drive query in a separate thread.
* JIRA ticket (_optional_): [PICARD-1235](https://tickets.metabrainz.org/browse/PICARD-1235)
=> PICARD-1235: Query available disc drive in separate thread on startup

picard/ui/util.py
On Linux the native dialog was used, but neither on GNOME nor KDE it actually does allow selection of multiple directories. Hence fall back to the Qt dialog on all operating systems.
* This is a…
* JIRA ticket (_optional_): [PICARD-1582](https://tickets.metabrainz.org/browse/PICARD-1582)
=> PICARD-1582: Fixed multi directory selection on Linux

picard/coverart/providers/caa.py
Makes sure latest CAA JSON data is used instead of stale ones.
Tested after changes to https://musicbrainz.org/release/60749511-d9f0-4933-8ec0-7fe7bcfb4af3/cover-art . Without this cached data was used even after Picard restart.
* This is a…
* JIRA ticket (_optional_): [PICARD-765](https://tickets.metabrainz.org/browse/PICARD-765)
=> PICARD-765: Do not use cached CAA JSON files

installer/picard-setup.nsi.in
* This is a…
We had removed the "Run Picard" option from the Window installer due to UAC. Since the installer was running with elevated permissions, directly running Picard caused Picard also running with elevated permissions. This for example disabled drag and drop.
* JIRA ticket (_optional_): [PICARD-1361](https://tickets.metabrainz.org/browse/PICARD-1361)
This PR re-enabled the "Run Picard" option as last step in the installer. The trick is using explorer.exe to launch Picard. Calling explorer.exe with another .exe files causes it to execute it. When a process gets started it inherits the rights from the calling process. Since starting explorer.exe does not spawn a new process but passes the argumens to the already running process of the …
=> PICARD-1361: NSIS installer launch picard

picard/script.py
If a script was already cached and a function used in this script got removed (e.g. by disabling a plugin) Picard crashed with a KeyError when trying to eval this function.
* This is a…
* JIRA ticket (_optional_): [PICARD-1584](https://tickets.metabrainz.org/browse/PICARD-1584)
Handle missing functions in the eval step.
=> PICARD-1584: Avoid crash when evaluating script with missing function

.gitattributes
This file is changed only automatically, diffing and merging it is usually pointless.
* This is a…
=> Treat picard/resources.py as binary file

picard/formats/wav.py, picard/ui/metadatabox.py
* This is a…
While Picard does not yet support tagging WAV files, the metadatabox still displayed all tags for WAV. This raised the expectation those tags can be edited and saved.
* JIRA ticket (_optional_): [PICARD-1547](https://tickets.metabrainz.org/browse/PICARD-1547)
Implement `WAVFile.supports_tag` to always return `False`. This is the same that is already done in the `MIDIFile` format class.
=> PICARD-1547: Mark WAV unsupported tags

picard/tagger.py, picard/ui/options/renaming.py, picard/ui/options/scripting.py, picard/ui/ui_options_renaming.py, ui/options_renaming.ui
* This is a…
Picard did not use monospaced fonts for script editing:
- In Options > Renaming the font was configured to be monospaced, but this was not working on macOS and Windows (it does work on Linux)
- In Options > Scripting it was not setup at all
* JIRA ticket (_optional_): [PICARD-571](https://tickets.metabrainz.org/browse/PICARD-571)
- Make both views (Scripting and Renaming) consistently use monospaced fonts on all platforms
- Create fonts with the "Monospace" family (works on Linux) and set style hint to TypeWriter (ensures the configured default monospaced font gets used on Windows)
- For macOS this still fails. Setup a custom font substitution to use "Menlo" for the "Monospace" family
=> PICARD-571: Use monospaced font for script editors

picard/ui/metadatabox.py
* This is a…
* JIRA ticket (_optional_): [PICARD-1588](https://tickets.metabrainz.org/browse/PICARD-1588)
Part of this was implemented in https://github.com/metabrainz/picard/pull/1254 in https://github.com/metabrainz/picard/pull/1254/commits/a8548cf98d3e22f8827279d651866296bf292b95
This fixes the properly, as the initial commit did introduce a bug (access to `file` variable, which a) is not always set and b) is just the last file from the previous iteration). I also figured this is worth a changelog entry on its own.
=> PICARD-1588: Fixed hiding unsupported tags in metadatabox

picard/pluginmanager.py
* This is a…
Trying to install an invalid plugin ZIP makes Picard crash.
Example ZIP to test: [add_album_column.zip](https://github.com/metabrainz/picard/files/3584762/add_album_column.zip)
* JIRA ticket (_optional_): [PICARD-1593](https://tickets.metabrainz.org/browse/PICARD-1593)
Handle the crash, remove the left over files from failed install.
=> PICARD-1593: Fix crash when plugin could not be installed

test/test_bytes2human.py
* This is a…
bytes2human calc_unit was lacking some tests
=> Increase test coverage of bytes2human

picard/formats/vorbis.py, test/formats/test_vorbis.py
This removes the restriction that Picard will never write the `REPLAGAIN_*` tags to Opus.
While for Opus there is a very own specification with the `R128_*` tags, the more standard tags are still supported by some software, and it should be the decision of the ReplayGain tool and / or user which tags to write.
See also discussion at https://chatlogs.metabrainz.org/brainzbot/metabrainz/2019-09-10/?msg=4454614&page=2
* This is a…
* JIRA ticket (_optional_): [PICARD-1586](https://tickets.metabrainz.org/browse/PICARD-1586)
=> PICARD-1586: Do not actively prevent the standard ReplayGain tags for Opus

picard/ui/options/renaming.py
Since renaming options handled scripting errors separately it hid other form validation errors.
* This is a…
An empty destination directory when "move_files" is enabled is an option form validation error. But the error message was hidden by the renaming option script error handling.
* JIRA ticket (_optional_): [PICARD-1025](https://tickets.metabrainz.org/browse/PICARD-1025)
Separate the script error handling from the generic option validation.
=> PICARD-1025: Do not hide error messages in renaming options

scripts/package-osx.sh
On problems uploading macOS packages to Transfer.sh curl can hang indefinitely, eventually causing the build to fail due to a timeout. Apply a timeout to the upload.  
* This is a…
=> CI: Add a timeout for macOS package uploads

.travis.yml, MANIFEST.in, scripts/run-sdist-test.sh
Ensure we package for PyPI with all test dependencies.
Fully test packaging sdist, extracting it and running the tests inside it. Fixes that we miss packaging test dependencies.
* This is a…
* JIRA ticket (_optional_): [PICARD-1601](https://tickets.metabrainz.org/browse/PICARD-1601)
=> PICARD-1601: Ensure we package for PyPI with all test dependencies

picard/ui/colors.py
Strings in Options > User Interface > Colors show untranslated
* This is a…
Fixed using `_()` for the color description label
* JIRA ticket (_optional_): [PICARD-1603](https://tickets.metabrainz.org/browse/PICARD-1603)
=> PICARD-1603: Show translated color UI labels

.travis.yml
=> Travis CI: The sudo tag is now deprecated on Travis

picard/const/sys.py, picard/tagger.py
As on macOS Picard looks really out of place when using the Fusion Style on Haiku. Use the native look there.
* This is a…
Use native style for Haiku. This patch is already part of https://github.com/haikuports/haikuports/tree/master/media-sound/picard, but I try to limit what I need to maintain separately in https://github.com/phw/picard/commits/haiku-port .
=> Haiku: use Haiku Qt style

NEWS.md, picard/__init__.py
=> Prepare release 2.2.1

picard/ui/options/interface_colors.py
* This is a…
Without this the labels do not expand and the text breaks even though there is enough space in the view.
* JIRA ticket (_optional_): [PICARD-1610](https://tickets.metabrainz.org/browse/PICARD-1610)
Removed the spacer, set the label itself to expanding.
=> PICARD-1610: Give color options labels maximum width

picard.spec
Current macOS builds do not run on macOS < 10.12. Setting LSMinimumSystemVersion enforces that this package cannot be started on older macOS versions with a proper message to the user.
* This is a…
* JIRA ticket (_optional_): [PICARD-1614](https://tickets.metabrainz.org/browse/PICARD-1614)
Set LSMinimumSystemVersion. I tested this by setting it to 10.15 locally, in this case trying to launch the app results in a dialog explaining that I have macOS 10.14 running and the minimum required is 10.15.
=> PICARD-1614: Set minimum macOS version to 10.12

requirements-macos.txt, requirements-win.txt
Use Qt bugfix release, might fix PICARD-1612
* This is a…
* JIRA ticket (_optional_): [PICARD-1612](https://tickets.metabrainz.org/browse/PICARD-1612)
=> Build with PyQt5 5.13.1 on macOS and Windows

scripts/package-osx.sh
On macOS builds verify:
- The `picard-run` binary can be executed
- `picard-run --long-version` reports support for both astrcmp C and libdiscid
- `fpcalc` binary is included and executable
* This is a…
=> Verify macOS app bundle contains dependencies

picard/ui/options/dialog.py
* This is a…
Recently with Picard 2.2 the Classical Extras plugin caused crashes for many users, since it was doing some direct access to internal Picard config implementation which was no longer available after some refactoring.
This provided pretty bad user experience:
- For the user it was not clear what was causing the issues, Picard was just closing
- The user had not really a chance recovering from this situation without deeper knowledge of how to manually change plugins.
* JIRA ticket (_optional_): [PICARD-1606](https://tickets.metabrainz.org/browse/PICARD-1606)
Avoids Picard crashing if e.g. a plugin provides a broken OptionsPage implementation by handling exceptions. This gives the user better feedback and eventually even allows user …
=> PICARD-1606: Handle OptionsPage exceptions

picard/ui/mainwindow.py, picard/ui/options/cdlookup.py, picard/util/cdrom.py
* This is a…
1. Since Picard 2.2 https://github.com/metabrainz/picard/pull/1249/commits/82c3e888a9d89e4d1aaa34c78f78eb14eb8bad63 the CD lookup toolbar button and menu did not allow quick access to multiple drives
2. Since forever the default shortcut for CD lookup did not use the new default device if the user changed it in options
* JIRA ticket (_optional_): [PICARD-1621](https://tickets.metabrainz.org/browse/PICARD-1621)
* JIRA ticket (_optional_): [PICARD-1624](https://tickets.metabrainz.org/browse/PICARD-1624)
=> PICARD-1621: Fix CD lookup button not showing multi drive menu

appveyor.yml
Run tests on Appveyor in separate step and report test results (see e.g. https://ci.appveyor.com/project/MetaBrainz/picard/build/job/y0fg2uerm0edqgx8/tests)
* This is a…
=> Appveyor: Run tests separately

appveyor.yml
This gets outdated quickly and is not necessary.
* This is a…
=> Appveyor: Do not include Picard version in build numbers

setup.py
Always force updating the en_* language specific locales when running `setup.py get_po_files`.
These files currently contain only strings that differ from the English source (that means British English spelling differences only). But since they are highly "incomplete" that are not always automatically updated.
While this must not always be the best practice I think it kind of makes sense for Picard. It makes it more likely the resources are kept up to date.
It's worth noting that this only works for the specific case of en_* locales, as English is the source. For other languages you still need complete translation files.
* This is a…
=> Always update en_* locales on get_po_files

picard/ui/options/cdlookup.py
Fixup for https://github.com/metabrainz/picard/pull/1304. Since 995281f saving options without CD auto detection available caused an error.
* This is a…
* JIRA ticket (_optional_): [PICARD-1624](https://tickets.metabrainz.org/browse/PICARD-1624)
=> PICARD-1624: Fix saving options without AUTO_DETECT_DRIVES

picard/ui/options/cdlookup.py
=> Tidy up CD Lookup UI options code

.travis.yml
sip got updated, but we need to build with an older version.
* This is a…
=> travisci: fixed builds with PyQt 5.8

picard/file.py
* This is a…
If `preserve_timestamps` is enabled Picard crashes when saving a file that was removed from disk already.
* JIRA ticket (_optional_): [PICARD-1637](https://tickets.metabrainz.org/browse/PICARD-1637)
Changed to not handle `PreserveTimesStatError` in `_save_and_rename`, there is nothing useful that can be done about this here. Raise this to the caller, making this being handled as error condition in `_saving_finished`.
This makes the calls to `self._preserve_times(old_filename, save)` and `save()` in `File._save_and_rename` to behave the same.
Also fixed handling the `PreserveTimesUtimeError`. Previously raising a `PreserveTimesUtimeError` would also have caused a file save error.
=> PICARD-1637: Fixed Picard crashing on preserve time exception

picard/formats/vorbis.py, test/formats/test_vorbis.py
If FLAC picture blocks are located before the Vorbis comments, Windows cannot read the tags. By ensuring the pictures are always located after the Vorbis comments the FLAC metadata will be visible and editable in Windows Explorer.
* This is a…
* JIRA ticket (_optional_): [PICARD-1630](https://tickets.metabrainz.org/browse/PICARD-1630)
Always sort the FLAC metadata blocks so picture blocks are located after the Vorbis comments block. This does not affect the order of any other blocks, also the order of the picture blocks is maintained.
=> PICARD-1630: Always save FLAC picture blocks after Vorbis comments

picard/config.py
If the user explicitly specified a config file being used, do not attempt to migrate any old settings. This is only done when using the app default settings location.
* This is a…
* JIRA ticket (_optional_): [PICARD-1640](https://tickets.metabrainz.org/browse/PICARD-1640)
=> PICARD-1640: Do not copy legacy settings when --config-file was specified

.circleci/config.yml
=> Add default circleci config

picard/ui/itemviews.py, picard/util/natsort.py, test/test_util_natsort.py
Adds natural sorting to itemviews. "Foo 10" should sort after "Foo 2"
* This is a…
* JIRA ticket (_optional_): [PICARD-1260](https://tickets.metabrainz.org/browse/PICARD-1260)
Add a `natsort` module with functionality for sorting with proper number handling.
There might be more places were this sorting could be applied, but this PR focuses on what was requested in the ticket.
=> PICARD-1260: Sort titles naturally

picard/ui/mainwindow.py
* This is a…
Picard crashes on startup if
- the system CD drive
- and the user has disabled the CD lookup button from the toolbar in Options > UI
* JIRA ticket (_optional_): [PICARD-1642](https://tickets.metabrainz.org/browse/PICARD-1642)
=> PICARD-1642: Fixed crash on startup if CD lookup button is disabled

picard.spec, scripts/picard-winconsole-hook.py, tagger.py
On Windows we try to attach the GUI app to console output. Move this code to a PyInstaller hook.
Reasoning:
- This is only needed on Windows when running as GUI app, not when running directly from console. 
- Attaching to console should happen as early as possible before anything else gets initialized. E.g. with this hook the console can be attached before other PyInstaller hooks start
* This is a…
=> Move Windows AttachConsole handling to PyInstaller launch hook

.travis.yml
=> travis: test with Python 3.8

picard/i18n.py
* This is a…
* JIRA ticket (_optional_): [PICARD-1644](https://tickets.metabrainz.org/browse/PICARD-1644)
Fixed the call to `translation.install()`. We passed an invalid parameter to translation.install() , but this had no effect in earlier Python versions.
See docs at https://docs.python.org/3/library/gettext.html#gettext.NullTranslations.install
=> PICARD-1644: Fixed gettext install with Python 3.8

picard/formats/asf.py, test/formats/test_asf.py
Improve error handling for `asf.unpack_image`.
* This is a…
Improvements to unpack_image taken from https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/formats/wma.py#L228
The function originally went from Picard into Quod Libet, but they improved the error handling. Stealing this back ;)
=> ASF: Improved error handling for unpack_image

picard/ui/searchdialog/__init__.py, picard/ui/searchdialog/album.py
Picard could crash in search dialog since the table widget sometimes was non-existant on events. 
* This is a…
* JIRA ticket (_optional_): [PICARD-1648](https://tickets.metabrainz.org/browse/PICARD-1648)
Fixed by making the table a permanent widget that gets shown/hidden on demand.
=> PICARD-1648: Fixed crashes in search dialog

picard/formats/apev2.py, test/formats/test_apev2.py
According to specification APEv2 tags should be read case insensitive. Previously Picard only read tags for which there was no explicit mapping case insensitive, but treated all explicitly mapped tags case sensitive.
* This is a…
* JIRA ticket (_optional_): [PICARD-1592](https://tickets.metabrainz.org/browse/PICARD-1592)
Apply the same case insensitive reading logic as it was previously added for some ID3 and ASF tags, but for APE this applies to all tags.
=> PICARD-1592: APEv2 tag case insensitive reading

picard/ui/searchdialog/__init__.py, picard/ui/searchdialog/album.py, picard/ui/searchdialog/artist.py, picard/ui/searchdialog/track.py
Allow selecting more than one item (album, artist or recording) in the built-in search dialogs to load them.
* This is a…
* JIRA ticket (_optional_): PICARD-1550
Use QAbstractItemView.ExtendedSelection to allow selection of more than one item in the search results. For album and recording search all selected items can be loaded into Picard at one, for artist search all selected artists can be opened in the browser at once.
=> PICARD-1650: Mutli selection search dialogs

picard/formats/mutagenext/tak.py, test/formats/test_apev2.py
Use TAK (Tom's Lossless Audiokodec) support from mutagen, if available.
* This is a…
* JIRA ticket (_optional_): PICARD-1652
I have submitted TAK support upstream to mutagen and the PR has been merged, see https://github.com/quodlibet/mutagen/pull/405/
This patch uses the upstream implementation if available, but falls back to our existing more simple implementation if not. If the upstream implementation is used the file variables `~length`, `~channels`, `~sample_rate` and `~bits_per_sample` will be available.
=> PICARD-1652: Use TAK implementation from mutagen if available

picard/tagger.py
The counts of files and albums in the status bar does not get updated when files or albums get removed. This fixes this.
* This is a…
* JIRA ticket (_optional_): PICARD-1651
=> PICARD-1651: Update status bar counts on file/album removal

picard/tagger.py
On macOS the MB login / authorization code dialog can end up being hidden behind the options window.
Avoids the dialog getting hidden behind options and inaccessible on macOS.
* This is a…
* JIRA ticket (_optional_): PICARD-1655
Open MB login dialog window modal.
=> PICARD-1655: Open MB login dialog window modal

picard/formats/mp4.py, test/formats/test_mp4.py
* This is a…
Svaing custom tags to MP4 is not supported.
* JIRA ticket (_optional_): PICARD-1098
Save tags to `----:com.apple.iTunes:{tagname}`, where `{tagname}` is treated case insensitive, but case preserving. This is compatible with most software supporting custom MP4 tags.
=> PICARD-1098: Support custom tags for MP4 

.travis.yml, scripts/package/package-osx.sh
* This is a…
Also deploy all images to Github. This will allow to easily provide specific builds for different OS versions. We might need this if we want to provide notarized builds for macOS 10.14 and later, but still provide builds for 10.12. If we are lucky the 10.14 builds will also run on 10.12, but currently this is unclear.
* JIRA ticket (_optional_): PICARD-1631
=> travis: add macOS version to image name

picard/disc.py
Make sure to use the bundled libdiscid.0.dylib in macOS app.
* This is a…
On macOS a system wide install of libdiscid could be used instead of the one included with the app. Especially with the changes for using the hardened runtime in PICARD-1653 this can cause the app fail to load the discid support, since apps using the hardened runtime can only load signed libraries, and the system wide install (e.g. installed with brew) probably is not signed.
* JIRA ticket (_optional_): PICARD-1653
On macOS the libraries located via `ctypes.util.find_library` are ultimately searched for with `ctypes.macholib.dyld.dyld_find`. 
Set `DYLD_FALLBACK_LIBRARY_PATH` to override the search location. See https://macholib.readthedocs.io/en/latest/dyld.html
=> PICARD-1658: Ensure bundled libdiscid used in macOS app

picard/ui/searchdialog/__init__.py, picard/ui/searchdialog/album.py, picard/ui/searchdialog/artist.py, picard/ui/searchdialog/track.py
* This is a…
The search results in the album, track and artist search dialogs can be sorted by columns. In many columns track and numbers can show up mixed with text (e.g. release name, catalogue number, track title etc.). Natural sorting of numbers would improve the results ("Super Compilation 10" should show up after "Super Compilation 2").
* JIRA ticket (_optional_): PICARD-1659
Use the recently introduced natsort (see https://github.com/metabrainz/picard/pull/1325).
Kind of as a side effect this PR also makes the code simpler and fixes the somewhat ugly handling of length sorting (which tried to split the string representation of the time and convert it back to seconds, even though we have the numeric length in metadata). This last part was …
=> PICARD-1659: Use natural sorting for search dialog results

picard/ui/options/tags.py
* This is a…
The "Preserved tags" input in Options > Tags has an autocomplete feature, suggesting tags.
But this does not work too well:
- Completion only triggers, if you don't have spaces after the comma. So writing "artist, t" will not trigger suggestions starting with "t", only "artist,t" does
- Once a completion has been selected it is entered into the edit field, but the user has to manually add the comma to enter another one. It would make sense to enter the comma for them so it is easy to enter multiple tags
* JIRA ticket (_optional_): PICARD-1661
- Ignore leading / trailing whitespace in autocomplete prefix
- Add ", " to end of input when inserting suggestion
=> PICARD-1661: Improve preserved tags auto completion

appveyor.yml, picard/__init__.py, scripts/package/macos-package-app.sh, scripts/package/win-package-app.ps1, setup.py
This is in preparation for app signing, where I want more flexibility and also run the entire process easily from command prompt manually.
* This is a…
=> ci: Moved windows packaging code into PowerShell script

appveyor.yml, scripts/package/win-package-app.ps1
* This is a…
Windows binaries (both installed files and the installer itself) are not signed for Windows. For the installer this triggers a warning dialog.
* JIRA ticket (_optional_): PICARD-1467
Code sign the binaries on Windows. The certificate file must be set on Appveyor as a base64 encoded PFX file as secure $CODESIGN_PFX_BASE64 variable.
For now this uses a self signed certificate for testing.
=> PICARD-1467: Codesign Windows Picard binaries

org.musicbrainz.Picard.desktop
Update the supported mimetypes in the .desktop file.
* This is a…
Consider all supported file formats. Generated from reading the _mimes attribute of the mutagen file classes.
=> Updated the mime type list in desktop files

appxmanifest.xml.in
This will register the Picard Windows app to be able to handle the marked file types and Picard will be available in the "Open with" menu of these files.
* This is a…
* JIRA ticket (_optional_): PICARD-1669
See https://docs.microsoft.com/de-de/windows/apps/desktop/modernize/desktop-to-uwp-extensions#associate
=> PICARD-1669: Set supported file types for Windows 10 app

picard/formats/vorbis.py, test/formats/test_vorbis.py
Save FLAC files even if images are too large to embed.
* This is a…
FLAC has a maximum block size of 16 MB. Currently trying to save FLAC files with images that are larger than this gives a saving error. It is impossible to save the files at all.
* JIRA ticket (_optional_): PICARD-1662
Check the expected block size on save and only save images if they have a valid size. Log errors otherwise.
This is a fix for the immediate saving issue reported in PICARD-1662. This is not supposed to be a full solution. As noted in PICARD-1662 it would be preferable if Picard could detect this condition earlier and provide builtin resizing capabilities. This is tracked in PICARD-1663 and related tickets.
=> PICARD-1662: Do not save too large images to FLAC

requirements-macos.txt, requirements-win.txt
Updated to latest mutagen 1.43 for the Windows and macOS builds
* This is a…
https://mutagen.readthedocs.io/en/latest/changelog.html#release-1-43-0
The most important changes for Picard are probably:
- Fixes AIFF files getting corrupted
- AC3 and TAK support
- Fix collections ABCs deprecation warning
- Support OptimFROG encoder version >= 5.100
=> Use mutagen 1.43 for macOS and Windows builds

.gitignore, .travis.yml, MANIFEST.in, scripts/picard.in, setup.py, tagger.py.in
* This is a…
Disabling the auto update during build with "python setup.py build --disable-autoupdate" currently has no affect to Windows or macOS builds.
The reason is that those builds use tagger.py as the start script, and not scripts/picard.
* JIRA ticket (_optional_): PICARD-1675
Generate tagger.py from tagger.py.in during build and apply the auto update according to build config.
=> PICARD-1675: Disable autoupdate works for pyinstaller and local builds

test/formats/test_aac.py, test/formats/test_ac3.py, test/formats/test_mp4.py
=> isort import sorting fixes

INSTALL.md
Update install instructions for running locally to use `setup.py build`. This is required for tagger.py getting build since https://github.com/metabrainz/picard/pull/1370
* This is a…
=> Update install restructions to use setup.py build

picard/ui/playertoolbar.py, picard/ui/taglistview.py
* This is a…
Instead of overriding `QWidget.event()` use more specific event handlers if available.
=> Use specific event handlers instead of generic event() if possible

scripts/package/macos-notarize-app.sh, scripts/package/macos-package-app.sh, scripts/package/macos-setup.sh
=> Fixed linting issues in shell script reported by codacy.

picard/ui/cdlookup.py
* This is a…
The user might want to load more than one result from the CD lookup dialog, e.g. to compare full metadata. This is similar to #1335 which implemented this for the search dialogs. This also makes these dialogs, that look very similar, to behave more similar.
* JIRA ticket (_optional_): PICARD-1680
Allow multiple selection, load all selected entries.
We might investigate to unify this dialog more with the release search dialog. After all CD lookup is a kind of specialized release search.
Either we at least make this dialog behave similar (e.g. unify displayed columns as much as it makes sense) or we can even reuse functionality.
=> PICARD-1680: Allow selecting multiple results in CD lookup dialog

picard/acoustid/__init__.py, picard/file.py
* This is a…
Previously only the first result (which has the highest score) was used. Now all results are used, weighted by their scores.
* JIRA ticket (_optional_): PICARD-1565
Create a recording list to match against from all results, but use the score to weight the recordings.
=> PICARD-1565: Consider all results returned from AcoustID lookups

.github/workflows/github-release.yml, scripts/package/changelog-for-version.py
This ads a Github Action that updates a new tagged release with proper title and changelog.
* This is a…
Implement a Github Action that runs only on release-* tags. It updates the title and changelog entry. For extracting the changelog a new script `changelog-for-version.py` is added.
As an test https://github.com/phw/picard/releases/tag/release-test was created using this action. This was the corresponding workflow run: https://github.com/phw/picard/commit/b2de297439eba89f4d0dbb0eef4331be4f676261/checks?check_suite_id=336456928
=> Update Github release from changelog

.github/workflows/package-macos.yml, .github/workflows/package-windows.yml, .github/workflows/run-tests.yml
=> Github Actions: Run on pull requests

.github/workflows/package-macos.yml, scripts/package/macos-setup.sh
* This is a…
Cache build libdiscid on macOS to reduce build time. We usually only have to rebuild this on version changes.
=> Github Actions: Cache libdiscid for macOS builds

picard/file.py, picard/ui/metadatabox.py, picard/util/preservedtags.py
* This is a…
Preserved tags currently are case senstitive. This is problematic custom tags, which might have different casing depending on which software wrote them.
* JIRA ticket (_optional_): PICARD-1523
Make preserved tags comparisson case insensitive. For this adapt the implementation used by metadatabox and reuse it in file.py (preserved tags are only handled at those two places).
In practice this only affects custom, unmapped tags, since names for mapped tags are all lowercase anyway.
=> PICARD-1523: Compare preserved tags case-insensitive

picard/ui/edittagdialog.py, picard/ui/metadatabox.py
Use multiline editor for lyrics and comments. This allows editing lyrics and comments in the metadatabox without loosing linebreaks.
* This is a…
Lyrics and comment tags often span multiple lines, but Picard only allows editing them in a single line.
* JIRA ticket (_optional_): PICARD-1682
=> PICARD-1682: Use multiline editor for lyrics and comments

appxmanifest.xml.in, installer/picard-setup.nsi.in, org.musicbrainz.Picard.appdata.xml.in, picard.spec, picard/__init__.py, setup.py
Introduce DISPLAY_NAME constant for use in metadata
This allows us to use the same value on multiple places where we need to specify a product display name for Picard.
* This is a…
=> Introduce DISPLAY_NAME constant for use in metadata

.prospector.yml
On Codacy this does not support Python 3 syntax and we have other checks in place for syntax.
Attempt to stop wrong syntax error reportings on Codacy.
* This is a…
=> Ignore syntax errors for prospector pyflakes checks.

picard/const/__init__.py, picard/const/attributes.py, picard/ui/edittagdialog.py, setup.py
This enhances the tag editing by:
- Provide `YYYY-MM-DD` placeholder text for date tag editing, `YYYY` for `originalyear` tag editing
- Provide autocompletion for `releasetype`, `releasestatus`, `releasecountry` and `media` tags, based on attribute data from MB
* This is a…
* JIRA ticket: PICARD-115, PICARD-1683
=> PICARD-115 / PICARD-1683: Tag editing UI helpers

picard/ui/edittagdialog.py, picard/ui/ui_edittagdialog.py, ui/edittagdialog.ui
* This is a…
Allow changing the order of multi-value tags in the tag editor dialog.
* JIRA ticket (_optional_): PICARD-1684
Allow sorting the entries by drag and drop or via dedicated buttons.
=> PICARD-1684: Allow reordering tag values in tag editor

picard/ui/edittagdialog.py
* This is a…
Editing already changed tags again duplicated all tag values.
The issue was introduced in https://github.com/metabrainz/picard/pull/1397
Unregister the event listeners for adding rows while updating the data.
=> Fixed EditTagDialog duplicating data on save

picard/ui/playertoolbar.py, picard/ui/widgets/__init__.py
Move a couple of generic reusable widgets from specific modules into picard.ui.widgets.
* This is a…
=> Move reusable widgets to picard.ui.widgets

picard/ui/widgets/__init__.py
If text is shortened in a ElidedLabel set the original text as a tooltip. That way the user is still able to discover the full text even if only a part is visible as shown below:
* This is a…
=> ElidedLabel: If text is elided set full text as a tooltip

picard/ui/ui_options_tags.py, ui/options_tags.ui
Fixed description label for preserved tags. Tags are now compared case insensitive
* This is a…
=> Fixed description label for preserved tags

picard/track.py
* This is a…
If a main view column is supposed to show data that is only available for a file not the track, this column will stay empty if there is only a single file matched to a track.
If only a single file is linked to a track and the data requested for a column is not available for the track, show the file column data instead.
This by default currently won't have a big effect, but it will help if we offer more selectable columns for the main tree views and it helps now for users who add custom columns via plugins.
=> Show file data in track columns

picard/ui/options/releases.py, picard/ui/widgets/__init__.py
This better reflects user expectation and slider behavior in other applications across all platforms.
* This is a…
Currently sliders in Picard just move one step into the according direction when clicked somewhere. This is the default Qt behavior for Qt on systems other than macOS. This affects the sliders for preferred releases and volume and speed control of the player.
But the typical behavior of sliders on all systems I have tested (macOS, Windows 10, Linux GNOME, Linux KDE Plasma) is to directly jump at the position the user clicked on. I think this is also expected user behavior. Interestingly even the Qt sliders already work like this on macOS.
I propose to change the sliders in Picard to behave like this on all platforms. We already …
=> PICARD-1692: Use ClickableSlider for all sliders in the UI

README.md
* This is a…
Add a Github Actions status badge and replace the currently unused CI badges with it.
=> Add Github Actions status badge to README.md

requirements-win.txt
=> Use PyQt 5.14.1 for Windows builds

picard/ui/__init__.py, picard/ui/mainwindow.py
* This is a…
When fingerprinting is disabled and the user tries to use scan, Picard asks the user if they want to open the options to configure fingerprinting. After the user has enabled fingerprinting Picard is supposed to perform the action. This commit restores this functionality which broke in f8eb755.
See discussion in https://github.com/metabrainz/picard/pull/1423
* JIRA ticket (_optional_): PICARD-1699
Connect to dialogs finished signal to handle this asynchronously.
=> PICARD-1699: Fix run fingerprinting after asking user to enable it

picard.spec, requirements-build.txt, scripts/package/win-common.ps1
Allows us to remove some Windows specific workarounds, fixes a CVE related to the portable onefile install.
See https://pyinstaller.readthedocs.io/en/v3.6/CHANGES.html for details
* This is a…
* JIRA ticket (_optional_): PICARD-1703
=> PICARD-1703: Upgrade to PyInstaller 3.6

picard/file.py
Fixes a regression introduced in 2cc0b35 were an AcoustId lookup loading a NAT showed an empty NAT.
* This is a…
=> Fixed AcoustId lookup loading empty nat

picard.spec, picard/plugin.py, picard/tagger.py
Allows opening supported file types on macOS from Finder or by drag and drop on the dock icon.
* This is a…
* JIRA ticket (_optional_): PICARD-1402
Register for supported file types. Register for actually supported types (see https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html) and also by file extension (needed for filetypes otherwise unknown to macOS, e.g. Musepack).
=> PICARD-1402: Register macOS app for supported file types

org.musicbrainz.Picard.appdata.xml.in, po/appstream/de.po, po/appstream/es.po, po/appstream/fi.po, po/appstream/fr.po, po/appstream/he.po, po/appstream/it.po, po/appstream/ja.po, po/appstream/nl.po, po/appstream/picard-appstream.pot, po/appstream/pt.po, po/appstream/pt_BR.po, po/appstream/sq.po, po/appstream/zh-Hans.po, po/appstream/zh.po, po/appstream/zh_CN.po, po/appstream/zh_TW.po, setup.py
This extends the appstream description of Picard (used in Linux app stores, but which I also want to utitize for the Windows store entry) by adding a paragraph about how Picard helps to organize the music library.
Also reverts the use of display-name placeholder in this file as it broke localization.
* This is a…
=> Extend appstream description

picard/metadata.py, test/test_metadata.py
=> Move code outside Metadata class, to ease testing

.github/workflows/package-macos.yml, scripts/package/macos-setup.sh
Fix macOS notarization by using a fcalc binary that was built with a current macOS SDK (>= 10.9 is required). The binary should still be compatible with older macOS versions but can be successfully notarized.
Using a macOS fpcalc build from custom repository until an official new version build with newer macOS SDK is available. I have already submitted the necessary build updates to chromaprint, see https://github.com/acoustid/chromaprint/pull/65
* This is a…
* JIRA ticket (_optional_): PICARD-1707
=> PICARD-1707: Download updated macOS fpcalc build

picard/formats/apev2.py, picard/formats/asf.py, picard/formats/id3.py, picard/formats/mp4.py, test/formats/common.py
* This is a…
`lyrics` tags could not be deleted from most supported tag formats.
* JIRA ticket (_optional_): PICARD-1711
Similar problems likely apply to the comment tag. But this is handled only partially in MP4 and ASF anyway. I'll look into that separately when tackling PICARD-239
=> PICARD-1711: Fix deleting lyrics tag from ASF, APE, ID3 files

picard/metadata.py, test/test_metadata.py
=> Tidy up Metadata, explode in smaller bits, better testing

picard/ui/mainwindow.py
Use standard search shortcut (actually Ctrl+F on all OS) to focus search input.
* This is a…
=> PICARD-1714: Use standard search shortcut to focus search input

picard/ui/__init__.py, picard/ui/widgets/editablelistview.py
Use standard key sequences instead of custom checks in keyPressEvent.
Ensures platform specific shortcuts are used.
* This is a…
=> Use standard key sequences instead of custom checks in keyPressEvent.

picard/ui/edittagdialog.py
* This is a…
The multiline editing for comment and lyrics tags (see PICARD-1682) did not work for tags in the format `lyrics:{desc}`
* JIRA ticket (_optional_): PICARD-1682
=> PICARD-1682: Fix multiline editing for lyrics:{desc} tags

picard/coverart/image.py, picard/file.py, picard/util/scripttofilename.py, test/test_scripttofilename.py
Allow changing the file extension with scripting in the file naming script. E.g. something like this is possible now:
```
$if($eq(%_extension%,fla),$set(_extension,flac))
```
Or standardizing file extensions for MP4:
```
$if($eq(%_extension%,mp4),$set(_extension,$if($is_video(),m4v,m4a)))
```
* This is a…
* JIRA ticket (_optional_): PICARD-1715
* Forum discussion: https://community.metabrainz.org/t/incorrect-extension-value/460939
=> PICARD-1715: Allow changing file extension in renaming script

picard/script.py, test/test_script.py
Before introduction of new functions, we had a pattern: "name" script function was defined by "func_name"
Recent patches changed this, introducing inconsistencies.
Also we have inmulti and lenmulti, so stick to this scheme for getmulti and others.
func_find_str -> func_find
find_str -> find
func_reverse_str -> func_reverse
reverse_str -> reverse
func_get_multi -> func_getmulti
func_foreach_multi -> func_foreach
func_while_loop -> func_while
func_map_multi -> func_map
A new decorator named `script_function()` is introduced to simplify registration of script functions.
* This is a…
=> Unify new and old script function names

picard/metadata.py, test/test_metadata.py
Improve results when matching files to multi-disc albums by considering the disc number. This helps especially on multi-disc compilations where the same tracks or even same track list appears on different mediums (e.g. https://musicbrainz.org/release/a49b7342-f038-380f-80c6-9a7832bbd3fa)
* This is a…
* JIRA ticket (_optional_): PICARD-1723
* Forums discussion: https://community.metabrainz.org/t/picard-2-3-beta-1/461345/10
Add discnumber to comparisson. Use a slightly lower weight then tracknumber, as the discnumber is often less reliable in badly tagged files.
=> PICARD-1723: Consider disc number when comparing metadata

picard/ui/itemviews.py
* This is a…
On scrolling sometimes the fingerprint indicator column got partial repaints, which were not supported. Completely repaint the cell now.
* JIRA ticket (_optional_): PICARD-1725
Repaint the whole widget area, not only the updated area indicated by the event.
=> PICARD-1725: Fix rendering artifacts in fingerprint indicator

picard/util/tags.py
* This is a…
* JIRA ticket (_optional_): PICARD-1727
=> PICARD-1727: Fix translating performer tag

.github/workflows/package.yml, test/test_file.py
Make the macOS binaries run on macOS 10.12 again.
* This is a…
Latest Picard binary builds for macOS did not start on macOS 10.12. The reason was the bundled Python being build for macOS 10.13 or later only.
* JIRA ticket (_optional_): PICARD-1733
Use the Python binaries downloaded from python.org again. The macos-setup.sh script already supported this, just configure the build to use it again.
Tested successfully on macOS 10.12 and 10.15
=> PICARD-1733: Fix builds for macOS 10.12

picard/script.py, test/test_script.py
* This is a…
* **Describe this change in 1-2 sentences**: Add a scripting function to return the current date and time.  This would be useful to record the last time the metadata was updated in a file.
There is currently no way to retrieve the current date and time to a tag.  This could be useful for including the timestamp of the last metadata update to a file.
* JIRA ticket: PICARD-1729
Added the `$datetime()` scripting function to return the current date and time.  This function accepts an optional parameter to set the format string (using the strftime formatting).
Another pull request to update the `Scripting` documentation on Picard Website will be prepared if this addition is accepted.
=> PICARD-1729: Add $datetime() function and associated tests

picard/ui/mainwindow.py, picard/ui/options/interface.py
* This is a…
The label "Generate AcoustID Fingerprints" is too long for the toolbar. 
* JIRA ticket (_optional_): PICARD-1736, PICARD-1737
Shorten this label to "Generate Fingerprints" when used in the toolbar, keep the longer label for the menu.
Also added a keyboard shortcut for this action.
=> PICARD-1736: Shorten label for "Generate AcoustID fingerprint" in toolbar

requirements-macos.txt, requirements-win.txt
=> Bundle mutagen 1.44 for macOS / Windows builds

picard/const/__init__.py, picard/util/bytes2human.py, picard/webservice/__init__.py
=> Improve Network Cache size logging, use SI human-readable units 

picard/ui/options/plugins.py
Simplify `PluginActionButton.open_plugin_dir` and leave the platform dependent handling to Qt. Tested on Linux and Windows.
* This is a…
=> Simplify the open_plugin_dir implementation

picard/acoustid/__init__.py, picard/acoustid/manager.py, picard/tagger.py, test/test_acoustidmanager.py
* This is a…
Avoids issues with exceeding the body size limit for submission requests. Also this makes the entire submission process more robust, as the submission of many fingerprints can now succeed partially instead of failing in its entirety.
* JIRA ticket (_optional_): PICARD-1688
Submit fingerprints in batches of 240.
The upper limit is around 250 fingerprints, which is equivalent to roughly 1 MiB of data. But use a batch count of actually 240 fingerprints per submission to have some leeway for varying data.
=> PICARD-1688: Submit AcoustID fingerprints in batches

picard/formats/asf.py
As a small addition to PICARD-1521 store the `originalfilename` tag also to ASF.
* This is a…
See also:
- http://msdn.microsoft.com/en-us/library/ms867702.aspx
- https://help.mp3tag.de/main_tags.html
* JIRA ticket (_optional_): PICARD-1740
=> PICARD-1740: Store originalfilename to ASF as WM/OriginalFilename

picard/script.py
* This is a…
* **Describe this change in 1-2 sentences**:  Removes the unused `try` block from the `$slice` scripting function.
The `$slice` scripting function contains a `try/except` block where the exception is never triggered.  This should be removed.
Remove the unnecessary `try/except` around the code block.
=> Remove unnecessary 'try' block from $slice function

picard/tagger.py
Specifying an invalid regex in Options > Advanced > Ignore paths (ignore_regex) and loading a file will crash Picard. E.g. settings this to something invalid like "["
* This is a…
* JIRA ticket (_optional_): PICARD-1744
Catch and log the exception
=> PICARD-1744: Fixed crash on invalid ignore_regex

.github/workflows/package.yml, picard.spec
Fix the libdiscid builds to run on macOS 10.12 Sierra.
* This is a…
* JIRA ticket (_optional_): PICARD-1745
Set MACOSX_DEPLOYMENT_TARGET to 10.12. Tested this on macOS 10.12.
=> PICARD-1745: libdiscid macos 10.12 compatibility

picard/releasegroup.py, picard/util/__init__.py, test/test_utils.py
* This is a…
Long list of countries make display of alternative releases far too wide
* JIRA ticket (_optional_): PICARD-1748
Limit number of countries displayed to 10
=> PICARD-1748: limit number of countries displayed to 10

picard/ui/mainwindow.py
* This is a…
Pressing the delete shortcut currently always removes files or albums, even if the metadatabox is focused.
* JIRA ticket (_optional_): PICARD-1754
This reverts 84d8341. QKeySequence.Delete is still used for item removal on the itemview and metadatabox panes (see MainWindow.keyPressEvent at https://github.com/metabrainz/picard/blob/master/picard/ui/mainwindow.py#L192). But if this action is registered globally item removal interfers with removing elements from MetadataBox.
=> PICARD-1754: Removed QKeySequence.Delete shortcut for remove action

appxmanifest.xml.in
Update the languages displayed on the Windows Store.
* This is a…
Windows Store currently only lists English as available language
* JIRA ticket (_optional_): PICARD-1755
For now limit this to the languages for which there is also a localized store page (which is based on completion of translating the appstream data).
This needs testing, I don't know whether this works as expected.
=> PICARD-1755: Specify available languages for Windows Store.

picard/__init__.py, picard/plugin.py, picard/pluginmanager.py, picard/ui/options/plugins.py, test/test_versions.py
* This is a…
Plugin update check is assuming version 1.10 < 1.9 due to comparing the version segments as strings.
* JIRA ticket (_optional_): PICARD-1756
Use `Version` class to implement version comparison. This also simplifies version handling at some points.
=> PICARD-1756: Fix plugin update version comparison

picard/script.py, test/test_script.py
* This is a…
Coverage of script functions code is incomplete
Improve tests and code so everything is covered, including corner-cases.
After these changes coverage is 99%, and 100% on script functions code.
=> Improve script functions test coverage
