metabrainz/picard

picard/ui/tagsfromfilenames.py
An exception was thrown when tags_from_filenames_format was not set or empty.
Fixes [PICARD-681](http://tickets.musicbrainz.org/browse/PICARD-681)
=> Fixed tags from filename dialog no opening on fresh install.

picard/mbxml.py
Fixes [PICARD-375](http://tickets.musicbrainz.org/browse/PICARD-375)
The ticket was already partially fixed as https://github.com/musicbrainz/picard/commit/008bee3e2e0f0ec2aa5d7e1aa51e12c3bc02d9eb does de-duplicate all MBID lists. But for this ticket to be completely solved I think also the work list should be de-duplicated.
=> Deduplicate work names in tags.

picard/track.py
Use full tag names and not substrings for comparisson so that e.g. ignoring "someothertag,hip hop rap" does not also ignore "rap". Also this change makes the comparison case insensitive to match the behavior on MB.org.
Fixes [PICARD-335](http://tickets.musicbrainz.org/browse/PICARD-335)
=> Improve folksonomy tag comparison for ignored tags.

picard/ui/mainwindow.py
This will disable the "Tags from filenames" action whenever it is unavailble. Without this fix the action stays enabled, but the dialog will just not open when clicking on the menu entry.
Fixes [PICARD-688](http://tickets.musicbrainz.org/browse/PICARD-688)
=> Enable "Tags from filenames" only if applicable.

picard/formats/mp4.py
Requires mutagen 1.27, but is backwards compatible with older versions.
Fixes [PICARD-683](http://tickets.musicbrainz.org/browse/PICARD-683)
=> PICARD-683: For MP4 files add the codec description to ~format.

picard/ui/options/cover.py
http://tickets.musicbrainz.org/browse/PICARD-705
=> [PICARD-705] Disable "caa_approved_only" by default

picard/acoustidmanager.py, picard/webservice.py
This helps identify the root cause for issues like [PICARD-82](http://tickets.musicbrainz.org/browse/PICARD-82) or [PICARD-706](http://tickets.musicbrainz.org/browse/PICARD-706) which are otherwise hard to impossible to debug with only some user info given.
Ticket for this imrpovement: [PICARD-708](http://tickets.musicbrainz.org/browse/PICARD-708)
=> PICARD-708: Log the server error message on Acoustid submission errors.

picard/ui/options/fingerprinting.py, picard/ui/ui_options_fingerprinting.py, ui/options_fingerprinting.ui
This patch validates the selected fpcalc executable in the options, if fingerprinting is enabled. The validation is done by running `fpcalc -v` and checking the output.
Fixes [PICARD-707](http://tickets.musicbrainz.org/browse/PICARD-707)
=> PICARD-707: Validate the fpcalc executable in options.

picard/ui/mainwindow.py
The behavior wasn't consistent whether user was using custom file selection dialog (which may return a list of directories), and the default one.
The parent directory of the selected directory is saved as "current_directory", which is returned by find_starting_directory() and passed to file selections dialogs as root directory
See http://tickets.musicbrainz.org/browse/PICARD-726
=> PICARD-726: save parent directory after folder selection in any case

picard/ui/mainwindow.py, picard/ui/util.py
Move it to its own class in picard.ui.util so it can easily be re-used.
Make the code a bit more robust (using findChildren() instead of findChild() which may have undefined behavior) and fix obsolete Qt DirectoryOnly.
=> Cleanup multiple directories selection code

picard/ui/itemviews.py
Some people don't know about the CTRL-A shortcut or shift click action to select all items in one of the treeview panes. This commit adds a discoverable context menu entry for those people. Typical use cases are selecting all items to then remove or save all items at once.
Fixes [PICARD-476](http://tickets.musicbrainz.org/browse/PICARD-476) and probably even [PICARD-210](http://tickets.musicbrainz.org/browse/PICARD-210).
Do you think this is valuable without adding too much clutter? Would you agree to consider this a solution to [PICARD-210](http://tickets.musicbrainz.org/browse/PICARD-210), too?
=> Add an context menu entry to select all items in a treeview.

picard/tagger.py, picard/ui/options/about.py, picard/util/versions.py
- keep versions sorted, use OrderedDict
- add -V/--long-version command-line option
- add Qt version in the list of versions
- update About page
Fixes http://tickets.musicbrainz.org/browse/PICARD-734
=> Add a -V/--long-version command-line option, display Qt version

picard/album.py, picard/mbxml.py, picard/track.py, picard/ui/options/folksonomy.py, picard/ui/ui_options_folksonomy.py, ui/options_folksonomy.ui
When the option is disabled, if no tags are found for release / release group, no genre is set.
With this option is checked, Picard will try to use album's artists tags in this case.
Ie. for release
http://musicbrainz.org/release/ec102c8e-981b-4aec-b1e4-35eda11f2bb6 it will set Genre to "Doom metal" even though there are no tags for release or release group.
http://tickets.musicbrainz.org/browse/PICARD-738
=> Add an option to fallback on artist's tags

picard/coverart/__init__.py, picard/coverart/image.py, picard/coverart/providers/__init__.py, picard/coverart/providers/local.py, picard/ui/options/cover.py, picard/ui/ui_provider_options_local.py, ui/provider_options_local.ui
It adds a cover art provider, which, when enabled, looks for files like cover.jpg, etc.. in local directory (where sound files are) and use image files found as cover art.
Inspired by http://forums.musicbrainz.org/viewtopic.php?id=2859
Solves:
http://tickets.musicbrainz.org/browse/PICARD-137
Related:
http://tickets.musicbrainz.org/browse/PICARD-257
http://tickets.musicbrainz.org/browse/PICARD-187
=> Add support for local cover art

picard/formats/id3.py
Sometimes used as alternative for `.mp2`.
=> Recognise .m2a file extension.

picard/ui/filebrowser.py
Enables sorting of directories/files on drives other than the system
root (c:) on Windows.
Fix for http://tickets.musicbrainz.org/browse/PICARD-754
=> PICARD-754: fix sorting in filebrowser

picard/track.py
When all tags have 0 votes, maxcount is 0, leading to a division by zero exception.
So filter the tags dict to only keep tags having positive votes count.
=> PICARD-753: ignore downvoted tags

picard/oauth.py
`setHost(port)` should be `setPort(Port)` and logic for port == 443 or port != 80 needs fixing.
=> Fix bug in oauth when port == 443

contrib/plugins/albumartist_website.py, picard/browser/filelookup.py, picard/oauth.py, picard/ui/options/plugins.py, picard/util/__init__.py, picard/webservice.py
This moves code that manually builds a QUrl object into a function in picard.util.
It does introduce a backwards incompatibility because setting a path with query parameters in it via QUrl.setPath will later encode the question mark, which building the QUrl object via QUrl.fromEncoded did not do (because it correctly figured out that the question mark marks the beginning of the query parameters). The only affected plugins seem to be `fanarttv` and `albumartist_website`. This is part of our public API via tagger.xmlws that's available to at least metadata processors.
One thing I'm not sure about is the change to picard/browser/filelookup.py: It seems to include a special case for opening collections in the browser via HTTPS all the time, but not anything else. I couldn't figure out from …
=> Move QUrl building code into a function

picard.desktop, picard/tagger.py
Fixes [PICARD-761](http://tickets.musicbrainz.org/browse/PICARD-761)
Gnome Shell currently fails to determine that a running Picard window belongs to the Picard application (meaning an application that has a .desktop file and is available in the application menu). That has some bad effects on both the Alt-Tab switcher and also the dock (see PICARD-761). Gnome applies various strategies to get the app from a running window, see https://git.gnome.org/browse/gnome-shell/tree/src/shell-window-tracker.c?h=gnome-3-16#n329 . Currently all approaches fail, as a result Gnome treats every Picard window as an application-less window.
This patch sets a unique WM_CLASS for Picard which Gnome can use to match it to the .desktop file.
Without this patch:
With patch:
I am not entirely sure why this is …
=> Fix for Gnome 3 Alt-Tab application name and window grouping.

picard/coverart/providers/__init__.py, picard/coverart/providers/caa.py
I wonder why **old** was not returned in the first place. Without it, *next_in_queue* was unable to check for *WAIT* signal, as None was returned.
http://tickets.musicbrainz.org/browse/PICARD-780
=> PICARD 780: CAA cover art provider runs even if cover art has already been loaded

picard/webservice.py
as reported in http://tickets.musicbrainz.org/browse/PICARD-788
Implements [the recommendation in the Qt documentation regarding QNetworkRequest.RedirectionTargetAttribute](http://pyqt.sourceforge.net/Docs/PyQt4/qnetworkrequest.html):
>The returned URL might be relative. Use QUrl.resolved() to create an absolute URL out of it.
Also fixes a issue where during redirects query arguments would be treated as part of the path and thus percent-encoded, by using `redirect.path()` and `redirect.queryItems()`, instead of directly using the path in the new request.
>D: 20:40:08 Waiting 510 ms before starting another request to ('anidb.net', 80)
>D: 20:40:08 Last request to ('anidb.net', 80) was 2515 ms ago, starting another one
>D: 20:40:08 GET …
=> Fix relative redirects

picard/mbxml.py, picard/track.py
Commit 334eba9d2823ac9d73f09b087643f6a4df745aaf added support for
falling back to the album artist's folksonomy tags for releases/release
groups without tags. This change adds further support to that to allow
compilation releases to use the track artists' tags since album artist
won't work.
=> Fall back to track artist tags for genre on comps.

picard/coverart/providers/caa_release_group.py
The method is using `super(CoverArtProviderCaaReleaseGroup, self).enabled()` which
is wrong, causing it to be skipped when CAA release has no cover artwork available.
=> PICARD-801: fix CoverArtProviderCaaReleaseGroup.enabled()

picard/ui/mainwindow.py
Currently, a new instance of LogView is created each time someone clicks `View Error/Debug Logs`, resulting in multiple log dialogs displaying same information. That would not be intentional.
=> PICARD-804: Avoid multiple instance of history and log dialogs

setup.py, tagger.py
Some distributions have switched to Python3 as default. So, /usr/bin/env
python opens up wrong interpreter.
=> Mention python2 in shebang

picard/webservice.py
On redirect, https urls without specified port defaults to port 80 causing an infinite redirect loop.
There are more issues:
- redirect 301 should be cached by Picard (it is handled as a 302 for now)
- the current handling of schemes (http vs https) and ports (80 vs 443 vs user-defined port) is quite messy
- this kind of infinite loop is not detected by Picard
=> PICARD-811: workaround https with port 80 issue

picard/ui/mainwindow.py
Need to pass mainwindow as parent to these dialogs so they quit
with the main window. This bug was introduced in -> 3f2f0f3.
Should I create a separate ticket for this. This was the original ticket -> http://tickets.musicbrainz.org/browse/PICARD-804.
=> Prevent stale log and history dialogs

picard/util/astrcmp.c
Fixes the gcc 6.1.1 warning:
```
picard/util/astrcmp.c: In function 'astrcmp':
picard/util/astrcmp.c:154:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
if (!PyArg_ParseTuple(args, "UU", &s1, &s2))
^~
picard/util/astrcmp.c:157:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
us1 = PyUnicode_AS_UNICODE(s1);
^~~
```
=> Make astrcmp indentation consistent

resources/img-src/picard.svg, setup.py
distutils does not seem to have an option to rename data_files on
install, so rename Picard_logo_no_text.svg -> picard.svg.
https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
=> Install SVG icon

INSTALL.txt, picard/formats/id3.py, picard/formats/mutagenext/compatid3.py, test/test_compatid3.py
Three parts:
(1) The monkey patching of EncodedTextSpec to ignore encoding errors
when using latin1 as encoding.
This gets replaced with a new id3text function which makes sure
that any value passed to mutagen can be encoded with the selected
encoding
(2) MultiSpec monkey patch to not null terminate a list of strings.
While this is valid according to the spec mutagen decided to terminate
all strings (not only the text lists handled here). If this is a
problem it should be discussed upstream (mutagen).
(3) compatid3 which implemented id3v2.3 support and added some
additional frames.
This gets replaced with the id3v2.3 support implemented upstream.
The additional frames still get passed to mutagen and, to match
the previous implementation, update_to_v23() gets wrapped to
allow some v2.4 …
=> id3: Remove various mutagen hacks which no longer work with newer mutagen

picard/mbxml.py, picard/tagger.py, picard/ui/mainwindow.py, picard/ui/searchdialog.py, picard/webservice.py
Allow searching for artists from a dialog. I'm not sure whether it will be super useful, but it's better for consistency with other two dialog which are *Album* (PR: https://github.com/metabrainz/picard/pull/486) and *Track* (PR: https://github.com/metabrainz/picard/pull/475). This dialog displays basic information about the artist, and provides an option to look him/her up in web browser.
This PR is based on rebase of #486. It would be helpful if review upto commit 851b581 be provided there.
=> Search for artists from dialog

picard/util/__init__.py, test/test_amazon_urls.py
Picard 1.3.2 cannot fetch cover art from amazon.
Because, picard can only fetch information from amazon without ssl.
But some releases have an amazon url with https.
This commit fix regex for amazon url parse function.
=> PICARD-848: Cannot fetch cover art from amazon link contains https scheme.

setup.py, test/__init__.py
When the tests are run using nosetests, the Qt uses sip API v1 by
default which causes nosetests to fail when running version_from_string
function which returns a QVariant object instead of a string.
=> Add support for nosetests

picard/ui/itemviews.py
When multiple files were linked to the same track and the changes to
the items were saved, the parent album icon didn't update to reflect
the change.
This was because of a buggy item.save() function which led to an update
call to the update() method of files. The files on update did not recu-
rsively call their parent items to be updated too.
=> PICARD-851: Correctly update parent items on save

picard/metadata.py
When a track with a non valid total-tracks has multiple release matches
on Picard, picard tries to apply a linear combination  of weights to
detect the best match. In the process it tried to typecast totaltracks
into and int.
This causes a ValueError when totaltracks is not castable into an int.
Added a try except clause to take care of the same.
=> PICARD-855: Adds errorhandler for missing meta-data

picard/file.py, picard/formats/mp4.py, picard/formats/vorbis.py, picard/metadata.py, picard/ui/metadatabox.py, test/test_formats.py
This implements the ability to remove existing tags from within Picard. The user can remove all values of a multivalue tag or delete an entire tag. Deleted tags will be removed from the file on saving.
This fixes both [PICARD-287](http://tickets.musicbrainz.org/browse/PICARD-287) and [PICARD-546](http://tickets.musicbrainz.org/browse/PICARD-546)
**This is work in progress**. The general functionality and the UI is ready, but the deletion requires format specific code I have so far implemented only for MP4 and Vorbis. It still needs to be implemented for ID3, ASF and Ape (that's why the tests are failing).
I would like to gather some early feedback. One thing that is obvious from the changes to formats/mp4.py and formats/vorbis.py that the code required to get the proper tag name …
=> Removable tags

picard/script.py
An arbitrarily large value if entered in GUI would cause the system to become unresponsive.
=> PICARD-865: Add limit to length in $num

picard/browser/browser.py, picard/tagger.py
While using the 'Lookup in the Browser' option, clicking the tagger button loads the album into Picard but since Picard doesn't come to surface, it looks like as if nothing is happening. This PR just adds a bring_tagger_front() function and makes a call it to it when one clicks on the tagger button.
=> PICARD-858: Remove apparent non-functionality of the tagger button

.gitignore
./scripts/picard gets build with setup.py build, so let's ignore it to make sure it doesn't accidentally get checked into git at some point.
=> Gitignore scripts/picard.

picard/ui/mainwindow.py
The submit button doesn't actually submit any information to MusicBrainz, but instead submits acoustic fingerprint information to AcoustID.org. The title of this button comes up over and over as a point of confusion for new users of Picard, so renaming it to be more precise will hopefully alleviate this point of confusion.
Jira ticket: https://tickets.metabrainz.org/browse/PICARD-897
=> PICARD-897: Rename "Submit" button to "Submit AcoustIDs".

picard/ui/options/cover.py, picard/ui/options/plugins.py, picard/ui/options/releases.py, picard/ui/options/scripting.py, picard/ui/sortablecheckboxlist.py
With reference to [Issue 870](https://tickets.metabrainz.org/browse/PICARD-870), Options in Cover Art Providers and taggers scripts were not removing old entries during a reset. This PR simply does that.
https://tickets.metabrainz.org/browse/PICARD-870
https://tickets.metabrainz.org/browse/PICARD-873
https://tickets.metabrainz.org/browse/PICARD-874
=> PICARD-870,873,874: Fix for List options not updating and saving on reset

picard/ui/options/dialog.py
Informative text wraps based on size of text
Before
After
=> PICARD-911: Messagebox wraps and displays title inappropriately

picard/i18n.py
See [PICARD-917](https://tickets.metabrainz.org/browse/PICARD-917)
Tested on Windows 7 and Windows 10.
=> PICARD-917: Use UI language as default on Windows

picard/plugin.py
Went for a more code-efficient method than adding a lot of try/except clauses.
=> PICARD-915: Handle Attribute errors to return None

picard/ui/searchdialog.py, po/picard.pot
Do we need a ticket for this? It is basically just a fixup for the builtin search.
Speaking of that: I could not find a ticket for the builtin search, but I guess we should have one for the release notes, right?
=> Do not translate widget names

picard/ui/options/dialog.py
I know that another [PR](https://github.com/metabrainz/picard/pull/491) already exists for this [issue](https://tickets.metabrainz.org/browse/PICARD-408), I just wanted to put forward this approach. Rather than simply increasing the default options dialog size, I have set the minimum width according to the contents of the pages_tree. 
This allows the splitter to nicely snap at the perfect pane size.
Note that I have expanded all the items to show that it fits, they're not expanded by default.
=> PICARD-408: Options pane is obscured

picard/plugin.py
https://tickets.metabrainz.org/browse/PICARD-945
Instead of presenting as a warning if a given plugin directory isn't found, just notify as an info-level message, as per https://chatlogs.metabrainz.org/brainzbot/metabrainz/msg/3802418/ – though demoting to info instead of debug.
=> PICARD-945: Demote non-existent plugin warning to info message.

picard/config.py, picard/config_upgrade.py, picard/tagger.py
It seems that if the ini-based config was initialized before creating the app instance, Qt would do a different initialization sequence and some configs would not be loaded. That caused it to not look for plugins in the app bundle.
@zas @mwiencek Can you please review?
=> Fix OS X package

picard/ui/mainwindow.py
Resolves [PICARD-942](https://tickets.metabrainz.org/browse/PICARD-942).
Make "Open Containing Folder" and "Open in Player" work for remote files.
See [QTBUG-13359](https://bugreports.qt.io/browse/QTBUG-13359) for cause and workaround.
Tested on Windows. Needs testing on Mac / Linux.
=> PICARD-942: Fix explore/play remote folders/files

README.md, picard/coverart/providers/caa.py, picard/ui/util.py
The URL for the ticket tracker has changed, so let's reflect this in the files.
I realise that the command also changed a number of .po files and that these changes will likely get lost, but that it was likely still less effort to just include them anyway rather than try and weed them out of the commit. However, not all .po files have this line and it isn't included in the .pot either, apparently, so not sure exactly where to change the .po file link properly. Maybe on Transifex somewhere.
Using:
`sed -i 's|http://tickets.musicbrainz.org|https://tickets.metabrainz.org|' $(git grep -l tickets.musicbrainz.)`
=> Update links to ticket tracker.

picard/tagger.py
Resolves [PICARD-958](https://tickets.metabrainz.org/browse/PICARD-958).
When dir or file names contain unicode characters and debug logging is on, then debug.log statements which use %s placeholders cause the following error:
```
File ".\picard\tagger.py", line 315, in event
event.run()
File ".\picard\util\thread.py", line 34, in run
self.func(*self.args, **self.kwargs)
File ".\picard\log.py", line 116, in _stderr_receiver
sys.stderr.write(formatted_log_line(level, time, msg + os.linesep))
File "C:\Program Files (x86)\Python2\lib\encodings\cp850.py", line 12, in encode
return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2010' in position 77: character maps to <undefined>
```
=> PICARD-958: Avoid dir/file name unicode errors

picard/log.py
This is a further fix to [PICARD-958](https://tickets.metabrainz.org/browse/PICARD-958).
No point in having traceback.
Instead if we get a unicode error, we try using a repr format for the message instead.
This replaces [PR #606](https://github.com/metabrainz/picard/pull/606).
=> PICARD-958: Fix-stderr-unicode encoding-errors

picard/const/__init__.py
https://tickets.metabrainz.org/browse/PICARD-952
This sets the `CAA_PORT` constant to 443, making the initial lookup to CAA be over HTTPS. However, after the initial lookup, it seems like CAA itself is sending back HTTP redirects for http:// URLs which Picard then follows (as it should). Effectively, this PR just changes the initial CAA lookup to HTTPS, but I'm not sure I can do any better for now/without adding a bunch of exceptions specifically for `coverartarchive.org` to the code.
Without patch:
```fish
(testenv) freso@koume ~/D/M/picard (master)> grep -i coverartarchive ~/tmp/picard-master.log  
D: 16:09:25 WSREQ: Starting another request to ('coverartarchive.org', 80) without delay
D: 16:09:25 Received reply for http://coverartarchive.org:80/release/66cf87ea-6731-4b33-9c93-8ee1e4c9d9 …
```
=> PICARD-952: Use HTTPS for Cover Art Archive.

picard/oauth.py, picard/ui/options/general.py, picard/util/__init__.py, picard/webservice.py
https://tickets.metabrainz.org/browse/PICARD-951
MusicBrainz.org is eventually going to go all HTTPS-only, though the webservice for now can still be reached via HTTP. To help the move to HTTPS, this commit makes URLs built via `build_qurl()` always use HTTPS when going to a MusicBrainz server (as defined by the `MUSICBRAINZ_SERVERS` constant).
This also means that the check in the `build_qurl()` function for whether a given page/URL is/requires an authentication for MusicBrainz is now redundant, as we're always using HTTPS on MusicBrainz, regardless of login/authentication status.
=> PICARD-951: Always use HTTPS for musicbrainz.org.

picard/album.py
Resolves [PICARD-953](https://tickets.metabrainz.org/browse/PICARD-953).
If an album has unmatched files it is now shown as incomplete even if all album tracks are matched to one file. Although the terminology would suggest that such an album is "complete", in practical terms the album is not perfect because in all likelihood the user needs to select a different release with more tracks.
=> PICARD-953: Show album with extra tracks unmatched

picard/script.py, test/test_script.py
inmulti arguments where evaluated before inmulti was executed, which
resulted in strings being passed as arguments, which breaks cases in which
the strings in multivalue variables contain the separator used to separate
multiple values (see PICARD-922).
This commit fixes the behaviour of inmulti so arguments are not evaluated
before they're passed, so it can extract the argument value as a list and
work with that.
This fixes https://tickets.metabrainz.org/browse/PICARD-922
=> PICARD-922: Fix inmulti behaviour with multi-values

picard/file.py, picard/tagger.py
Handles both removal before save starts and removal whilst file is being
saved.
Resolves [PICARD-972](https://tickets.metabrainz.org/browse/PICARD-972).
=> PICARD-972: Avoid save if file removed

scripts/package-win.bat
It should be the full version with current time for master builds,
short version for tags.
=> Fix version number in the Windows installer

picard/ui/itemviews.py
Resolves a minor bug in #631.
If file path is invalid we need to skip the rest of the code in the for loop since filename is not set.
Ticket https://tickets.metabrainz.org/browse/PICARD-995.
=> PICARD-995: Avoid error on OSX invalid file path

.mailmap
Consolidate some of the mismatching author and committer name:email pairs in the logs.
See https://git-scm.com/docs/git-shortlog#_mapping_authors
------
I was trying to do some code analysis on the code and the results got somewhat skewed due to mismatching of commits to disparate authors when they were in fact the same author using multiple names and/or e-mail addresses.
@lalinsky, @samj1912, @Sophist-UK, and @suhas2go are you okay with this? Do you want to be credited differently?
=> Add .mailmap file.

.gitlab-ci.yml, scripts/package-osx.md
I wanted to get rid of the old Mac Mini that I use for builds, so I experimented with creating OS X 10.7 VM. It's surprisingly running quite well. I documented all the steps needed to set up the build env from a clean install. I also use the latest version of Python instead of the old system one.
=> OS X package env rebuild

picard/tagger.py, picard/ui/itemviews.py
In case a cluster is moved to the RHS of the windows, it gets moved to
unmatched files. The cluster should instead stay as is since the target is
invalid.
=> PICARD-1005: Fix drag'n'drop behaviour on blank targets

.travis.yml, scripts/setup-osx.sh, setup.py
Replaced the dockerized travis config with the previous one as it tests for more environments and add OSX tests.
=> Add OSX tests and a build matrix for different linux envs

.gitlab-ci.yml, scripts/package-osx.md
Reverts metabrainz/picard#641 since the OSX VM seems to be producing builds that crash instantly.
Moving back to the old config.
=> Revert "OS X package env rebuild"

.gitlab-ci.yml, picard/ui/coverartbox.py, picard/ui/itemviews.py, picard/util/__init__.py, scripts/package-osx.sh
This fixes the failing OSX builds for Picard.
The prime reasons for failing builds were-
1. Circular imports in util.get_file_path
2. Updated py2app version which breaks OSX builds. (Last working version is 0.11)
=> Fix OSX builds

picard/ui/mainwindow.py, picard/ui/options/interface.py
With #567 support for customizable toolbars was added.
This commit changes the set_tab_order function to correspond with the
custom toolbar layout dynamically.
See: https://tickets.metabrainz.org/browse/PICARD-1011
=> PICARD-1011: Set action toolbar tab order according to custom order

picard/formats/id3.py
Sorry, I was trying to squash the commits down and accidentally closed the old pull request, can't reopen it. Following on from https://github.com/metabrainz/picard/pull/634.
So I tested it out and if you're okay with making the TXXX function at the class level instead of a local function, I can subclass in a plugin, add a custom version, and then replace the mp3 format with my custom one. I've tested it locally and this works fine. I've got the plugin ready to go if you're happy with this.
https://tickets.metabrainz.org/browse/PICARD-990
=> PICARD-990: Avoid multiple value TXXX frames

picard/album.py, picard/cluster.py, picard/const/__init__.py, picard/coverart/image.py, picard/file.py, picard/metadata.py, picard/track.py, picard/ui/coverartbox.py, picard/ui/infodialog.py, picard/ui/mainwindow.py, picard/util/lrucache.py
This PR adds support to show album/cluster cover art on the CoverArtBox.
I think it's better shown with an example, so...
When an album is looked up and the cover image has changed (slightly, but it has change) it shows up as http://i.imgur.com/M6dFXna.png
When one track is selected, and a different cover image is dropped for that track: http://i.imgur.com/W6xfS2L.png
Then when the user clicks on the album... http://i.imgur.com/ITX4e3g.png
Another file from another album (which has a different cover art) is added to track 9 of that album: http://i.imgur.com/jAt7ZLJ.png
And then another file is added to another track and other covers are dropped to other tracks on that album: http://i.imgur.com/XSig6BS.png
https://tickets.metabrainz.org/browse/PICARD-1000
=> PICARD-1000: Show album/cluster cover art

picard/config.py, picard/tagger.py
This is mostly useful for debugging to avoid touching the main configuration
file while trying different settings, but could also be used for switching
between multiple tagging profiles.
https://tickets.metabrainz.org/browse/PICARD-1024
=> PICARD-1024: Allow specifying a configuration file path

picard/ui/mainwindow.py
Stop Add Directory opening one directory higher if you don't select any sub-directories.
Resolves https://tickets.metabrainz.org/browse/PICARD-1023
=> PICARD-1023: Tweak Add Directory path persistance

picard/album.py, picard/file.py, picard/track.py, picard/ui/coverartbox.py, picard/ui/options/interface.py
This adds a cover art context menu that allows users to select if they want dropped images to replace the current images or they want them to be appended to the current images. The context menu also adds an option to "Keep original images" which allows to ignore downloaded images and keep the original images if users prefer the images they already have.
Fixes [PICARD-1030](https://tickets.metabrainz.org/browse/PICARD-1030)
=> PICARD-1030: Add cover art context menu and "keep original images" option

picard/ui/coverartbox.py
Dropping remote images from google images was broken since
it needs to use the fallback_data and it was being ignored in
CoverArtThumbnail.fetch_remote_image . Instead of adding the parameter
I removed the method and made the connection from the parent class,
as it should have been done.
=> Don't ignore parameters in image_dropped signal

picard/file.py
Missing from #658 which resolved https://tickets.metabrainz.org/browse/PICARD-1021
Resolves https://tickets.metabrainz.org/browse/PICARD-1042.
=> PICARD-1042: Fix missing import for PICARD_APP_NAME

picard/formats/id3.py, picard/util/tags.py
This PR adds support for loading and saving the TOAL and TOPE tags.
It does not add support for populating these from MB - see ticket for details.
Resolves https://tickets.metabrainz.org/browse/PICARD-1034
=> PICARD-1034: Add support for loading and saving TOAL & TOPE id3 frames

picard/album.py
=> PICARD-1055: Disable update_metadata_images while updating a NatAlbum's tracks

picard/ui/infodialog.py
htmlescape has been imported *from* picard.util, using
picard.util.htmlescape doesn't make sense.
https://tickets.metabrainz.org/browse/PICARD-1056
=> PICARD-1056: Don't crash when opening file info dialogs

picard/formats/id3.py
Support for other formats will be added in PRs for PICARD-1048
=> PICARD-1034: Add missing definitions for MBIDs for TOAL TOPE

INSTALL.md, resources/README.md
PEP 394 makes it clear that python should only be used for applications that can
be run with both Python 2 and Python 3, python3 should be used for Python 3.
pip3 is used because that's what Python 3 compatible pip is called on at least
Arch, Debian, Fedora and Ubuntu.
=> INSTALL, resources/README: Explicitly refer to python3

picard/coverart/image.py
There was a str/bytes issue that was causing error on
saving CA images as files
Fixes: https://tickets.metabrainz.org/browse/PICARD-1058
=> PICARD-1058: Fix save file as images

test/test_util_astrcmp.py
After #689 tests fail if astrcmp is not compiled.
Resolves https://tickets.metabrainz.org/browse/PICARD-1063
=> PICARD-1063: Fix astrcmp tests if not compiled

.travis.yml
I have activated travis for my fork of picard and get emails about builds
failing because this step fails.
=> Don't run steps involving transifex if credentials are not available

setup.py
The names which sys.platform uses are not well-known across all users (darwin
for macOS for example), so this doesn't change the values used in the packaging
scripts.
=> patch_version: Use sys.platform as the default platform name

picard/script.py, test/test_script.py
Python 3 / PEP3102 introduced keyword-only arguments, like in
def foo(a, *, b):
pass
where `b` can't be set as a positional argument. This can't be expressed in
tagger script, so reject calls to register such functions.
This also gets rid of a DeprecationWarning for inspect.getargspec.
=> Reject functions with required keyword-only arguments

picard/tagger.py
Picard with Qt5 now supports high-dpi displays. To render icons for
higher resolutions, simply add a 2x scaled png files along with the
normal file with the name as image@2x.png
See http://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/
for more details
Fixes: https://tickets.metabrainz.org/browse/PICARD-817
To test, you can try `export QT_SCALE_FACTOR=2` and check if the icon is rendered sharply (although picard itself will appear huge)
=> PICARD-817: Enable high DPI support for Picard

INSTALL.md, MANIFEST.in, setup.py
Since all of Picard's requirements are available on pip,
this PR makes changes to the setup script to allow submitting a
distribution file to PyPi. A MANIFEST.in was included to add data dirs.
New packages can be submitted via python setup.py sdist upload -r pypi
=> Update setup script to allow submitting pip packages

picard/util/cdrom.py
Py3 strings are unicode, so we have to call the Unicode version of GetDriveType.
=> PICARD-1084: Call Unicode version of GetDriveType

README.md
This is actually the markdown you get from travis, I'm not sure where the one
without the link came from.
=> Add the link to the test results to the travis badge

picard/ui/options/plugins.py
getOpenFileNames was previously called getOpenFileNamesAndFilter (see [0]) and
returns a tuple (filenames, filter). Since we're not interested in the filter,
discard it.
This is similar to other fixes already done for QFileDialogs in mainwindow.py
and fingerprinting.py.
[0] http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html#qfiledialog
=> PICARD-1106: Discard the second return value of QFileDialog.getOpenFileNames

picard/tagger.py
shutil.copystat supports it and there's some code called by Picard (for example
when trying to install plugins) that passes the argument. Support it to fix
crashes in those cases.
=> _patched_shutil_copystat: Support the follow_symlinks keyword argument

test/test_webservice.py
mock is not part of the standard library, only unittest.mock is.
=> Use unittest.mock instead of mock

picard/util/astrcmp.py, picard/util/versions.py
It can also be displayed using -V command line option along various libs versions
=> Display astrcmp implementation (C or Python) in About and debug log

appveyor.yml, test/test_acoustid.py, test/test_mbjson.py, test/test_releaseversions.py
We recently added compatibility for Windows tests.
This is to make sure the tests are working. They were currently facing an encoding issue on reading the test json files.
=> Add windows testing

picard/file.py
Resolves https://tickets.metabrainz.org/browse/PICARD-1126
=> PICARD-1126: Add meaningful error log during lookup requests

picard/tagger.py
It should be `_search` instead of `search`.
=> PICARD-1138: Fix attribute error due to wrong value in string

picard/album.py
In the JSON representation, these media do not have a 'tracks' element
containing the list of tracks.
@samj1912 I'm not sure if this is intentional in the JSON format and needs to be handled here or in MBS.
=> PICARD-1147: Handle media with only data tracks

picard/tagger.py
.smbdelete files are temporary versions of files that should have been deleted but cannot be due to  samba bug(?). We should not load these files even if we have ignore-hidden-files unchecked.
Note: I am not running on a Mac and have not tested this code.
This PR resolves [PICARD-1143](https://tickets.metabrainz.org/browse/PICARD-1143).
=> PICARD-1143: Prevent loading .smbdelete* files

picard/mbjson.py
If the server provides multiple languages, use all of them. Otherwise, fall
back to the single language field.
https://tickets.metabrainz.org/browse/PICARD-1123
=> PICARD-1123: Multiple work languages are collapsed

picard/ui/util.py
On Windows on Qt5 it appears you need to avoid native dialog.
As far as I can tell, this was actually a bug under Qt4 (because native
dialog wasn't used anyway) and it should always have been specified.
I have only added win32 to the exception list. This may be required on
all platforms, but I am unable to test this.
Resolves https://tickets.metabrainz.org/browse/PICARD-1085
=> PICARD-1085: Fix multi-directory load on Windows

picard/ui/metadatabox.py
The `discard` argument is expected to be a sequence, but the syntax `discard=('elem')` is equivalent to `discard='elem'`.
A trailing comma is needed in this case: `discard=('elem',)` so discard is actually a tuple with a single element.
=> Fix removal of ~length from sets, incorrect single-element tuple syntax

picard/disc.py, picard/tagger.py, picard/util/thread.py
It makes the log cleaner, as most of times CD read error is due to CD not inserted.
Without debug mode, output looks like:
```
E: 16:58:00 Error while reading b'/dev/sr1': cannot open device `/dev/sr1'
```
With debug mode:
```
D: 16:58:17 Reading CD using device: b'/dev/sr1'
E: 16:58:17 Error while reading b'/dev/sr1': cannot open device `/dev/sr1'
E: 16:58:17 Traceback (most recent call last):
File "./picard/util/thread.py", line 47, in run
result = self.func()
File "./picard/disc.py", line 55, in read
raise e
File "./picard/disc.py", line 50, in read
disc = discid.read(device)
File "/home/zas/.virtualenvs/picard2/lib/python3.5/site-packages/discid/disc.py", line 55, in read
disc.read(device, features)
File "/home/zas/.virtualenvs/picard2/lib/python3.5/site-packages/discid/disc.py", line …
```
=> Only output CD read failure traceback in debug mode

picard/ui/searchdialog.py
Track/Album/ArtistSearchDialog share the same code, move it to parent class, and reduce code redundacy.
=> Simplify search dialog save/restore states code

picard/metadata.py
* This is a…
According to the history, those passed the Album or Track and not a Tagger object as the first
argument already in Picard 0.15.1.
I didn't make one, since nothing changes and the API is documented in the picard-website repository. Since these are not passed as keyword arguments, there should be no plugin relying on their name.
Rename the argument.
Nothing.
=> run{album,track}_metadata_processors: Correct the first arguments name

picard/releasegroup.py
When releases are built from node, fields are assigned values None at
times which doesn't play well with the string join in a couple of lines
below. This fixes that and reduces code by using default values.
* This is a…
* JIRA ticket (_optional_): [PICARD-1179](https://tickets.metabrainz.org/browse/PICARD-1179)
=> PICARD-1179 Fix release builder logic

picard/webservice/__init__.py
* This is a…
Exclude non-(5xx errors and 429) from slow down
Queries getting 404s cause unneeded slow down
* JIRA ticket : fix [PICARD-1181](https://tickets.metabrainz.org/browse/PICARD-1181)
Set slow down on 5xx errors and few others.
Review
=> PICARD-1181: slow down only on certain errors (429, 5xx)

picard/ui/options/plugins.py
* This is a…
The check box wasn't being unchecked as plugin.enabled wasn't initialized.
* JIRA ticket (_optional_): [PICARD-1067](https://tickets.metabrainz.org/browse/PICARD-1067)
=> PICARD-1067: Visual bug after un-checking an installed plugin

picard/webservice/__init__.py, picard/webservice/api_helpers.py, picard/webservice/ratecontrol.py, test/test_webservice.py
API is modified to use methods to get/set delays, instead of setting global variables
* This is a…
=> Move throttling code to its own file

picard/ui/searchdialog/__init__.py
* This is a…
Current code relies on row number to identify the selected item, and therefore,
after sorting, it returns the data at the row position BEFORE sorting
Fixing it requires more work, using QTableView and models.
Disable search dialog table sort until we implement it correctly.
Review
=> searchdialog: disable sorting as it is broken by design

picard/ui/searchdialog/__init__.py, picard/ui/searchdialog/album.py, picard/ui/searchdialog/artist.py, picard/ui/searchdialog/track.py
* This is a…
Sorting in SearchDialog wasn't enabled at start, enabling it revealed various issues:
- returned row was incorrect after a re-ordering of rows
- sort order of certain columns was incorrect (Length column of Track search for example), because the default sort key is a string.
Subclass QTableWidgetItem and optionnaly set a per-column sort method ('duration' or 'number')
Store row in the data array as UserRole on first column and retrieve it on accept.
Test & review
=> Fix sorting in SearchDialog

picard/ui/cdlookup.py, picard/ui/ui_cdlookup.py, ui/cdlookup.ui
* This is a…
Save CD Lookup dialog size and header state to persist options, and restore them when needed. 
Every time a CD lookup is done you have to scroll or make the resulting window larger to see all the information to distinguish releases, especially the catalog number and barcode (as the last columns). The barcode column often is cut off.
Picard should store and remember that window setting (and maybe auto-size the smaller columns).
Save CD Lookup dialog size and header state to persist options, and restore them when needed. 
* fix [PICARD-1175](https://tickets.metabrainz.org/browse/PICARD-1175)
=> PICARD-1175: save and restore CD Lookup dialog and headers states

picard/mbjson.py, picard/ui/cdlookup.py
* This is a…
Display all elements, one per line, instead of just the first one for:
- release dates & countries
- labels
- catnos
Fix [PICARD-994](https://tickets.metabrainz.org/browse/PICARD-994)
=> PICARD-994: Show all release countries in CD lookup

picard/log.py, picard/tagger.py, picard/ui/logview.py, picard/webservice/ratecontrol.py
- use standard logging module as backend
- implement a circular buffer handler for in-app log view
- use default logging levels
- debug mode is now tied to verbosity
- default log format changed, adding source/lineno infos and milliseconds precision
- history log changed to logging/circular buffer handler too
- log view was changed accordingly
- Save As button added
- Clear Log (only the in-memory buffer and the view) button added, with confirmation dialog
- Highlight text and button added
- Verbosity toggling menu added
- Debug mode check box removed (replaced by verbosity = Debug)
Replace https://github.com/metabrainz/picard/pull/830
=> Rework logging system and in-app log view

picard/__init__.py, picard/config_upgrade.py, picard/coverart/providers/caa.py
Suggested by sambhav in https://github.com/metabrainz/picard/pull/833/files#r167294289
It also fixes the issue reported at https://tickets.metabrainz.org/browse/PICARD-1189?focusedCommentId=45336&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-45336
=> Handle caa_image_size option change in an upgrade hook, bump version to 2.0.0dev3

picard/ui/filebrowser.py, picard/ui/options/interface.py, picard/ui/options/renaming.py
* This is a…
Set default paths to standard locations
Default paths are quite unpredictable, for example, the "Move files to" points to current directory (.) which leads to unexpected behaviour if not changed before moving files.
Picard behaviour is different from most apps in this regard.
Since Qt5.0, QStandardPaths provide standard locations for all systems, use it.
=> Set default paths to standard locations

picard/tagger.py, picard/ui/cdlookup.py, picard/ui/itemviews.py, picard/ui/logview.py, picard/ui/mainwindow.py, picard/ui/metadatabox.py, picard/ui/options/dialog.py, picard/ui/options/scripting.py, picard/ui/searchdialog/__init__.py, picard/ui/tagsfromfilenames.py, picard/util/__init__.py
It is useful for:
- users having UI issues on startup (too small, too big, out of screen, etc...)
- devs for testing purposes
Fix [PICARD-1201](https://tickets.metabrainz.org/browse/PICARD-1201)
=> PICARD-1201: Add -N/--no-restore option to not restore persisted sizes and positions

picard/ui/metadatabox.py
It prevents following error:
File "/usr/lib/python3.6/site-packages/picard/ui/metadatabox.py", line 292, in contextMenuEvent
column = item.column()
AttributeError: 'NoneType' object has no attribute 'column'
* This is a…
Right click to show context menu in metadata box without an item selected leads to following error:
```
File "/usr/lib/python3.6/site-packages/picard/ui/metadatabox.py", line 292, in contextMenuEvent
column = item.column()
AttributeError: 'NoneType' object has no attribute 'column'
```
* JIRA ticket (_optional_): [PICARD-1202](https://tickets.metabrainz.org/browse/PICARD-1202)
Test for current item not being None
=> PICARD-1202: only use current item if there's actually one

picard/config.py
Reading and dumping too often from QSettings causes picard to lock up.
This makes sure we only read on start and dump on change.
* This is a…
* JIRA ticket (_optional_): [PICARD-1204](https://tickets.metabrainz.org/browse/PICARD-1204)
=> PICARD-1204: Read and dump values to QSettings only when necessary

picard/ui/__init__.py, picard/ui/cdlookup.py, picard/ui/edittagdialog.py, picard/ui/infodialog.py, picard/ui/logview.py, picard/ui/mainwindow.py, picard/ui/options/dialog.py, picard/ui/searchdialog/__init__.py, picard/ui/searchdialog/album.py, picard/ui/searchdialog/artist.py, picard/ui/searchdialog/track.py, picard/ui/tagsfromfilenames.py
* This is a…
Simplify save/restoration of dialog geometry, using standard Qt saveGeometry() and restoreGeometry()
A lot of code duplication, lack of checks for valid positions and/or sizes, plus various small issues.
* JIRA ticket (_optional_): [PICARD-1093](https://tickets.metabrainz.org/browse/PICARD-1093)
Implement a generic class managing most of it.
http://doc.qt.io/qt-5/restoring-geometry.html
=> Generic class to save/restore dialog geometry, code simplification

picard/album.py, picard/script.py, picard/track.py
Fixes PICARD-259 (and associated sub-tickets)
This moves the taggerscript evaluation to happen when a file is matched (i.e. when a file is added to a track), where it has access to the both the file metadata *and* the track metadata.
In order to ensure that the titles in the user interface are correct, this is done by saving an extra copy of the original musicbrainz metadata in track.orig_metadata. The taggerscript is run as per normal
on track.metadata, but the file matching will use track.orig_metadata and re-run the taggerscript on the merged data.
This is an updated version of the code previously submitted as #170 
* This is a…
* JIRA ticket (_optional_): [PICARD-259](https://tickets.metabrainz.org/browse/PICARD-259)
=> Allow tagger script to access file metadata

picard/ui/infodialog.py, picard/ui/ui_infodialog.py, picard/ui/util.py, ui/infodialog.ui
=> Info dialog cleanup

picard/tagger.py
It is a workaround for a Qt bug, resulting on partially truncated group box titles.
* This is a…
* JIRA ticket (_optional_): [PICARD-1206](https://tickets.metabrainz.org/browse/PICARD-1206)
=> PICARD-1206: force style for GroupBox::title

picard/formats/__init__.py, picard/formats/id3.py, picard/formats/vorbis.py
Since Picard 2.0 picard uses a min. mutagen version 1.39. These are not
needed anymore.
* This is a…
=> Remove un-needed guard clauses for mutagen imports

picard/ui/itemviews.py
* This is a…
Loading alternative versions if those other releases don't have the country set fails. Test e.g. with https://musicbrainz.org/release-group/6d5c316e-1dcf-30e1-ac4d-726d67a747c4
* JIRA ticket (_optional_): [PICARD-1199](https://tickets.metabrainz.org/browse/PICARD-1199)
Check countries for `None`
=> PICARD-1199: Fix loading alternative versions if countries or formats is None

picard/ui/options/plugins.py
* This is a…
While resizing the plugin option page, font size in plugin names changes.
* JIRA ticket (_optional_): [PICARD-1226](https://tickets.metabrainz.org/browse/PICARD-1226)
Just force set the style sheet for qtreewidget.
before
after
=> PICARD-1226: Fix font size issues occuring while resizing plugin option page. 

picard/plugin.py
Picard crashes with an 'Unable to execute tagger script' message due to py2 syntax.
This fixes the crash by catching the exception and logging an error message saying that Picard is unable to load a specific plugin.
* This is a…
* JIRA ticket (_optional_): [PICARD-1221](https://tickets.metabrainz.org/browse/PICARD-1221)
=> PICARD-1221: Handle exception on loading incompatible plugins

picard/ui/ui_cdlookup.py, ui/cdlookup.ui
* This is a…
Improve button labels in CD Lookup dialog
Buttons are labelled "OK" and "Lookup manually": it isn't obvious what they do
Use explicit labels, re-using what it is used in other dialogs.
Replace "OK" with "Load into Picard" (already used in In-app Search Dialog)
Replace "Lookup manually" with "Lookup in Browser" (already used in different dialogs)
Add accel keys (&)
=> CD Lookup dialog: use explicit button labels and key accels

picard/script.py
* This is a…
An exception is raised because of invalid regexp
If argument contains '*' (or any other re reserved and unescaped character), an invalid regexp can be build, leading to an exception
* JIRA ticket : [PICARD-1252](https://tickets.metabrainz.org/browse/PICARD-1252)
Just use `re.escape()` on each argument before using them.
=> PICARD-1252: properly escape strings used to build a regexp

picard/coverart/image.py
The bug was being caused when encode_filename returns a string object on a platform that supports unicode filenames. To deal with it, simply call decode_filename, create a new filename and encode it again.
* This is a…
* JIRA ticket (_optional_): [PICARD-1253](https://tickets.metabrainz.org/browse/PICARD-1253)
=> PICARD-1253: Fix coverart image file save on platforms that support and OSX

picard/cluster.py
* This is a…
Remove button is still enabled if there isn't anything to remove in the unclustered file. Similarly, there is expand all and collapse all option in the context menu if there isn't anything to expand and collapse.
* JIRA ticket (_optional_): [PICARD-1228](https://tickets.metabrainz.org/browse/PICARD-1228)
=> PICARD-1228: Enable remove button for unclustered files only when applicable

picard/const/attributes.py, picard/coverart/utils.py, test/test_coverart_utils.py
That can happen if a new cover art type is added in MB that Picard doesn't yet
know about. Instead of raising a KeyError (and crashing), just return the raw
type, which is good enough until we have something better to show.
* This is a…
See above.
* JIRA ticket (_optional_): [PICARD-1277](https://tickets.metabrainz.org/browse/PICARD-1277)
See above.
Backport this to 1.4.something? Otherwise all users on older releases (Debian, Ubuntu, ...) will not be able to load albums with new cover art types.
=> PICARD-1277 (workaround): translate_caa_type: Return the input if the type is unknown

picard/metadata.py, picard/ui/coverartbox.py, picard/ui/infodialog.py
Fix two crashes.
* This is a…
- Fix crash when using drag&drop from Google Images to the coverartbox widget due to code not being fully ported from Qt4 to Qt5.
- Fix crash due to KeyError exceptions when trying to match a cluster with a release that doesn't have any track in musicbrainz.
- Fix crash when a cluster has a file with track number and a file without any track number information and the user opens the info dialog on the cluster.
- Ported code to Qt5
- Catch and handle exceptions properly
- Treat files with no track number as having track number 0.
=> PICARD-1302, PICARD-1303, PICARD-1304: Fix crashes

picard/ui/searchdialog/track.py
If the file doesn't belong to an album, we have to load a NAT and then move the file there. Also fix the call to self.tagger.move_file_to_nat which was missing a parameter (the file to move)
Fix a picard crash when the "search for a similar track" dialog is opened and a recording with no album
is selected.
* This is a…
* Load a recording as a NAT correctly when the recording doesn't have an album.
Picard crashes with the following backtrace when a recording like https://musicbrainz.org/recording/7f7dfdc4-c5ed-45b3-9363-a403ddff8445 is selected in the search dialog. 
Traceback (most recent call last): 
File "/usr/lib64/python3.6/site-packages/picard/ui/searchdialog/_init_.py", line 345, in accept 
self.accept_event(row) 
File "/usr/lib64/python3.6/site-packages/picard/ui/searchdialog/track. …
=> PICARD-1305: Fix crash when the file doesn't belong to an album

picard/file.py, test/test_filesystem.py, test/test_formats.py
Fix a crash moving additional files when their full path contains non-ascii characters.
* This is a…
When moving additional files, the call to ```encode_filename``` encodes the path to the original filename converting the variable from str to bytes, provoking the next exception . ```shutil.move``` only accepts strings (the documentation don't specifically mention that for ```shutil.move```, but it does for [```copy```](https://docs.python.org/3/library/shutil.html#shutil.copy), ```copyfile```, ```copymode```, etc. and the error makes clear the same is true for ```shutil.move```)
File "./picard/util/thread.py", line 47, in run
result = self.func()
File "./picard/file.py", line 222, in _save_and_rename
self._move_additional_files(old_filename, …
=> PICARD-1207: Fix handling paths with unicode characters on python3

picard/file.py, picard/util/filenaming.py
picard crashes when opening the options dialog if the cwd doesn't exist
* This is a…
The way to reproduce it:
```
mkdir foo
cd foo
picard .
```
Now on a different terminal, do ```rmdir foo```
And on Picard, open the Options dialog. Picard will crash due to a call to os.getcwd() raising an exception inside os.path.abspath/realpath .
* JIRA ticket: [PICARD-1306](https://tickets.metabrainz.org/browse/PICARD-1306)
Handle FileNotFoundError exceptions raised from os.path.abspath and
os.path.realpath used by the options dialog for the examples in the
file naming tab.
=> PICARD-1306: Fix crash opening the options dialog if cwd doesn't exist

picard/metadata.py
It happens when looking up a track with script $set(newartists, %artists%)
* This is a…
```
File “.\picard\album.py”, line 279, in _finalize_loading
self._new_metadata.strip_whitespace()
File “.\picard\metadata.py”, line 349, in strip_whitespace
self.apply_func(lambda s: s.strip())
File “.\picard\metadata.py”, line 334, in apply_func
for key, values in self.rawitems():
RuntimeError: dictionary changed size during iteration
```
Using simple script `$set(newartists, %artists%)`
* JIRA ticket (_optional_): [PICARD-1318](https://tickets.metabrainz.org/browse/PICARD-1318)
Use `super().__setitem__()`
=> PICARD-1318: Fix dictionary changed size during iteration error

picard/formats/id3.py, picard/formats/mutagenext/compatid3.py, picard/ui/options/tags.py, picard/ui/ui_options_tags.py, test/test_formats.py, ui/options_tags.ui
* This is a…
For ID3 Picard is currently saving the `grouping` tag to `TIT1` and `work` to `TXXX:Work`. Originally iTunes actually used `TIT1` for grouping, but later repurposed `TIT1` to be used for the work name. For `grouping` they introduced the non-standard frame `GRP1`.
The result is that files tagged with Picard will show up wrong in iTunes: If you save the `grouping` tag it will instead be displayed as work name and saving `work` will actually not show up in iTunes at all.
The re-purposing of `TIT1` makes it difficult to deal with this in a generic manner. A lot of software followed Apple's original approach to use `TIT1` for grouping, so we can not simply change this to `GRP1`. Also using `TIT1` seems to be closer to the ID3 standard. …
=> PICARD-1245: Add an option to save grouping and work compatible with iTunes

picard/coverart/image.py
* This is a…
Allow the file naming script for cover art to access additional metadata about the cover art itself, such as types, maintype and comment. This will allow e.g. the filename to be based upon the image type.
* JIRA ticket (_optional_): [PICARD-1319](https://tickets.metabrainz.org/browse/PICARD-1319)
Add the following additional metadata variables for the cover ar file name script:
- `coverart_maintype`: The main type of the artwork as determined by `CoverArtImage.maintype`
- ` coverart_types`: Full multivalue list of all types
- ` coverart_comment`: The cover art comment
This will allow something like this:
```
$if($eq(%coverart_maintype%,front),AlbumArt,%album%_%coverart_maintype%)
```
With this change we can discuss to also remove …
=> PICARD-1319: Provide cover art metadata in cover art naming script

picard/coverart/providers/caa.py
* This is a…
* **Describe this change in 1-2 sentences**: This change provides the user with the option of excluding selected cover art types from downloading from CAA.
[STYLE-980](https://tickets.metabrainz.org/browse/STYLE-980) has added a new cover art style "Raw / Unedited".  Although beneficial for identifying and allowing better images for archival purposes, the images within this type are generally not suitable for tagging purposes.  Picard currently allows the user to select the types of images to download from CAA, but does not provide the ability to exclude selected image types from being downloaded.
* JIRA ticket: [PICARD-1273](https://tickets.metabrainz.org/browse/PICARD-1273): Add an option to exclude new cover art type "Raw / Unedited"
This change adds new user settings to …
=> PICARD-1273: Add an option to exclude new cover art type "Raw / Unedited"

picard/util/cdrom.py
* This is a…
In Picard 2 the CD drive selection is broken due to wrong check for the platform. Hence Picard falls back to show only a simple input for the device name.
* JIRA ticket (_optional_): [PICARD-1321](https://tickets.metabrainz.org/browse/PICARD-1321)
In Python 3 sys.platform is 'linux' and no longer 'linux2'
=> PICARD-1321: Fix CD drive selection on Linux

picard/coverart/image.py, picard/file.py, picard/util/textencoding.py, test/test_textencoding.py
* This is a…
When disabling Metadata > Convert Unicode punctuation characters to ASCII and enabling File Naming > Replace non-ASCII any character that has a replacement containing slash or backslash will cause new folders created.
* JIRA ticket (_optional_): [PICARD-803](https://tickets.metabrainz.org/browse/PICARD-803)
Allow affected functions from `util.textencoding` to work in a path save way, where `/` and `\` will never be used as replacements and substituted with `_` instead. Use this in the file naming context.
=> PICARD-803: ASCII replacements can cause folder creation

picard/coverart/image.py, picard/file.py, picard/util/textencoding.py, test/test_textencoding.py
Backports the following commits to 2.0.x:
- PICARD-803: ASCII replacements can cause folder creation (#929)
=> [2.0.x] PICARD-803: ASCII replacements can cause folder creation

picard/util/cdrom.py
Backports the following commits to 2.0.x:
- PICARD-1321: Fix CD drive selection on Linux (#930)
=> [2.0.x] PICARD-1321: Fix CD drive selection on Linux

picard/coverart/providers/caa.py
* This is a…
Using "Restore all defaults" doe snot reset the selected CAA cover art types.
Furthermore the CAA cover art types are saved immediately to settings after saving, no matter if the user closes the options dialog with "Make it so!" or "Cancel"
* JIRA ticket (_optional_): [PICARD-1323](https://tickets.metabrainz.org/browse/PICARD-1323)
1. Make the CAA options page restore_defaults method also reset the CAA types
2. When closing the CAA types dialog don't immediately persist the selected types to settings but do so only if the options are actually saved
=> PICARD-1323: Restore all defaults resets CAA types

picard/ui/options/cover.py
Backports the following commits to 2.0.x:
- PICARD-1322: Fix crash when using "Restore all defaults" (#931)
=> [2.0.x] PICARD-1322: Fix crash when using "Restore all defaults"

picard/formats/id3.py, test/test_formats.py
* This is a…
Picard fails to save ID3 tags that contain an iTunNORM comment, see https://community.metabrainz.org/t/cant-convert-bytes-object-to-str-implicitly/396592
* JIRA ticket (_optional_): [PICARD-1329](https://tickets.metabrainz.org/browse/PICARD-1329)
=> PICARD-1329: Fix saving iTunNORM tags to ID3

.isort.cfg, picard/__init__.py, picard/acoustid/__init__.py, picard/coverart/__init__.py, picard/ui/__init__.py, picard/ui/options/__init__.py, picard/ui/searchdialog/__init__.py, picard/util/__init__.py, picard/webservice/__init__.py, test/test_versioncompare.py
* This is a…
Some files were forgotten during last isort pass, because isort ignores `__init__.py` files per default.
Fix config file to include those but few exceptions.
=> Fix isort config to not skip __init__.py files (but few)

picard/acoustid/json_helpers.py, picard/file.py, picard/metadata.py
For NAT recordings AcoustId returns incomplete results and we have only the recording ID. Allow Picard to load such results as NAT.
* This is a…
* JIRA ticket (_optional_): [PICARD-105](https://tickets.metabrainz.org/browse/PICARD-105)
Even with only the recording ID Picard can load a track as NAT. This patch enables this for AcoustId results.
=> PICARD-105: Allow loading AcoustId recording as NAT

picard/ui/infodialog.py
ch is a string
In Info Dialog, Picard displayed Mono/Stereo for 1 or 2 channels, it was broken at some point
* This is a…
Comparing int to string doesn't work, and thus the number of channels was displayed in all cases
* JIRA ticket (_optional_): [PICARD-1340](https://tickets.metabrainz.org/browse/PICARD-1340)
Compare to "1" and "2"
=> PICARD-1340: fix display of Mono/Stereo for channels in info dialog

picard/cluster.py, picard/tagger.py, picard/track.py
* This is a…
Removing files from Picard takes a long time if many files are loaded. This is especially noticeable when deleting unclustered files. On my system with approx. 3700 unclustered files deletion goes at a rate of 180 files per 10 seconds. While delting such a large number of files Picard's UI is unresponsive.
The reason for this is mainly the call to `update_metadata_images()`, which itself iterates over all files in a cluster.
* JIRA ticket (_optional_): [PICARD-1339](https://tickets.metabrainz.org/browse/PICARD-1339)
This change basically makes sure calls to update_metadata_images are done only once per cluster / track when multiple files get removed. Since update_metadata_images iterates over all files inside a cluster doing this …
=> PICARD-1339: Remove O(n^2) complexity when deleting files

picard.spec
It is enforced by pyinstaller 3.4
Empty DEST not allowed when adding binary and data files. Maybe you want to used '.'.
Caused by 'discid.dll'.
https://github.com/pyinstaller/pyinstaller/issues/3066
* This is a…
appveyor checks are failing since pyinstaller 3.4
=> Fix pyinstaller complaining about empty DEST

picard.spec
https://tickets.metabrainz.org/browse/PICARD-1281
http://www.openradar.me/8600732
=> PICARD-1281: Drop deprecated CFBundleGetInfoString from info.plist

picard/file.py, test/test_filesystem.py
When multiple patterns for move additional files matched the same file an exception was thrown when attempting to move the files again after it already had been moved.
* This is a…
* JIRA ticket (_optional_): [PICARD-1346](https://tickets.metabrainz.org/browse/PICARD-1346)
=> PICARD-1346: Fix exception with move additional files

picard/tagger.py, picard/ui/mainwindow.py
On macOS Picard currently looks alien because it does not use native styling.
* This is a…
* JIRA ticket (_optional_): [PICARD-1358](https://tickets.metabrainz.org/browse/PICARD-1358)
This PR makes the following changes:
- Disable the Fusion style for macOS
- Unify title and toolbar on macOS (so it blends together instead of appearing as two distinct areas)
- Disable icons for the menu. It is very uncommon that a macOS application provides icons there
The results look like this:
The old look:
I purposefully only set this for macOS for now. On my Linux with GNOME 3 Picard used the exact same styling when I removed `setStyle('Fusion')`, and I was not in the mood to test a dozen other DEs. But I think the general styling is ok in most cases. It …
=> PICARD-1358: Use native Qt style for macOS

picard/ui/itemviews.py
* This is a…
Picard is not showing a proper drag indicator when dragging items from the tree views. On Linux and Windows nothing is shown, on just the usually useless first part (truncated) of the file URL is displayed (e.g. "file:///MyHD/...").
* JIRA ticket (_optional_): [PICARD-664](https://tickets.metabrainz.org/browse/PICARD-664)
Render the first selected item's row as a drag image. Here is how it looks like in action:
Tested on all Windows, Mac and Linux
=> PICARD-664: Render the first dragged row as drag representation

picard/ui/mainwindow.py
Usually windows on macOS can be closed via a "Close Window" command, which is available both in the "File" menu and the keyboard shortcut ⌘W. This PR adds such a menu action to Picard on macOS
* This is a…
* JIRA ticket (_optional_): [PICARD-1285](https://tickets.metabrainz.org/browse/PICARD-1285)
While the change in this PR allows closing utility windows like activity protocol and debug log as well as the main window, it does not work as expected with the preferences window. This can be considered a bug caused by the fact that the preferences window is a modal dialog, which in Qt causes the menu items to get disabled. The issue is tracked at [PICARD-1282](https://tickets.metabrainz.org/browse/PICARD-1282). Still this PR provides the general …
=> PICARD-1285: Add Close Window menu entry for macOS

picard/script.py
Fix a crash when parsing an incomplete regular expresion that is still being written
* This is a…
This patch catches the re exceptions for $rsearch and $rreplace so
picard doesn't crash.
If you write $rsearch(text,) in the file naming script window and then move the cursor between the comma and the closing parenthesis and start writing a regular expression like [a-z], picard crashes as soon as the '[' character is entered, since it tries to parse the regular expression and the re module raises an exception.
* JIRA ticket (_optional_): [PICARD-1374](https://tickets.metabrainz.org/browse/PICARD-1374)
Catch the exception and just return as if the text didn't match
=> PICARD-1374: Fix a crash when parsing an incomplete regular expresion being written

picard/plugin.py
* This is a…
Fixes a crash when uninstalling a plugin which provides an option page, the re-installing it again.
After re-installing the previously installed plugin, opening the options would crash, since the option page is now registered twice.
The issue was introduced with the reworked option page in PICARD-1313. In general extension points should be deregistered when uninstalling a plugin. The specific crash described above was only for `register_options_page`, but similar issues might happen with other extension points.
* JIRA ticket (_optional_): [PICARD-1313](https://tickets.metabrainz.org/browse/PICARD-1313)
=> PICARD-1313: Unregister extension points when uninstalling a plugin

picard/util/bytes2human.py
* This is a…
locale.format is deprecated in favor of locale.format_string since Python 3.7.
locale.format_string is exactly like it with less limitations. This makes a few warnings during tests disappear.
=> Use locale.format_string instead of locale.format

test/test_bytes2human.py
* This is a…
Fixes the deprecation warning:
```
picard/test/test_bytes2human.py:84: DeprecationWarning: 'U' mode is deprecated
with open(path, 'rU') as f:
```
The U mode was to unify different line endings, but since we control the read file here this is not really needed anyway.
=> Don't use deprecated U file open mode

picard/script.py, test/test_script.py
* This is a…
`$matchedtracks()` currently requires an argument (this is historic baggage, at some point tagger script did not support functions without argument). This is a resubmission of PR #367 by @Sophist-UK, please see the discussions there for details. I just added unit tests.
* JIRA ticket (_optional_): [PICARD-637](https://tickets.metabrainz.org/browse/PICARD-637)
=> PICARD-637: Allow $matchedtracks any number of args 

picard/ui/ui_options_renaming.py, picard/ui/ui_options_script.py, ui/options_renaming.ui, ui/options_script.ui
* This is a…
The script editors in Picard currently allow pasting richt text content. See e.g. this example with pasted content from musicbrainz.org:
While the pasted content is converted to plain text on saving, this behavior is confusing when pasting.
* JIRA ticket (_optional_): [PICARD-1405](https://tickets.metabrainz.org/browse/PICARD-1405)
Set `QTextEdit.setAcceptRichText(False)`. This prevents the user to paste rich text (it will be converted to plain text), but does not effect the formatted display of syntax highlighting.
=> PICARD-1405: Do not allow rich text input in script editors

picard/formats/mp4.py, test/test_formats.py
* This is a…
Picard does not save the `work` tag to MP4, even though there is a work tag in MP4 (which is displayed in iTunes and others) and we already save the tag to MP3 in a way that is also interpreted by iTunes and others in the same field (see #928).
* JIRA ticket (_optional_): [PICARD-1068](https://tickets.metabrainz.org/browse/PICARD-1068)
This adds support for writing `©wrk` to MP4 to get a result like this in iTunes:
Note that this is already possible for MP3, so it is just consistent to support it for MP4 as well.
Previous attempt to support this ended in discussions about what MusicBrainz data should be stored there, because the work as defined in MusicBrainz is often not what you actually want to write to this tag. But I think …
=> PICARD-1068: Save work tag for MP4 as ©wrk

picard/__init__.py, picard/acoustid/__init__.py, picard/coverart/providers/caa.py, picard/oauth.py, picard/plugin.py, picard/ui/searchdialog/album.py, picard/util/checkupdate.py, picard/webservice/__init__.py, picard/webservice/api_helpers.py, test/test_versions.py
* This is a…
This PR aims to make the webservice and code that uses it more error tolerant. Most web service requests Picard currently makes operate under the assumption of a successful response with a valid response body. Hence a broken response by the server, e.g. changed JSON structure or sending HTML instead of expected JSON, in many cases lead to Picard crashing.
* JIRA ticket (_optional_): [PICARD-1338](https://tickets.metabrainz.org/browse/PICARD-1338)
This PR provides the following changes:
- When using `parse_response_type` to let the web service module handle the parsing of JSON or XML responses any parsing error is treated as an error in the request and an error object is passed to the callback. This frees the caller from checking if …
=> PICARD-1338: More resilient webservice

picard/ui/itemviews.py
With dark theme modified files are shown with black text on dark background.
* This is a…
The text color for modified files was supposed to be theme aware, but generating the color failed. Creating a QColor object from a QPalette ColorRole does not work (maybe it worked in Qt4). The result was always a black color.
* JIRA ticket (_optional_): [PICARD-1320](https://tickets.metabrainz.org/browse/PICARD-1320)
Switch the text color to use the color for foreground text. When the "color_modified" option gets initialized we don't have access to the current palette, so I decided to remove the "color_modified" config option entirely, as it defaulted to the standard foreground text color anyway and we don't make use of these options currently anyway.
=> PICARD-1320: Fix text color for modified files for dark themes

picard/ui/collectionmenu.py
* This is a…
The collection sub menu currently does not display and behave like a normal menu. Mainly the menu items render without margins and do not highlight on activation.
* JIRA ticket (_optional_): [PICARD-1060](https://tickets.metabrainz.org/browse/PICARD-1060)
The reason for the differences is that we render those menu items with a custom widget which we need for the tri-state checkboxes.
Implement the necessary changes to render with margin and background highlighting. Capture the mouse over and menu item activated events to properly mark mouse overed items as active and render active items with background.
I tested this on Gnome and KDE (KDE with a light and a dark theme). In both cases the menu rendered exactly as e.g. the "other …
=> PICARD-1060: Fix collections menu not looking and behaving like a normal menu

picard/formats/apev2.py, picard/formats/asf.py
* This is a…
Curently the tags originalalbum and originalartist are not fully mapped to supported tagging formats. This PR tries to improve the situation for WMA and APE.
* JIRA ticket (_optional_): [PICARD-1314](https://tickets.metabrainz.org/browse/PICARD-1314)
* JIRA ticket (_optional_): [PICARD-1407](https://tickets.metabrainz.org/browse/PICARD-1407)
* JIRA ticket (_optional_): [PICARD-1408](https://tickets.metabrainz.org/browse/PICARD-1408)
I think uncontroversial changes are:
- ASF: Map to `WM/OriginalAlbumTitle` and `WM/OriginalArtist`
- Ape: Map `originalartist` to `Original Artist`
Supported this way by Media Monkey, Jaikoz. See
- http://www.jthink.net/jaudiotagger/tagmapping.html
- …
=> PICARD-1314: originalalbum/originalartist mappings for APE and ASF

picard/ui/mainwindow.py
Network / UNC paths on Windows cannot be opened, affects open containing folder and open in player actions.
* This is a…
* JIRA ticket (_optional_): [PICARD-1415](https://tickets.metabrainz.org/browse/PICARD-1415)
Remove an older workaround for a similar problem which is no linger required in Qt5 and actually breaks this functionality.
=> PICARD-1415: Fix opening UNC paths on Windows

picard/plugin.py
* This is a…
Picard is showing plugins even if they are incompatible with currently supported API versions. This fix checks the compatibility and ignores incompatible plugins when loading the list.
* JIRA ticket (_optional_): [PICARD-1417](https://tickets.metabrainz.org/browse/PICARD-1417)
There is also the proposal to filter this already server side, see [PW-27](https://tickets.metabrainz.org/projects/PW/issues/PW-27). That also would require some client changes, but additionally provide some complication server side with caching of different API version combinations. I'm actually in favor of applying this simple client side fix so we have something in place for the next release. We can still later do the server side change.
The advantage of …
=> PICARD-1417: Do not show plugins that are incompatible

picard/i18n.py, picard/tagger.py
* This is a…
The keyboard shortcuts currently do not show up localized, so e.g. German users also see "Ctrl+S" for saving files, but actually should see it localized "Strg+S". Same is true for default dialogs, e.g. file open dialogs currently always show up with English button labels.
* JIRA ticket (_optional_): [PICARD-1418](https://tickets.metabrainz.org/browse/PICARD-1418)
Setup default Qt translations. This makes sure standard dialogs and keyboard shortcut hints show up in the user selected language.
=> PICARD-1418: Setup default Qt translations

picard/file.py, test/test_file.py
* This is a…
When clustering files they are supposed to be ordered by disc and tracknumber. But since all metadata in Picard 2.0 is returned as strings this breaks the sorting.
* JIRA ticket (_optional_): [PICARD-1341](https://tickets.metabrainz.org/browse/PICARD-1341)
Convert numbers to int. The `file.discnumber` and `file.tracknumber` properties where supposed to return integers before, as can be seen by the default 0 getting returned.
It might be worth discussing to support more representations of tracknumbers here, like e.g. vinyl numbering ('A1', 'A2'), strings in the form `"3/42"` or even latin numbers. But I think this would be part of a separate issue and require all of Picard supporting this. For here I wanted to focus on fixing the …
=> PICARD-1341: Fix cluster sorting by disc and track number

setup.py
Builds for Snap package do not contain locale files.
* This is a…
Snap packages use `setup.py bdist_wheel` for generating the package. Currently the way our locale files are built causes them to be not included in the data package of the wheel.
* JIRA ticket (_optional_): [PICARD-1398](https://tickets.metabrainz.org/browse/PICARD-1398)
Fix installation of locale files to be in the proper data file used by the setuptools. This ensures not matter how the final packaging works the locale files will be included.
For now only tested locally with normal setup.py install and bdist_wheel commands. Before merging I want to test the CI builds for Win and Mac.
=> PICARD-1398: Fix installing locales when running setup.py bdist_wheel

picard/tagger.py, picard/ui/mainwindow.py, picard/ui/options/general.py
* This is a…
Currently if a request to MB requires authentication and the user is not authorized or has invalid oauth tokens set a dialog will be shown asking the user to authenticate with "Yes" / "No" buttons. But currently there is no implementation behind clicking "Yes", so nothing will happen.
This fix changes this by initiating the oAuth flow allowing the user to directly authenticate instead of going to the options.
One issue remains: The request causing this issue still fails. The QNetworkAccessManager.authenticationRequired signal requires to either set credentials before the signal returns or the request will fail with an AuthenticationRequiredError.
To my knowledge Qt does not provide an asynchroneous way to handle authentication, see …
=> PICARD-1430: On MB auth errors allow the user to start the oAuth flow

picard/const/languages.py
zh_CN (Chinese (China)) should read "中文（中国大陆）" not "中文".
zh_TW (Chinese (Taiwan)) should read "中文（台灣）" not “傳統中文".
* This is a…
* JIRA ticket (_optional_): [PICARD-1450](https://tickets.metabrainz.org/browse/PICARD-1450)
=> PICARD-1450: Fix language labels for zh_CN and zh_TW

picard/ui/coverartbox.py
It seems at some point it has become neccessary to accept
dragMoveEvents as well as dragEnterEvents in order to
let Qt know that we want to receive drop events.
Fix drop events on coverartbox which were previously ignored by what appears to be a behaviour change in Qt.
* This is a…
When dragging  a file from a file manager (or an image from the browser) and dropping it over the CoverArtBox, ActiveLabel.dragEnterEvent is correctly called and it's accepting the event, but ActiveLabel.dropEvent is not called at all because some logic looks to be preventing it.
* JIRA ticket: [PICARD-1453](https://tickets.metabrainz.org/browse/PICARD-1453)
It seems at some point it has become necessary to also accept the dragMoveEvent in order to Qt to call the dropEvent method, which is what this pull …
=> PICARD-1453: Fix drop events on coverartbox

picard/tagger.py
For locales that are not available for Qt Picard currently shows a warning like:
W: 08:47:12,788 /usr/lib/python3.7/site-packages/picard/tagger.main:861: Error loading Qt locale sv_SE
This actually shows up a lot, since Qt has not that many locales included. If I look at the avilable Qt locales on my system this is only ar, bg, ca, cs, da, de, en, es, fa, fi, fr, gd, gl, he.
But the warning confuses users and makes them think something is broken.
Reduce the log level of this warning and reword it to be less scary.
* This is a…
* JIRA ticket (_optional_): [PICARD-1470](https://tickets.metabrainz.org/browse/PICARD-1470)
=> PICARD-1470: Make Qt locale loading warning less visible

picard/album.py, picard/tagger.py
On disc lookup set the disc ID only for the tracks on the disc being looked up.
* This is a…
The feature of Picard to set the disc ID used for a disc lookup on the loaded metadata was from a time when releases had only a single medium. It set the disc ID for all tracks, regardless on whether they are on the looked up disc or not.
* JIRA ticket (_optional_): [PICARD-323](https://tickets.metabrainz.org/browse/PICARD-323)
Handle multiple disc IDs and set them only for tracks on the looked up disc. The following changes have been made:
1. Album handles a list of disc IDs
2. A new hidden variable `~musicbrainz_discids` is set on the tracks, holding all disc IDs MusicBrainz has stored for the corresponding medium
3. On lookup the tag …
=> PICARD-323: Fix discid for multidisc releases

picard/acoustid/__init__.py
When using existing fingerprint for AcoustId lookup properly set the duration parameter.
* This is a…
If a file already contains a fingerprint, Picard will use this for AcoustId lookup instead of calling fpcalc. In this case Picard was submitting a parameter `duration=0`, which caused a 400 error from AcoustId:
```json
{"status": "error", "error": {"message": "missing required parameter \"duration\"", "code": 2}}
```
* JIRA ticket (_optional_): [PICARD-1473](https://tickets.metabrainz.org/browse/PICARD-1473)
Submit a proper duration
=> PICARD-1473: Fix AcoustId lookup with existing fingerprint

picard/acoustid/__init__.py, picard/metadata.py
Take the number of sources for a AcoustId into account when selecting the best match. This gives better matches in cases where an AcoustId is also attached to the wrong recording.
* This is a…
AcoustId tracks the number of sources for each linked MB recording. A higher number usually gives a higher confidence that this AcoustId is linked to the correct release, but Picard does currently not consider this.
* JIRA ticket (_optional_): [PICARD-1242](https://tickets.metabrainz.org/browse/PICARD-1242)
Calculate a score for recordings based on the sources relative to the recording with the most sources. E.g. if there are two recordings linked, one with 30 and one with 10 sources, the first one will get a score of 100 (percent), the second one of 33. …
=> PICARD-1242: Consider AcoustId source count

picard/ui/itemviews.py
The user has to press left arrow key twice to navigate from a track item to the album.
* This is a…
Track items in the tree view, even if containing only a single file, are set to be expanded, even though their child item is not even visible.
* JIRA ticket (_optional_): [PICARD-938](https://tickets.metabrainz.org/browse/PICARD-938)
Do not set track items with only a single file to expanded.
=> PICARD-938: Do not expand track item with single file

scripts/package-osx.sh
Do not fail the build if macOS upload to transfer.sh fails.
As discussed with @zas on IRC we do not really care in most cases if this fails, but it currently quite often fails with server errors from transfer.sh. We still want this functionality though, as sometimes you need to access the build binaries for pull requests. If it failed and we find out we need it restarting the build is usually a quick solution.
This basically reverts https://github.com/metabrainz/picard/pull/1085
The general approach that errors in package-osx.sh should fail the build still is true
=> CI: Do not fail the build if macOS upload to transfer.sh fails

appveyor.yml, installer/picard-setup.nsi.in, setup.py
Show proper version string in file properties of Windows install .exe file.
* This is a…
Looking at the file properties of the Windows installer show outdated version string, since that was hard coded.
* JIRA ticket (_optional_): [PICARD-1474](https://tickets.metabrainz.org/browse/PICARD-1474)
Set the version accordingly.
Before and after:
Some notes:
1. `VIProductVersion` actually is shown as "File version" ("Dateiversion" in the screenshot) in the properties dialog. This must be defined.
2. `VIProductVersion` must be in the format `0.0.0.0`, only digits allowed
3. You need to specify both `FileVersion` and `ProductVersion` in the version metadata. These are strings. `ProductVersion` is shown in the dialog as "Product version", I don't know …
=> PICARD-1474: Fix version information in Windows installer exe

picard/tagger.py, picard/track.py, picard/ui/itemviews.py
Fix handling of non-album tracks in error case and make it generally more usable.
* This is a…
If loading of a NAT fails it is stuck with the "[loading track information]" message. It does never display any error. Also it is not possible to remove any NAT, you can only remove the entire "non-album tracks" pseudo album.
* JIRA ticket (_optional_): [PICARD-729](https://tickets.metabrainz.org/browse/PICARD-729)
The core changes to fix PICARD-729 are:
- Show an actual error state with error icon, error details in tooltip and message "could not load recording"
- Allow removing single NATs
I also did some general cleanup that improve the usability of this feature:
- The NATs pseudo album is loaded always expanded, otherwise newly added NATs are not …
=> PICARD-729: NAT error handling

picard/coverart/image.py, test/picardtestcase.py, test/test_coverart_image.py, test/test_formats.py, test/test_imagelist.py
Fixes issues where files where shown as modified when loading again and comparing against cover art with more than one type.
* This is a…
Cover art images that have both "front" and another type will cause files been shown as modified if they are saved and reloaded. Reason ist that only the front type gets stored, but comparison with the original image with more types than fails.
* JIRA ticket (_optional_): [PICARD-1178](https://tickets.metabrainz.org/browse/PICARD-1178)
The following cases can happen:
- Format does not support cover art (this is currently only the case for formats that don't support tagging at all, which means currently WAV and MIDI)
- Format supports cover art, but no types (MP4, APE)
- Format supports cover art with exactly …
=> PICARD-1178: Support comparing cover images with only one type

picard/ui/mainwindow.py, picard/ui/searchdialog/__init__.py, picard/ui/util.py
QLineEdit has a clearButtonEnabled property since 5.2 which is meant for this purpose.
It also fixes an issue with clear button icon size
* This is a…
* JIRA ticket (_optional_): [PICARD-1480](https://tickets.metabrainz.org/browse/PICARD-1480)
=> PICARD-1480: Remove unneeded ButtonLineEdit

picard/formats/vorbis.py, test/test_formats.py
Write image width and height for embedded cover art to FLAC files
* This is a…
When saving images to FLAC files Picard does not set image width and height. This results with those values being set to 0. This causes issues with some software reading the files.
* JIRA ticket (_optional_): [PICARD-455](https://tickets.metabrainz.org/browse/PICARD-455)
Write image width and height for embedded cover art to FLAC files, added test
=> PICARD-455: Set dimensions for images saved to FLAC

picard/file.py, picard/tagger.py
- replace list + sort with a heap, faster
- rename  tagger._acoustid to tagger.acoustidclient (it's a AcoustidClient object)
- do not use File._lookup_finished() outside file.py
- use class constants (integers) instead of strings for File._lookup_finished() lookuptype parameter
* This is a…
=> File cleanup

picard/file.py
If old file and new file are in the same directory, there's no need to move any additionnal files
Apparently, the code wasn't really taking care of this,
since its introduction in https://github.com/metabrainz/picard/commit/6d4dc078aeff5a57f6fb9eaf568e96fb9a2eda20
* This is a…
=> _move_additional_files(): return asap if same directory

INSTALL.md, picard/disc.py, picard/util/cdrom.py
* This is a…
Picard cannot run without this patch and missing `libdiscid` and `python-libdiscid`.
It falls back on `discid` module, but when this one is trying to load `libdiscid` it fails with:
`OSError: libdiscid.so.0: cannot open shared object file: No such file or directory`
According to https://python-discid.readthedocs.io/en/latest/install/#dependencies
*The module discid cannot be imported without Libdiscid >= 0.2.2 installed.
If you want to use it as optional dependency, import the module only when
needed or catch the OSError when libdiscid is not found.*
So catch OSError and define discid to None.
After that, Picard runs but emits a warning:
`W: …
=> Better handling of missing libdiscid, catching OSError

picard/coverart/__init__.py, picard/coverart/image.py, test/test_coverart_image.py
* This is a…
Local cover art providers fails loading images on Windows. The issue was introduced in https://github.com/metabrainz/picard/pull/1111, the way the path was converted to QUrl and back was implemented to naively.
* JIRA ticket (_optional_): [PICARD-1490](https://tickets.metabrainz.org/browse/PICARD-1490)
=> PICARD-1490: Fix local cover art loading on Windows

picard/config_upgrade.py
Using QMessageBox.question with custom buttons is not supported in Qt5. Use custom implementation.
* This is a…
* JIRA ticket (_optional_): [PICARD-1493](https://tickets.metabrainz.org/browse/PICARD-1493)
=> PICARD-1493: Fixed opening message box during 1.0 config upgrade

picard/metadata.py, test/test_coverart_image.py, test/test_metadata.py
Inheriting from `dict` is rather messy, so let's inherit from `collections.abc.MutableMapping` instead which is meant for that.
The conversion isn't that easy, and some tests were dependent on `dict` methods.
But the move has a lot of advantages:
- much cleaner
- `del metadata['tag']` is working
- `Metadata([('tag', 'value')])` can be used to create the object from an iterable
- `Metadata([('tag', 'value'), ('ignoreme': '')]` or `Metadata(tag='value', ignoreme='')` are equivalent to:
```python
m = Metadata()
m['tag'] = 'value'
```
- `metadata.keys()` and `metadata.values()` are working as expected
- `len(metadata)` is returning number of tags plus number of images (as ` __bool__` somehow was doing)
- a method `getraw()` was added, because none of `__getitem__()`, `get()`, `getall()` were …
=> Metadata class: inherit from MutableMapping instead of dict

picard/ui/options/renaming.py, picard/util/settingsoverride.py, test/test_settingsoverride.py
A bug was introduced recently in https://github.com/metabrainz/picard/commit/04dcd4691bd57f2e24f2054e47e666ab843d891d
It was fixed in https://github.com/metabrainz/picard/commit/4990cef589496cabf0613bee4b6b2bac6a11797c
This PR is a cleanup of this fix
=> Cleanup missing clear existing tags setting fix

picard/config.py, test/test_config.py
@zas Since commit 2c457b8dcd7c77f78557dfd02a4111862c0eb31c we have a strange bug, where `BoolOption` values seem to get reset to their default values.
I don't fully understand it yet. In both implementations the `not hasattr(self, "convert")` call at https://github.com/metabrainz/picard/blob/master/picard/config.py#L243 is `False`, so it does not get overridden by `type(default)`. But with the changes from 2c457b8dcd7c77f78557dfd02a4111862c0eb31c the convert function never gets called. I assume `IntListOption` is affected as well, but we don't use that.
Any ideas. Just reverting your change of course seemingly fixes the issue, but this does not seem to be the solution. Something is wrong here, and the change just uncovered it.
=> Fix loading BoolOption from config

setup.py
Running `setup.py test` with the `--tests=...` argument broke recently when introducing submodules for tests. This commit fixes this again, allowing something like:
```
python setup.py test --test=test_mbjson,formats.test_wav
```
* This is a…
=> Fixed invoking "python setup.py test --tests=..."

picard/ui/infodialog.py
QDesktopServices takes care of honoring the user configuration so
when opening an image, the user preferred external app is used
instead of always using a web browser.
Fixes PICARD-1501
Use QDesktopServices to open cover images instead of webbrowser2
* This is a…
If a user configures the desktop to open images with a given application, it's unexpected that Picard uses a web browser instead.
* JIRA ticket: [PICARD-1501](https://tickets.metabrainz.org/browse/PICARD-1501)
Use QDesktopServices instead of using webbrowser2 to open the image file.
=> PICARD-1501: Use QDesktopServices to open cover images instead of webbrowser2

picard/tagger.py, picard/ui/mainwindow.py
Patch by Philipp Hahn
* This is a…
device name is set using Action text, which contains & accelerator
* JIRA ticket : [PICARD-1503](https://tickets.metabrainz.org/browse/PICARD-1503)
Pass device name as QAction data
=> PICARD-1503: fix CDROM device containing ampersand (&)

picard/__init__.py, picard/tagger.py
Follow up to PICARD-1502, `QApplication.setDesktopFileName` is a static method intended to be called before QApplication is created (just like e.g. `setApplicationName`)
* This is a…
* JIRA ticket (_optional_): [PICARD-1502](https://tickets.metabrainz.org/browse/PICARD-1502)
We could reuse `PICARD_APP_ID` elsewhere, e.g. in setup.py. We duplicate this string a lot. Will submit a separate PR.
=> PICARD-1502: Call setDesktopFileName before creating QApplication

picard/file.py, picard/track.py
This fixes a saving error after "keep original metadata" or after files have been moved around.
Reason is that the `ImageList` in `metadata.images` gets turned into a regular list under some circumstances. This was introduced in recent metadata refactorings.
* This is a…
=> Fix crash when saving after "keep original cover art.

picard/script.py, test/test_script.py
* This is a…
Having the scripting functions is_complete() or matchedtracks() in naming script and saving a cluster causes an exception.
See also https://community.metabrainz.org/t/problem-on-right-click-cluster-and-save/426786
* JIRA ticket (_optional_): [PICARD-1517](https://tickets.metabrainz.org/browse/PICARD-1517)
=> PICARD-1517: Fix running matchedtracks()/is_complete() on clusters

test/data/test.ini, test/test_config.py
Currently Picard's test cases can be affected by existing user configuration and might fail.
* This is a…
* JIRA ticket (_optional_): [PICARD-1506](https://tickets.metabrainz.org/browse/PICARD-1506)
For tests provide an empty config file.
I am not entirely sure what is happening and I could not find anything in the Qt docs at https://doc.qt.io/qt-5/qsettings.html#QSettings-3
But if there is no empty config file Qt seems to initialize the specified config file path with a copy of the application's config. I can easily reproduce what @Freso reported on PICARD-1506, and providing an empty file solves the issue for me.
=> PICARD-1506: Provide empty config for tests

picard/tagger.py
* This is a…
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
* JIRA ticket (_optional_): [PICARD-1533](https://tickets.metabrainz.org/browse/PICARD-1533)
=> PICARD-1533: Set Qt.AA_EnableHighDpiScaling before application gets created

picard/metadata.py, picard/track.py, test/test_metadata.py
When loading already tagged NAT files into Picard which contain embedded cover art, the first loaded file loads normally, but every additional loaded file gets the cover art of all previously loaded files attached.
See discussion at https://community.metabrainz.org/t/album-modified-and-complete-on-every-load-but-no-modifications/432044
* This is a…
* JIRA ticket (_optional_): [PICARD-1529](https://tickets.metabrainz.org/browse/PICARD-1529)
Preserve the file images instead of applying images from `NatAlbum`.
A few considerations:
1. I thought about removing `self.metadata.copy(self.album.metadata)` completely, as by default this does not provide any additional metadata. But having the ability to set tags for all NATs on the `NatAlbum` level has …
=> PICARD-1529: Avoid loaded NATs getting assigned cover art from other NATs

test/test_util_lrucache.py
* This is a…
https://docs.python.org/3/library/unittest.html#deprecated-aliases
=> unittest.assertEquals() is deprecated in favor of assertEqual()

picard/releasegroup.py
* This is a…
When releases have a lot of media the list of number of tracks can be far too long for clean display
* JIRA ticket (_optional_): [PICARD-1546](https://tickets.metabrainz.org/browse/PICARD-1546)
Truncate it if > 10
=> PICARD-1546: Truncate tracks in Other Releases menu when too many media

setup.py
* This is a…
I'm trying to update the (quite out of date) OpenBSD port of picard. Our process uses the --single-version-externally-managed option to install. The distutils version of install doesn't support it, but the main setuptools version of install does.
Change from importing install from distutils.commands.install to setuptools.commands.install
=> Switch import of install from distutils to setuptools to support --single-version-externally-managed

MANIFEST.in
Add test *.aac files to MANIFEST.in so that source tarball for PyPI has all the data files for the tests.
* This is a…
A subset of the regression tests fail when I run them on OpenBSD. Most of them fail due to the test-apev2.aac is missing from the test/data/ directory from the PyPI tarball. Looks like aac files were forgotten from the MANIFEST.in file. Adding them puts them in the tarball generated by python3 setup.py sdist.
This simple change to MANIFEST.in should include those files for future source tarballs.
No other actions.
=> Add test *.aac files to MANIFEST.in 

picard/metadata.py
* This is a…
When comparing a file to a track Picard only considers the search score for album tracks, not for standalone recordings (AKA non-album tracks).
* JIRA ticket (_optional_): [PICARD-1551](https://tickets.metabrainz.org/browse/PICARD-1551)
=> PICARD-1551: Consider search score when comparing files to NATs

MANIFEST.in, setup.py
* This is a…
As reported https://stackoverflow.com/questions/56737424/how-to-fix-error-option-single-version-externally-managed-not-recognized/56740829 trying to install Picard via pip on Windows currently fails.
There are actually multiple independent issues:
1. `setup.py` install tries to generate the installer config from `installer/picard-setup.nsi.in`, but it's not included in the source
2. `setup.py` (indirectly) depends on PyQt5
3. Our `setup.py` does not support `--single-version-externally-managed`, this is already fixed in #1210
* JIRA ticket (_optional_): [PICARD-1549](https://tickets.metabrainz.org/browse/PICARD-1549)
1. Include the installer files in the source distribution. I think that makes sense to allow the full functionality …
=> PICARD-1549: Fixed pip install on Windows

picard/pluginmanager.py
Since 73b0954ef6c6435c2f1ee8f6dd1ae17c5640bfce plugin installation from ZIP uses hard links to efficiently "copy" the temporary file to it's final location.
This fails when the underlying file system does not support hard links. I originally found this bug when trying Picard on Haiku, which BFS file system does not support hard links. But same is true e.g. on Windows should the user e.g. have it's user directory on an FAT32 formatted drive. Or if we get to the point where we support "portable" installations on e.g. a USB pen drive, which often are FAT32 formatted.
This patch still uses the hard link approach, but falls back to copying the file if this fails. The assumption is that hard link support is the rule, but we have to deal with, well, the exceptional case sometimes.
This patch was …
=> Fix plugin installation on FS without hardlink support

picard/__init__.py, picard/config_upgrade.py, picard/const/__init__.py, test/test_config_upgrade.py, test/test_script.py
* This is a…
If there is no track number in metadata the default script will still write "00" to the file name.
* JIRA ticket (_optional_): [PICARD-1556](https://tickets.metabrainz.org/browse/PICARD-1556)
Check for tracknumber being set in the default script.
=> PICARD-1556: Ignore empty track numbers in default naming script

picard/acoustid/json_helpers.py, test/test_acoustid.py
* This is a…
* JIRA ticket (_optional_): [PICARD-1564](https://tickets.metabrainz.org/browse/PICARD-1564)
Avoid setting unused field when parsing AcoustId medium info.
=> PICARD-1564: AcoustId metadata parsing must not set "track" field

picard/coverart/providers/caa.py, picard/ui/__init__.py, picard/ui/mainwindow.py, picard/ui/options/dialog.py, picard/ui/options/interface.py
* This is a…
On macOS all windows can usually be closed with ⌘W. Qt enables this already for some dialogs, but this does not work for all dialogs we use, most significantly not for the options dialog, but also not for e.g. "Tags from filenames" and smaller dialogs opened inside options.
* JIRA ticket (_optional_): [PICARD-1282](https://tickets.metabrainz.org/browse/PICARD-1282)
* JIRA ticket (_optional_): [PICARD-1571](https://tickets.metabrainz.org/browse/PICARD-1571)
Enable the ⌘W for all dialogs by implementing it in `PicardDialog` and making sure all dialogs inherit from it.
This PR also addresses the issue that on macOS one could open more then one instance of the options dialog ([PICARD-1571](https://tickets.metabrainz.org/browse/PICARD-15 …
=> PICARD-1282: Allow closing all dialogs on macOS with ⌘W

.travis.yml, CONTRIBUTING.md, picard/collection.py, picard/const/__init__.py, picard/i18n.py, picard/plugin.py, picard/releasegroup.py, picard/script.py, picard/tagger.py, picard/ui/options/dialog.py, picard/ui/options/interface.py, picard/ui/options/releases.py, picard/ui/tagsfromfilenames.py, picard/util/__init__.py, picard/util/filenaming.py, picard/util/textencoding.py, picard/util/webbrowser2.py, picard/webservice/__init__.py, setup.cfg
* This is a…
This makes some PEP8 fixes and ensures that at least all source inside `picard/` can be checked with flake8. Adds flake8 source code check to CI.
I added some exceptions for specific cases inline as well as ignoring a few rules globally. The now additionally ignored rules are:
**E226: missing whitespace around arithmetic operator**
While I in general think it is better to have whitespace around arithmetic operators there are cases where it makes sense to omit them. E.g. we often have something like `data[pos:pos+2]`. Adding whitespace here looks a bit off to me (`data[pos:pos + 2]`). Also something like `2*3 + 4*4` reads nicer then `2 * 3 + 4 * 4` as the precedence of the operations is more visible. I think this is even mentioned …
=> PEP8 fixes, check with flake8

picard/ui/coverartbox.py
* This is a…
This fixes two issues with cover art drag and drop from Google image search.
1. This allows dragging the larger image preview in Google search results, which appears when one clicks on one of the small preview images. This is implemented by parsing a image URL out of the HTML content included in the drop. The solution is a bit hackish, but I think Google image search warrants some special handling. See discussion in https://tickets.metabrainz.org/browse/PICARD-1575
2. Google image search in Google Chrome on Linux will include the actual image data in the drop as `application/octet-stream` data. This was already handled by Picard, but unfortunately this is the data as displayed, meaning it will drop the smaller preview image. As we …
=> PICARD-1575: Fixes for cover art drag and drop

picard/ui/playertoolbar.py
A couple of optimizations after testing the player on macOS. Most notably this fixes the playback speed changing on macOS (by disabling a workaround which is needed for Linux and Windows).
Also some Layout fixes, which theoretically are also present on other platforms but not as notable there.
* This is a…
=> PICARD-1488: macOS player fixes

picard/ui/itemviews.py
* This is a…
On windows the expand indicator for a release in the tree view was missing directly after having loaded a release. Any further action, like loading another release or clicking the tree view caused the indicator to appear.
I could not reproduce this on Linux, but on Windows it is a thing even with latest Qt 5.13. But on Windows it is easily reproducible.
* JIRA ticket (_optional_): [PICARD-1446](https://tickets.metabrainz.org/browse/PICARD-1446)
After updating the release item force an update by invoking `emitDataChanged()`.
This is more a workaround, basically I think this is a Qt or PyQt bug.
=> PICARD-1446: Fixed missing expand indicator for releases

picard/ui/options/dialog.py
On macOS when clicking "Restore defaults" or "Restore all defaults" in options dialog, the confirmation dialog is opened in the background and not visible to the user.
* This is a…
Properly set the parent dialog. This makes this a proper modal dialog also on macOS
=> PICARD-1585: Ensure restore defaults dialog opens in foreground on macOS

picard/ui/options/interface_colors.py
Due to the parent buttons stylesheet all buttons in the QColorDialog got colored as well. This happened e.g. on Windows, where no native color chooser is available.
* This is a…
This is a fun bug in the new color options (#1199). Found this on Windows, although it will happen on every platform where the custom Qt color dialog is used and not a platform native one (e.g. also Linux with KDE, but not on GNOME). The stylesheet `QPushButton { background-color: %s; }` also colors all buttons in the color chooser:
If you want to experience this on Linux with e.g. GNOME (where otherwise a native dialog is being used), just replace
```
new_color = QtWidgets.QColorDialog.getColor(self.color, title=_("Choose a color"), parent=self)
```
with 
```
dlg = …
```
=> PICARD-1524: Fix color chooser getting all buttons colored

picard/formats/vorbis.py, test/formats/test_vorbis.py
* This is a…
Picard fails to load files with invalid `metadata_block_picture` tag (e.g. not base64 or the decoded content is not a FLAC picture block).
* JIRA ticket (_optional_): [PICARD-1591](https://tickets.metabrainz.org/browse/PICARD-1591)
- Handle exceptions for base64 decoding and FLAC picture block parsing.
- Added tests for errors in cover art and for loading the legacy `COVERART` tag
=> PICARD-1591: Error tolerant loading of metadata_block_picture

picard/ui/options/tags.py
Avoids some kind of thread lock when saving options.
* This is a…
When saving the options while a file is selected and the `clear_existing_tags` was toggled, Picard could completely freeze up (at least on Linux, I could not reproduce on Windows). The basic cause is the call to `MetadataBox.update`.
To reproduce:
1. Open current master with e.g. `./tagger.py test/data/test.mp3`
2. Select the loaded file (so that the metadatabox shows the metadata of this file)
3. Open Options, toggle Tags > Clear existing tags
4. Save Options
Often the app is now unresponsive. If this does not work, just repeat steps 3. and 4. Usually after not more than 5 tries I can reproduce this. But often it freezes on first try for me.
* JIRA ticket (_optional_): …
=> PICARD-1590: Fixed thread locking when saving options

picard/ui/edittagdialog.py
* This is a…
If the user edits the tag name inside the tag edit box, the text cursor always jumps to the end of the input on every keypress.
E.g. if the user wants to edit the tag name "start_abc_end" by replacing the inner "abc" with something else they would place the cursor in the middle of the string. But on every input (removing a character, adding a character) the cursor jumps to the end of the string.
* JIRA ticket (_optional_): [PICARD-1595](https://tickets.metabrainz.org/browse/PICARD-1595)
Reset the cursor position after updating the `QComboBox` selection.
=> PICARD-1595: Keep cursor position when editing tag names

picard/config.py, picard/ui/options/tags.py
* This is a…
The issue occurs when writing a config value and directly afterwards reading one. it hangs in reading then .This behavior came with https://github.com/metabrainz/picard/commit/a63cc6bdd1614476c63244e1dce92500dd1219f2 at https://github.com/metabrainz/picard/blob/master/picard/config.py#L94
Here it calls ConfigSection__contains__, which calls ConfigSection._subkeys, which calls QSettings.allKeys(). and allkeys() never returns. Instead of calling .allKeys() you can also call QSettings.contains() or QSettings.sync(), has the same effect of locking up
* JIRA ticket (_optional_): [PICARD-1590](https://tickets.metabrainz.org/browse/PICARD-1590)
avoid calling allKeys() or contains() on the QSetting instance and instead maintain a own list …
=> PICARD-1590: fix thread lockups

picard/ui/filebrowser.py, picard/ui/itemviews.py
* This is a…
The horizontal scroll position in all three main window panes (file browser, untagged files, tagged files) resets to 0 when selection changes. This is default behavior of `QTreeView.scrollTo`.
* JIRA ticket (_optional_): [PICARD-622](https://tickets.metabrainz.org/browse/PICARD-622)
Reimplement `scrollTo` to better handle horizontal scroll position.
- For the file browser, set the horizontal scroll position to the indentation level of the parent. This allows intuitive and easy navigation through deep hierarchies without the need of manually handling the scrolling.
- For the untagged / tagged files panes we don't have deep hierarchies, but potentially large data columns. Just keep the current horizontal scrolling position. Usually …
=> PICARD-622: Do not reset horizontal scroll position in main window panes on selection change

picard/album.py, picard/metadata.py, picard/track.py
Fixed the first parameter name of `run_track_metadata_processors` from `track_object` to `album_object`, because this is what gets actually passed here.
Also switched the parameters `track` and `release` around to match the order for the public API.
* This is a…
=> Fixed names of parameters for run_track_metadata_processors

picard/file.py, picard/util/__init__.py, picard/util/emptydir.py, test/test_emptydir.py, test/test_utils.py
This protects standard directories like e.g. ~/Desktop being deleted if empty.
* This is a…
Folders considered "special", such as the Desktop, default Music or other media folders or even configuration folders, could get deleted by the "Remove empty directories" option. This PR fixes this.
* JIRA ticket (_optional_): [PICARD-456](https://tickets.metabrainz.org/browse/PICARD-456)
Exclude directories listed in `QStandardPaths`. When comparing also resolve symlinks.
=> PICARD-456: Do not remove empty standard directories

picard/ui/options/dialog.py
When the options dialog is closed an instance of it stays around in the background, reacting to events and consuming resources. This was caused by changing opening the dialog directly instead of using `exec_()` in f8eb75596e8090d2f08e9290608dbe7a9f4964d4
* This is a…
* JIRA ticket (_optional_): [PICARD-1607](https://tickets.metabrainz.org/browse/PICARD-1607)
=> PICARD-1607: Ensure OptionsDialog gets deleted when closed

scripts/package-osx.sh
This uploads the macOS build artifacts to a S3 bucket instead of using transfer.sh
* This is a…
`transfer.sh` is frequently blocking builds and is very unreliable. Also we don't control how long artifacts are available and we have no single place to check for the latest artifacts.
Setup uploading artifacts to a S3 bucket.
For this to work we need to set the following variables in Travis CI:
- `AWS_ARTIFACTS_BUCKET`
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`
I have already setup a bucket for this and I would be fine with keeping this, but it could make senseto use a bucket created via a MetaBrainz AWS account. It just should be using credentials that …
=> travisci: Upload macOS artifacts to S3

picard/tagger.py
If a folder “[non-album tracks]” is available at the third pane, it can only be removed, if it’s empty. 
* This is a…
Directly removing the NAT pseudo-album broke with c6815c4fada5f6f006673d21cecf870f88cc932c. This commit fixed the issue, that removing both the non-album tracks album and the last NAT track would cause a crash, since removal of the NAT album was attempted twice.
* JIRA ticket (_optional_): [PICARD-1608](https://tickets.metabrainz.org/browse/PICARD-1608)
Allow direct removal of the NAT album, but ensure duplicate calls to remove_album() do not crash.
=> PICARD-1608: Allow removal of "non-album tracks" pseudo-album again

picard/util/versions.py
Use `qVersion()` instead of `QT_VERSION_STR`
This shows the proper runtime version of Qt being used instead of the Qt version PyQt was built against.
* This is a…
* JIRA ticket (_optional_): [PICARD-1609](https://tickets.metabrainz.org/browse/PICARD-1609)
=> PICARD-1609: Show actual runtime version of Qt

picard/ui/options/cover.py
If none of save images to tags or save images to files is enabled, cover art is totally disabled, greying out ca providers list somehow make it more obvious.
* This is a…
* JIRA ticket (_optional_): [PICARD-1619](https://tickets.metabrainz.org/browse/PICARD-1619)
=> PICARD-1619: grey out cover art providers list if cover art is disabled

test/test_taggenrefilter.py
* This is a…
`*` only repeats the preceding regular expression, but in the old test, there was
nothing preceding it. This showed up when tests were executed via `python
setup.py test`:
> .........................................E: 20:54:38,617 /home/wieland/dev/picard/picard/track.__init__:88: Failed to compile regex /*/: nothing to repeat at position 0
> Traceback (most recent call last):
>   File "/home/wieland/dev/picard/picard/track.py", line 86, in __init__
>     regex_search = re.compile(remain, re.IGNORECASE)
>   File "/usr/lib/python3.7/re.py", line 234, in compile
>     return _compile(pattern, flags)
>   File "/usr/lib/python3.7/re.py", line 286, in _compile
>     p = sre_compile.compile(pattern, flags)
>   File …
=> test_regexfilter: Fix the test

picard/ui/options/genres.py
* This is a…
1. The tooltips on the genre options are quite long and not trivial to understand for people not
already familiar with them. Hiding them after just 5 seconds is way too soon
2. One of the examples claimed `+word*` means `word*` is excluded. This is wrong.
1. To not get into bikeshedding over how long the tooltip should be shown, just don't hide it.
2. Fix the description of the example.
None
=> PICARD-1632: Genre ui improvements

picard/i18n.py, requirements-macos.txt
On macOS the system locale was not detected, thus setting language to "System default" did not work.
* This is a…
* JIRA ticket (_optional_): [PICARD-1633](https://tickets.metabrainz.org/browse/PICARD-1633)
This failed due to:
- macOS returning language / country separated by "-" instead of "_" (en-UK instead of en_UK)
- required pyobjc modules not being packaged
=> PICARD-1633: fix system locale detection on macOS

picard/ui/filebrowser.py
Fixes the horizontal scroll position of the file browser on macOS to properly show the selected items and its parent.
* This is a…
The automatic setting of the horizontal scroll position in the filebrowser as implemented in https://github.com/metabrainz/picard/pull/1274 does not work properly on macOS, there the position is always shifted one index to the right.
The problem is that for macOS we set `self.setRootIndex(self.model.index("/Volumes"))`, and the code that determines the indentation level does not take this different root into account.
* JIRA ticket (_optional_): [PICARD-1634](https://tickets.metabrainz.org/browse/PICARD-1634)
Fix the indentation code to consider the actually used root of the view.
=> PICARD-1634: fix filebrowser horizontal scroll position on macOS

picard/i18n.py
* This is a…
On a POSIX system if the environment is configured to have different locales (e.g. setting display language to German, but number formatting to English) Picard fails to detect the system configured language.
The reason is that Picard assumes that `locale.setlocale(locale.LC_ALL, '')` always returns the default locale name, but this is only true if all locale categories have the same locale. If one or more locale categories define different locales the returned value is instead a string like:
```python
"LC_CTYPE=de_DE.UTF-8;LC_NUMERIC=en_GB.UTF-8;LC_TIME=en_GB.UTF-8;LC_COLLATE=de_DE.UTF-8;LC_MONETARY=en_GB.UTF-8;LC_MESSAGES=de_DE.UTF-8;LC_PAPER=en_GB.UTF-8;LC_NAME=de_DE.UTF-8;LC_ADDRESS=de_DE.UTF-8;LC_TELEPHONE=de_DE.UTF-8;LC_MEASURE …
```
=> PICARD-1636: Fixed POSIX compliant default locale detection

picard/pluginmanager.py
* This is a…
Plugin loading errors included nearly no information about which plugin from where was loaded at the point of failure and/or swallowed stack traces. Fix that.
Log all the things! The individual commits have more details, including log entries before & after the change.
This also makes `plugin_error` behave more like the functions in `picard.log` in that it just takes an unformatted string with placeholders for formatting and a bunch of strings and does the formatting, instead of leaving that up to its callers.
No.
=> Log more information when a plugin failed to load

picard/ui/itemviews.py
When files are already have state = REMOVED but the itemviews UI updates Picard could crash since there are no colors defined for this state.
* This is a…
* JIRA ticket (_optional_): [PICARD-1635](https://tickets.metabrainz.org/browse/PICARD-1635)
Define the color dicts as defaultdict.
Questions to all reviewers: Do you think we should remove the definitions that are now same as default from the dict? I left it in for now so the code is more explicit, but technically it is not needed.
So just:
```
FileItem.file_colors = defaultdict(lambda: TreeItem.text_color, {
File.PENDING: interface_colors.get_qcolor('entity_pending'),
File.ERROR: interface_colors.get_qcolor('entity_error'),
})
```
instead of 
```
FileItem.file_colors = defaultdict(lambda: …
```
=> PICARD-1635: Fixed crashes on UI update for deleted files

.travis.yml
* This is a…
* **Describe this change in 1-2 sentences**: Condense IRC notification alerts from three messages to one.
The Travis CI bots are very verbose in `#metabrainz`. Currently, it comes across as three lines:
```
<travis-ci> metabrainz/picard#5094 (master - 3bd4c03 : Philipp Wolfer): The build passed.
<travis-ci> Change view : https://github.com/metabrainz/picard/compare/e44eafc03758...3bd4c031af96
<travis-ci> Build details : https://travis-ci.org/metabrainz/picard/builds/595956271
```
This commit changes how Travis sends an alert to the `#metabrainz` IRC channel. This makes it easier for someone like me to filter human noise from bot noise in reading my client scrollback.
This commit condenses them into one:
```
<travis-ci> [infrastructure:upgrade/teleirc-1.3.2@9f909cb - build …
```
=> travis: Condense IRC notification to one message

picard/formats/apev2.py, picard/formats/vorbis.py, test/formats/common.py, test/formats/test_apev2.py, test/formats/test_id3.py, test/formats/test_vorbis.py
Tags in the format of performer:instrument were not saved to Vorbis and APEv2 tags if instrument contained non-ASCII characters.
* This is a…
* JIRA ticket (_optional_): [PICARD-1643](https://tickets.metabrainz.org/browse/PICARD-1643)
Fixed support for `performer:*`, `lyrics:*` and `comment:*` tags for Vorbis and APEv2. Added tests.
=> PICARD-1643: Fixed saving performer tags to Vorbis and APEv2

picard/ui/options/plugins.py
* This is a…
On macOS the plugin status button does not update the icon on click. This seems to be a repainting issue of Qt. Calling repaint() on the button works around this.
* JIRA ticket (_optional_): [PICARD-1647](https://tickets.metabrainz.org/browse/PICARD-1647)
=> PICARD-1647: Fix plugin status icon not getting repainted

appveyor.yml, picard.spec, picard/const/__init__.py, picard/webservice/__init__.py, scripts/picard-portable-hook.py
This provides Picard in a self contained exe file, which can directly be started from anywhere. Configuration and plugin data is placed in a folder “MusicBrainz-Picard” next to the exe.
* This is a…
Some users have requested a "portable" version of Picard for Windows. Portable in this context means, the application can be run without installation and the application data is self contained (e.g. does not save config on the system).
For the user the value is that they can run Picard without installation and e.g. place it on a USB stick together with all of its configuration. It also is an easy way to try different versions of Picard independently from one another.
That last part is interesting for us, as we can easily allow users to test new …
=> PICARD-118: Portable Windows version

picard/formats/mutagenext/aac.py, test/formats/test_aac.py
For AAC files with APEv2 tags the length calculation was off, since the size of the APEv2 block was used in the estimate. Now the length of the APEv2 block gets taken out of the length estimate.
Improve the length calculation of AAC files.
* This is a…
For AAC files the length is an estimate calculated based on the file length. If AAC files get tagged with APEv2 tags the length of the APEv2 block is included in the length calculation, thus in some cases making the file appear significantly longer.
This, btw, is an issue most playback software has unless it specifically supports AAC files tagged with APEv2.
* JIRA ticket (_optional_): PICARD-1629
Try to remove the APEv2 tag size from the length calculation.
It is worth noting that this is still …
=> PICARD-1629: Better length calculation for AAC with APEv2

picard/cluster.py, picard/ui/coverartbox.py
Allow dropping cover art on a cluster's cover art box.
* This is a…
* JIRA ticket (_optional_): PICARD-1656
Implement handling cover art dropped on a clusters `CoverArtBox`.
The replacement code really cries for refactoring. The code for updating cover art for `Album`, `Track` and now `Cluster` (https://github.com/phw/picard/blob/9491a6a80053bf9c69a9f1c21274c66acf61cd10/picard/ui/coverartbox.py#L469) duplicates a lot.
But there are always these slight differences that make it difficult to reduce the redundancy here: 
- `Album` has tracks, `Cluster` not
- `Track` needs special handling of the album instance
- `Album.update` takes a parameter, `Cluster.update` not
I am not really sure how to handle this. I thought about subclassing `Item` and …
=> PICARD-1656: Allow changing coverart of clusters

picard/formats/apev2.py, test/formats/test_apev2.py
When reading APEv2 tags case insensitive, preserve existing casing.
In #1334 case insensitive reading of APE tags was introduced. But saving tags always used the casing set by Picard.
This changes the behavior to keep existing casing.
* This is a…
* JIRA ticket (_optional_): PICARD-1592
=> PICARD-1592: Preserve case for APEv2 tags

picard/file.py, picard/formats/id3.py, picard/formats/mp4.py, picard/metadata.py, test/test_metadata.py
* This is a…
The methods of `Metadata` which set data are inconsistent. `__setitem__` and `set` behave differently and only `__setitem__` did conversion to string. This is a confusing API. Also because tag values are treated as strings everywhere this lead to a lot of explicit `str()` conversions when using `add` or `add_unique`.
* JIRA ticket (_optional_): PICARD-1406
- All Metadata methods setting data (`__setitem__`, `set`, `add`, `add_unique`) will convert values to strings
- `__setitem__` and `set` are equivalent
- get rid of explicit `str()` conversions when calling `add` / `add_unique`
I searched both the Picard and picard-plugins code for uses of `set`, `add` and `add_unique`. In all cases code was either passing already an string or …
=> PICARD-1406: Make setting data in Metadata consistently use strings

picard/script.py, test/test_script.py
Some scripting functions, that look like they should be used as a boolean condition in an $if, will always evaluate to true. Affected are $is_complete, $startswith and $endswith.
* This is a…
* JIRA ticket (_optional_): PICARD-1667
Fixed the affected functions.
=> PICARD-1667: Functions for boolean checks must return "" on False

picard/file.py, picard/metadata.py
* This is a…
Picard does happily match audio only recordings to video files and video recordings to audio files.
* JIRA ticket (_optional_): PICARD-1666
Add a weight that triggers if the video flag of both the file and the recording match.
I tested with a couple of video files, which then really preferred the video recordings on MB if they existed.
Some considerations:
- The weight is there to trigger Picard preferring an equivalent video file. But it is intentionally not set too high to not get a match with otherwise wrong metadata just because it is a video
- Video recordings do often not exist on MB, hence it is important to still allow matching video files to recordings not flagged as video.
- Likewise we don't reliable detect if a file is …
=> PICARD-1666: Consider video / audio when comparing files to tracks

picard/formats/mp4.py
* This is a…
Added checks to the actual presence of values in mp4 tags "trkn" and "disk". If not present, just ignore and don't set it into parsed metadata
When importing a file with these tags set but with empty values picard breaks with an exception and marks as errored.
Steps to reproduce:
1. Make a m4a/mp4/acc file with these tags present but with empty values
2. Try to import them in picard
* JIRA ticket : PICARD-1668
Add checks of actual value presence in them
~~I will add tests as I just found them for formats/mp4.~~
Ready to merge
=> PICARD-1668: Added checks for actual value presence in "trkn" and "disk" mp4 tags

picard/formats/mp4.py, test/formats/test_mp4.py
* This is a…
Apple supports a `hdvd` atom in MP4, which is a 8 bit integer where:
0 - SD
1 - 720p
2 - 1080p
We can use the presence of this atom to identify a file as video.
This requires mutagen 1.43, see https://github.com/quodlibet/mutagen/pull/386
* JIRA ticket (_optional_): PICARD-1672
Set the `~video` variable for all MP4 files containing the `hdvd` atom.
=> PICARD-1672: Flag MP4 files with the hdvd tag as video

picard/ui/infostatus.py, picard/ui/mainwindow.py, picard/ui/statusindicator.py
* This is a…
The taskbar on Windows 7 and later can show a progress indicator. If Picard is busy with long running operations, e.g. web requests for a large collection or saving a lot of files, it would be useful to make use of this to indicate progress.
* JIRA ticket (_optional_): PICARD-1673
Use `QWinTaskbarButton` to update the progress display in the Windows taskbar (see animation below). The progress is based on both pending files and pending requests.
FOr implementation I abstracted the existing update of the counts in the status bar to support alternative implementations of showing pending actions.
The implementation was done to allow additional implementations. The clear candidate for this on Linux is implementing the …
=> PICARD-1673: Show load and save progress in Windows taskbar

picard/tagger.py, picard/ui/statusindicator.py
Same functionality as implented on Windows in #1368, but for Linux desktops supporting the DBus based [Unity Launcher API](https://wiki.ubuntu.com/Unity/LauncherAPI).
* This is a…
* JIRA ticket (_optional_): PICARD-1674
Expose the [`com.canonical.Unity.LauncherEntry` DBus interface](https://wiki.ubuntu.com/Unity/LauncherAPI#Low_level_DBus_API:_com.canonical.Unity.LauncherEntry). The DBus interface is initiated always except for platforms where it does not make sense. If DBus is not available this is handled by QDBus, the `bus.registerObject` returns False in this case and the `UnityLauncherEntryStatusIndicator` skips any updates.
This was tested on:
- Ubuntu with default Ubuntu GNOME desktop (which is using Dash to Dock)
- KDE Plasma
- Arch …
=> PICARD-1674: Linux desktop progress indicator using Unity.LauncherEntry DBus interface

.github/workflows/package-macos.yml, .github/workflows/package-windows.yml, .github/workflows/run-tests.yml, scripts/package/macos-package-app.sh, scripts/package/macos-setup.sh, scripts/package/win-package-appx.ps1, scripts/package/win-package-installer.ps1, scripts/package/win-package-portable.ps1, scripts/package/win-setup.ps1
Run tests and packaging / deployment with Github Actions
* This is a…
This performs all our test, build and deployment tasks we have running on travis / appveyor into Github actions.
Advantages:
- All tasks in one place
- Unified and simpler configuration. E.g. the majority of code in `run-tests.yml` is shared between operating systems (there is only a minor difference for installing gettext on Linux and macOS)
- Packaging of the macOS and Windows apps is pretty similar
- We get artifacts storage for all builds (previously only for appveyor)
- It is more flexible, since Github Actions is more than just for CI. E.g. we can react to changes on releases
- It runs faster (full run with all builds and tests is …
=> Use GitHub Actions for CI

picard/mbjson.py, picard/metadata.py, test/picardtestcase.py, test/test_mbjson.py, test/test_metadata.py, test/test_releaseversions.py
If the search scores returned by the server are not integer values Picard crashed during metadata comparisson.
* This is a…
* JIRA ticket (_optional_): PICARD-1678
Try to convert score to integer, handle conversion errors.
=> PICARD-1678: Fix Picard crashing on non-integer search scores

picard/cluster.py, picard/file.py, picard/ui/options/matching.py, test/test_metadata.py
* This is a…
Cluster lookup was not using preferred release type.
* JIRA ticket (_optional_): PICARD-1664
This adds `releasetype` to the weights for cluster lookup.
The score was set so that it is the same as in the file weights relative to the total score.
File weights are currently:
```
comparison_weights = {
"title": 13,
"artist": 4,
"album": 5,
"length": 10,
"totaltracks": 4,
"releasetype": 20,
"releasecountry": 2,
"format": 2,
"isvideo": 2,
}
```
This is 62 maximum, with releasetype being 32%. Applying this to cluster gives:
```
comparison_weights = {
'album': 17,
'albumartist': 6,
'totaltracks': 5,
'releasetype': 16,
'releasecountry': 2,
'format': 2,
}
```
I am not entirely sure about this, we could probably lower this but it is hard to …
=> PICARD-1664: Use preferred release type for cluster lookup

picard/album.py, picard/cluster.py, picard/ui/itemviews.py
Makes the list of columns displayed in the two main panes user configurable.
* This is a…
* JIRA ticket (_optional_): PICARD-170
Add a context menu to the view headers which allows the user to select the columns to be displayed (see screenshot below). A "Restore default columns" action is also available.
Saving the state was simplified by using `QHeaderView.saveState()` and `QHeaderView.restoreState()`. This makes sure the visible columns, their sizes and their position are all saved. As a side effect this now also persists the order of columns, which previously could already be changed but the change was not saved.
For the columns I chose columns that were commonly requested in discussions (see below) and which can easily be used and are …
=> PICARD-170: Customizable main panel columns

picard/ui/itemviews.py, picard/ui/widgets/tristatesortheaderview.py
* This is a…
Currently once a column is selected for sorting the treeview stay sorted. One can toggle between ascending and descending order or sort a different column, but the treeview cannot be set to an unsorted state.
* JIRA ticket (_optional_): PICARD-1349
Implement a custom `TristateSortHeaderView`, which toggles between the three states "ascending", "descending" and unsorted.
The implementation has to work around that a `mouseReleaseEvent` occurs both when a click happened and when a move or resize option ended. Only when it was not a move or resize it was an actual click that changes sort order. Unfortunately the default implementation does not indicate a indication of this. To avoid reimplementing all of `mousePressEvent`, …
=> PICARD-1349: Allow resetting a column to unsorted state

picard/tagger.py
* This is a…
On macOS mnemonics are disabled by default. But this also means that many UI elements (e.g. triggering buttons in dialogs) cannot be used with keyboard only as it is possible on other platforms. Enabling this on macOS allows better keyboard navigation for all users consistent across platforms.
* JIRA ticket (_optional_): PICARD-1312
Call `qt_set_sequence_auto_mnemonic` to enable mnemonics.
This is somewhat against macOS UI guidelines, but the alternative would be to add separate shortcuts for all kind of actions across the entire app just for macOS.
For background see
- https://doc.qt.io/qt-5/qshortcut.html#mnemonic
- https://community.metabrainz.org/t/ui-keyboard-input-code-question-arrow-key-input-tkinter-gtk/453139/13
=> PICARD-1312: Enable mnemonics for buttons and other UI elements on macOS

picard/ui/itemviews.py
* This is a…
The [non-album tracks] is a special type of AlbumItem entry that holds all the loaded non-album tracks. Currently this is sorted into the list like every other album, which can non-album tracks hard to find.
I propose to keep this special entry always on the first position of the right pane to make it easier to handle non-album tracks.
* JIRA ticket (_optional_): PICARD-1686
Always insert the NAT album entry at first position and implement `__lt__` comparison so this item always sorts at first position.
=> PICARD-1686: Always keep [non-album tracks] at first position

picard/ui/options/plugins.py
* This is a…
Plugins in the system plugins folder are not uninstallable by the user due to missing permissions. Hence only offer the uninstall option for plugins in the user directory.
* JIRA ticket (_optional_): PICARD-1665
=> PICARD-1665: Only enable uninstall for user installed plugins

picard/ui/mainwindow.py
* This is a…
Even though both the log view and the activity history dialog implement PicardDialog, their geometry is not persisted. This is because those dialogs are permanent and never actually closed.
* JIRA ticket (_optional_): PICARD-1693
Save geometry of logview dialogs on exit
=> PICARD-1693: Save geometry of log view dialogs

picard/ui/__init__.py, picard/ui/mainwindow.py, picard/ui/options/dialog.py
Replace the specific implementation in MainWindow to manage a single instance of OptionsDialog by a generic implementation.
* This is a…
Add a `SingletonDialog` class that can be subclassed by dialogs to enable management of a single instance open at a time. This single instance can still be closed and destroyed, but as long as the `SingletonDialog` functions are used to create the dialog no more than one instance exist.
This is currently only used by OptionsDialog but could now be easily reused by dialogs with similar requirements.
=> Added generic SingletonDialog class for managing a single dialog instance

picard/util/__init__.py, picard/util/scripttofilename.py, picard/util/textencoding.py, test/test_scripttofilename.py, test/test_textencoding.py, test/test_utils.py
* This is a…
Allow backslashes to be used in filenames on systems other than Windows. Only if Windows compatibility is activated backslashes will be replaced as before.
* JIRA ticket (_optional_): PICARD-321
The core change is in `util.sanitize_filename`, where there is now no longer a hardcoded replacement of `\` and `/` but instead `os.sep` and `os.altsep` are used an a `win_compat` parameter is accepted in addition. Ensure functions in `textencoding`  and `script_to_filename` set the `win_compat` parameter accordingly.
Tested on Linux and Windows 10
=> PICARD-321: Support backslash in filenames on non-Windows OS

.github/workflows/pypi-release.yml
* This is a…
Publish release tags to PyPI using Github Actions.
* JIRA ticket (_optional_): PICARD-1596
Added Github Actions workflow to publish to PyPI using Twine.
I have tested the commands in this order locally minus the actual twine upload, but I could not fully test this workflow. I think it is fine, but please look at it carefully. Once this is merged we probably should do a dev release soon to check our deployment process in entirety.
There are some [Github Actions](https://github.com/marketplace?utf8=%E2%9C%93&type=actions&query=pypi) specifically for this, but I think the process using twine directly is so straight forward that adding basically another dependency and passing the credentials around to another external dependency is …
=> PICARD-1596: Use Github Actions to publish to PyPI

picard/__init__.py, setup.py, test/test_versions.py
Re-add ability to mark alpha, beta and rc pre-release versions
* This is a…
For Picard versions support the version identifiers 'alpha', 'beta' and 'rc' again (in addition to 'final' and 'dev'). This used to be supported, but got lost at some point
Long version strings will be e.g. 2.3.0beta2. If the shortened string is generated the idenfitiers for alpha and beta will be shortened to 'a' and 'b' (e.g. 2.3.0b2). This confirms to pre-release versioning is defined in PEP 440.
The background for this is that I really want to do a proper beta release for Picard 2.3 this time, as there are some changes where I would like to see a release that clearly indicates it is a pre-release meant to gather user feedback. Also before this I would like to tag an …
=> Allow pre-release version numbers (alpha, beta, rc)

.github/workflows/run-tests.yml
Run tests on Github Actions with older sip dependencies (mainly older PyQt5 versions).
* This is a…
Run tests with older sip dependencies. To not escalate this too much I limited this to run on Linux only. For macOS and Windows I would prefer to only officially support the versions we have defined in the `requirements-{mac|win}.txt` files, as used by the packaging, and the actual latest versions.
I also consider to run these extended tests only on the master branch and not for all PRs, opinions?
I had an alternative implementation where I ran tests with different dependencies inside the current jobs, see https://github.com/phw/picard/commit/5291de1f56cc610cbee2dff44c62f14ac57ff9cb
But I dislike how this …
=> GHA: Run tests with older dependencies

picard/ui/itemviews.py
* This is a…
The "Other versions" context menu entry for albums is currently always inactive. This broke with the addition of configurable album columns, since the check if only a single item was selected relied on the number of columns.
=> Fix "Other versions" context menu not being active

picard/const/__init__.py, picard/plugin.py, picard/ui/options/plugins.py, scripts/pyinstaller/portable-hook.py, test/test_plugins.py
This is a bugfix for https://github.com/metabrainz/picard/pull/1400 on Windows.
* This is a…
Without this path comparisson to check wheter a plugin is installed in the user plugin dir fails on Windows. The issue is that the compared paths can look like this:
```
plugin.dir == "C:\Users\Developer\AppData\Local\MusicBrainz\Picard\plugins"
USER_PLUGIN_DIR == "C:/Users/Developer/AppData/Local\MusicBrainz\Picard\plugins"
```
* JIRA ticket (_optional_): PICARD-1665
=> PICARD-1665: Normalize plugin and const paths for better comparison

picard.spec, picard/__init__.py, picard/config.py, picard/pluginmanager.py, picard/version.py, test/test_plugins.py, test/test_versions.py
The version identifier was previously compared alphabetically, which fails for e.g. "dev" < "alpha".
* This is a…
With the recent addition of (again) supporting alpha, beta and rc releases the comparison of the version identifier broke. This would lead to warnings such as "Warning: config file 2.3.0.dev1 was created by a more recent version of Picard (current is 2.3.0.alpha1)".
Implement proper version comparison by introducing a Version class (inherited from tuple), which implements proper comparison operators. Also moved the logic fro to and from string conversion there.
`picard.version_from_string` is now considered obsolete, but I did not yet remove it as it might be used by plugin code. …
=> Implement proper version comparison for dev, alpha, beta and rc releases

picard/ui/coverartbox.py, picard/ui/logview.py
* This is a…
In PyQt 5.14 the exclusive parameter for QActionGroup is no longer available. Also QActionGroup is exclusive by default in Qt5 (it even was in Qt4), so there is no need to set this (see https://doc.qt.io/qt-5/qactiongroup.html#QActionGroup).
* JIRA ticket (_optional_): PICARD-1700
=> PICARD-1700: Fix crash on PyQt >= 5.14 on cover art context menu

org.musicbrainz.Picard.desktop, picard/tagger.py
Fixes Picard's handling of argv and allows passing the default Qt command line arguments (e.g. `-style [Stylename]`)
* This is a…
The current handling of argv caused some issues. The QApplication classes expect a full argv to be passed to them, but we only passed on the remaining args, which caused a few issues.
- argv[0] is supposed to be the path to the executed binary, but it wasn't for us. This breaks e.g. `QCoreApplication.applicationFilePath` and also was what caused us to need to include this `StartupWMClass` workaround
- Command line arguments for Qt and/or X which require an additional keyword (e.g. `-style` or `-desktop`) where broken. E.g. if passing `-style Windows` then "Windows" would be interpreted as a filename, and Qt would …
=> PICARD-1054: Allow Qt to handle default Qt and X command line arguments 

picard/album.py, picard/tagger.py, picard/ui/itemviews.py
Make sure the UI stays responsive while clustering, moving large amount of files in the tree view or while matching files to releases.
* This is a…
While matching files to releases Picard becomes unresponsive. This is especially noticeable on releases with a huge number of tracks like e.g. https://musicbrainz.org/release/44f53f7b-7a0c-4796-b06c-1077327b13ff
* JIRA ticket (_optional_): PICARD-1625
Keep the UI responsive by frequently calling `QCoreApplication.processEvents()` while processing a list of files.
Also ensure the drop handlers finish fast and the actual processing is done afterwards by using `QtCore.QTimer.singleShot()`. If this is not done drag and drop will not work until the operation has fully completed.
I also had tried to …
=> PICARD-1625: Keep UI responsive when clustering, moving or matching large amount of files

picard/formats/id3.py, picard/util/tags.py, test/formats/common.py, test/formats/test_id3.py, test/test_util_tags.py
Adds syntax `comment:{language}:{description}` in addition to existing `comment:{language}:{description}` for comment tag names.
* This is a…
ID3 allows saving a language for comment tags. Currently Picard is hard coded to always write "eng", and most of the files seen in the wild seem to default to "eng".
An exception is MediaMonkey, which allows the user to write "custom" tags. Those custom tags get stored to COMM frames with a description on "Songs-DB_Custom1", "Songs-DB_Custom2" etc. and language set to "XXX".
Picard not supporting this currently has two affects:
- Trying to create such a tag with Picard fails. $set(comment:Songs-DB_Custom1,test) will write a COMM tag with proper description, but language set to "eng".
- Loading such a file …
=> PICARD-1589: Support language for ID3 comments.

picard/ui/mainwindow.py
* This is a…
There is no keyboard shortcut for Remove albums/files action, and Ctrl+D is already used for Add Folder.
* JIRA ticket (_optional_): PICARD-1712
Use Ctrl+E as shortcut, and `e` as accelerator for Add Folder
Use Del/Ctrl+D for Remove action
See https://doc.qt.io/qt-5/qkeysequence.html
=> PICARD-1712: use QtGui.QKeySequence.Delete for remove albums/files shortcut

picard/formats/apev2.py, picard/formats/asf.py, picard/formats/id3.py, picard/metadata.py, picard/util/tags.py, test/formats/common.py, test/test_metadata.py, test/test_util_tags.py
* This is a…
Some of Picard's tag names allow an additional description separated by a colon, e.g. "comment:desc". In case the description part is empty and the tag ends on a colon this is now treated the same as without any colon. So "lyrics" and "lyrics:" are the same tag.
* JIRA ticket (_optional_): PICARD-239
Change `Metadata` to treat tags ending on a colon behave the same as the same without the colon.
Handling this in Metadata makes this change immediately available in scripting and to all formats. Script using both forms will still work. Only minor changes where necessary to the formats themselves.
=> PICARD-239: Handle tags like "comment" and "comment:" the same

picard/acoustid/json_helpers.py, test/data/ws_data/acoustid.json, test/test_acoustid.py
Make the release primary and secondary type as provided by AcoustId available to the matching.
This actually makes the preferred release types work for AcoustId lookups.
* This is a…
* JIRA ticket (_optional_): PICARD-1646
Convert release types returned from AcoustID into proper MB structure.
I tested this with https://www.youtube.com/watch?v=Nw_rbZ5kJU8 (which is the track also used in the ticket) and some local files. With the change it is possible switching between EP, Album and Compilation result for this recording by changing the weighting for preferred release types.
=> PICARD-1646: Consider release types for AcoustId results

picard/config.py
Make an update of existing config file on upgrade.
* This is a…
Picard's configuration will get updated if necessary on updates, but there is no support for downgrade. That means older versions of Picard might not be able to run with config files created by newer versions and an update might make the config unusable by older versions.
* JIRA ticket (_optional_): PICARD-1717
1. When running a version that is newer then the loaded config file, make a copy of the current config with a name of `Picard-x.y.z.ini`, where `x.y.z` is the old version. This ensures old config gets saved before it is altered, giving the user the opportunity to restore the old config if needed.
2. When starting Picard and there is an existing `Picard-x.y.z.ini` file …
=> PICARD-1717: Backup config on upgrade

picard/script.py, test/test_script.py
Add new functions to the scripting library.
* This is a…
* **Add new functions as:**
* 'find' substring within string
* string 'reverse'
* 'substr' to extract a substring from a string
* 'get_multi_item' to get an element from a multi-value variable
* 'foreach' to loop through each item in a multi-value variable
* 'for' loop
* 'while' loop
This additional functionality will allow users to easily access individual elements of multi-value variables, and perform repetitive code within loops that can be dynamically constructed.  Additional string functions allow searching for and extracting substrings.  Reverse can be used to find the last occurrence of a substring rather than just the first.
* JIRA ticket (_optional_): PICARD-1716
Suggested changes to the Scripting page of the Picard Website …
=> PICARD-1716: Add script functions for strings, multi-value variables, and loops

picard/metadata.py, picard/script.py, test/test_metadata.py, test/test_script.py
Since Picard 2.2 with commit 503b520 both $unset and $delete behave basically the same, both marking a tag for deletion.
* This is a…
* JIRA ticket (_optional_): PICARD-1719
Added an explicit `Metadata.unset` method to clear a tag without adding it to the deleted_tags array. use this for $unset.
Also added tests for $unset to avoid future regressions.
=> PICARD-1719: Fix $unset must not mark tags for deletion.

picard/script.py, test/test_script.py
Add a scripting function to join the elements of a multi-value variable into a string using a supplied join phrase. An example might be `$set(artist_string,$join(%artists%,\, ))`
* This is a…
* **Describe this change in 1-2 sentences**: Added a `join_multi()` scripting function to join the elements of a multi-value variable into a string using a supplied join phrase.  Also added associated tests.
Provide a way to quickly and easily join the elements of a multi-value variable into a string, using a custom join phrase between the elements.
* JIRA ticket : PICARD-1721
Added a `join()` scripting function to join the elements of a multi-value variable into a string using a supplied join phrase.  Also added associated tests.
=> PICARD-1721: Add $join() script function and associated tests

picard/script.py, test/test_script.py
Add a scripting function to extract (slice) a portion of a multi-value variable. An example would be to use `$setmulti(supporting_artists,$slice(%artists%,1))` to get a multi-value variable with all artists except the first.
* This is a…
* **Add new `$slice_multi()` scripting function with associated tests.**:
* JIRA ticket: PICARD-1720
Added new `$slice()` scripting function with associated tests.
=> PICARD-1720: Add scripting $slice() with associated tests.

picard/ui/options/__init__.py, picard/ui/options/plugins.py
Fix crash when closing options while loading plugins
* This is a…
Closing options while the web request for plugins is running causes Picard to crash with
RuntimeError: wrapped C/C++ object of type QTreeWidget has been deleted
That's because the C++ object has already been deleted while the callback still has a reference to the Python wrapper objects.
See also http://enki-editor.org/2014/08/23/Pyqt_mem_mgmt.html
* JIRA ticket (_optional_): PICARD-1726
Work around Qt C++ objects getting deleted before request callback gets called by connecting to the destroyed signal and setting a deleted state.
This feels kind of hacky, but I could not find a clean way to otherwise detect if an object is deleted. This fixes the issue and I think is an …
=> PICARD-1726: Fix crash when closing options while loading plugins

picard/file.py
Since the addition of the generate AcoustID fingerprints feature it was possible that files on the left pane were marked for fingerprint submission (red fingerprint indicator icon, "Submit AcoustIDs" lighted up).
* This is a…
The issue happens if a file on the left has the fingerprint generated and also has the `musicbrainz_recordingid` tag set.
But submitting fingerprints should only be done if files are properly matched to tracks on the right. They should not be marked as submittable if they are on the left, even if they have `musicbrainz_recordingid` set. This behavior is confusing, as the left is supposed to contain unmatched files with probably wrong metadata.
Only update the acoustidmanager with a …
=> PICARD-1724: Do not mark fingerprints in left pane for submission

test/formats/common.py, test/formats/test_vorbis.py, test/picardtestcase.py, test/test_bytes2human.py, test/test_config.py, test/test_coverart_utils.py, test/test_emptydir.py, test/test_file.py, test/test_filesystem.py, test/test_plugins.py, test/test_releaseversions.py, test/test_utils.py
- QSettings object needs special care, as file was re-created on exit
- Append a cleanup function as soon as possible to ensure temporary dirs & files are removed in any case
- prefer addCleanup() over tearDown(), keeping creation and cleanup together
* This is a…
Many stuff is left over in temporary directory (/tmp on linux) after running tests.
=> Tests: ensure temporary directories and files are removed after tests

picard/mbjson.py, test/data/ws_data/release.json, test/test_mbjson.py
Better tagging capabilities for multi-release country releases by providing a `%_releasecountries%` variable and improved selection of the value for `%releasecountry%`.
* This is a…
The existing "releasecountry" tag contains a single release country as returned in the country field for a release as returned by the MB web service. If there are multiple release countries only the first is used (in alphabetical order it seems).
* PICARD-1751
* PICARD-1752
- Add a `%_releasecountries%` variable
- Consider preferred releases to select the value for `%releasecountry%`
=> PICARD-1751, PICARD-1752: multi release country tagging

picard/acoustid/__init__.py, picard/acoustid/manager.py, picard/file.py, picard/tagger.py, picard/ui/itemviews.py, test/test_file.py
* This is a…
If a file already contains an acoustid_fingerprint tag and "Ignore existing AcoustID fingerprints" is turned off and if scan is used on this file, then:
fpcalc does not get called (expected)
the fingerprint does not get added to AcoustId manager (fail)
The result is that even after matching the file to a proper recording it is not possible to submit the AcoustID.
Also ideally Picard would already indicate the presence of the fingerprint after loading the file.
* JIRA ticket (_optional_): PICARD-1750
- Refactor the code so that `File` actually manages the acoustid_* attributes. This makes these always available and centralizes the calls to update AcoustIDManager.
- Already set `File.acoustid_*` attributes on file load, if the file …
=> PICARD-1750: Set AcoustID fingerprint to AcoustIDManager

picard/script.py, test/test_script.py
* This is a…
* **Describe this change in 1-2 sentences**: Added negative length checking to `$num` function.  Also added tests for negative length and length greater than 20.
* JIRA ticket: PICARD-1772
When a negative length is provided as an input to `$num`, the number will be right-padded with spaces.  The number of spaces added is the absolute value of the negative length provided.
Add negative length checking to `$num` function.
=> PICARD-1772: Fix negative length handling in $num

picard/script.py, test/test_script.py
* This is a…
* **Describe this change in 1-2 sentences**: Have `$find` return "" rather than "-1" on not found
* JIRA ticket: PICARD-1781
The `$find` scripting function currently returns "-1" if `needle` is not found in `haystack`.  This was based on the return value of the Python `find` method.  This is not consistent with other Picard scripting functions, which return "" for a `False` (not found?) condition.  For consistency, consider changing the `$find` function to return "" on a "not found" condition.
Have $find return "" rather than "-1" on not found.
=> PICARD-1781: Have $find return '' rather than '-1' on not found

picard/script.py, test/test_script.py
* This is a…
* **Describe this change in 1-2 sentences**:  Trap the `ValueError` in `$datetime`.
* JIRA ticket: PICARD-1776
When specifying a platform-specific format code (e.g. "%-d" on Windows 7), `$datetime` crashes with a ValueError.
Trap the `ValueError` in `$datetime` and ~~return "Invalid Format" message~~ raise a `ScriptRuntimeError` exception.
=> PICARD-1776: Trap ValueError exception in $datetime function

picard/tagger.py
With Qt 5.14 setting HighDpiScaleFactorRoundingPolicy allows proper scaling to e.g. 150% on Windows 10. Otherwise Qt5 would just scale to the next full factor, e.g. 200%.
* This is a…
* JIRA ticket (_optional_): PICARD-1777
Since Qt 5.14 is is possible to set `HighDpiScaleFactorRoundingPolicy.PassThrough`. This will configure Qt to use the scaling factor as provided by the operating system, e.g. 1.5 on Windows if the scaling is set to 150%. By default it is set to `Round`, which results in 1.5 getting rounded up to 2.
I tested this on Windows and Linux:
- Windows with Qt 5.14 will now correctly consider the scaling factor. With Qt 5.13 this is not supported and a system setting of 150% will effectively scale to 200%.
- Linux GNOME 3.34 …
=> PICARD-1777: Properly support fractional scaling on Windows 10

picard/coverart/providers/caa.py
* This is a…
When downloading PDF cover art images, thumbnail URL is only the first letter of the actual URL.
This leads to various problems.
```
D: 18:12:01,232 coverart.next_in_queue:204: Downloading CaaThumbnailCoverArtImage(url='h', types=['booklet'], support_types=True, support_multi_types=True, is_front=False)
D: 18:12:01,232 webservice.ratecontrol._out_of_backoff:229: ('ia800305.us.archive.org', 80): oobackoff; delay: 1000ms -> 1000ms; slow start; window size 1.000 -> 2.000
D: 18:12:01,233 webservice.ratecontrol.get_delay_to_next_request:113: ('', 80): First request
D: 18:12:01,234 webservice.ratecontrol.increment_requests:138: ('', 80): Incrementing requests to: 1
D: 18:12:01,235 webservice.ratecontrol.decrement_requests:146: ('', 80): …
```
=> PICARD-1784: fix a typo leading to Coverart error: Host not found

_config.yml, picard/ui/searchdialog/__init__.py, picard/ui/tablebaseddialog.py
This creates a superclass with the common code pulled out of SerachDialog so that I can use it in Match Dialog, per your suggestion in PR-1497
* This is a…
PR 1497 created new dialog box which resulted in duplicated code with SearchDialog 
Refactored out the duplicated common code to a new class that can be shared. and changed SearchDialog to use it.
=> Dialog superclass

picard/acoustid/json_helpers.py, picard/metadata.py, test/test_acoustid.py
#Summary
Parse additional fields from the AcoustId response
* This is a…
AcoustId returns many data elements, but not all are parsed out and made available within Picard.
Changed acoustid/json_helpers.py to parse out additional data elements.
=> Parse additional fields from the AcoustId response

picard/cluster.py, picard/file.py, picard/metadata.py, picard/util/__init__.py, requirements-macos.txt, requirements-win.txt, requirements.txt, setup.py
New logic to include the release date in scoring process.
(Separated out from PR 1771 as you requested)
* This is a…
Seems some of the results from AcoustId don't have a release date, and we need a way to de-prioritize those records with lower quality data from the match process.
PICARD-1796
Enhanced the scoring process to consider the release date.  It will give highest Part Score to results that have a date that match our own tag, next to records that have a date where year is +/-2 years, next to records that have a non-blank date, next a minimal score if the date is missing, and the lowest Part Score if the date is there but does not match.
Sorry need little guidance on creating the JIRA you asked to have associated with this.
Please ignore the _config.yml for theme.  Very bizzare that …
=> PICARD-1796: Date scoring logic

picard/mbjson.py, test/data/ws_data/recording_credits.json, test/test_mbjson.py
EWI must not become E W I
* This is a…
The _decamelcase function in mbjson turns "EWI" into "E W I".
* JIRA ticket (_optional_): PICARD-1803
Fix the decamelcase function, to not enter spaces before a upper case character if it is preceded by another upper case or whitespace character.
@zas This fixes the issue of added whitespaces in EWI, but I am not sure about two things:
1. Do we need the decamelcase at all? For which attributes is it needed? I have a faint memory of this, but it probably is for some legacy reason. If it is only for some specific attributes we maybe could at least call decamelcase only when needed.
2. With this patch "EWI" still gets turned to lowercase "ewi". Is this expected? Should we change it?
=> PICARD-1803: Fixed decamelcasing relationship attributes

picard/file.py, picard/formats/__init__.py
* This is a…
Prioritize loading based on file extension and fallback to format guessing if it fails.
The current logic opens one file at a time, reads the file header, try to guess the file format based on the header and then proceeds to the loading phase. This results in a huge overhead of opening every single file twice, which in case of large libraries can be even worse as the file doesn't stay in memory cache.
* JIRA ticket (_optional_): PICARD-1809
Assume that a file extension is correct if one exists. Try to load the file based on the file extension and fallback to format guessing based on the header if it fails. Finally, retry loading with guessed format. There are 3 file opening operations in case of failures, but the file stays cached …
=> PICARD-1809: Load based on extensions, fallback to guessing if it fails

picard/tagger.py, picard/ui/statusindicator.py
* This is a…
* Make PyQt5.QtDBus optional / do not fail if QtDBus cannot be imported
It is possible to install PyQt5 without support for dbus ([e.g. under gentoo](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/PyQt5/PyQt5-5.14.2.ebuild?id=52d0279f1ae255004dbf5b3e5b8525d6ff1e4912#n125)) resulting in Picard failing to start up with a message like
```
File "/usr/bin/picard", line 2, in <module>
from picard.tagger import main
File "/usr/lib/python3.7/site-packages/picard/tagger.py", line 61, in <module>
from PyQt5.QtDBus import QDBusConnection
ModuleNotFoundError: No module named 'PyQt5.QtDBus'
```
PICARD-1818
Wrap imports of `PyQt5.QtDBus` with `try`.
=> PICARD-1818: Make PyQt5.QtDBus optional

picard/track.py
This commit sorts genres lexicographically so that the order is
deterministic, preventing tag updates due to changes in hash functions
etc.
* This is a…
[PICARD-1823](https://tickets.metabrainz.org/browse/PICARD-1823)
When opening releases on different platforms I've noticed that the order of genre tags is non-deterministic (probably due to differences in the Python hash function), which causes the genre tag to be needlessly rewritten. 
This trivial commit calls sort() on the genre array, ensuring that the order of genres is deterministic.
=> PICARD-1823: Sort genre tags lexicographically

picard/formats/__init__.py, picard/formats/vorbis.py, test/formats/common.py, test/formats/test_vorbis.py
Fixes e.g. loading Ogg Opus files with .ogg extension, instead of assuming .ogg is always Ogg Vorbis.
* This is a…
This broke in PICARD-1809 when we started preferring the file extension again. Now every .ogg file iso considered a generic file in a Ogg container. This means of course for these files we basically do content based detection again.
* JIRA ticket (_optional_): PICARD-1826
=> PICARD-1826: Consider .ogg files as generic Ogg container files

picard/cluster.py, picard/ui/itemviews.py, picard/ui/mainwindow.py
* This is a…
Mitigate code that forces unnecessary draws during item updates, letting Qt handle the changes. Prevent exponential checks caused by `MainPanel._view_update_selection`, as detailed in https://github.com/metabrainz/picard/pull/1543#issuecomment-633148605 during the removal of an item of the selected list (all moves cause this). 
* JIRA ticket (_optional_): PICARD-1831
The solution implemented in this PR bypasses the the selection checks by disabling them during processing (e.g. moving things around either manually or during clustering). As soon as the move finishes, the selection can be changed. 
The other change to reduce draws works by removing `if self.isSelected(): [...]`, which updated the screen on the spot if changes were …
=> PICARD-1831: Mitigate performance impacts of file selection and UI updates during processing

picard/formats/id3.py, picard/formats/mutagenext/compatid3.py
This cleans up compatid3 by removing frames that are natively supported by mutagen >= 1.37 (which is our current minimum supported version). In 1.38 even `GRP1` would be supported, but I think it is ok to stick with 1.37 for now.
* This is a…
=> Remove frames from compatid3 supported by mutagen >= 1.37

picard/formats/id3.py, picard/formats/mutagenext/compatid3.py, picard/formats/wav.py
AIFF and DSF lacked support for the tags albumsort, artistsort, titlesort and discsubtitle due to limitations in using CompatID3.
* This is a…
* JIRA ticket (_optional_): PICARD-1842
Add a `compatid3.update_to_v23` that can be used on existing `mutagen.id3.ID3` instances.
=> PICARD-1842: Full ID3 tag support for AIFF, DSF and WAVE

picard/version.py, test/test_versions.py
* This is a…
A version "2" should be treated equivalent to "2.0" or "2.0.0". Allows setting a single digit plugin version and have it displayed correctly.
* JIRA ticket (_optional_): PICARD-1820
=> PICARD-1820: Allow single digit versions like "2" to be parsed

picard/tagger.py, picard/ui/itemviews.py, picard/ui/mainwindow.py
* This is a…
Speeds up loading by scanning the entire directory before feeding threads instead of concurrently, preventing starvation of worker threads.
Speeds up clustering and file moving by disabling panel sorting during operations. 
Load and clustering are slow, especially with a large library. More details can be found [here](https://github.com/metabrainz/picard/pull/1531).
Partially addresses PICARD-840, PICARD-905, PICARD-1432 and PICARD-1780, but none of them in particular.
* JIRA ticket (_optional_): PICARD-1843
1 - Scan entire directory before feeding worker threads, to prevent starvation (around 3x/8x speedup without/with the following changes).
2 - Postpone inclusion of loaded files to the unclustered_files cluster to the …
=> PICARD-1843: Improves load and clustering performance

picard/browser/filelookup.py, picard/ui/metadatabox.py
Add "Lookup in Browser" context menu for musicbrainz_discid
* This is a…
For other MusicBrainz identifies, such as MB release or artist ID, Picard offers a "Lookup in Browser" context menu of the metadata box.
Add this option also for musicbrainz_discid
* JIRA ticket (_optional_): PICARD-1845
=> PICARD-1845: Add "Lookup in Browser" context menu for musicbrainz_discid

picard/cluster.py, picard/config.py, picard/metadata.py, picard/tagger.py, picard/ui/itemviews.py, picard/util/progresscheckpoints.py, picard/util/textencoding.py, po/picard.pot, test/test_util_progresscheckpoints.py
* This is a…
Clustering is slow due to a multitude of factors, but especially due to screen updates and things blocking the main thread, which handles these updates. Offloading clustering to a worker thread mitigates this problem.
Some of the changes meant to https://github.com/metabrainz/picard/pull/1543 ended up being lost while I was reworking the code to remove the Python threads code. This PR contains those changes.
* JIRA ticket (_optional_): PICARD-1844
This PR contains the following changes to address the slow clustering issue:
Updating statusbar with the clustering progress, as it takes some time to complete
~Return a Python event when sending callbacks for the main thread, allowing worker threads to wait for the main thread, giving it …
=> PICARD-1844: Further improve loading and clustering performance

picard/metadata.py, picard/script.py, test/test_metadata.py
Having Metadata.unset raise an KeyError is kind of unexpected, especially as other operations like Metadata.get or Metadata.delete don't do this.
This also fixes a possible crash introduced in https://github.com/metabrainz/picard/pull/1556
See discussion in https://github.com/metabrainz/picard/pull/1559
* This is a…
* JIRA ticket (_optional_): PICARD-1846
Update Metadata.unset to always succeed, even for unknown values.
=> PICARD-1846: Do not raise KeyError in Metadata.unset

picard/ui/statusindicator.py
With recent improvements on the performance the processing difference between loading a file and a network request became more obvious, making the progress bars look odd. Weight pending requests higher to better reflect actual progress.
The part of loading the files is still faster, but I think now it "feels good" for the user looking at the progress bar, which is kind of what counts.
On a side note I also tested if there is any performance impact on having the status indicators active or not. But there was no measurable difference in overall loading time of my 4k test files. The status update (which handles both updating the status bar at the bottom and the desktop progress bars) is already throttled, and this seems to be sufficient.
=> Adjust weights for pending files and requests in progress indicators

picard/tagger.py, picard/ui/__init__.py, picard/ui/logview.py, picard/ui/options/renaming.py, picard/ui/options/scripting.py, picard/ui/widgets/scripttextedit.py
Fix using the proper monospaced font on Windows in correct size.
* This is a…
The script editor font on Windows is rendered smaller then elsewhere. Also sometimes it picks a font which renders pixelated. Same was true for the log view.
* JIRA ticket (_optional_): PICARD-1753
Explicitly define a font based on operating system. The generic approach did not work well on Windows and chose a less optimal font. Also explicitly setting the font overwrote the font size on Windows to be way too small.
I also tried other ways getting a decent default font, but it did not work reliable. E.g. ` const QFont fixedFont = QFontDatabase::systemFont(QFontDatabase::FixedFont)`   gave a very bad result on Linux, and about the same mess as before on Windows.
On …
=> PICARD-1753: Fixed script font not scaling on Windows

picard/ui/options/dialog.py
Remember the option page the user had opened the last time and show this again as default when opening the options dialog.
* This is a…
* JIRA ticket (_optional_): PICARD-920
Remember the last active page in a config option. Ignore the about name, as I think this is not useful and opening Help > About should not reset the last active real options page.
=> PICARD-920: Remember last opened options page

picard/util/natsort.py, test/test_util_natsort.py
Fix crash when loading files where tag values contain null characters, if those tags are used for column sorting.
* This is a…
`natsort.natkey` will crash on strings which contain `\0` chars.
```
(env) ~\devel\musicbrainz\picard [PICARD-1852-about-dialog]> python .\tagger.py
W: 16:20:30,547 ui.mainwindow.create_actions:529: CDROM: discid library not found - Lookup CD functionality disabled
File ".\picard\ui\itemviews.py", line 872, in __lt__
return self.sortkey(column) < other.sortkey(column)
File ".\picard\ui\itemviews.py", line 877, in sortkey
return natsort.natkey(self.text(column).lower())
File ".\picard\util\natsort.py", line 36, in natkey
return [int(s) if s.isdigit() else strxfrm(s)
File …
```
=> PICARD-1853: Fix natsort crashing on strings with '\0'

.pylintrc, picard/coverart/utils.py, picard/i18n.py, picard/ui/options/releases.py, setup.cfg
If available, use gettext.pgettext (available since Python 3.8). Fall back to custom implementation for older Python versions.
* This is a…
For the attributes we need to access gettext strings with context. Normally this is provided by gettext with the pgettext(context, message) function, but this was not available in Python until version 3.8
* JIRA ticket (_optional_): PICARD-1856
Add support for pgettext in Python 3.8, but keep the old code for older versions.
=> PICARD-1856: Use gettext.pgettext in Python 3.8

picard/util/natsort.py, test/test_util_natsort.py
Picard crashes in natsort when encountering characters that are considered numeric, but not decimal, such as e.g. `²`.
* This is a…
* JIRA ticket (_optional_): PICARD-1853
Use `str.isdecimal` to check for valid characters. Add tests to ensure there is no crash, but decimal numbers also from other writing systems still work. That means natsort will still naturally sort e.g. numbers in Arabic script (٠١٢٣٤٥٦٧٨٩), but not crash on superscript or subscript characters.
The code now would not properly sort `'⁸'` < `'⁰⁹'`. We could implement also this by converting the input string to e.g. `'^8'` and `'^09'`. But this ads additional overhead, it makes natkey more than twice as slow. I don't think it is worth it, but I have an implementation of this at …
=> PICARD-1853: Fix crash in natsort on superscript numeric chars

picard/file.py
If a file is matched against a NAT during lookup, ensure the full metadata is loaded for this recording instead of relying on the search result.
* This is a…
When a file got matched against a standalone recording (aka non-album track) the metadata from the search result was used, which lacked extended metadata.
* JIRA ticket (_optional_): PICARD-1855
Ensure a separate request for the recording is made, including all the metadata.
The details of your change. Talk about technical details, considerations, or
other interesting points. If you have a lot to say, be more detailed in this
section.
-->
=> PICARD-1855: Ensure all recording details get loaded for NATs

picard/tagger.py
* This is a…
Postpone move to target to make sure MBIDs can be checked first.
* JIRA ticket (_optional_): PICARD-1864
During refactoring to reduce moves between clusters, I didn't pay enough attention to target!=none case of file_loaded (which doesn't happen unless you're moving things around from file browser), skipping necessary checks.
Reorder the move to target and remove return to make sure all files are tested for 'analyze_new_files' and 'ignore_file_mbids'.
=> PICARD-1864: Reorder move to target

picard/file.py, picard/tagger.py
Properly handle trying an alternative file format on file load errors by injecting the guessed file format into the file load queue. Avoids issues with the loaded file object being the wrong type and having two file objects causing the pending files to be displayed wrongly.
* This is a…
The implementation of trying alternatve file format in File._load_check has some flaws.
For one, it just returns the result of a different format, but the original `File` object stays the same. So you e.g. get a MP3 file called "mp3.wav" properly loaded because `WAVFile._load_check()`  will return the result of `MP3File._load()`, but the original file object will still be of type `WAVFile`.
Also the creation of the additional file object will increase the …
=> PICARD-1867: Fix guess_format fallback on file load error

picard/ui/itemviews.py, picard/ui/mainwindow.py
* This is a…
Restore itemview calls to MainWindow.update_selection, fixing coverart updates on the metadatabox. 
While trying to improve performance with large libraries, I ended up removing MainWindow.update_selection calls, which are exponential. Further analysis shown that the expensive part of the call is the comparison of tag values of selected files and respective updates of the metadatabox.
* JIRA ticket (_optional_): PICARD-1866
Calls to MainWindow.update_selection are restored in itemview updates, but using a flag to indicate the selection remains the same to skip tag comparison during updates. This solves part of the reported issues, while still requiring the user to manually change the file selection to trigger the expensive updates. …
=> PICARD-1866: Restore cheaper update_selection for itemview updates

picard/ui/colors.py, picard/ui/options/scripting.py, picard/ui/theme.py
Instead of having a separate configurable color use the color from the syntax theme.
* This is a…
When a dark background is used for the scripting documentation window the functions are not readable. Change the code to use the function color for the syntax theme, which can  be made aware of the color.
* JIRA ticket (_optional_): PICARD-1881
Take the function color from the syntax theme.
Right now this fixes the issue for Windows, not macOS and KDE. For macOS our release builds do currently not support dark theme anyway. For KDE we need to detect usage of dark UI.
=> PICARD-1881: Use scripting syntax function color for script docs

picard/ui/theme.py
* This is a…
Change color of inactive highlighted items to differentiate them from active highlighted items.
Active and inactive highlighted items currently use the same color, confusing users as reported in [link](https://community.metabrainz.org/t/picard-2-4-beta-2-selection-focus-issue/484898).
Differentiate active and inactive color for highlighted items, deriving the color from the selected accent.
```
if dark_theme:
palette.setColor(QtGui.QPalette.Link, accent_color.lighter())
palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Highlight, accent_color.lighter())
palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, accent_color)
else:
palette.setColor(QtGui.QPalette.Link, …
```
=> Increase contrast between focused and unfocused highlighted items while using accent colors on Windows

scripts/pyinstaller/macos-library-path-hook.py
Hello,
i downloaded MusicBrainz 2.3.2 and 2.4.0b2 on macOS 10.13.6 (latest for my mac)
- Starting "MusicBrainz Picard" from DMG ist works
- Starting "MusicBrainz Picard" from a copy everywhere on hard drive the system tells me "is damaged and cannot be opened"
- Calling "...//MusicBrainz\ Picard.app/Contents/MacOS/picard-run" from terminal it works, too!
What fucking apple guardian makes "MusicBrainz Picard" unable to start on macOS 10.13.6?
=> PICARD 2.3.2 / 2.4.0b2 "is damaged and cannot be opened. Move to trash"

picard/mbjson.py, test/data/ws_data/release.json, test/test_mbjson.py, test/test_metadata.py
* This is a…
Don't use release relationships in tags when "Use release relationships" is disabled.
When "Use track relationships" is enabled in Metadata Options but "Use release relationships" is disabled, Picard would write release relationships to tags anyway. There is no way at the webservice request level to exclude Release-Artist relationships if you also want Recording-Artist and Work-Artist relationships, so the release-level relationships must be filtered out client-side.
* JIRA ticket (_optional_): PICARD-1889
Filter out release-level relationships if "Use release relationships" is disabled.
=> PICARD-1889: Don't use release relationships if "Use release relationships" is disabled

picard/formats/vorbis.py, test/formats/test_vorbis.py
* This is a…
Deleting of totaldiscs or totaltracks failed if the file only contained disctotal or tracktotal tags, but not also totaldiscs or totaltracks.
* JIRA ticket (_optional_): PICARD-1892
Check existence of tags before trying to delete them. Added a test.
=> PICARD-1892: Fixed deleting totaldiscs / totaltracks from Vorbis tags

picard/file.py, picard/util/__init__.py, test/test_tracknum.py
* This is a…
Do not detect parts of longer numbers as track no., e.g. "Song 2015" must not be detected as track no. 15.
* JIRA ticket (_optional_): PICARD-1894
=> PICARD-1894: Fix tracknumber detection from filename

picard/metadata.py, picard/util/__init__.py, test/test_utils.py
* This is a…
* JIRA ticket (_optional_): PICARD-1891
Incorrect year data could cause unhandled exceptions.
- catch exceptions in extract_year_from_date() and log them to debug
- return None if year cannot be extracted
- check for None in metadata.compare_to_release_parts() before trying to compare years
This isn't perfect, the function is called a lot of time and it spams debug log (if enabled)
Note: I removed a very old comment in imports that doesn't make any sense (it was introduced 6 years ago in 323d12892c7f975b1e7286f57d72b60274a096e7) and it was making isort unhappy.
=> PICARD-1891: handle incorrect date parsing exceptions

picard/ui/mainwindow.py, picard/ui/metadatabox.py
* This is a…
Update metadatabox more frequently to reflect user changes after editing a single file/cluster/track/album.
* JIRA ticket (_optional_): PICARD-1866
In PR https://github.com/metabrainz/picard/pull/1579 part of the issue in PICARD-1866 was solved, but it still required users to click on other items and then click again on the edited item to update its tags. 
This PR lets Picard continue updating the metadata box in case a single file/cluster/track/album is selected, which should solve the issue for what is assumed to be the common use case. If more than a cluster/album are selected, the metadatabox keeps its original value during updates to prevent reprocessing the tags. If the file/track selection changes, the metadatabox is …
=> PICARD-1866: Update metadatabox if a single file/cluster/track/album metadata changes.

picard/util/__init__.py, requirements.txt
dateutil < 3.8.1 will throw ValueError, and not the derived ParseError. For compatibility with existing Linux distros.
* This is a…
=> Support python-dateutil 3.7

picard/ui/widgets/scripttextedit.py
Fixed Picard crashing when entering `$noop(\)` as a script.
* This is a…
* JIRA ticket (_optional_): PICARD-1902
Fixed syntax highlighting to check for end of script.
=> PICARD-1902: Fixed script syntax highlighter crash

picard/album.py, picard/ui/metadatabox.py
* This is a…
Use original values is only available for tracks with files attached. Now tracks and albums can also be resetted. 
Try selecting an album with a few files matched to tracks and others with no files. Now change a tag (e.g. album name), then right-click to restoring the original values. 
If the tag was saved to the album, it won't be recovered as the orig_metadata field was empty (L378 of album) and the context menu didn't create the calls to set the tags to their original values (L366-370 of metadatabox).
If the tag was saved to an unmatched track, it won't be recovered as the context menu didn't create the calls to set the tags to their original values (L371-374 of metadatabox). Even if it was restored, you wouldn't see as the …
=> PICARD-1913: Expand "Use original values" to tracks and albums

picard/ui/edittagdialog.py, picard/ui/ui_edittagdialog.py, ui/edittagdialog.ui
After entering or selecting the tag name open automatically switch to editing the value. Enter key enters new value instead of closing dialog.
* This is a…
The tag editor dialog is a bit awkward to use and it is easy to close the dialog without action.
* JIRA ticket (_optional_): PICARD-1860
Make the enter key add a new value and automatically switch to value edit mode after a tag has been selected in the tag selector.
=> PICARD-1860: Easier editing in tag edit dialog

picard/ui/theme.py
There is no separate look for inactive / active checkboxes on Windows 10 with dark theme
* This is a…
* JIRA ticket (_optional_): PICARD-1921
Status quo:
Fixed:
Set inactive base color.
I could not find a proper color used commonly for this on Windows, but this way it looks good to me. Lighter or darker make it look out of place.
=> PICARD-1921: Set base color for inactive elements with dark Windows theme

picard/file.py
Trying to save cover art as separate files would fail, if there is no image with type "front" and caa_save_single_front_image is enabled.
* This is a…
* JIRA ticket (_optional_): PICARD-1918
Check if a front image was found before updating the list of images to save. This way we don't end up with `images == [None]` 
This fixed the exception, but we have a more general problem with this.
The caa_save_single_front_image option is really odd, and I am not fully sure what it is supposed to do. First off it is presented as a CAA option, but it applies to all cover art.
Also the code as it was and is now suggests that if there is no front image all images will be saved anyway. That looks wrong to me. Either it should save nothing or maybe fall back …
=> PICARD-1918: Fix issue saving cover art without front image

picard/ui/itemviews.py
When files have the fingerprint generated the fingerprint column gets emptied after clustering the files. This is a pure display issue, as the fingerprint is still kept with the file.
* This is a…
* JIRA ticket (_optional_): PICARD-1928
The issue got introduced with the refactoring in 155da500f43e7661808ab4cce911466e75ddb759, but is not directly caused by it but rather makes the problem visible.
Update file item after being added to cluster item
=> PICARD-1928: Ensure fingerprint status icon is rendered correctly after clustering

picard/album.py, picard/tagger.py
Fixes the issue introduced in fac2b37 where files did not get moved to the album after a loading error.
* This is a…
* JIRA ticket (_optional_): PICARD-1931
Allow registering `run_when_loaded` callbacks that are run always even in case of error.
=> PICARD-1931: Ensure file gets moved to album after load

.github/workflows/run-tests.yml, MANIFEST.in, scripts/package/run-sdist-test.sh
Verify in CI the sdist package is complete and passes tests.
This makes sure the sdist tarball includes all files needed to run the tests.
* This is a…
Users and distributions wanting to install or package from the sdist and wanting to verify the tests pass need to have the tests available.
* JIRA ticket (_optional_): PICARD-1935
I know we had this discussion before (see #1282 and #1288), but I have to agree with David who reported on PICARD-1935. The tests should really be part of the source, it should not be difficult to run the tests from it.
If I look at the default behavior of setuptools (including test) and the documentation at https://docs.python.org/3/distutils/sourcedist.html#specifying-the-files-to-distribute I really think it is the …
=> PICARD-1935: Include tests in sdist (again)

picard/album.py
Fixes another issue related to PICARD-1931: if you load a file with invalid mbid, this now gets moved to the unmatched files entry on the release that failed to load. but when you add another file with the same invalid release ID later, it is not displayed there (the file is loaded, but does not show)
* This is a…
* JIRA ticket (_optional_): PICARD-1931
=> PICARD-1931: Fix files not getting moved to album which failed to load

picard/cluster.py
If clusters where removed because of file removal scan or lookup selection updates where disabled. Ensure selection gets updated.
* This is a…
Selection was not updated after automatic cluster removal, e.g. during lookup or scan. This meant the action buttons stayed enabled, and e.g. the remove file action would still be available but crash on use.
* JIRA ticket (_optional_): PICARD-1939
Have selection update enabled for cluster removal. The actual selection changed event will still only trigger, if the cluster was actually selected before. In itemviews.py `cluster.item.setSelected(False)` gets called, which does not trigger any even if the status does not actually change.
=> PICARD-1939: Ensure selection update after cluster removal

picard/tagger.py, picard/ui/filebrowser.py, picard/ui/itemviews.py, picard/ui/mainwindow.py
This replaces tagger.add_directory and simplifies the code to load files at different places. As suggested at https://github.com/metabrainz/picard/pull/1623#pullrequestreview-483911047
* This is a…
=> Add tagger.add_paths to load both files and directories

picard/mbjson.py
* This is a…
* JIRA ticket (_optional_): PICARD-1946
Map _vocal arranger_ relationship to the `arranger` tag (in addition to unspecific _arranger_, _instrument arranger_ and _orchestrator_).
This change has been tested with a manipulated [release from the test server](https://test.musicbrainz.org/release/542ef258-7bfd-48a6-83f3-443291a0ea29) as I have not found a suitable release that has all the other arranger relationship types besides a _vocal arranger_ relationship.
=> PICARD-1946: Map "vocal arranger" relationship to arranger tag

picard/album.py, picard/metadata.py, picard/track.py, test/test_metadata.py
This allows using existing file metadata and and specific file variables (such as e.g. %_bitrate%) to be used in tagger script.
* This is a…
* JIRA ticket (_optional_): PICARD-259, PICARD-23
When a file gets moved to a track run the scripts on a combined metadata object consisting of the file's metadata + the track's metadata.
A similar patch had been proposed earlier in #170, but it got reverted. This patch is conceptually the same, but a bit simpler due to:
- we now have `track.orig_metadata` already available
- the script is not run against the track's metadata again, which also means we do not need to handle the file removal as restoring file's original metadata is already done. I don't think we need to re-run the script on the track, as …
=> PICARD-259: Execute tagger script when file gets moved to track

picard/album.py, picard/tagger.py, picard/ui/itemviews.py
* This is a…
When dragging and dropping multiple files onto a track, assign the first file to this track and the following files to the following tracks in order.
* JIRA ticket (_optional_): PICARD-1879
Currently when dragging and dropping multiple files onto a track all the dropped files get assigned to this track. This is probably seldom what you want unless you explicitly have multiple files of the same track.
This patch changes the default behavior so multiple files get matched in sequence to multiple tracks, starting with the first file getting matched to the track being dropped on and the following files to the next tracks.
For the rare circumstances someone really wants to add multiple files to a single track the patch allows dragging with the Alt modifier pressed. I consider this …
=> PICARD-1879: Sequential matching of files on drop

requirements-macos.txt
This PR downgrades PyQt from 5.13.2 to 5.13.1, which resolves startup issues on the new macOS 11 Big Sur.
* This is a…
* JIRA ticket (_optional_): PICARD-1858
On macOS Big Sur the application stops responding after start without showing the UI. Actually even a very minimalistic Qt5 app with only an empty window will stop responding as soon as the app's mainloop gets executed. The exact reason is unknown, but it happens with PyQt >= 5.13.2 (tested up to 5.15.1).
This actually only happens when running from the packaged app. Running from Picard from source works fine. For now I can't say whether the core problem lies within PyQt5 or PyInstaller.
For now downgrade PyQt. As we are using PyQt 5.13 series anyway for backward compatibility with macOS 10.12 this does not matter much.
For the …
=> PICARD-1858: Fix running on macOS Big Sur

picard/ui/itemviews.py
Fixes a crash when opening the context menu on an album with loading errors.
* This is a…
* JIRA ticket (_optional_): PICARD-1954
Picard crashes with 
```
File ".\picard\ui\itemviews.py", line 588, in contextMenuEvent
if obj.release_group.loaded:
AttributeError: 'NoneType' object has no attribute 'loaded'
```
Check if the release group exists for the album before enabling the "Other versions" menu.
=> PICARD-1954: Fix crash on context menu for album with loading error

picard/__init__.py, picard/config_upgrade.py, picard/ui/itemviews.py, picard/ui/mainwindow.py, test/test_config_upgrade.py
Prevent complete hiding of metadata box or file panes
* This is a…
By completely dragging the splitter between the file panes and the metadata box up or down the user can completely hide any of those parts. This results in a UI that appears broken, and without any hint to the user that there is a missing part and that they can make it visible again.
See the screenshots in PICARD-1951
* JIRA ticket (_optional_): PICARD-1951
Set the parts of the splitter to be not-collapsible.
Note: According to Qt5 documentation one should be able to do this with a single call to `splitter.setChildrenCollapsible(False)`, see https://doc.qt.io/qt-5/qsplitter.html#childrenCollapsible-prop
But when I tried this (with PyQt 5.15.1 on Windows 10) it had no effect. Only setting `setCollapsible` per element …
=> PICARD-1951: Prevent complete hiding of metadata box or file panes

picard/ui/options/interface.py
* This is a…
Make the built-in search enabled by default.
* JIRA ticket (_optional_): PICARD-1955
The built-in search is easier to use for new users and does not rely on the browser integration (which causes frequent trouble for new users and needs quite some technical explaining if it does not work as expected). Also the "Lookup in browser" functionality is still available separately, even from within the search dialogs.
We keep the option. The browser based search can offer more flexibility, as it allows using all the search functionality the MB website has to offer. Hence advanced users might want to turn off the built-in search.
Existing users are not affected, their config remains untouched.
=> PICARD-1955: Use built-in search by default

picard/ui/itemviews.py, picard/ui/widgets/tristatesortheaderview.py
* This is a…
Allow locking the table headers in the main view.
Locked headers cannot be changed. This prevents accidental resorting and changes to the list views. The lock state of each table header is persisted.
* JIRA ticket (_optional_): PICARD-1782
Implement locking in `TristateSortHeaderView` and add an action to the header's context menu to toggle this.
=> PICARD-1782: Allow locking itemview table headers

picard/ui/filebrowser.py
* This is a…
Allow the user to load files into Picard by double clicking files or folders in the file browser. Double clicking to open a file is a common behaviour and offers another alternative to drag and drop (which sometimes is difficult to do) or the new context menu entry.
* JIRA ticket (_optional_): PICARD-1957
=> PICARD-1957: Load files in file browser on double click

picard/ui/widgets/tristatesortheaderview.py
* This is a…
As suggested in #1643 show a tooltip explaining how to unlock a locked table header. The tooltip is shown when the user clicks on a locked table header.
* JIRA ticket (_optional_): PICARD-1782
=> PICARD-1782: Show a tooltip when user clicks on locked table header

scripts/package/macos-package-app.sh
* This is a…
In macOS packaging script support detection of version 11.0 for notarization support.
There are actual two issues with the version detection for macOS 11 Big Sur:
1. Have notarization enabled for version 11. This was discussed in https://github.com/metabrainz/picard/pull/1351, but not added since we did not know anything about major version 11 at that point.
2. Support versions with only two segments. The versioning code assumed the version always had 3 segments (0.0.0), but Big Sur reports itself as being 11.0 only. This caused the MACOS_VERSION_MAJOR variable to be 11.0. The changed script will both properly detect the major version for 11.0.0 and 11.0.
=> macOS: Handle OS version 11.0 in package script

scripts/package/macos-package-app.sh
* This is a…
Add a symlink to `/Applications` in the macOS DMG image. This is quite common when distributing macOS applications to offer the user a simple way to install the app on the system.
`/Applications` is the usual place for putting the app bundle and having the symlink makes it easy for the user to copy the app bundle over without the need to open a second Finder window.
* JIRA ticket (_optional_): PICARD-1958
Add a symlink to the DMG
=> PICARD-1958: macOS: Add a link to /Applications to DMG

picard/ui/options/scripting.py, picard/ui/theme.py, picard/ui/widgets/scripttextedit.py
* This is a…
Try to automatically switch the syntax highighting color on a dark color scheme.
* JIRA ticket (_optional_): PICARD-1882
Picard might use a dark color palette. This can happen e.g. on KDE (which sets a color palette based on the selected theme), or  by the user actually switching the Qt style once we have #1638 merged. Dark background colors makes reading the default syntax highlighting theme difficult. We have an optimized version for dark colors and should use this.
This PR tries to dynamically detect dark background colors being used by actually looking at the lightness of the base color set in the palette.
Note: If the color is somewhere in between both themes might actually look bad. But this would be more an issue with the theme itself, the issue is not limited to our …
=> PICARD-1882: Generic detection of dark color scheme in use

picard/ui/ui_cdlookup.py, ui/cdlookup.ui
* This is a…
If there are matches for a disc ID but it does not match the release the users are looking for, many users struggle with how to actually submit the disc ID.
The dialog offers a "Lookup in Browser" button, but it is not obvious that this provides a way to submit the disc ID to MB. I suggest renaming the button to "Submit disc ID".
* JIRA ticket (_optional_): PICARD-1959
=> PICARD-1959: Rename disc ID "Lookup in Browser" to "Submit disc ID"

picard/ui/options/interface.py, picard/ui/theme.py, picard/ui/ui_options_interface.py, ui/options_interface.ui
* This is a…
In #1635 it is proposed to use the system Qt theme on Linux. This is an alternative proposal to still default to the Fusion theme but add an option to opt-in using the system theme.
* JIRA ticket (_optional_): PICARD-1952
Picard uses the Fusion themes on most platforms, with the notable exception of macOS where Qt's "macintosh" theme is used.
On Linux it is common to configure different Qt themes, so some users want Picard to obey this. On the other hand we as the devlopers can't guarantee that the UI remains pretty and usable when an arbitrary theme is being used.
Still default to the Fusion theme, but add an option "Use system theme" in Options > User interface . When selected, Picard will use the system's default theme. When this is being activated a warning is shown to …
=> PICARD-1952: Add option to use system theme on systems other than macOS and Windows

picard/mbjson.py, test/test_mbjson.py
* This is a…
Do not lower case or de-camelcase attribute names. Fixes issues with instrument names getting case messed up.
This was introduced very eraly in d923c9a. Originally MB provided a more fixed list of instruments, with instrument names as attributes actually being camel cased.
This is no longer the case and instruments should now be used as given in the API response.
* JIRA ticket (_optional_): PICARD-1961, PICARD-1804
Remove the obsolete code.
=> PICARD-1961: Keep instrument and other attributes spelling as is

picard/tagger.py
* This is a…
Avoid a possible crash due to a stack overflow when loading files.
When loading a large list of files this could result in a stack overflow,
since tagger.move_files calls QCoreApplication.processEvents, which in
return might process an event to call tagger.move_files again, resulting
in a deep recursion. See PICARD-1963 for a more detailed explanation.
* JIRA ticket (_optional_): PICARD-1963
Refactor the special case of moving a single file into a separate method.
Note that instead removing the processEvents calls from tagger.move_files is not really an option. This method is basically a large UI update task, so needs to run in the main thread. And not processing events in between makes Picard unresponsive in other cases.
=> PICARD-1963: Avoid stack overflow when loading large amount of files

picard/file.py, picard/metadata.py, picard/track.py, test/test_metadata.py
* This is a…
Restore the "clear existing tags" functionality, which broke when we enabled scripting to use the file's metadata in #1631
* JIRA ticket (_optional_): PICARD-259
If "clear existing tags" is enabled, do not use the files metadata in the scripting. Still allow use of the technical variables (~bitrate, ~channels etc.).
Question/Discussion: This also means you can't use the file's existing variables in your script if you have clear existing tags enabled, but this kind of makes sense to me. If we actually would want to allow access to metadata for the script without actually making it part of the file's metadata I would have a solution for this ready: A metadata proxy object that holds the main metadata for read write, but also gives access to a secondary readonly metadata object. …
=> PICARD-259: Fix clear_existing_tags

picard/ui/mainwindow.py
* This is a…
When the user tries to submit fingerprints but has no AcoustID API key configured a warning dialog is shown. Add a button to directly open the fingerprinting options from within this dialog.
* JIRA ticket (_optional_): PICARD-1965
=> PICARD-1965: Allow opening AcoustID options from missing API key dialog

picard/ui/options/scripting.py
* This is a…
Fixed rendering of scripting documentation for scripts running from right to left.
* JIRA ticket (_optional_): PICARD-1964
Set the general text direction to right-to-left. Also insert a left order mark into code blocks, to fix rendering of code snippets.
The latter is necessary, because in a code block like "$set(...)" the leading $ would still be rendered in RTL mode, that means it would visually turn into "get(a)$". Take e.g. the following without the left-order-mark:
<span dir="rtl">עִבְרִית $get(a) עִבְרִית</span>
And with left-order-mark:
<span dir="rtl">עִבְרִית &lrm;$get(a) עִבְרִית</span>
Example of how it looks like:
=> PICARD-1964: Support right-to-left text flow in scripting docs

picard/metadata.py, picard/track.py, test/test_metadata.py
* This is a…
Fixes track times getting reset to 0 if files get matched to tracks and clear_existing_tags is active.
* JIRA ticket (_optional_): PICARD-1972
Use the full track metadata object to copy all data and don't treat it as a dict.
This just copies the metadata tags as a dict:
```
m = Metadata(old_metadata)
```
This does a full copy:
```
m = Metadata()
m.update(old_metadata)
```
=> PICARD-1972: When matching files to tracks preserve track length

picard/ui/tagsfromfilenames.py, test/test_tagsfromfilenames.py
* This is a…
Fix tags from filenames crashing if same tag is used more than once in match expression.#
Also allow parsing hidden tags.
* JIRA ticket (_optional_): PICARD-1974, PICARD-1975
Refactor tags from filenames to have a `TagMatchExpression` class to handle parsing the expression and matching files. This allows testing.
Fix the issue with multiple groups of same name by separating tag names from group names and ensure group names are unique. Also fix setting hidden tags with an underscore expression like `%_foo%` (PICARD-1975).
=> PICARD-1974: Fix Tags From Filenames handling same tag multiple times

picard/coverart/__init__.py, picard/coverart/image.py
* This is a…
Loading cover art images from URLs with query arguments (such as e.g. `https://api.deezer.com/album/393516/image?size=big`) fails because the query arguments do not get passed properly to the webservice module.
* JIRA ticket (_optional_): PICARD-1976
Properly handle parse the query arguments and use them in the ws request.
=> PICARD-1976: Fixed handling query args in CoverArtImage URLs

picard/formats/mp4.py
* This is a…
For MP4 both "comment" and "comment:" must be treated the same and must be saved to @cmt.
When loading tags Picard loaded `@cmt` as `comment:`, but this is treated as just `comment` internally. On saving the mapping expected `comment:` again, and if receiving just `comment` it would consider it an unmapped tag and save to ` ----:com.apple.iTunes` instead.
* JIRA ticket (_optional_): PICARD-1979
Fix the mapping to be `comment`
=> PICARD-1979: Fix saving comment tag to MP4 files

picard/track.py
* This is a…
Fix images not getting saved for files matched to a track.
* JIRA ticket (_optional_): PICARD-1982
Fix setting track images to the file when it gets matched to the file. This broke in #1631
Files matched to a track always get the track's images copied over.
=> PICARD-1982: When matching file to track copy images

picard/file.py, picard/util/__init__.py
* This is a…
If a file got renamed and the only change was in casing Picard would append a number on case insensitive file systems (except on Windows).
On Windows this worked because `os.path.normcase`, which was used by `picard.util.pathcmp`, would do the proper thing and normalize the casing. But on other OS it would leave the paths as is, even if the underlying filesystem is case insensitive.
* JIRA ticket (_optional_): PICARD-214
Use `os.path.samefile` to properly check if the old and new path refer to the same file. This is fully supported even on Windows since Python 3.2.
Note that `os.path.samefile` requires a stat on both paths in order to compare inodes. But I don't see a easy way around that.
Needs more testing.
So far I tested this …
=>  PICARD-214: Fix Picard adding numbers on file rename on case insensitive file systems

picard/file.py
* This is a…
Fix renaming files on Windows if only casing is changed and Python >= 3.8 is in use.
* JIRA ticket (_optional_): PICARD-1990
This affects only Windows with Python >= 3.8, as `os.path.realpath` will
return the path as it is on disk.
Do not make `File.make_filename` return `os.path.realpath`. This should be fine, as it already use `os.path.realpath` on the directory. Still use `os.path.realpath` on the result of `File._rename` to ensure we use a canonical name for the reloaded file.
See https://github.com/metabrainz/picard/pull/1665#issuecomment-715899992 for in-depth explanation.
Also https://gist.github.com/phw/d30ffb94171c5ea3248691f951310d54 for an overview of case-insensitive behavior and issues.
=> PICARD-1990: Fix file renaming not performed on case-only changes

picard/mbjson.py
* This is a…
Use "performer:chorus master" instead of performer:conductor for chorus master
* JIRA ticket (_optional_): PICARD-1985
"performer:conductor" is not really fitting. This changes makes this consistent with how we handle concertmaster.
=> PICARD-1985: Use "performer:chorus master" instead of performer:conductor

picard/ui/itemviews.py
* This is a…
* JIRA ticket (_optional_): PICARD-1997, PICARD-1989
The fingerprint column has a huge impact on rendering performance. The column content gets repainted a lot and can reduce loading performance significantly.
Use the default icon implementation of `QTreeWidget` instead of custom implementation.
In my tests this improved performance a lot. If the fingerprint column is visible this reduced loading time for 4k files by 80%. Even if the column is hidden loading time is still reduced by 32%. See the following results for loading 4k files (with ignore MBIDs):
|                        |  master | this patch | reduction |
|--------------------|------------|---------------|------------|
| column visible | 78s       | 16s           |  79% …
=> PICARD-1997: Reduce performance impact of fingerprint column

picard/cluster.py, picard/file.py, picard/track.py, picard/ui/coverartbox.py, picard/ui/mainwindow.py, picard/util/imagelist.py
* This is a…
* JIRA ticket (_optional_): PICARD-1828
Add a new class `FileList`, which acts kind of like a temporary ad-hoc cluster. In fact I have made it the parent of the `Cluster` class, as it shares some basic code.
The cover art box only can handle a single object. When multiple files are selected create a `FileList` object and use this for the cover art box.
This PR also optimized the event handling and avoids unnecessary signalling. Previously the coverart box caused many selection changes. For "use original coverart" it even relied on a roundtrip to update cover art on items -> items signal updates -> main window updates selection -> cover art box updates view. This is not needed, the cover art box can update right away. Indeed with > …
=> PICARD-1828: Allow setting cover art for multiple selected files

picard/file.py, picard/util/filenaming.py, requirements-win.txt, requirements.txt, test/test_util_filenaming.py
* This is a…
* JIRA ticket (_optional_): PICARD-1991, PICARD-1992
If a rename results only in the casing of file names changing this is not applied by a simple `shutil.move` or `os.rename` in some situations on case insensitive file systems. Specifically this never works for Linux when using case insensitive file systems (e.g. FAT32, ext4 with case-insensitivity enabled, CIFS share) and on Windows 10 for FAT32 and extFAT file systems.
See also the comparison on https://gist.github.com/phw/d30ffb94171c5ea3248691f951310d54
IF a case-only change happens (file stays in same directory, file name changes only in casing) on a case insensitive file system (case sensitive file systems are not affected by design) and the OS is affected by this (macOS …
=> PICARD-1992: Fix case only changes when renaming files

picard/ui/metadatabox.py
* This is a…
* JIRA ticket (_optional_): PICARD-2005
IF multiple tracks have been selected where some have changes in existing tags but the first track being looked at has no changes because incoming metadata is empty,  
THEN the tag is being shown as unchanged.
If you take the example from PICARD-2005 and look at the code at https://github.com/metabrainz/picard/blob/master/picard/ui/metadatabox.py#L538 the following happens:
If the first file being considered is the one of track 2, the tag "lyrics_language" will have:
orig values `['Japanese']`  
new values `[]`
It then gets new values set to orig values, and the tag is added to `existing_tags`. This results in no change (both ori values and new values are the same).
The next track being …
=> PICARD-2005: Fix tags being shown as unchanged if multiple tracks are selected

picard/formats/midi.py, picard/tagger.py
* This is a…
Audio fingerprinting can by design not work on MIDI files. Disable the fingerprinting action for those files and avoid spawning fingerprinting processes if those files are part of a selection that can be fingerprinted.
* JIRA ticket (_optional_): PICARD-2007
Implement `MIDIFile.can_analyze`
=> PICARD-2007: Disable fingerprinting for MIDI files

picard/album.py, picard/file.py, picard/tagger.py
* This is a…
* JIRA ticket (_optional_): PICARD-2006, PICARD-2012
When files gets loaded that are already matched to a release, the files are not added to the release until after the album is fully loaded. This was changed in https://github.com/metabrainz/picard/commit/fac2b37d8cf8dad8e821de541b9c40ee2ae0a0b8 .
This causes various issues:
- The files are not available to plugins or cover art providers that run during the loading of the release. See PICARD-2006
- In case of a MBID redirect, where the redirect target is already loaded, Picard attempts to move unmatched files to the already loaded release. This broke with the above commit, causing the files to being still loaded without being visible in the UI. PICARD-2012
- The files are not …
=> PICARD-2006: Optimize moving files to albums on load

picard/tagger.py
* This is a…
* JIRA ticket (_optional_): PICARD-1948
This was originally introduced in PICARD-1777 to improve scaling support on Windows.
It causes UI regressions on Linux were it sometimes results in wrong scaled
fonts if no scaling factor is configured.
Limit this to Windows for now.
=> PICARD-1948: Limit fractional scaling support to Windows

.github/workflows/package.yml, requirements-build.txt
* This is a…
PyInstaller 4.1 was released, allowing us to build with Python 3.8 or 3.9
Build with PyInstaller 4.1 and use latest Python 3.8.x for Windows builds
**Why not use Python 3.9 for Windows?**
Python 3.9 dropped support for Windows 7. I actually tested building with Python 3.9 and the builds will indeed fail to start on Win 7. While I think we will at some point no longer support Windows 7 and I already would not be willing to make bigger compromises just to keep it alive, there is also no need to break compatibility without need.
**Why not use newer Python for macOS?**
For some reason not quite clear to me using any Python version later then 3.7.6 results in code signing errors and a resulting …
=> Build with PyInstaller 4.1 and use latest Python 3.8.x for Windows builds

picard/tagger.py
* This is a…
* JIRA ticket (_optional_): PICARD-2017
When the non-album track "album" entry got removed just before a non-album track was also removed Picard would crash.
I actually could not intentionally reproduce this, but in theory it can happen. tagger.remove just goes over all selected objects to remove and calls the appropriate functions. If it would have both the non-album tracks "album" entry and the NATs themselves queued for deletion and deletes the album first, it would still call the remove_nat per file.
Check for existence of self.nats
=> PICARD-2017: Fix crash when removing NATs

setup.py
Generate appdata for non-Linux platforms.
* This is a…
Setup attempts to install the appdata for all platforms not darwin, haiku1, or win32, yet it is only generated for linux. This was introduced in [edfa273](https://github.com/metabrainz/picard/commit/edfa2733535b328ab7deeff6c7cf619642fd1319) and causes installation errors on platforms such as FreeBSD since the appdata was not previously generated. 
Generate the appdata for the platforms that setup tries to install it on.
=> Generate appdata for non-Linux platforms

picard/tagger.py
* This is a…
* JIRA ticket (_optional_): PICARD-2020
If already tagged files are loaded into Picard, but the existing album or recording IDs are stored as multi-value (can be the same ID stored multiple times), then Picard will fail to detect the IDs and hence not load the album or NAT.
if musicbrainz_albumid or musicbrainz_recordingid contain multiple values, use the first one to load the proper album / recording for already tagged files.
=> PICARD-2020: Handle multi-value musicbrainz_albumid/musicbrainz_recordingid on load

picard/util/filenaming.py
* This is a…
Fixes errors when moving files from a network path to local path (or vice versa) on Windows, if both paths refer to the same file.
* JIRA ticket (_optional_): PICARD-2021
See the detailed description in PICARD-2021
Ignore SameFileError when moving files
=> PICARD-2021: Ignore SameFileError when moving files

picard/coverart/image.py, picard/file.py, picard/util/__init__.py, test/test_utils.py
* This is a…
Works around the issue that os.path.isabs detects a path like \\server\share not as absolute.
This can break file naming on Windows shares and result in recursive sub folders.
* JIRA ticket (_optional_): PICARD-2019
One Windows a network share can be addressed like `\\server\share`. There can be additional sub directories under this share, e.g.  `\\server\share\foo`. Likewise there can be `\\server\share\` which uses the top level dir of this share. This is semantically the same as `\\server\share`. But Python's os.path.isabs detects `\\server\share` (without any dir) as a relative path.
This caused creation of recursive directory structures on repetitive saves of files, if the target dir was set to `\\server\share`.
See also …
=> PICARD-2019: Fix os.path.isabs not detecting Windows share correctly

picard/ui/itemviews.py
* This is a…
Improves the tooltip when a processing error (like a CAA retrieval failure) causes the Album icon to indicate an error.
I was getting albums with an error icon. I tracked this down to a failure to retrieve CAA covers.
* JIRA ticket (_optional_): PICARD-2033, PICARD-2035
Provide a better tooltip.
=> PICARD-2035: Improve the tooltip on Album errors

picard/tagger.py, picard/ui/edittagdialog.py, picard/ui/mainwindow.py, picard/ui/metadatabox.py, test/test_ui_mainwindow.py
* This is a…
* JIRA ticket (_optional_): PICARD-2028
Removing or clustering files calls MainWindow.update_selection a lot. This can cause a significant slow down if many files are selected.
Call MainWindow.update_selection only once after the deletion / clustering is completed.
Also refactored MainWindow.ignore_selection_changes to use a context manager, so one can do:
```python
with window.ignore_selection_changes:
```
The main cause why the many calls to update_selection caused such a significant slowdown in PICARD-2028 is actually the cover art for multiple selected files feature. While this performs well for the case that the user selects a huge amount of files it is still significantly slow that repated update_selection calls will greatly …
=> PICARD-2028: Ignore selection changes when clustering or removing files

picard/ui/options/fingerprinting.py
* This is a…
* JIRA ticket (_optional_): PICARD-2016
Automatically strip whitespace on entered AcoustID API keys. This avoids a typical user error when copy and pasting this key from elsewhere.
Use a `QValidator` to fixup the input automatically
=> PICARD-2016: Strip whitespace from AcoustID API key automatically

picard/album.py, picard/cluster.py, picard/file.py, picard/tagger.py, picard/track.py, picard/ui/coverartbox.py, picard/ui/infodialog.py, picard/ui/item.py, picard/ui/itemviews.py, picard/ui/mainwindow.py, picard/ui/metadatabox.py, picard/ui/ratingwidget.py, picard/ui/scriptsmenu.py, picard/util/imagelist.py, test/test_imagelist.py
* This is a…
* JIRA ticket (_optional_): PICARD-2028
Cover art updates are rather expensive. This can be even more problematic then before since support for setting cover art for multiple selected files in #1673.
This PR aims to optimize this by unifying the cover art handling across different object types and avoiding updates if they are not necessary.
- Unify handling of cover art between the different object types `Album`, `Track`, `Cluster` and `File`. The API of those objects is now similar enough to remove special handling at many places
- Avoid calling updates to cover art box unless selection changed. The cover art box instead relies on signalling for the rare case where cover art changes for a loaded object
- Avoid signalling in cover …
=> PICARD-2028: Optimize and speedup coverart updates

picard/album.py, picard/cluster.py, picard/file.py, picard/script/functions.py, picard/track.py, picard/ui/itemviews.py
* This is a…
On some operations Picard issues excessive calls to MainWindow.update_selection.
Saving a single file caused 3 calls to update_selection, even if nothing selection relevant changed. Refreshing an album with only 8 tracks and matched files for each even caused 66 calls to update_selection.
Reduce the number of calls to update_selection by skipping unneeded ones (e.g. because .
For a file save it is now only a single update_selection per file.
Refreshing the album with 8 tracks is down to 17 calls /from 66). Still much, but way better. The calls where mostly caused by moving the files between tracks -> unmatched files -> matching to tracks again. The patch avoids moving the previously matched …
=> Avoid update selection on save and album refresh

picard/tagger.py, picard/ui/mainwindow.py, picard/ui/playertoolbar.py, picard/ui/scriptsmenu.py, picard/ui/searchdialog/album.py, picard/util/__init__.py, test/test_utils.py
* This is a…
`tagger.get_files_from_objects` is used in many places, usually for iterating over the selected files. `tagger.get_files_from_objects` however first creates a list of objects, chains their `iterfiles()` methods and again converts the result into a list.
Add a `picard.util.iter_files_from_objects` function which yields all files for the selected objects, allowing efficient iteration over all selected files. This also reduces dependency on the global tagger object.
Keep `get_files_from_objects` returning a list for cases where a list is actually wanted and for backward compatibility.
=> Add a tagger.iter_files_from_objects method

picard/ui/filebrowser.py
* This is a…
* JIRA ticket (_optional_): PICARD-2050
When clicking on the arrow icon for a folder and the view would reposition due to selection change the expansion is not performed, as the mouse event is handled after position has been changed.
Process the click before updating selection
=> PICARD-2050: File browser does not handle first click to expand folder

picard/ui/colors.py, picard/ui/options/interface_colors.py, test/test_interface_colors.py
* This is a…
Use different interface colors for light and dark themes.
* JIRA ticket (_optional_): PICARD-2047, PICARD-2056
Some of the default colors don't work well in the log view if a dark theme is in use.
Store a separate set of colors for light and dark UI in options. Use the one matching the current theme. This allows both having separate defaults and for the user to configure the UI differently for light and dark. This is interesting for users switching mode (e.g. some people use dark mode only in the evening / night).
Only two colors were actually changed: The info color (white instead of black) and the debug color (a bit lighter purple):
=> PICARD-2047: Provide separate set of interface colors for dark themes

picard/ui/mainwindow.py
* This is a…
On case-sensitive file systems the Add File dialog does not show files with matching extension, if it is uppercase (e.g. test.MP3).
* JIRA ticket (_optional_): PICARD-2058
Add both lower and upper case extensions to the filters.
Do this only on OS other than Win or macOS. macOS and Windows usually support case sensitive file names. Furthermore on both systems the file dialog filters list all extensions we provide, which becomes a bit long when we give the full list twice.
=> PICARD-2058: Allow selection of files with upper case extension in add file dialog on Linux

picard/ui/mainwindow.py
* This is a…
Allow showing all files, independent of file type, in the Add Files file selector dialog. This allows selection of files which might have uncommon extensions or none at all.
* JIRA ticket (_optional_): PICARD-2057
=> PICARD-2057: Add a "All files" filter to add files dialog

picard/file.py
* This is a…
* JIRA ticket (_optional_): PICARD-2045
Calling `file.clear_pending()`  does not properly reset the CHANGED or NORMAL state, as it only looks at file.similarity. This e.g. causes files with changed status to become normal after fingerprinting.
Refresh the state on clear pending.
=> PICARD-2045: Recalculate changed state after file.clear_pending()

picard/album.py, picard/cluster.py, picard/tagger.py
* This is a…
Removing an album or track where multiple files had been matched to a single track could result in only half of the files being actually removed. This was introduced in bab8447.
Get the full list of files before starting iterating. Also some minor refactoring / code simplification.
=> Fixed removing album or track with multiple files attached

picard/cluster.py
* This is a…
* JIRA ticket (_optional_): PICARD-2064
Clusters always show an empty value in the album column in itemviews.
Fix the condition logic. The intention was not to fill the album column for special clusters ("Unclustered files" showing "Unclustered files" as album name doesn't make much sense).
=> PICARD-2064: Fixed clusters not showing album name in album column
